In [ ]:
!curl -s -q https://raw.githubusercontent.com/agricolamz/2025_morphological_transducers/refs/heads/main/task_tests/Makefile -o Makefile; make

Cleaning up old install, if any...
removed '/etc/apt/trusted.gpg.d/apertium.gpg'
removed '/etc/apt/preferences.d/apertium.pref'
removed '/etc/apt/sources.list.d/apertium.list'
Determining Debian/Ubuntu codename...
Found evidence of jammy...
Settling for jammy - enabling the Apertium nightly repo...
Installing Apertium GnuPG key to /etc/apt/trusted.gpg.d/apertium.gpg
Installing package override to /etc/apt/preferences.d/apertium.pref
Creating /etc/apt/sources.list.d/apertium.list
Running apt-get update...
All done - enjoy the packages! If you just want all core tools, do: sudo apt-get install apertium-all-dev
sudo apt-get install hfst lexd
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
hfst is already the newest version (3.17.1+g4008~52376baa-4~jammy1).
lexd is already the newest version (1.3.5+g180~55b0b7b6-20~jammy1).
0 upgraded, 0 newly installed, 0 to remove and 22 not upgraded.

#Обработка словарей

In [ ]:
import pandas as pd

In [ ]:
# @title
%%writefile dct_all.csv
,агульское слово,заметка,диалектологизм,русский перевод,часть речи
0,абаб,мн. ч. абабар,нет,тётя,существительное
1,абажур,мн. ч. абажурар,нет,абажур,существительное
2,абанемент,мн. ч. абанементар,нет,абонемент,существительное
3,абанент,мн. ч. абанентар,нет,абонент,существительное
4,абанкьул,мн. ч. абанкьулар,нет,лоб,существительное
5,аббат,нет,нет,вечный,прилагательное
6,абдал,мн. ч. абдалар,нет,дурак; глупец,существительное
7,абдал хьас,нет,нет,глупеть; тупеть,глагол
8,абдалвел,нет,нет,тупость,существительное
9,абдалди,нет,нет,нелепо; неумело,наречие
10,абдалф,нет,нет,глупый,прилагательное
11,абзац,мн. ч. абзацар,нет,абзац,существительное
12,абиранг,нет,нет,светло-голубой,прилагательное
13,абитуриент,мн. ч. абитуриентар,нет,абитуриент,существительное
14,аблигаци,мн. ч. аблигацибур,нет,облигация,существительное
15,аборт,мн. ч. абортар,нет,аборт,существительное
16,абояр,мн. ч. абоябур,нет,обои,существительное
17,абразец,мн. ч. абразецар,нет,образец,существительное
18,абур,мн. ч. абурар,нет,честь,существительное
19,абур алеф,нет,нет,приличный; пристойный,прилагательное
20,абур аф,нет,нет,пристойный,прилагательное
21,абурар,нет,нет,скромность; приличие,существительное
22,абурлувел,нет,нет,честь,существительное
23,абурсуз,нет,нет,недостойный,прилагательное
24,абъект,мн. ч. абъектар,нет,объект,существительное
25,абъем,мн. ч. абъемар,нет,объём,существительное
26,ав,нет,да,да,частица
27,ав,нет,да,да,наречие
28,аваз1,мн. ч. авазар,нет,клевета; сплетня,существительное
29,аваз2,мн. ч. авазар,нет,напев,существительное
30,аваза,мн. ч. авазар,нет,известие; слух; молва,существительное
31,авал вахттари,нет,нет,раньше; прежде,наречие
32,авала,нет,нет,раньше; прежде; давно,наречие
33,аваланф,нет,нет,старинный,прилагательное
34,авантюра,мн. ч. авантюрабур,нет,авантюра,существительное
35,авантюрист,мн. ч. авантюристар,нет,авантюрист,существительное
36,авар шуй,мн. ч. авар шувар,нет,аварец,существительное
37,авар хьир,мн. ч. авар хьирар,нет,аварка,существительное
38,аваранф,нет,нет,беспокойный,прилагательное
39,август,нет,нет,август,существительное
40,авдал,нет,нет,непутёвый,прилагательное
41,авлия,нет,нет,никчёмный,прилагательное
42,автисади,нет,нет,вон,наречие
43,авгус дагIай,нет,нет,безвестность,существительное
44,авчи,мн. ч. авчибур,нет,охотник,существительное
45,авчивел,нет,нет,охота,существительное
46,агалкьунар,нет,нет,успешно,наречие
47,агвар акьас,нет,нет,показать,глагол
48,агвас,нет,нет,видеть,глагол
49,агнемёт,мн. ч. агнемётар,нет,огнемёт,существительное
50,агуб,мн. ч. агубар,нет,вид; облик,существительное
51,агубар,нет,нет,внешность; наружность; образ,существительное
52,агубар алди,нет,нет,образцово; примерно,наречие
53,агубар алеф,нет,нет,видный; приличный,прилагательное
54,агудж,мн. ч. агуджар,нет,вес,существительное
55,агуна-дагуна,нет,нет,мельком,наречие
56,агъ1,мн. ч. агъар,нет,бедро; ляжка,существительное
57,агъ2,мн. ч. агъар,нет,бязь,существительное
58,агъа,мн. ч. агъабур,нет,господин,существительное
59,агъавес,нет,нет,подняться,глагол
60,агъдарукьаф,нет,нет,беспомощный,прилагательное
61,агъзур,мн. ч. агъзурар,нет,кила; тонна,существительное
62,агъзур,нет,нет,тысяча,числительное
63,агъзур грамм,нет,нет,кило,существительное
64,агъзур меттр,нет,нет,километр,существительное
65,агъу,мн. ч. агъубур,нет,яд,существительное
66,агъуйинф,нет,нет,ядовитый,прилагательное
67,агъул,нет,нет,агульский,прилагательное
68,агъул хьир,мн. ч. агъул хьирар,нет,агулка,существительное
69,агъул шуй,мн. ч. агъул шувар,нет,агулец,существительное
70,агъуларинф,нет,нет,агульский,прилагательное
71,агъутIанас,нет,нет,торчать,глагол
72,агь,нет,нет,ох,междометие
73,агь,мн. ч. агьар,нет,стон; проклятие,существительное
74,агьал,нет,нет,сейчас; теперь,наречие
75,агьал димари,нет,нет,тотчас,наречие
76,агьатас,нет,нет,налить,глагол
77,агьилвел,нет,нет,старость,существительное
78,агьрам,мн. ч. агьрамар,нет,рычаг,существительное
79,агIай,мн. ч. агIайибур,нет,улитка,существительное
80,ад1,мн. ч. адар,нет,ляжка,существительное
81,ад2,нет,нет,преисподняя,существительное
82,ада акьас,нет,нет,выплатить,глагол
83,ада вахттар,нет,нет,дефицит,существительное
84,ада джуьре,нет,нет,изобилие,существительное
85,ада джуьрейинф,нет,нет,изобильный,прилагательное
86,ада джуьрс,нет,нет,изобильный,прилагательное
87,адаб,нет,нет,совесть; воспитанность,существительное
88,адабият,мн. ч. адабиятар,нет,литература,существительное
89,адаблу,нет,нет,вежливый,прилагательное
90,адаблувел,нет,нет,стеснительность,существительное
91,адабсуз,нет,нет,бессовестный; наглый,прилагательное
92,адаверевус,мн. ч. адаверевусар,нет,спуск,существительное
93,адавес,нет,нет,спуститься,глагол
94,адавусаас акьас,нет,нет,создать; сотворить,глагол
95,адад,мн. ч. ададар,нет,дядя,существительное
96,ададивас,нет,нет,стащить; стянуть,глагол
97,ададжикас,нет,нет,подмести,глагол
98,адайис,нет,да,приехать,глагол
99,адайкIас,нет,нет,передать,глагол
100,адайхьас,нет,нет,сбросить,глагол
101,адайчIвас,нет,нет,слезть,глагол
102,адайшас,нет,нет,спрыгнуть,глагол
103,адарцас,нет,нет,порезать,глагол
104,адаф,нет,нет,беззлобный,прилагательное
105,адахас1,нет,нет,снести,глагол
106,адахас2,нет,нет,свезти,глагол
107,адахъас,нет,нет,открыть; раскрыть,глагол
108,адахъуф,нет,нет,открытый; расстёгнутый; обнажённый,прилагательное
109,адджикас,нет,нет,вымести,глагол
110,адегъан йис,нет,нет,выплатить,глагол
111,ади,нет,нет,внизу,наречие
112,адиас,нет,нет,снизу,наречие
113,адигIас,нет,нет,оттуда,наречие
114,адикас,нет,нет,выгнать; прогнать,глагол
115,адиккди,нет,нет,пониже,наречие
116,адикIас,нет,нет,передать,глагол
117,адикIу багв,мн. ч. адикIу багвар,нет,выступ,существительное
118,адис,нет,нет,приехать,глагол
119,адихьас,нет,нет,утвердить,глагол
120,адлу,нет,нет,известный; знаменитый,прилагательное
121,адсузвел,нет,нет,безвестность,существительное
122,аджутъ,нет,нет,сердитый,прилагательное
123,аджутъвел,нет,да,ярость,существительное
124,аджутъди,нет,нет,сердито,наречие
125,аджутъсуз,нет,нет,беззлобный,прилагательное
126,аджутъсузвел,нет,нет,беззлобность,существительное
127,аджукъ,нет,нет,зависть,существительное
128,ае кар,мн. ч. ае курар,нет,факт,существительное
129,ае кар,нет,нет,очевидный,прилагательное
130,аждагьа,мн. ч. аждагьабур,нет,дракон,существительное
131,азад,нет,нет,свободный; независимый,прилагательное
132,азадвел,нет,нет,независимость,существительное
133,азадди,нет,нет,независимо,наречие
134,азар,мн. ч. азарар,нет,болезнь; зараза,существительное
135,азархана,мн. ч. азарханабур,нет,больница,существительное
136,азгар,нет,нет,безоблачный,прилагательное
137,азгъунвел,нет,нет,упрямство,существительное
138,азгъунди,нет,нет,упрямо,наречие
139,азият,мн. ч. азиятар,нет,боль; мучение,существительное
140,азияткар,мн. ч. азияткурар,нет,мученик,существительное
141,азияттикк ккеф,мн. ч. азияттикк ккеттар,нет,мученик,существительное
142,азман хIа кар,мн. ч. азман хIа курар,нет,событие,существительное
143,азманвел,нет,нет,рост,существительное
144,азманди,нет,нет,крупно,наречие
145,азманф,нет,нет,огромный,прилагательное
146,азманхIаф,нет,нет,крупный,прилагательное
147,айван,мн. ч. айванар,нет,балкон; веранда; терраса,существительное
148,айгъур,мн. ч. айгъурар,нет,жеребец,существительное
149,айрутмиш,нет,да,разлучать,глагол
150,акуранас,нет,нет,белить; побелить,глагол
151,аккуьшуб,нет,нет,заброшенность; обветшалость,существительное
152,акьас,нет,нет,делать,глагол
153,акьас пуб,мн. ч. акьас пубар,нет,обещание,существительное
154,акье пуб,нет,нет,велеть,глагол
155,акьун кIиркIвас,нет,нет,исполнить,глагол
156,алагъшуб,нет,нет,рвота,существительное
157,аладивас,нет,нет,ударить,глагол
158,аладикIас,нет,нет,сказать,глагол
159,алайхьас,нет,нет,сбросить; скинуть,глагол
160,алайчIвас,нет,нет,слезть; спуститься,глагол
161,алайшас,нет,нет,спрыгнуть,глагол
162,аларуджуб,нет,нет,скрученность,существительное
163,аларуцавус,мн. ч. аларуцавусар,нет,поворот,существительное
164,аларуцас,нет,нет,проведать,глагол
165,алархьас,нет,нет,упасть,глагол
166,алахъас,нет,нет,покрыть,глагол
167,алача,мн. ч. алачабур,нет,кляча,существительное
168,алачух,мн. ч. алачухар,нет,палатка; шатёр,существительное
169,алгъадаркас,нет,нет,падать; упасть,глагол
170,алгъадиб,нет,нет,разъярённость,существительное
171,алгъадинаф,нет,нет,разъярённый,прилагательное
172,алгъадис,нет,нет,разъяриться,глагол
173,алгъузуф,мн. ч. алгъузуттар,нет,наблюдатель,существительное
174,алгъихьас,нет,нет,поднять,глагол
175,алдаф дуья алайкуная,нет,нет,безоблачный,прилагательное
176,алдахъас1,нет,нет,обнажиться; открыться; раздеть,глагол
177,алдахъас2,нет,да,стянуть; стащить,глагол
178,алдахъуф,нет,нет,обнажённый,прилагательное
179,алддучIаф,нет,нет,устойчивый,прилагательное
180,алдиджи,мн. ч. алдиджибур,нет,обмотка,существительное
181,алдихьас,нет,нет,скинуть,глагол
182,алдучIаф,нет,нет,стойкий,прилагательное
183,алекъун,нет,нет,верхом,наречие
184,алийи ягъ,мн. ч. алийи ягъар,нет,дата,существительное
185,алифбе,нет,нет,азбука,существительное
186,алиянас,нет,нет,поставить,глагол
187,алкъан,мн. ч. алкъанар,нет,аркан,существительное
188,аллагьдин диван,мн. ч. аллагьдин диванар,нет,наказание,существительное
189,аллайкуф,нет,нет,ясный,прилагательное
190,алархьас,нет,нет,несчастье,существительное
191,алархьуб,нет,нет,напасть,существительное
192,алучIуб,нет,нет,упорство,существительное
193,алмас,мн. ч. алмасар,нет,алмаз; стеклорез,существительное
194,алранг,нет,нет,розовый,прилагательное
195,алттагъу багв,мн. ч. алттагъу багвар,нет,выступ,существительное
196,алттар хьас,нет,нет,ошибиться,глагол
197,алттар хьуб,мн. ч. алттар хьубар,нет,ошибка,существительное
198,алукас,нет,нет,налёт,существительное
199,алукуб,нет,нет,нападение,существительное
200,алухIанас,нет,нет,ссориться; конфликтовать,глагол
201,алухIуб,мн. ч. алухIубар,нет,перепалка; ссора; ругательство; брань,существительное
202,алухIубар,нет,нет,ругательство,существительное
203,алучIуб,нет,нет,усердие,существительное
204,алучIубар,нет,нет,старание,существительное
205,алучIун,нет,нет,энергично,наречие
206,алцанас,нет,нет,взвешивать,глагол
207,алчагь,мн. ч. алчагьар,нет,негодяй; подлец,существительное
208,алчагь тIулар акьас,нет,нет,гнусавить,глагол
209,алчагьвел,нет,нет,гнусавость,существительное
210,алчагьди,нет,нет,подло,наречие
211,алчагьф1,нет,нет,гнусавый,прилагательное
212,алчагьф2,нет,нет,подлый,прилагательное
213,алчахьас,нет,нет,покрыть,глагол
214,алчикас,нет,нет,настропалить; натравить; настроить против,глагол
215,алчихьас,нет,нет,умножение,существительное
216,алчихьас,нет,нет,набросить,глагол
217,алчихьас сасрайил,нет,нет,оклеветать,глагол
218,алчихьуб,мн. ч. алчихьубар,нет,обговаривание; заклинание; наговор; клевета,существительное
219,амана,нет,да,если,союз
220,аманат,мн. ч. аманатар,нет,поручение; завещание,существительное
221,амузрис,нет,да,нарочно; специально,наречие
222,амир,мн. ч. амирар,нет,приказ,существительное
223,амма,нет,нет,но; однако; зато,союз
224,анджахь,нет,да,только,наречие
225,аннамазвел,нет,нет,упрямство,существительное
226,апкьан,мн. ч. апкьанар,нет,обед,существительное
227,апкьанин ягъ,нет,нет,полдень,существительное
228,апрел,нет,нет,апрель,существительное
229,апперацибур аркьаф хирург,нет,нет,хирург,существительное
230,ара,мн. ч. арабур,нет,промежуток; пауза,существительное
231,арайи архьуб,нет,нет,размолвка,существительное
232,арайиъ ихьубар,нет,нет,склока,существительное
233,аран,нет,нет,полоскость,существительное
234,араттор,мн. ч. аратторар,нет,оратор,существительное
235,арбягъ,нет,нет,среда,существительное
236,арганизаци,мн. ч. арганизацибур,нет,организация,существительное
237,арзуман,нет,нет,милый,прилагательное
238,арифметика,мн. ч. арифметикабур,нет,арифметика,существительное
239,аришвариш,нет,нет,торговля,существительное
240,аришваришчи,мн. ч. аришваришчибур,нет,торговец,существительное
241,аркестр,мн. ч. аркестрар,нет,оркестр,существительное
242,армени,мн. ч. арменибур,нет,армянин,существительное
243,арс,нет,нет,серебро,существительное
244,арсуранф,нет,нет,серебряный,прилагательное
245,артил,нет,нет,артель,существительное
246,аруцас,нет,нет,искать,глагол
247,арх,мн. ч. архар,нет,канава,существительное
248,архайинвел,нет,нет,спокойствие,существительное
249,архайинди,нет,нет,удобно,наречие
250,архайинф,нет,нет,спокойный,прилагательное
251,архIас,нет,нет,стричь (овец),глагол
252,арчIвас акьас,нет,нет,разрушить,глагол
253,арчIуб,нет,нет,обветшалость,существительное
254,арчIувел,нет,нет,разрушенность; разорённость,существительное
255,арчIувусар,нет,нет,развалины,существительное
256,асир,мн. ч. асирар,нет,век,существительное
257,асккидай,нет,нет,болтливо; несерьёзно,наречие
258,аслан,мн. ч. асланар,нет,лев,существительное
259,асланвел,нет,нет,мужество,существительное
260,аспирант,мн. ч. аспирантар,нет,аспирант,существительное
261,аспирантура,мн. ч. аспирантурабур,нет,аспирантура,существительное
262,ассистент,мн. ч. ассистентар,нет,ассистент,существительное
263,ассуз,нет,нет,ненадёжный,прилагательное
264,аставел,нет,нет,осторожность,существительное
265,астт,мн. ч. асттар,нет,подол,существительное
266,астта,нет,нет,тихо,наречие
267,астта,нет,да,неторопливый,прилагательное
268,астта-астта,нет,да,медленно; потихоньку,наречие
269,аставел,нет,да,неторопливость,существительное
270,асттраноми,мн. ч. асттраномибур,нет,астрономия,существительное
271,асулсуз,нет,нет,бесполезный,прилагательное
272,атом,мн. ч. атомар,нет,атом,существительное
273,атомный,нет,нет,атомный,прилагательное
274,атутас,нет,да,потрясти,глагол
275,аттархьевел,нет,нет,беспутство,существительное
276,аттатIу ранг,нет,да,яркий,прилагательное
277,аттверевус,мн. ч. аттверевусар,нет,выход,существительное
278,аттвес,нет,нет,выйти,глагол
279,аттдахьу тукун кIил,нет,нет,бутон,существительное
280,аттивас1,нет,нет,снести; вытащить,глагол
281,аттивас2,нет,нет,свезти,глагол
282,аттикас,нет,да,выгнать,глагол
283,аттракцион,мн. ч. аттракционар,нет,аттракцион,существительное
284,аф авуса атун,нет,нет,немедленно,наречие
285,аф агъилди,нет,нет,подробный; полный,прилагательное
286,аф агъилди,нет,нет,точнее,частица
287,афар,мн. ч. афарар,да,пироги,существительное
288,афекьуф,мн. ч. афекьуфар,нет,ассистент,существительное
289,афтобиографи,мн. ч. афтобиографибур,нет,автобиография,существительное
290,афтомат,мн. ч. афтоматар,нет,автомат,существительное
291,афтопортрет,мн. ч. афтопортретар,нет,автопортрет,существительное
292,афторучка,мн. ч. афторучкабур,нет,авторучка,существительное
293,афтостанци,мн. ч. афтостанцибур,нет,автостанция,существительное
294,афттабуз,мн. ч. афттабузар,нет,автобус,существительное
295,ахир кIил,мн. ч. ахир кIилар,нет,результат; итог; исход; конец,существительное
296,ахиранф,нет,нет,конечный,прилагательное
297,ахирахъди,нет,нет,наконец,наречие
298,ахиримджи,нет,да,конечный; последний,прилагательное
299,ахиркIил,нет,нет,наконец,наречие
300,ахлакъсуз,нет,нет,невоспитанный,прилагательное
301,ахсарар,нет,да,заря,существительное
302,ахсари,мн. ч. ахсарибур,да,рассвет,существительное
303,ахта,мн. ч. ахтабур,нет,мерин,существительное
304,ахттиар сузвел,нет,нет,бесправие,существительное
305,ахттигьар,нет,нет,позволение; разрешение; полномочие; право,существительное
306,ахттигьар адай,нет,нет,запрет,существительное
307,ахттигьар адахъуб,нет,нет,запретность,существительное
308,ахттигьар ай,нет,нет,свободно; вольно,наречие
309,ахттигьар аф,нет,нет,свободный; вольный,прилагательное
310,ахттигьар дайис,нет,нет,запретить,глагол
311,ахттигьар фаф,нет,нет,уполномоченный,прилагательное
312,ахттилат,мн. ч. ахттилатар,нет,разговор; беседа; слово; рассказ,существительное
313,ахттилатчи,мн. ч. ахттилатчибур,нет,собеседник,существительное
314,ахун-лехIеф,нет,нет,постель,существительное
315,ахIаджихIуб,нет,нет,помощь; забота,существительное
316,ахIакьас,нет,нет,признание,существительное
317,ахыхьас,нет,нет,гнаться,глагол
318,ахыхьуб,нет,нет,погоня,существительное
319,ахIуф,нет,нет,широкий,прилагательное
320,ахьасра ай,нет,нет,будучи,деепричастие
321,ахIабаб,мн. ч. ахIабабар,да,бабушка,существительное
322,ахIадад,мн. ч. ахIададар,да,дедушка,существительное
323,ахIаф,мн. ч. ахIафар,да,голова (должностное лицо),существительное
324,ахIмакьсуз,нет,нет,невоспитанный,прилагательное
325,ахIттибар алдаф,нет,нет,ненадёжный,прилагательное
326,ахIттият вел,нет,нет,осторожность; предосторожность,существительное
327,ахIттият фаф,нет,нет,осторожный,прилагательное
328,ацIу рудар,нет,нет,кишечник,существительное
329,ацIувел,нет,нет,полнота,существительное
330,ацIун яшаринф,нет,нет,пожилой,прилагательное
331,ацIунглайинф,нет,нет,частый,прилагательное
332,ацIуф,нет,нет,сытый; полный,прилагательное
333,ачаве ус,нет,нет,вход,существительное
334,ачаверевус,нет,нет,вход,существительное
335,ачавес,нет,нет,войти,глагол
336,ачар хьас,нет,нет,оказаться,глагол
337,ачатас,нет,нет,тратить,глагол
338,ачикуф,нет,нет,осуждённый,прилагательное
339,ачирхьас,нет,нет,бить; ударять; ударить,глагол
340,ачмиш,нет,нет,открытый; обнажённый; расстёгнутый,прилагательное
341,ачмиш акьас,нет,нет,открывать,глагол
342,ачмиш хьас,нет,нет,открыться; обнажиться,глагол
343,ачухь акьас,нет,нет,открыть; раскрыть,глагол
344,ачухь хьас,нет,нет,развеселиться,глагол
345,ачухьвел,нет,нет,настроение,существительное
346,ачухьди,нет,нет,ясно,наречие
347,ачухьф,нет,нет,ясный,прилагательное
348,ачIан уркI,мн. ч. ачIан уркIар,нет,подмышка,существительное
349,аш,мн. ч. ашар,нет,каша; плов,существительное
350,ашбаз,мн. ч. ашбазар,нет,повар,существительное
351,ашкар,нет,нет,очевидный; явный,прилагательное
352,ашкара,нет,нет,явно; открыто,наречие
353,ашкIин,мн. ч. ашкIинар,нет,вдовец,существительное
354,ашкIин хьир,нет,нет,вдова,существительное
355,ашкIин шуй,нет,нет,вдовец,существительное
356,ашна,мн. ч. ашнабур,нет,знакомый; приятель,существительное
357,ашнавел,нет,нет,знакомство,существительное
358,ашузан,мн. ч. ашузанар,нет,черпак,существительное
359,ашхана,мн. ч. ашханабур,нет,столовая,существительное
360,ашчи,мн. ч. ашчибур,нет,дармоед,существительное
361,аяз,мн. ч. аязар,нет,холод; мороз; стужа,существительное
362,аяз кей,нет,нет,морозить,глагол
363,аязди,нет,нет,холодно,наречие
364,аязинф,нет,нет,морозный,прилагательное
365,аязлу,нет,нет,морозный,прилагательное
366,аяки,нет,нет,если,союз
367,баб,мн. ч. бабар,нет,мать,существительное
368,багагь,нет,нет,завтра,наречие
369,багагьинф,нет,нет,завтрашний,прилагательное
370,багами,нет,нет,утро,существительное
371,багамикестги,нет,нет,утром,наречие
372,багамин ямаг,мн. ч. багамин ямагар,нет,завтрак,существительное
373,багаминттар,нет,нет,завтрак,существительное
374,багв,мн. ч. багвар,нет,бок; сторона,существительное
375,багниш,мн. ч. багнишар,нет,медведь,существительное
376,багулив,нет,нет,возле; поблизости; рядом; вблизи,наречие
377,багулив,нет,нет,около,предлог
0,багулив хьуб,нет,нет,соседство,существительное
1,багунттар,нет,нет,родня,существительное
2,багунф,нет,нет,близкий; родственный,прилагательное
3,багур,мн. ч. багурар,да,дурак,существительное
4,багъ1,мн. ч. багъар,нет,сад,существительное
5,багъ2,мн. ч. багъар,нет,фитиль,существительное
6,багъиш акьас,нет,нет,подарить,глагол
7,багълу,мн. ч. багълубур,нет,пачка,существительное
8,багъманчи,мн. ч. багъманчибур,нет,садовод,существительное
9,багъри,нет,нет,любимый,прилагательное
10,багьрум,нет,нет,желанный,прилагательное
11,багъчи,мн. ч. багъчибур,нет,садовод,существительное
12,багьа даваф,нет,нет,дешёвый,прилагательное
13,багьа шуьша,нет,нет,хрусталь,существительное
14,багьа шуьшайинф,нет,нет,хрустальный,прилагательное
15,багьади,нет,да,дорого,наречие
16,багьадур,мн. ч. багьадурар,нет,богатырь,существительное
17,багьайи,нет,нет,дорого,наречие
18,багьайин гъван,мн. ч. багьайин гъванар,нет,яхонт,существительное
19,багьайин шейъ,нет,нет,драгоценность,существительное
20,багьайинф,нет,нет,драгоценный,прилагательное
21,багьана,мн. ч. багьанабур,нет,причина; повод,существительное
22,багьана кикIас девеф,нет,нет,безупречный,прилагательное
23,багьачи,мн. ч. багьачибур,нет,торговец,существительное
24,багьна,мн. ч. багьнабур,да,повод,существительное
25,багIвай,нет,нет,странный; необычный,прилагательное
26,багIвайди,нет,нет,странно; необычно,наречие
27,багIтIур,нет,да,грязь,существительное
28,бадан,мн. ч. баданар,да,туловище,существительное
29,бадбад,мн. ч. бадбадар,нет,индейка,существительное
30,бадра,мн. ч. бадрабур,нет,ведро,существительное
31,баджанах,мн. ч. баджанахар,нет,свояк,существительное
32,баджарагълу,нет,да,способный,прилагательное
33,баджаранф1,нет,нет,способный; умелый,прилагательное
34,баджаранф2,нет,нет,добрый,прилагательное
35,базар,мн. ч. базарар,нет,базар,существительное
36,базу,мн. ч. базубур,нет,жердь,существительное
37,байкъуш1,нет,да,развалины,существительное
38,байкъуш2,мн. ч. байкъушар,да,сова,существительное
39,байрам,мн. ч. байрамар,нет,праздник,существительное
40,бак,мн. ч. бакар,нет,цистерна,существительное
41,бакар,нет,да,нужный; необходимый,прилагательное
42,бакъукъ,нет,нет,халва,существительное
43,бакIлихар,нет,да,фасоль,существительное
44,бала,мн. ч. балабур,да,ребёнок; дитя,существительное
45,бала гIадавел,нет,нет,беспечность,существительное
46,бала гIудай,нет,нет,беспечно,наречие
47,бала гIудаф,нет,нет,беспечный,прилагательное
48,балгъан,нет,да,слизь; мокрота,существительное
49,балла,мн. ч. баллабур,да,несчастье; беда,существительное
50,балугъ,мн. ч. балугъар,нет,рыба,существительное
51,балут,мн. ч. балутар,нет,дуб,существительное
52,палут,мн. ч. палутар,нет,дуб,существительное
53,балхун,нет,нет,гной,существительное
54,бальница,мн. ч. бальницабур,нет,больница,существительное
55,банд,мн. ч. бандар,нет,обруч,существительное
56,барабар,нет,нет,равный,прилагательное
57,баракат,нет,нет,изобилие,существительное
58,барка,нет,нет,праздничный; светный,прилагательное
59,баркаллагь,нет,нет,спасибо,частица
60,бармак,мн. ч. бармакар,нет,папаха,существительное
61,барут,мн. ч. барутар,нет,порох,существительное
62,басмиш,нет,да,разгромить,глагол
63,басня,мн. ч. баснябур,нет,басня,существительное
64,басрикъ,мн. ч. басрикъар,нет,буря,существительное
65,баттал,мн. ч. батталар,нет,чужая (вещь),существительное
66,баттинккабур,нет,нет,туфли,существительное
67,батIар идеми,мн. ч. батIар идемар,нет,красавец,существительное
68,батIар ниъ,мн. ч. батIар ниар,нет,аромат,существительное
69,батIар хьас,нет,нет,похорошеть,глагол
70,батIар хьир,мн. ч. батIар хьирар,нет,красавица,существительное
71,батIарвел,нет,нет,красота,существительное
72,батIарди,нет,нет,красиво,наречие
73,батIарди гъургъай,нет,нет,красноречиво,наречие
74,батIарди гъургъаф,нет,нет,красноречивый,прилагательное
75,батIарди гъургъуб,нет,нет,красноречивость,существительное
76,батIарф,нет,нет,красивый; хороший,прилагательное
77,батIарф даф,нет,нет,некрасивый,прилагательное
78,бахилвел,нет,нет,восхищение,существительное
79,бахилф,нет,нет,восхищённый,прилагательное
80,бахсуз,нет,нет,несчастный,прилагательное
81,бахт1,мн. ч. бахттар,нет,доля; рок,существительное
82,бахт2,нет,нет,счастье,существительное
83,бахтт йиб,нет,нет,удача,существительное
84,бахтт кедаф,мн. ч. бахтт кедаттар,нет,неудачник,существительное
85,бахтт кедаф,нет,нет,невезучий,прилагательное
86,бахтт кеф,нет,нет,счастливый,прилагательное
87,бахттикъара,мн. ч. бахттикъарабур,нет,несчастливец,существительное
88,бахттлу,нет,да,счастливый,прилагательное
89,бахълухъ,мн. ч. бахълухъар,нет,кувалда,существительное
90,бачча,мн. ч. баччабур,нет,кличка,существительное
91,бачI,мн. ч. бачIар,нет,лапа,существительное
92,баша акъас,нет,нет,наказать,глагол
93,башбурт,мн. ч. башбуртар,нет,паспорт,существительное
94,башгъавел,нет,да,отличие; различие,существительное
95,башчи,мн. ч. башчибур,нет,главарь,существительное
96,баябан,мн. ч. баябанар,нет,пустыня,существительное
97,баягъуз,нет,нет,заброшенный,прилагательное
98,баяки,нет,да,снова; опять,наречие
99,баян,нет,нет,известный,прилагательное
100,баят хъуф,нет,нет,заброшенный,прилагательное
101,бег,мн. ч. бегар,нет,бек,существительное
102,бегела,нет,нет,ползком,наречие
103,бегьем акъас,нет,нет,совершить; исполнить,глагол
104,бегьем хъас,нет,нет,созреть,глагол
105,бегьемди,нет,нет,вдоволь,наречие
106,бегьемф1,нет,нет,подробный; полный,прилагательное
107,бегьемф2,нет,нет,безупречный,прилагательное
108,бегьуш,мн. ч. бегьушар,нет,наркоз,существительное
109,бегIли,мн. ч. бегIлибур,нет,вишня; черешня,существительное
110,бедавай,нет,нет,зря,наречие
111,бедбахт,нет,нет,невезучий; несчастный,прилагательное
112,бедгIе,мн. ч. бедгIебур,да,сплетня,существительное
113,без,мн. ч. безар,нет,бязь,существительное
114,бейкар,нет,нет,безработный,прилагательное
115,белге,мн. ч. белгебур,нет,улика,существительное
116,бембег,нет,нет,хлопок; вата,существительное
117,беневша,мн. ч. беневшабур,нет,фиалка,существительное
118,бензи,мн. ч. бензибур,нет,лицо (бессовестное),существительное
119,бере,нет,нет,время,существительное
120,берек,нет,нет,необходимый; нужный,прилагательное
121,берхел,мн. ч. берхелар,нет,палас,существительное
122,берхIем,мн. ч. берхIемар,нет,платье; рубашка,существительное
123,бетер,нет,нет,напасть,существительное
124,бетер,нет,да,худший,прилагательное
125,бетI,мн. ч. бетIар,нет,долька,существительное
126,бетIур,мн. ч. бетIурар,нет,грязь; слякоть,существительное
127,бетIурар,нет,нет,помои,существительное
128,бехIс,нет,нет,зависть,существительное
129,бехIс фаф,нет,нет,завистливый,прилагательное
130,бехIс фаф,нет,нет,завистливо,наречие
131,бигь,мн. ч. бигьар,нет,задаток,существительное
132,бигьам,нет,нет,кончить; созреть,глагол
133,бигьар,нет,нет,приход; урожай,существительное
134,бигьи,мн. ч. бигьибур,нет,паяльник,существительное
135,бизар,нет,нет,скучный,прилагательное
136,бизар акъас,нет,нет,беспокоить,глагол
137,бизарвел,нет,нет,усталость,существительное
138,бизарвелар,нет,нет,неудобство,существительное
139,бика,мн. ч. бикабур,нет,госпожа,существительное
140,бил-бил джагьра,нет,нет,розовый,прилагательное
141,бина1,нет,нет,исход,существительное
142,бина2,нет,нет,основание,существительное
143,бинф туракъ ранг,нет,нет,оранжевый,прилагательное
144,бирдан,нет,нет,сразу,наречие
145,битав,нет,нет,крепкий,прилагательное
146,бицIи,нет,нет,мало,наречие
147,бицIи гунан вахтт,нет,нет,детство,существительное
148,бицIи джакьв,мн. ч. бицIи джакьвар,нет,птичка,существительное
149,бицIи кьут,мн. ч. бицIи кьуттар,нет,камушек,существительное
150,бицIи музар,мн. ч. бицIи музарар,нет,крошка,существительное
151,бицIи нецIв,мн. ч. бицIи нецIвар,нет,ручей,существительное
152,бицIи руш,мн. ч. бицIи рушар,нет,девочка,существительное
153,бицIи сундукь,мн. ч. бицIи сундукьар,нет,шкатулка,существительное
154,бицIи сур,мн. ч. бицIи сурар,нет,ломтик,существительное
155,бицIи усттул,мн. ч. бицIи усттулар,нет,стул,существительное
156,бицIи чарккв,мн. ч. бицIи чаркквар,нет,детёныш,существительное
157,бицIи шиниккв,мн. ч. бицIи шиникквар,нет,малыш,существительное
158,бицIи ягълукъ,мн. ч. бицIи ягълукъар,нет,косынка,существительное
159,бицIиф,мн. ч. бицIиттар,нет,малый (малец),существительное
160,бицIиф,нет,нет,маленький,прилагательное
161,бишекIв,мн. ч. бишекIвар,нет,ястреб,существительное
162,биябур,нет,нет,осрамлённый,прилагательное
163,биябур акъуф,нет,нет,опозоренный,прилагательное
164,биябур хъуф,нет,нет,опозоренный,прилагательное
165,блокнот,мн. ч. блокнотар,нет,блокнот,существительное
166,бокс,нет,нет,бокс,существительное
167,бомба,мн. ч. бомбабур,нет,бомба,существительное
168,борт,мн. ч. бортар,нет,борт,существительное
169,борщ,мн. ч. борщар,нет,борщ,существительное
170,ботаника,нет,нет,ботаника,существительное
171,бригада,мн. ч. бригадабур,нет,бригада,существительное
172,бронза,нет,нет,бронза,существительное
173,брошюра,мн. ч. брошюрабур,нет,брошюра,существительное
174,буг,мн. ч. бугар,да,окраина; сторона,существительное
175,бугаригъ,нет,да,поблизости,наречие
176,бугъ,мн. ч. бугъар,нет,пар,существительное
177,бугъа,мн. ч. бугъабур,нет,бык; вол,существительное
178,бугътан,мн. ч. бугътанар,нет,клевета; навет,существительное
179,бугъу,мн. ч. бугъубур,нет,сова,существительное
180,будай,мн. ч. будаяр,нет,кукла,существительное
181,буй,мн. ч. бувар,нет,рост,существительное
182,буйирмишар,нет,нет,замечание,существительное
183,буйругъ,мн. ч. буйругъар,нет,приказ,существительное
184,букъ акъас,нет,нет,обидеться,глагол
185,букъ акъуф,нет,нет,сердитый,прилагательное
186,букIацин якк,мн. ч. букIацин яккар,да,свинина,существительное
187,булбул,мн. ч. булбул,нет,соловей,существительное
188,булл,нет,да,обильный,прилагательное
189,буллах,мн. ч. буллахар,нет,родник,существительное
190,буллугъчи,нет,нет,богатый,прилагательное
191,булур,мн. ч. булурар,нет,лупа,существительное
192,бурдж,мн. ч. бурджар,нет,долг; обязанность,существительное
193,бурджуни,нет,нет,взаймы,наречие
194,буреф,нет,нет,коричневый,прилагательное
195,буржум,мн. ч. буржумар,нет,пружина,существительное
196,буркьун,мн. ч. буркьунар,нет,даргинец,существительное
197,бурма,мн. ч. бурмабур,нет,винт; шуруп,существительное
198,бурма чIарар алеф,нет,нет,кудрявый,прилагательное
199,бурмабур,нет,нет,кудри,существительное
200,бурмиш,мн. ч. бурмишар,нет,приказание; поручение,существительное
201,бурт,мн. ч. буртар,нет,борт,существительное
202,бурунз,мн. ч. бурунзар,нет,рис,существительное
203,бурнуздин аш,мн. ч. буруздин ашар,нет,плов,существительное
204,бусеIет,нет,да,тотчас,наречие
205,бусракъ,мн. ч. бусракьар,нет,буря,существительное
206,бустан,мн. ч. бустанар,нет,огород,существительное
207,буфайка,мн. ч. буфайкабур,нет,фуфайка,существительное
208,бухьатI,мн. ч. бухьатIар,нет,толстяк (толстушка),существительное
209,бучкка,мн. ч. бучккабур,нет,бочка,существительное
210,буш,нет,нет,слабый,прилагательное
211,буш хьас,нет,нет,обессилеть; ослабеть,глагол
212,бушвел,нет,нет,хрупкость; слабость; худоба,существительное
213,бушкъаб,мн. ч. бушкъабар,нет,блюдце,существительное
214,бушф1,нет,нет,хрупкий; слабый,прилагательное
215,бушф2,нет,нет,вялый,прилагательное
216,буIуф,мн. ч. буIуттар,нет,тихоня; молчун,существительное
217,буюр,мн. ч. буюрар,нет,просьба,существительное
218,буярмиш,мн. ч. буярмишар,нет,поручение; приказание,существительное
219,ваба,нет,нет,холера,существительное
220,ваз,мн. ч. вазар,нет,месяц; луна,существительное
221,вазир,мн. ч. вазирар,нет,представитель; посланник,существительное
222,вазифа,мн. ч. вазифабур,нет,обязанность,существительное
223,вазифа акьас,нет,нет,обязать,глагол
224,вазифабур,нет,нет,обязательство,существительное
225,вайзар,нет,да,плакать; причитать,глагол
226,вайсара,мн. ч. вайсарар,нет,причитание,существительное
227,вайшавар,нет,нет,плач; рыдание,существительное
228,вакил,мн. ч. вакилар,нет,защитник; посол; посланник,существительное
229,вакк,мн. ч. ваккар,нет,кабан,существительное
230,ваккалан якк,мн. ч. ваккалан яккар,нет,свинина,существительное
231,вакъ,мн. ч. вакъар,нет,чашка; миска,существительное
232,вакъиа,мн. ч. вакъиабур,да,событие; факт,существительное
233,вакъфа,нет,да,безвестность,существительное
234,вала,мн. ч. валадар,нет,ребёнок; дитя; мальчик,существительное
235,вала,мн. ч. валибур,нет,представитель; правитель,существительное
236,варв,мн. ч. варвар,нет,пчела,существительное
237,вардиш акъас,нет,нет,воспитать,глагол
238,вардиш дакъуф,нет,нет,невоспитанный,прилагательное
239,вардишакъуб,нет,нет,воспитанность,существительное
240,вардишттинф,нет,нет,воспитанный,прилагательное
241,вардишф,нет,нет,воспитанный,прилагательное
242,вартт,нет,нет,вверх; наверх,наречие
243,варттал,нет,нет,наверху; сверху,наречие
244,варттал алеф,нет,нет,верхний,прилагательное
245,вартталас агубар,нет,нет,наружность,существительное
246,вартталди,нет,нет,вверх; наверх,наречие
247,вартти багв,мн. ч. вартти багвар,нет,верхушка,существительное
248,варттинф,нет,нет,верхний,прилагательное
249,варха,нет,нет,подальше; далеко,наречие
250,варха гьаттар даргваф,нет,нет,близорукий,прилагательное
251,вархаас,нет,нет,издалека,наречие
252,вархавел,мн. ч. вархавелар,да,расстояние,существительное
253,вархайи,нет,нет,вдали,наречие
254,вархайиас,нет,нет,издалека,наречие
255,вархайиаф,нет,нет,дальний,прилагательное
256,вархалас,нет,нет,издалека,наречие
257,варханф,нет,нет,дальний,прилагательное
258,вас са миннат,мн. ч. вас са миннатар,нет,просьба,существительное
259,васият,мн. ч. васиятар,нет,завещание,существительное
260,ватан,мн. ч. ватанар,нет,родина; отечество,существительное
261,ватанагьли,мн. ч. ватанагьлибур,нет,соотечественник,существительное
262,ватандаш,мн. ч. ватандашар,нет,гражданин,существительное
263,ватандинф,мн. ч. ватандинттар,нет,соотечественник; гражданин,существительное
264,ватанперас,мн. ч. ватанперасар,нет,патриот,существительное
265,ватанчи,мн. ч. ватанчибур,нет,гражданин,существительное
266,вафа,мн. ч. вафабур,нет,отдача,существительное
267,вафалу,нет,нет,полезный; благодатный,прилагательное
268,вахт,нет,нет,время,существительное
269,вахтт,мн. ч. вахттар,нет,час; пора,существительное
270,ваъ,нет,нет,нет,частица
271,вегьши,мн. ч. вегьшибур,да,дикарь,существительное
272,вегIда,мн. ч. вегIдабур,да,время; срок,существительное
273,вегIз,мн. ч. вегIзар,нет,наставление; проповедь,существительное
274,вегIшинф,нет,нет,дикий,прилагательное
275,велвела,мн. ч. велвелар,да,шум; крик; переполох,существительное
276,велед,мн. ч. веледар,да,ребёнок; дитя; мальчик,существительное
277,вереф,нет,нет,годный,прилагательное
278,верхь,мн. ч. верхьар,нет,тополь,существительное
279,верш,нет,нет,сто,числительное
280,верш,мн. ч. вершар,нет,сотня,существительное
281,верш ис,мн. ч. верш исар,нет,век,существительное
282,верш исанф,нет,нет,вековой,прилагательное
283,вершф,нет,нет,сотый,прилагательное
284,вес,нет,нет,пойти,глагол
285,веф,нет,нет,твой,местоимение
286,вехIши,мн. ч. вехIшибур,нет,дикарь,существительное
287,вехIши инсан,мн. ч. вехIши инсанар,нет,варвар,существительное
288,вехIшинф,нет,нет,дикий,прилагательное
289,вец,мн. ч. вецар,нет,бык; вол,существительное
290,викIегь,нет,нет,мужественный,прилагательное
291,викIегьвел,нет,нет,смелость,существительное
292,вилаят,мн. ч. вилаятар,нет,округа; область,существительное
293,виргул,мн. ч. виргулар,нет,запятая,существительное
294,вичI-вичIар,мн. ч. вичI-вичIарар,нет,щекотка,существительное
295,врач,мн. ч. врачар,нет,врач,существительное
296,вун,нет,нет,ты,местоимение
297,гажин,мн. ч. гажинар,нет,графин,существительное
298,газит,мн. ч. газитар,нет,газета,существительное
299,гам,мн. ч. гамар,нет,замок,существительное
300,гами,мн. ч. гамибур,нет,корабль; судно,существительное
301,гамиш,мн. ч. гамишар,нет,буйвол,существительное
302,гамишин урч,мн. ч. гамишин урчар,нет,буйволёнок,существительное
303,гандридж,мн. ч. гандриджар,нет,иней,существительное
304,гап,мн. ч. гапар,нет,ладонь,существительное
305,гаргар,мн. ч. гаргарар,нет,колокольчик,существительное
306,гардан,мн. ч. гарданар,нет,шея,существительное
307,гарданбаз,мн. ч. гарданбазар,нет,хомут,существительное
308,гарданди аф,мн. ч. гарданди аттар,нет,иждивенец,существительное
309,гардандиас адайхьа куллагьар,нет,нет,ожерелье,существительное
310,гардандин гвадж,мн. ч. гардандин гваджар,нет,затылок,существительное
311,гардандин кьакь,мн. ч. гардандин кьакьар,нет,шея,существительное
312,гарухар,нет,нет,фасоль,существительное
313,гарч,мн. ч. гарчар,да,половина,существительное
314,гаф,мн. ч. гафар,нет,слово; разговор,существительное
315,гаф-чIал,мн. ч. гафар-чIалар,нет,замечание; упрёк,существительное
316,гаш,мн. ч. гашар,нет,голод,существительное
317,гаш ккеф,нет,нет,голодный,прилагательное
318,гашвел1,нет,нет,голод,существительное
319,гашвел2,нет,нет,скупость,существительное
320,гашин-гъуй,мн. ч. гашин-гъуяар,нет,скупец,существительное
321,гашинф,мн. ч. гашинттар,нет,жадный (человек),существительное
322,гашинф,нет,нет,жадный,прилагательное
323,гвадж,мн. ч. гваджар,нет,затылок,существительное
324,гвегIванар,мн. ч. гвегIванар,нет,носок; чулок,существительное
325,гебур,нет,нет,она,местоимение
326,геда,мн. ч. гедабур,да,мальчик; юноша; парень; сын,существительное
327,гедабур-рушар,нет,нет,молодёжь,существительное
328,гена,нет,да,ещё; опять,наречие
329,генг,нет,нет,обеспеченный,прилагательное
330,генгди,нет,нет,широко; просторно,наречие
331,генев,мн. ч. геневар,да,конопля,существительное
332,герек,нет,нет,годный,прилагательное
333,герек даваф,нет,нет,бесполезный; ненужный,прилагательное
334,герек хьас,нет,нет,понадобиться,глагол
335,герекф1,нет,нет,нужный; необходимый,прилагательное
336,герекф2,нет,нет,годный; приемлемый,прилагательное
337,гигIван,мн. ч. гигIванар,да,носок; чулок,существительное
338,гидехIен,нет,нет,столько,наречие
339,гилгенф,нет,нет,круглый,прилагательное
340,гим,мн. ч. гимар,нет,годекан,существительное
341,гирами,нет,нет,милый; возлюбленный,прилагательное
342,гиран акъас,нет,нет,обидеть; оскорбить; опечалить,глагол
343,гиран хьуф,нет,нет,обиженный,прилагательное
344,гиранвел,мн. ч. гиранвелар,нет,обида,существительное
345,гирванкка,мн. ч. гирванккабур,нет,фунт,существительное
346,гиргенф,нет,нет,круглый,прилагательное
347,гирекхъуб,нет,нет,надобность; необходимость,существительное
348,гитан,мн. ч. гитанар,нет,кошка,существительное
349,гитанин чарккв,мн. ч. гитанин чаркквар,нет,котёнок,существительное
350,гич,нет,нет,туда,наречие
351,гуг,мн. ч. гугар,нет,череп,существительное
352,гугурт,мн. ч. гугуртар,нет,сера,существительное
353,гудж,мн. ч. гуджар,нет,сила; мощь,существительное
354,гудж алихъуб,нет,нет,усилие,существительное
355,гудж алихьун,нет,нет,сильно,наречие
356,гудж аф,мн. ч. гудж аттар,нет,власть,существительное
357,гудж аф,нет,нет,мощный,прилагательное
358,гудж хъай,нет,нет,мощно,наречие
359,гуджар гуланас,нет,нет,обессилеть,глагол
360,гуджлу,нет,нет,мощный,прилагательное
361,гуджлувел,мн. ч. гуджлувелар,нет,сила; могущество,существительное
362,гула,мн. ч. гулабур,нет,пуля,существительное
363,гуланас,нет,нет,теряться; пропасть,глагол
364,гуланас акъас,нет,нет,потерять (вес),глагол
365,гулуб1,нет,нет,исчезновение,существительное
366,гулуб2,нет,нет,потеря,существительное
367,гулун вес,нет,нет,пропасть,глагол
368,гулуф,нет,нет,безвестность,существительное
369,гунагь,мн. ч. гунагьар,нет,грех,существительное
370,гунагьар кедаф,нет,нет,безгрешный,прилагательное
371,гунагьар кеф,мн. ч. гунагьар кеттар,нет,грешник,существительное
372,гунагьсуз,нет,нет,безгрешный,прилагательное
373,гунагьчи,мн. ч. гунагьчибур,нет,грешник; нечестивец,существительное
374,гуни,мн. ч. гунивар,нет,хлеб,существительное
375,гунтI,мн. ч. гунтIар,нет,копна,существительное
376,гурджи,мн. ч. гурджибур,нет,грузин,существительное
377,гучI,мн. ч. гучIар,нет,испуг; страх,существительное
378,гучI алихьуб,мн. ч. гучI алихьубар,нет,угроза,существительное
379,гучI вереф,нет,нет,страшный,прилагательное
380,гучI гьихьуб,мн. ч. гучI гьихьубар,нет,угроза,существительное
381,гучI хъудаф,нет,нет,бесстрашный,прилагательное
382,гучI хьас,нет,нет,испугаться,глагол
383,гучIай,нет,нет,боязливо,наречие
384,гучIаф,нет,нет,трусливый,прилагательное
385,гучIвел,мн. ч. гучIвелар,нет,испуг; страх; боязнь,существительное
386,гучIевел,нет,нет,трусость,существительное
387,гучIрахI,мн. ч. гучIрахIар,нет,трус,существительное
388,гучIрахI,нет,нет,робкий; трусоватый,прилагательное
389,гучIрахIвел,нет,нет,трусость,существительное
390,гучIсуз,нет,нет,бесстрашный,прилагательное
391,гьудег,мн. ч. гьудегар,нет,буйволёнок,существительное
392,гьузги,мн. ч. гьузгибур,да,зеркало,существительное
393,гьузел,мн. ч. гьузелар,нет,красавица,существительное
394,гьузелвел,нет,нет,красота,существительное
395,гьузчи,мн. ч. гьузчибур,нет,наблюдатель; шпион,существительное
396,гьулге,мн. ч. гьулгебур,нет,зонт,существительное
397,гьулерш,мн. ч. гьулершар,нет,клей,существительное
398,гьулеш,мн. ч. гьулешар,нет,клей,существительное
399,гьулишанвел,нет,нет,красота,существительное
400,гьурчег,нет,нет,стройный; красивый,прилагательное
401,гюлейтIар,нет,нет,гулянье,существительное
402,гюлишан,нет,нет,прекрасный,прилагательное
403,гюна,нет,нет,юг,существительное
404,гюна,нет,нет,солнечный,прилагательное
0,гьаб,мн. ч. гьабар,нет,чашка,существительное
1,гьавур,нет,да,понимание; осознание,существительное
2,гьавурди адай,нет,нет,непонятно; нелепо,наречие
3,гьавурди адар хьаф,нет,нет,непонятный,прилагательное
4,гьавурди архьас,нет,нет,понять; осознать,глагол
5,гьавурди архьаф,нет,нет,понятный,прилагательное
6,гьавурди архьуб,нет,нет,понимание; осознание; ясность,существительное
7,гьавурди аф,нет,да,ясный; понятный,прилагательное
8,гьад,мн. ч. гьадар,нет,молот; молоток,существительное
9,гьадаланф,нет,да,ударять,глагол
10,гьадахъай,мн. ч. гьадахъаяр,нет,булавка,существительное
11,гьадивас,нет,нет,поднять,глагол
12,гьаз,нет,нет,зелень,существительное
13,гьазевел,нет,нет,свежесть,существительное
14,гьазеф,нет,нет,зелёный,прилагательное
15,гьазиди,нет,нет,будучи,деепричастие
16,гьайри,нет,да,никто,местоимение
17,гьалатI,мн. ч. гьалатIар,да,ошибка,существительное
18,гьалибвел,мн. ч. гьалибвелар,нет,победа,существительное
19,гьам,нет,нет,печаль; скорбь; тоска; переживание; горе,существительное
20,гьам,нет,нет,грустный,прилагательное
21,гьам кей,нет,нет,печально; горестно,наречие
22,гьам кидавел,нет,нет,беззаботность,существительное
23,гьам хьуб,нет,нет,сожаление,существительное
24,гьамар акьас,нет,нет,переживать; горевать,глагол
25,гьамар-дардари аф,нет,нет,скорбящий,прилагательное
26,гьамари угуф,нет,нет,горюющий,прилагательное
27,гьамкеф,нет,нет,грустный,прилагательное
28,гьамлу,нет,нет,печальный,прилагательное
29,гьамлуди,нет,нет,печально,наречие
30,гьамсуз,нет,нет,беспечный; беззаботный,прилагательное
31,гьамсузвел,нет,нет,беспечность; беззаботность,существительное
32,гымасудзи,нет,нет,беспечно; беззаботно,наречие
33,гьамфай,нет,нет,печально; горестно,наречие
34,гьара акьуб,нет,нет,грабёж; разбой,существительное
35,гьараг,мн. ч. гьарагар,да,ожерелье,существительное
36,гьарачи,мн. ч. гьарачибур,да,грабитель; разбойник,существительное
37,гьареф,нет,нет,заглавный,прилагательное
38,гьариб,нет,нет,костлявый,прилагательное
39,гьарибвел,нет,да,худоба; худощавость,существительное
40,гьархьалай,мн. ч. гьархьалаяар,нет,соня,существительное
41,гьархьас,нет,нет,спать,глагол
42,гьас,нет,нет,принести,глагол
43,гьафил хьас,нет,нет,забыться,глагол
44,гьвад,мн. ч. гьвадар,нет,потолок; крыша,существительное
45,гьван,мн. ч. гьванар,нет,камень,существительное
46,гьванкIар,нет,нет,север,существительное
47,гыба,мн. ч. гьибабур,да,клевета; сплетня,существительное
48,гьиба акьас,нет,да,оклеветать,глагол
49,гьибгьер,мн. ч. гьибгьерар,нет,рябина,существительное
50,гьивгьар,мн. ч. гьивгьарар,да,брусника,существительное
51,гьил,мн. ч. гьилар,нет,рука,существительное
52,гьил гьушан,нет,нет,простите,междометие
53,гьил хъухьай,нет,нет,мелочно,наречие
54,гьили ай,нет,нет,зажиточно,наречие
55,гьили аф,нет,нет,зажиточность,существительное
56,гьили аф,нет,нет,обеспеченный,прилагательное
57,гьили ахьуб,нет,нет,состоятельность,существительное
58,гьили хьуб,нет,нет,зажиточность,существительное
59,гьилив,мн. ч. гьиливар,нет,рукав,существительное
60,гьилин гIан,мн. ч. гьилин гIанар,нет,ладонь,существительное
61,гьират,нет,да,честь,существительное
62,гьиратлувел,нет,нет,ревность,существительное
63,гьирд,мн. ч. гьирдар,нет,липа,существительное
64,гьирхIуб,нет,нет,запинка; задержка,существительное
65,гьузанас,нет,нет,подождать,глагол
66,гьузар акьас,нет,нет,задержать,глагол
67,гьузуб,мн. ч. гьузубар,нет,запинка; задержка; перерыв,существительное
68,гьуй,мн. ч. гьубур,нет,собака; пёс; овчарка,существительное
69,гьулантт,мн. ч. гьуланттар,нет,покупатель,существительное
70,гьурагъал,мн. ч. гьурагъалар,нет,яйцо,существительное
71,гьурбат,мн. ч. гьурбатар,нет,чужбина,существительное
72,гьургьуб,мн. ч. гьургьубар,нет,спор; перепалка,существительное
73,гьурд,мн. ч. гьурдар,нет,кулак,существительное
74,гьурт,мн. ч. гьуртар,нет,пена,существительное
75,гьутIу хъвехь гIаф,нет,нет,курносый,прилагательное
76,гьух,мн. ч. гьухар,да,горло,существительное
77,гьушанас,нет,нет,покупать,глагол
78,гъушу шейъ,мн. ч. гъушу шейъар,нет,покупка,существительное
79,гъуянас,нет,нет,принять,глагол
80,гьава1,мн. ч. гьавабур,нет,воздух; атмосфера; среда; климат; погода,существительное
81,гьава2,мн. ч. гьавабур,нет,мотив,существительное
82,гьава3,мн. ч. гьавабур,нет,чувство,существительное
83,гьава хьас,нет,нет,вырасти,глагол
84,гьававел,мн. ч. гьававелар,нет,высота,существительное
85,гьавади,нет,нет,высоко,наречие
86,гьавайи1,нет,нет,впустую; зря,наречие
87,гьавайи2,нет,нет,бесплатно; даром; безвозмездно,наречие
88,гьавайи ухIаф,мн. ч. гьавайи ухIаттар,нет,дармоед,существительное
89,гьавайик,нет,нет,высоко,наречие
90,гьавайикес,нет,нет,громко,наречие
91,гьавайинф1,нет,нет,бесполезный,прилагательное
92,гьавайинф2,нет,нет,воздушный,прилагательное
93,гьаваф,нет,нет,высокий,прилагательное
94,гьаписаь,нет,нет,вон,наречие
95,гьапчи,нет,нет,туда (вниз),наречие
96,гьагьрай,нет,нет,ах,междометие
97,гьайда,нет,нет,айда; ну-ка,междометие
98,гьакIанф,нет,нет,поддельный; фальшивый; бесполезный,прилагательное
99,гьакIанф даваф,нет,нет,значимость,существительное
100,гьал,нет,нет,сейчас; теперь,наречие
101,гьала,нет,нет,всё ещё,наречие
102,гьалдинф,нет,нет,теперешний; сегодняшний,прилагательное
103,гьалисаас,нет,нет,оттуда,наречие
104,гьаллисаь,нет,нет,там (наверху),наречие
105,гьаме суманвел,нет,нет,подобие,существительное
106,гьаме суманф,нет,нет,подобный,прилагательное
107,гьамиштти,нет,нет,так,частица
108,гьамишттинф,нет,нет,такой; такой-то,местоимение
109,гьара,нет,нет,ну-ка,междометие
110,гьарай,нет,нет,аж,частица
111,гьарай,мн. ч. гьараяр,нет,крик; призыв,существительное
112,гьараяр,нет,нет,шум; переполох,существительное
113,гьарф,нет,нет,каждый; всякий,прилагательное
114,гьар-ягъа,нет,нет,ежедневно,наречие
115,гьате,нет,нет,тот,местоимение
116,гьатисаас,нет,нет,оттуда,наречие
117,гьатисаас,нет,нет,вот,частица
118,гьатисагь,нет,нет,там,частица
119,гьатисади,нет,нет,туда; вон,наречие
120,гьатисади,нет,нет,вот,частица
121,гьатисаь,нет,нет,вон; там,наречие
122,гьатисаь,нет,нет,вот,частица
123,гьатич,нет,нет,туда,наречие
124,гьатта,нет,да,аж,частица
125,гьевес,мн. ч. гьевесар,да,чувство,существительное
126,гьеджат,мн. ч. гьеджатар,да,нужда,существительное
127,гьез,мн. ч. гьезар,нет,наслаждение,существительное
128,гьекI,мн. ч. гьекIар,нет,цена,существительное
129,гьекI,нет,нет,правильный; верный,прилагательное
130,гьел,мн. ч. гьелар,нет,стрела,существительное
131,гьелал,нет,нет,годный,прилагательное
132,гьелбет,нет,нет,конечно,вводное слово
133,гьелбетта,нет,нет,конечно,вводное слово
134,гьелсуз,нет,нет,нездоровый,прилагательное
135,гьеме,нет,нет,этот,местоимение
136,гьемишанди,нет,нет,всегда,наречие
137,гьемишанф,нет,нет,постоянный; вечный,прилагательное
138,гьер вазала,нет,нет,ежемесячно,наречие
139,гьер джуреттар,нет,нет,разное,существительное
140,гьер иса,нет,нет,ежегодно,наречие
141,гьер рангуни ай,нет,нет,цветасто,наречие
142,гьер хIурин чIал,мн. ч. гьер хIурин чIалар,нет,диалект,существительное
143,гьерттар,нет,нет,разное,существительное
144,гьерттин гьава,нет,нет,особенность,существительное
145,гьерф,нет,нет,всякий; каждый,прилагательное
146,гьерф,нет,нет,разница; разное,существительное
147,гьерчибатан,нет,нет,легкомысленный,прилагательное
148,гьесул хьас,нет,да,оказаться,глагол
149,гьетебете,мн. ч. гьетебетебур,нет,лепет,существительное
150,гьеч,мн. ч. гьечар,нет,яблоко,существительное
151,гьин,нет,нет,конечно,вводное слово
152,гьиндуьшкка,мн. ч. гьиндуьшккабур,нет,индюшка,существительное
153,гьинкI,мн. ч. гьинкIар,нет,икота,существительное
154,гьич,нет,да,нисколько,наречие
155,гьичра,нет,нет,нисколько,наречие
156,гьудуркIуб,мн. ч. гьудуркIубар,нет,недостаток; изъян,существительное
157,гьудуркIуф,нет,нет,полоумный,прилагательное
158,гьул адаф,нет,нет,бессильный,прилагательное
159,гьунар1,мн. ч. гьунарар,нет,заслуга,существительное
160,гьунар2,мн. ч. гьунарар,нет,подвиг,существительное
161,гьунар кей,нет,нет,умело,наречие
162,гьунарлу,нет,нет,умелый; искусный,прилагательное
163,гьунарлуди,нет,нет,умело; мастерски,наречие
164,гьунарчи,мн. ч. гьунарчибур,нет,фокусник,существительное
165,гьундур,мн. ч. гьундурар,нет,повеса,существительное
166,гьуркьун,нет,нет,успешно,наречие
167,гьуркIуф,нет,нет,зрелый,прилагательное
168,гьуруцаф усттуларигь,мн. ч. гьуруцаттар усттуларигь,нет,официант,существительное
169,гьучархьуб,нет,нет,встреча,существительное
170,гьучихьас,нет,нет,рекомендация; предложение,существительное
171,гьуькум,мн. ч. гьуькумар,нет,наказание,существительное
172,гIагьдис,нет,нет,приехать,глагол
173,гIагьуюб,нет,нет,неправда,существительное
174,гIад,мн. ч. гIадар,нет,звезда,существительное
175,гIадивас,нет,нет,ударить,глагол
176,гIадулвел,нет,нет,мягкость,существительное
177,гIадулди,нет,да,мягко,наречие
178,гIазаб,нет,нет,мучение,существительное
179,гIазабинф,нет,нет,трудный,прилагательное
180,гIазиз,нет,нет,любимый; обожаемый,прилагательное
181,гIайиб,нет,да,стыд,существительное
182,гIала шуй,мн. ч. гIала шуяр,нет,гость; кунак,существительное
183,гIан1,мн. ч. гIанар,нет,нутро,существительное
184,гIан2,мн. ч. гIанар,нет,двор,существительное
185,гIана,нет,нет,внутри,наречие
186,гIанаас,нет,нет,изнутри,наречие
187,гIайнабур,нет,нет,очки,существительное
188,гIанаь,нет,нет,внутри,наречие
189,гIанеф,нет,нет,жирный,прилагательное
190,гIантIи вардиш акъуф,нет,нет,избалованный,прилагательное
191,гIантIикIай,нет,нет,избалованный,прилагательное
192,гIабахь,мн. ч. гIабахъар,нет,вечер,существительное
193,гIабахьи,нет,нет,вечером,наречие
194,гIабдал,мн. ч. гIабдалар,нет,болван,существительное
195,гIабдал,нет,нет,непутёвый,прилагательное
196,гIабиччай,мн. ч. гIабиччаяр,нет,болван,существительное
197,гIар,мн. ч. гIарар,нет,пастбище; сенокос,существительное
198,гIарза,мн. ч. гIарзабур,нет,жалоба,существительное
199,гIаруцай1,мн. ч. гIаруцаяр,нет,шалопай,существительное
200,гIаруцай2,мн. ч. гIаруцаяр,нет,попрошайка,существительное
201,гIархьуб,нет,нет,развращенность,существительное
202,гIаттивас,нет,нет,вытащить,глагол
203,гIаттивуй,мн. ч. гIаттивубар,нет,выбор,существительное
204,гIатIуб,нет,нет,общительность,существительное
205,гIатIуна,нет,нет,общительно,наречие
206,гIатIуф,нет,нет,общительный,прилагательное
207,гIатIушвел,нет,нет,общительность,существительное
208,гIатIушинф,нет,нет,дружелюбный,прилагательное
209,гIатIушун,нет,нет,общительно,наречие
210,гIафна,мн. ч. гIафнабур,нет,огурец,существительное
211,гIахъуб,нет,нет,беспорядок,существительное
212,гIачагуланас,нет,нет,теряться,глагол
213,гIачучIуб,нет,нет,участие,существительное
214,гIашкъ,мн. ч. гIашкъар,нет,увлечение; страсть,существительное
215,гIебиччи,мн. ч. гIебиччибур,нет,болван,существительное
216,гIедат,мн. ч. гIедатар,нет,обычай; адат; традиция,существительное
217,гIеджибанвел,нет,нет,странность; необычность,существительное
218,гIеджибангъилди,нет,нет,странно; непонятно,наречие
219,гIеджибанф,нет,нет,странноватый; непонятный,прилагательное
220,гIеджибистти,нет,да,странно; удивительно,наречие
221,гIеджиз,мн. ч. гIеджизар,нет,бедняк,существительное
222,гIеджиз,нет,нет,беспомощный,прилагательное
223,гIеджизвел,нет,нет,бедность; нищета; нужда,существительное
224,гIеджизди,нет,нет,бедно,наречие
225,гIеджизди адаф,нет,нет,обеспеченный,прилагательное
226,гIеджизф,нет,нет,бедный; жалкий; несчастный,прилагательное
227,гIезаб,мн. ч. гIезабар,нет,мука; мучение; боль,существительное
228,гIезаб йис,нет,нет,пытать,глагол
229,гIезаб ккей,нет,нет,мучительно,наречие
230,гIезаб эс,нет,нет,мучить,глагол
231,гIезабар,нет,нет,страдания,существительное
232,гIезабарикк ккеф,мн. ч. гIезабарикк ккеттар,нет,мученик,существительное
233,гIезабин унар,нет,нет,стоны,существительное
234,гIезабинф,нет,нет,мучительный,прилагательное
235,гIезаблу,нет,нет,мучительный,прилагательное
236,гIезаблуди,нет,нет,мучительно,наречие
237,гIемчи,нет,нет,чихание; чих,существительное
238,гIемчи акьас,нет,нет,чихнуть,глагол
239,гIер адай,нет,нет,бесстыдно,наречие
240,гIер адаф,мн. ч. гIер адаттар,нет,бесстыдник,существительное
241,гIерекьи,мн. ч. гIерекьибур,нет,водка,существительное
242,гIерза,мн. ч. гIерзабур,нет,заявление,существительное
243,гIерзачи,мн. ч. гIерзачибур,нет,заявитель,существительное
244,гIерсузвел,нет,нет,бессовестность,существительное
245,гIерсузди,нет,нет,бессовестно,наречие
246,гIерчIвеф,нет,нет,посторонний,прилагательное
247,гIетIлас,мн. ч. гIетIласар,нет,атлас,существительное
248,гIешкъ,нет,нет,желание,существительное
249,гIешкъ алди,нет,нет,увлечённо,наречие
250,гIешкъ фаф,нет,нет,увлечённый,прилагательное
251,гIешкъ хъуб,нет,нет,желание,существительное
252,гIешкъвел,нет,нет,увлечённость,существительное
253,гIешкъунинф,нет,нет,желанный,прилагательное
254,гIешукъ,мн. ч. гIешукъар,нет,ашуг,существительное
255,гIибар,нет,нет,бусы,существительное
256,гIикIас,нет,нет,сунуть,глагол
257,гIилимлу,нет,нет,научный,прилагательное
258,гIилимлувел,нет,нет,научность,существительное
259,гIилимлуди,нет,нет,научно,наречие
260,гIилми,мн. ч. гIилмибур,нет,наука,существительное
261,гIинчI,мн. ч. гIинчIар,нет,улыбка,существительное
262,гIифрит,мн. ч. гIифритар,нет,демон; дьявол,существительное
263,гIифритвел,нет,нет,хитрость,существительное
264,гIихьас,нет,нет,бросить,глагол
265,гIуб,мн. ч. гIубар,нет,лягушка,существительное
266,гIуд,мн. ч. гIудар,нет,куропатка,существительное
267,гIудафанар,нет,нет,близнецы,существительное
268,гIудулвел,нет,нет,мягкость,существительное
269,гIудулди,нет,нет,мягко; душевно,наречие
270,гIудулф,нет,нет,мягкий; душевный,прилагательное
271,гIуй,мн. ч. гIуяр,нет,картошка,существительное
272,гIул,мн. ч. гIулар,нет,лето,существительное
273,гIулана,нет,нет,летом,наречие
274,гIун,мн. ч. гIунар,нет,плечо,существительное
275,гIун хьудаф,нет,нет,беззащитный,прилагательное
276,гIунар,нет,нет,спина,существительное
277,гIунарин яIан,мн. ч. гIунарин яIанар,нет,позвоночник,существительное
278,гIур1,мн. ч. гIурар,нет,заяц; кролик,существительное
279,гIур2,мн. ч. гIурар,нет,мука; тесто,существительное
280,гIур хулан,мн. ч. гIурар хулан,нет,кролик,существительное
281,гIургIур,нет,нет,слизь; мокрота,существительное
282,гIурч,мн. ч. гIурчар,нет,охота,существительное
283,гIурчахьан,мн. ч. гIурчахъанар,нет,охотник,существительное
284,гIурчевел,нет,нет,охота,существительное
285,гIуьбехь,мн. ч. гIуьбехьар,нет,вечер,существительное
286,гIуьбехъми,нет,нет,вечером,наречие
287,гIуьзур кеф,нет,нет,нездоровый,прилагательное
288,гIуьзур кIацI керхьеб,мн. ч. гIуьзур кIацIар керхьебар,нет,болезнь,существительное
289,гIуьфуверш,нет,нет,пятьсот,числительное
290,гIуьфуд,нет,нет,пять,числительное
291,гIуьфцIур,нет,нет,пятьдесят,числительное
292,гIэшкъ алди,нет,нет,устремлённо,наречие
293,гIэшкъ фаф,нет,нет,устремлённый,прилагательное
294,гIэшкъвел,нет,нет,устремлённость,существительное
295,дабакь,мн. ч. дабакьар,нет,ящур,существительное
296,дабакь,мн. ч. дабакьар,нет,хромой,прилагательное
297,дабакьвел,нет,нет,хромота,существительное
298,дабан,мн. ч. дабанар,нет,каблук,существительное
299,давамлу,нет,нет,продолжительный,прилагательное
300,давамлувел,нет,нет,долгота,существительное
301,даваттар акьуб,нет,нет,хулиганство,существительное
302,даваттар аркьаф,мн. ч. даваттар аркьаттар,нет,хулиган,существительное
303,даваттар аркьаф,мн. ч. даваттар аркьаттар,нет,шаловливый,прилагательное
304,даваттин гунтI,мн. ч. даваттин гунтIар,нет,проказник; шалун,существительное
305,давдагъ,мн. ч. давдагъар,нет,дурень; оболтус,существительное
306,давур,мн. ч. давурар,нет,период; век,существительное
307,даги,мн. ч. дагибур,нет,ишак; осёл,существительное
308,дагин къамч,мн. ч. дагин къамчар,нет,ослёнок,существительное
309,дагучIай,нет,нет,отважно; храбро,наречие
310,дагучIаф,нет,нет,бесстрашный; храбрый,прилагательное
311,дагучIуб,нет,нет,смелость,существительное
312,дагъал,мн. ч. дагъалар,да,осколок,существительное
313,дагълу,нет,нет,горный,прилагательное
314,дагъусттан хьир,мн. ч. дагъусттан хьирар,нет,дагестанка,существительное
315,дагъутстандинф,мн. ч. дагъутстандинттар,нет,дагестанец,существительное
316,дагъутстанлу,мн. ч. дагъутстанлубур,нет,дагестанец,существительное
317,дагь замана,мн. ч. дагь заманабур,нет,древность,существительное
318,дагь заманайинф,нет,нет,старый; старинный,прилагательное
319,дагьар,мн. ч. дагьарар,нет,гора; скала,существительное
320,дагьарарин ачI,мн. ч. дагьарарин ачIар,нет,ущелье,существительное
321,дагьарариъ гьурзан рекъ,мн. ч. дагьарариъ гьурзан рекъар,нет,перевал,существительное
322,дагьариас вере мукь,мн. ч. дагьариас вере мукьар,нет,туннель,существительное
323,дагьарин ачI,мн. ч. дагьарин ачIар,нет,пропасть,существительное
324,дагьарин улуд,мн. ч. дагьарин улудар,нет,пещера,существительное
325,дагьур,мн. ч. дагьурар,нет,серп,существительное
326,дагIай,нет,нет,нелепо; неумело,наречие
327,дагIайвел,нет,нет,неосведомлённость,существительное
328,дагIви,мн. ч. дагIвибур,нет,война,существительное
329,дад1,мн. ч. дадар,нет,отец; папа,существительное
330,дад2,мн. ч. дадар,нет,вкус,существительное
331,дадна-баб,нет,нет,родители,существительное
332,дадсуз,нет,нет,невкусный,прилагательное
333,дадуьрхьеф1,нет,нет,невезучий; несчастный,прилагательное
334,дадуьхьеф2,нет,нет,непримиримый,прилагательное
335,дазу,мн. ч. дазубур,нет,граница,существительное
336,дайиб,нет,нет,отказ,существительное
337,дайран,нет,да,немало; значительно,наречие
338,даккан акьас,нет,нет,отвращение,существительное
339,дакканди1,нет,нет,брезгливо,наречие
340,дакканди2,нет,нет,нехотя,наречие
341,дакканф,нет,нет,неприятный,прилагательное
342,дакьикьа,мн. ч. дакьикьабур,нет,минута,существительное
343,дакIар,мн. ч. дакIарар,да,окно,существительное
344,далай,мн. ч. далаяр,нет,песня; частушка,существительное
345,далгъас1,нет,нет,разворотить,глагол
346,далгъас2,нет,нет,разойтись,глагол
347,далгъуб,нет,нет,разрушение; хаос,существительное
348,далдам,мн. ч. далдамар,да,барабан,существительное
349,далдамчи,мн. ч. далдамчибур,да,барабанщик,существительное
350,далил,мн. ч. далилар,нет,аргумент; довод,существительное
351,даллу,мн. ч. даллубур,нет,дурак; дурень,существительное
352,даллувел,нет,нет,дурость,существительное
353,далюкIе Iуьмур хъаф,нет,нет,вечный,прилагательное
354,дамакъар,нет,нет,высокомерие,существительное
355,дамакъар кеф,нет,нет,гордый,прилагательное
356,дамакъвел,нет,нет,заносчивость; зазнайство,существительное
357,дамакъилди,нет,нет,заносчиво,наречие
358,дамар,мн. ч. дамарар,нет,сустав,существительное
359,дамаринф,нет,нет,жилистый; сосудистый,прилагательное
360,дамашникар,нет,нет,чувяки,существительное
361,дамдам,мн. ч. дамдамар,нет,барабан,существительное
362,дамдамчи,мн. ч. дамдамчибур,нет,барабанщик,существительное
363,даммар,нет,нет,жила,существительное
364,данг,мн. ч. дангар,нет,стук; лязг; звон,существительное
365,дар1,мн. ч. дарар,нет,палка; балка; брус,существительное
366,дар2,мн. ч. дарар,нет,лес,существительное
367,дар3,мн. ч. дарар,нет,стебелёк,существительное
368,дар,нет,да,узкий; тесный,прилагательное
369,дараджа,нет,нет,положение,существительное
370,дарамат,мн. ч. дараматар,нет,сооружение; здание,существительное
371,даран,мн. ч. даранар,да,кабан,существительное
372,дарвел,нет,да,узость; теснота,существительное
373,дарги шуй,мн. ч. дарги шувар,нет,даргинец,существительное
374,дард,мн. ч. дардар,нет,переживание; скорбь; горе; тоска; мучение,существительное
375,дард кей,нет,нет,горестно,наречие
376,дард кеф,нет,нет,печальный; горестный,прилагательное
377,дард лаг-лаг,мн. ч. дард лаг-лагар,нет,болтун,существительное
378,дард хьас акьас,нет,нет,оскорбить,глагол
379,дардар акьас,нет,нет,переживать; горевать,глагол
380,дарди,нет,нет,узко; тесно,наречие
381,дардтти,нет,нет,тоскливо,наречие
382,дардуманф,нет,нет,любимый; обожаемый; незаменимый,прилагательное
383,дарин,нет,нет,глубокий,прилагательное
384,даринвел,нет,нет,глубина,существительное
385,даринди,нет,да,глубоко; углублённо,наречие
386,дарискьалвел,нет,нет,мелочность,существительное
387,дарискьалди,нет,нет,мелочно,наречие
388,дарих,нет,нет,скучающий,прилагательное
389,дарих хьас,нет,да,грустить; истосковаться,глагол
390,дарихвел,нет,нет,тоска; скука,существительное
391,дарихди,нет,нет,тоскливо,наречие
392,дарман,мн. ч. дарманар,нет,лекарство,существительное
393,дарманар,нет,нет,медикаменты,существительное
394,дармандинф,нет,нет,целебный,прилагательное
395,дарс,мн. ч. дарсар,нет,урок,существительное
396,дарсар ягIархъуб,нет,нет,образованность,существительное
397,дарф,нет,да,узкий; тесный,прилагательное
398,дарчин,мн. ч. дарчинар,нет,корица,существительное
399,дасмал,мн. ч. дасмалар,нет,полотенце,существительное
400,даста,мн. ч. дастабур,нет,пачка,существительное
401,дастта,мн. ч. дасттабур,нет,пучок,существительное
402,дафтт,мн. ч. дафттар,нет,бубен,существительное
403,дафттар,мн. ч. дафттарар,нет,книга,существительное
404,дахе баб,мн. ч. дахе бабар,нет,мачеха,существительное
405,дахе руш,мн. ч. дахе рушар,нет,падчерица,существительное
406,дахи1,нет,нет,давно; прежде,наречие
407,дахи2,нет,нет,рано,наречие
408,дахи гIатIуршаф,нет,нет,активный,прилагательное
409,дахил,мн. ч. дахилар,нет,полочка,существительное
410,дахьас,нет,нет,открывать; открыть,глагол
411,дахьуна,нет,нет,открыто,наречие
412,дахьуна ая,нет,нет,открыто,наречие
413,дахьуф,нет,нет,открытый,прилагательное
414,дач,мн. ч. дачар,нет,пачка,существительное
415,дашбаш,мн. ч. дашбашар,нет,подношение; взятка,существительное
416,дать,нет,нет,нет,частица
417,даягъ,мн. ч. даягъар,нет,опора,существительное
418,даягъвел,нет,нет,заступничество,существительное
419,дева,мн. ч. девабур,нет,верблюд,существительное
420,девекъуш,мн. ч. девекъушар,нет,страус,существительное
421,девлет,мн. ч. девлетар,нет,богатство; состояние,существительное
422,девлет хьас,нет,нет,разбогатеть,глагол
423,девлетар,нет,нет,состоятельность; богатство; ресурсы,существительное
424,девлетвел,нет,нет,состоятельность; зажиточность,существительное
425,девлетлу,мн. ч. девлетлубур,нет,богач,существительное
426,девлетлу,нет,нет,богатый,прилагательное
427,девлетлу хьас,нет,да,разбогатеть,глагол
428,девлетлуди,нет,нет,богато,наречие
429,девлетти,нет,нет,зажиточно,наречие
430,дегьна,мн. ч. дегьнабур,нет,водоворот,существительное
431,дегIви,мн. ч. дегIвибур,нет,война; фронт,существительное
432,дегIви акьас,нет,нет,ссориться; воевать,глагол
433,дегIви хьуф,мн. ч. дегIви хьуттар,нет,фронтовик,существительное
434,дегIуь акьас,нет,да,конфликтовать; воевать; ссориться,глагол
435,декабр,нет,нет,декабрь,существительное
436,делек,мн. ч. делекар,нет,парикмахер,существительное
437,делекхана,мн. ч. делекханабур,нет,парикмахерская,существительное
438,дембеден,нет,да,сразу; моментально,наречие
439,демек,мн. ч. демекар,нет,курятник,существительное
440,демек,мн. ч. демекар,нет,ягнятник,существительное
441,ден бидан,нет,да,немедленно,наречие
442,дере,мн. ч. деребур,нет,долина; ущелье,существительное
443,дерей,мн. ч. дереяар,да,шёлк,существительное
444,дерейинф,мн. ч. дерейинфар,да,земляк,существительное
445,дерец,мн. ч. дерецар,нет,соха,существительное
446,дехи,нет,да,рано,наречие
447,диб,мн. ч. дибар,нет,основа,существительное
448,дибахарай,нет,нет,тафта,существительное
449,диван,мн. ч. диванар,нет,суд,существительное
450,диван акъас,нет,нет,наказать,глагол
451,дивас,нет,нет,курить,глагол
452,дилавар,нет,нет,красноречивый,прилагательное
453,дилаварвел,нет,нет,красноречивость,существительное
454,дилаварди,нет,нет,красноречиво,наречие
455,дилмаш,мн. ч. дилмашар,нет,полиглот,существительное
456,дин,мн. ч. динар,нет,религия; вера,существительное
457,динагьли,нет,нет,набожный; религиозный,прилагательное
458,динди аф,мн. ч. динди аттар,нет,верующий,существительное
459,динди аф,нет,нет,набожный; религиозный,прилагательное
460,диндж,нет,нет,сытый,прилагательное
461,дирбаш1,мн. ч. дирбашар,нет,умелец,существительное
462,дирбаш2,мн. ч. дирбашар,нет,храбрец,существительное
463,дирбаш,нет,нет,ловкий,прилагательное
464,дирбашвел,нет,нет,мужество,существительное
465,дирбашди,нет,нет,отважно; храбро,наречие
466,диреф,нет,нет,бойкий; шустрый; ловкий; сноровистый,прилагательное
467,диттаф,нет,нет,здоровый,прилагательное
468,диф,мн. ч. дифар,нет,туман,существительное
469,дихьеф,нет,нет,жидкий,прилагательное
470,дихьи,нет,нет,жидко,наречие
471,дишагьли,мн. ч. дишагьлибур,нет,женщина,существительное
472,дугъре,нет,нет,правдивый,прилагательное
473,дудай,мн. ч. дудар,да,кукла,существительное
474,дудук,мн. ч. дудукар,нет,свисток,существительное
475,дуджас,нет,нет,лизать; слизывать,глагол
476,дуджурай,мн. ч. дуджураяар,нет,свёрток,существительное
477,дуз акьас,нет,нет,обновить; починить,глагол
478,дуз даф,нет,нет,фальшивый,прилагательное
479,дуз дахьуб,мн. ч. дуз дахьубар,нет,несправедливость,существительное
480,дуз хьуб,мн. ч. дуз хьубар,нет,примирение,существительное
481,дузалвел,нет,да,справедливость,существительное
482,дузан,мн. ч. дузанар,да,равнина,существительное
483,дузвел,нет,нет,правдивость; честность; прямота; справедливость; непорочность; верность,существительное
484,дуздавевел,мн. ч. дуздавевелар,нет,несправедливость,существительное
485,дузди,нет,нет,правдиво; честно; прямо; точно,наречие
486,дузди гъузуф,нет,нет,вертикально,наречие
487,дузди дапас,нет,нет,соврать,глагол
488,дуздингъилди,нет,нет,безупречно; честно,наречие
489,дуздин кар,нет,нет,правда,существительное
490,дуздинф1,нет,нет,правдивый; честный; незапятнанный; справедливый; верный,прилагательное
491,дуздинф2,нет,нет,равный,прилагательное
492,дузф,нет,нет,истинный; верный,прилагательное
493,дукан,мн. ч. дуканар,нет,магазин,существительное
494,дукьанас,нет,нет,вязать,глагол
495,дукьуб,мн. ч. дукьубар,нет,шов,существительное
496,дукьум,мн. ч. дукьумар,да,нить,существительное
497,дукьуминф,нет,да,нитяной,прилагательное
498,дукI,нет,нет,просо,существительное
499,дул,мн. ч. дулар,нет,приплод,существительное
500,дулег,мн. ч. дулегар,нет,селезёнка,существительное
501,дуллугъ,мн. ч. дуллугъар,нет,заработок,существительное
502,дулма,нет,нет,голубцы,существительное
503,дунгъуз,мн. ч. дунгъузар,нет,ругательство,существительное
504,дунгъузугъли,мн. ч. дунгъузугълибур,да,ругательство,существительное
505,дурахал,мн. ч. дурахалар,нет,ножовка; пила,существительное
506,дурахIелар,мн. ч. дурахIеларар,нет,игра,существительное
507,дурби,мн. ч. дурбибур,нет,бинокль,существительное
508,дуркьан кIалиб,мн. ч. дуркьан кIалибар,нет,фасон,существительное
509,дурна,мн. ч. дурнабур,нет,журавль,существительное
510,дурум,нет,да,нетерпеливый,прилагательное
511,дурус,нет,нет,верный,прилагательное
512,дуруц,мн. ч. дуруцар,нет,соха,существительное
513,дурхIуб,мн. ч. дурхIубар,нет,фокус,существительное
514,дурхIубар,нет,нет,игра,существительное
515,дустт,мн. ч. дусттар,нет,друг; приятель,существительное
516,дусттагъ,мн. ч. дусттагьар,нет,тюрьма,существительное
517,духттур,мн. ч. духттурар,нет,доктор; медик; врач; фельдшер,существительное
518,дуч,мн. ч. дучар,нет,вязанка,существительное
519,душман,мн. ч. душманар,нет,враг,существительное
520,душманвел,нет,нет,вражда,существительное
521,душманди,нет,нет,враждебно,наречие
522,дуя,нет,нет,мир; вселенная,существительное
523,дуьгIе,мн. ч. дуьгIебур,нет,молитва,существительное
524,дуьлбен,мн. ч. дуьлбенар,нет,тюрбан,существительное
525,дуьрбебур,нет,нет,бинокль,существительное
526,дуьхьуьб1,мн. ч. дуьхьуьбар,нет,согласие; примирение,существительное
527,дуьхьуьб2,мн. ч. дуьхьуьбар,нет,удача,существительное
528,джаваб,мн. ч. джавабар,да,ответ,существительное
529,джагв,нет,нет,белизна,существительное
530,джагвар акьас,нет,нет,белить; побелить,глагол
531,джагвар чIар,мн. ч. джагвар чIарар,нет,седина,существительное
532,джагварф,нет,нет,светлый; бледный,прилагательное
533,джагварф,нет,нет,белый,прилагательное
534,джад,мн. ч. джадар,нет,кузница,существительное
535,джаза,мн. ч. джазабур,нет,наказание; взыскание; штраф,существительное
536,джазалу,нет,нет,осуждённый,прилагательное
537,джазасузвел,нет,нет,безнаказанность,существительное
538,джазасузди,нет,нет,безнаказанно,наречие
539,джакьв,мн. ч. джакьвар,нет,птица; воробей,существительное
540,джакьварин муг,мн. ч. джакьварин мугар,нет,кормушка,существительное
541,джал,мн. ч. джалар,нет,забор; плетень,существительное
542,джалабрихъай дуьхьуб,нет,нет,дружелюбие,существительное
543,джалабрихъай дуьхьуна,нет,нет,дружелюбно,наречие
544,джалайихъай дуьхьуф,нет,нет,дружелюбный,прилагательное
545,джалгъа1,мн. ч. джалгъабур,нет,ряд,существительное
546,джалгъа2,мн. ч. джалгъабур,нет,тропинка,существительное
547,джалла,нет,нет,весь; все,местоимение
548,джалла хьай,нет,нет,совместно,наречие
549,джалла ягIаф,мн. ч. джала ягIаттар,нет,знаток,существительное
550,джаллабрин гIаф,нет,нет,общий; всеобщий; совместный,прилагательное
551,джаллабрин хIаф,мн. ч. джалабрин хIаттар,нет,главарь,существительное
552,джаллабрис ягIаф,нет,нет,известный; знаменитый,прилагательное
553,джаллабрина аф,мн. ч. джаллабрина аттар,нет,общепринятость,существительное
554,джаллабринф,нет,нет,общий; всеобщий,прилагательное
555,джаллабрихьай,нет,нет,общительно,наречие
556,джаллабур,нет,нет,каждый,прилагательное
557,джаллабур,нет,нет,все,местоимение
558,джаллайинф,нет,нет,всеобщий,прилагательное
559,джаллатI,мн. ч. джаллатIар,нет,палач,существительное
560,джам,мн. ч. джамар,нет,итог; сумма,существительное
561,джан,мн. ч. джанар,нет,туловище,существительное
562,джандак,мн. ч. джандакар,нет,тело,существительное
563,джандин кIалибар,нет,нет,телосложение; фигура,существительное
564,джандин са мукъ,мн. ч. джандин са мукьар,нет,орган,существительное
565,джанджал,нет,да,алчный,прилагательное
566,джанджалвел,нет,да,алчность,существительное
567,джанджалди,нет,нет,изворотливо,наречие
568,джаннат,нет,нет,рай,существительное
569,джаннаттинф,нет,нет,райский,прилагательное
570,джар1,мн. ч. джарар,нет,сметана,существительное
571,джар2,мн. ч. джарар,нет,слой,существительное
572,джарга,мн. ч. джаргабур,нет,строй,существительное
573,джарх,мн. ч. джархар,нет,овёс,существительное
574,джасад,мн. ч. джасадар,нет,тело; труп,существительное
575,джасус,мн. ч. джасусар,нет,шпион,существительное
576,джасусвел акьас,нет,нет,шпионить,глагол
577,джафа,мн. ч. джафабур,нет,старание; усилие; труд,существительное
578,джафалу,нет,да,трудный,прилагательное
579,джафасуз,нет,нет,лёгкий,прилагательное
580,джафасузвел,нет,нет,простота; доступность,существительное
581,джетельем,нет,нет,ад; преисподняя,существительное
582,джекьетI,мн. ч. джекьетIар,нет,рябчик,существительное
583,джемеIет,мн. ч. джемеIетар,нет,общество,существительное
584,джемеIетинф,нет,нет,народный; общественный,прилагательное
585,дженг,нет,нет,борьба,существительное
586,дженглу,нет,нет,воинственный,прилагательное
587,дженнет,нет,да,рай,существительное
588,джерехI,мн. ч. джерехIар,нет,целитель; хирург,существительное
589,джилар зурзуб,мн. ч. джилар зурзубар,нет,землетрясение,существительное
590,джилд,мн. ч. джилдар,нет,переплёт,существительное
591,джилинф,нет,нет,земельный,прилагательное
592,джимилар,нет,нет,кизил,существительное
593,джин,мн. ч. джинар,нет,джин,существительное
594,джин дакьуна,нет,нет,явно,наречие
595,джин хьас,нет,нет,спрятаться,глагол
596,джинаван,нет,да,тайный,прилагательное
597,джинакьуб,мн. ч. джинакьубар,нет,тайна,существительное
598,джинди,нет,нет,втайне; исподтишка; секретно; тайно,наречие
599,джиндин кар,мн. ч. джиндин курар,нет,секрет; тайна,существительное
600,джиндинф,нет,нет,секретный; тайный,прилагательное
601,джиневел,мн. ч. джиневелар,да,тайна,существительное
602,джинегв,мн. ч. джинегвар,нет,ястреб,существительное
603,джинеф,нет,да,секретный; тайный,прилагательное
604,джир хьас,нет,нет,расчёсывать,глагол
605,джихер,мн. ч. джихерар,нет,груша,существительное
606,джиял,мн. ч. джиялар,да,участок,существительное
607,джуваб,мн. ч. джувабар,нет,ответ,существительное
608,джугьутI,мн. ч. джугьутIар,нет,еврей,существительное
609,джудж,мн. ч. джуджар,да,тетрадь,существительное
610,джум атай,нет,нет,нехотя,наречие
611,джумарт,нет,нет,щедрый,прилагательное
612,джумартвел,нет,да,щедрость,существительное
613,джумартди,нет,нет,щедро,наречие
614,джуматвел,нет,нет,щедрость,существительное
615,джуматти,нет,нет,щедро,наречие
616,джуматтинф,нет,нет,щедрый,прилагательное
617,джуна,мн. ч. джунабур,нет,марля; бинт,существительное
618,джуре акьас,нет,нет,разлучить,глагол
619,джуре мукьариас адиф,мн. ч. джуре мукьариас адиттар,нет,турист,существительное
620,джуревел,мн. ч. джуревелар,нет,отличие; разница; разное; разновидность,существительное
621,джуревелар,нет,нет,перемена,существительное
622,джуреттарил алчихьас,нет,нет,взваливать,глагол
623,джут,мн. ч. джутар,нет,пара,существительное
624,джут,нет,нет,парный,прилагательное
625,джуьмIа,нет,нет,пятница,существительное
626,джуьнихьас,нет,нет,спрятаться,глагол
627,джуьреф1,нет,нет,отдельный,прилагательное
628,джуьреф2,нет,нет,посторонний,прилагательное
0,егьсуз,нет,нет,бессильный,прилагательное
1,единица,мн. ч. единицабур,нет,единица,существительное
2,езид,мн. ч. езидар,нет,изменник; предатель,существительное
3,езидвел,мн. ч. езидвелар,нет,измена; предательство,существительное
4,елкан,мн. ч. елканар,нет,парус,существительное
5,емаг,нет,нет,еда; пища,существительное
6,емиш,мн. ч. емишар,нет,плод; фрукт,существительное
7,ериверш,нет,нет,семьсот,числительное
8,ерид,нет,нет,семь,числительное
9,ерсари аф,нет,нет,горюющий; скорбящий,прилагательное
10,ерсеф,нет,нет,обветшалость; ветхость,существительное
11,ерсузвел,нет,нет,легкомысленность,существительное
12,ерсузди,нет,нет,легкомысленно,наречие
13,ерхе акьас,нет,да,вытянуть; удлинить,глагол
14,ерхе хьас,нет,нет,удлиниться,глагол
15,ерхевел,мн. ч. ерхевелар,да,рост,существительное
16,ерхеф,нет,да,протяжённый; длинный,прилагательное
17,ерхьиверш,нет,нет,шестьсот,числительное
18,ерхьид,нет,нет,шесть,числительное
19,ерхьцIур,нет,нет,шестьдесят,числительное
20,ерчIуд,нет,нет,девять,числительное
21,ерIевел,нет,да,ширина,существительное
22,ерIеф,нет,нет,широкий,прилагательное
23,ерIиди,нет,нет,широко,наречие
24,есир,нет,нет,плен; пленник,существительное
25,етим,мн. ч. етимар,нет,сирота,существительное
26,етум,мн. ч. етумар,нет,сирота,существительное
27,етум хьас,нет,нет,осиротеть,глагол
28,ехIсуз,нет,нет,бесчётный,прилагательное
29,жекъеф,нет,да,короткий,прилагательное
30,жекъи,нет,нет,коротко,наречие
31,жекъиди,нет,нет,коротко,наречие
32,жугъри,мн. ч. жугърибур,нет,персик,существительное
33,жулуркъ,мн. ч. жулуркьар,нет,жулик,существительное
34,жуьлез,мн. ч. жуьлезар,нет,селезёнка,существительное
35,забит,нет,нет,жёсткий,прилагательное
36,забун хьас,нет,нет,похудеть,глагол
37,забунвел,мн. ч. забунвелар,нет,худоба; хрупкость,существительное
38,забунвелар,нет,нет,худощавость,существительное
39,забунф,нет,нет,хилый,прилагательное
40,забур,мн. ч. забурар,нет,пластырь,существительное
41,зав,нет,нет,нёбо,существительное
42,зав курас,мн. ч. зав кураcap,нет,рассвет,существительное
43,зав куруб,мн. ч. зав курубар,нет,заря,существительное
44,завал,мн. ч. завалар,нет,несчастье; бедствие,существительное
45,завал акьун,нет,нет,мобилизованно,наречие
46,завал хьун,нет,нет,собранно,наречие
47,завар1,нет,нет,нёбо,существительное
48,завар2,мн. ч. заварар,нет,грохот,существительное
49,заварин цIа,мн. ч. заварин цIабурар,нет,бедствие,существительное
50,заваринф1,нет,нет,небесный,прилагательное
51,заваринф2,нет,нет,воздушный,прилагательное
52,загьир,нет,нет,очевидный; явный; ясный,прилагательное
53,загьмат,мн. ч. загьматар,нет,труд; усилие,существительное
54,зад,мн. ч. задача,нет,вещь,существительное
55,заз,мн. ч. зазар,нет,колючка; шип; заноза,существительное
56,закат,мн. ч. закатар,нет,налог,существительное
57,закконар ягIаф,мн. ч. закконар ягIаттар,нет,юрист,существительное
58,закконаринф,нет,нет,юридический,прилагательное
59,залзала,мн. ч. залзалабур,нет,землетрясение,существительное
60,залил,нет,нет,униженный,прилагательное
61,залумат,нет,нет,гнёт; угнетение,существительное
62,замана,мн. ч. заманабур,нет,время,существительное
63,замин,мн. ч. заминар,нет,залог,существительное
64,заминвел,мн. ч. заминвелар,нет,поручительство,существительное
65,занг,мн. ч. зангар,нет,звонок,существительное
66,занг акьас,нет,нет,звонить; позвонить,глагол
67,занг аркьаф,мн. ч. занг аркьаттар,нет,телефон,существительное
68,зангар аркьаф,мн. ч. зангар аркьаттар,нет,колокольчик,существительное
69,зар,нет,нет,блеск; сияние; позолота,существительное
70,зарар,нет,нет,вред; ущерб,существительное
71,зарар аркьаф,мн. ч. зарар аркьаттар,нет,вредитель,существительное
72,зарар кедаф,нет,нет,безобидный,прилагательное
73,зарар кеф,нет,нет,вредный,прилагательное
74,зарарвел,мн. ч. зарарвелар,нет,вредность,существительное
75,зарарлувел,мн. ч. зарарлувелар,нет,вредность,существительное
76,зарарсуз,нет,нет,безобидный,прилагательное
77,зарарчи,мн. ч. зарарчибур,нет,вредитель,существительное
78,зарафат,мн. ч. зарафатар,нет,шутка,существительное
79,зарафатар,нет,нет,юмор; анекдот,существительное
80,зарафатар акьас,нет,нет,шутить,глагол
81,зарафатвел,нет,нет,шутовство,существительное
82,зарафатинф,нет,нет,шутливый; шуточный,прилагательное
83,зарафатсуз,нет,нет,серьёзный,прилагательное
84,зарафатчи,мн. ч. зарафатчибур,нет,весельчак; шутник,существительное
85,зарафатчивел,нет,нет,шутовство,существительное
86,зарбвел,нет,да,быстрота,существительное
87,заИнф,нет,нет,бледный,прилагательное
88,заИнф хьас1,нет,да,обессилеть; ослабеть,глагол
89,заИнф хьас2,нет,да,похудеть,глагол
90,заИнфвел,мн. ч. заИнфвелар,нет,худоба,существительное
91,зегьер,мн. ч. зегьерар,нет,яд,существительное
92,зегьерлу,нет,да,ядовитый,прилагательное
93,зегьмат,мн. ч. зегьматар,да,старание; усилие; труд,существительное
94,зейда,нет,нет,много,наречие
95,зейтун,мн. ч. зейтунар,нет,маслина; оливка,существительное
96,зерфел,мн. ч. зерфелар,нет,сито,существительное
97,зеф,нет,нет,мой; моя; моё,местоимение
98,зеф,нет,нет,собственный,прилагательное
99,зибз1,мн. ч. зибзар,нет,муравей,существительное
100,зибз2,мн. ч. зибзар,да,рябина,существительное
101,зигьин,нет,нет,восприимчивость,существительное
102,зигьин фай,нет,нет,талантливо,наречие
103,зигьинлуди,нет,нет,талантливо,наречие
104,зид,нет,нет,привередливый; скандальный,прилагательное
105,зикри,мн. ч. зикрибур,нет,радение,существительное
106,зиндан,мн. ч. зинданар,нет,яма,существительное
107,зиринг,нет,нет,проворный,прилагательное
108,зиянкар,мн. ч. зиянкарар,нет,вредитель,существительное
109,зиянкарвел,мн. ч. зиянкарвелар,нет,вредность,существительное
110,зияхI хьуф,нет,нет,заброшенный,прилагательное
111,зугьмат,мн. ч. зугьматар,нет,запах; вонь,существительное
112,зулмат1,мн. ч. зулматар,нет,жестокость,существительное
113,зулмат2,мн. ч. зулматар,нет,беспросветность,существительное
114,зулум,мн. ч. зулумар,нет,насилие; тирания,существительное
115,зулум хьаф,нет,нет,жестокий,прилагательное
116,зулумар,нет,нет,жестокость; угнетение; гнёт,существительное
117,зулумар аркьаф,мн. ч. зулумар аркьаттар,нет,угнетатель; тиран,существительное
118,зулумди1,нет,да,мощно; сильно,наречие
119,зулумди2,нет,нет,жестоко,наречие
120,зулумкар,мн. ч. зулумкурар,нет,угнетатель; тиран,существительное
121,зун,нет,нет,я,местоимение
122,зур,нет,нет,моча,существительное
123,зурба,мн. ч. зурбабур,нет,храбрец,существительное
124,зурба1,нет,нет,умелый,прилагательное
125,зурба2,нет,нет,смелый; храбрый; сильный,прилагательное
126,зурба идеми суман,нет,нет,мужественно,наречие
127,зурба идеми суманф,нет,нет,мужественный,прилагательное
128,зурбавел1,нет,нет,ловкость; умение,существительное
129,зурбавел2,мн. ч. зурбавелар,нет,сила; смелость,существительное
130,зурбади,нет,да,ловко; умело,наречие
131,зурбайи,нет,нет,ловко,наречие
132,зурд,мн. ч. зурдар,нет,ясень,существительное
133,зуре,нет,нет,частый,прилагательное
134,зурзас1,нет,нет,трясти,глагол
135,зурзас2,нет,нет,дрожать,глагол
136,зурлу,нет,нет,могучий,прилагательное
137,зурлуди,нет,да,мощно; сильно,наречие
138,зурна,мн. ч. зурнабур,нет,зурна,существительное
139,зуьлер,мн. ч. зуьлерар,нет,крыльцо,существительное
140,зуьлерарин къирагъ,мн. ч. зуьлерарин къирагъар,нет,перила,существительное
141,зуьлерз,мн. ч. зуьлерзар,да,селезёнка,существительное
142,и,нет,нет,да,наречие
143,и,нет,нет,да,частица
144,ибагI акьас,нет,да,нагреть,глагол
145,ибагI хьас,нет,нет,нагреться,глагол
146,ибагIвел,нет,нет,тепло,существительное
147,ибагIди,нет,да,тёплый,прилагательное
148,ибгIа акьас,нет,нет,нагреть,глагол
149,ибгIа хьас,нет,нет,нагреться,глагол
150,ибгIай,нет,нет,тепло,существительное
151,ибгIаф,нет,нет,тёплый,прилагательное
152,иблис,мн. ч. иблисар,нет,чёрт; демон; дьявол,существительное
153,иблис,нет,нет,хитрый; коварный,прилагательное
154,ибрахъан,мн. ч. ибрахъанар,нет,серьга,существительное
155,ибур,мн. ч. ибурар,нет,ухо,существительное
156,ибурихъан,мн. ч. ибурихъанар,да,серьга,существительное
157,ибхь,мн. ч. ибхьар,нет,снег,существительное
158,ибхь суман джагварф,нет,нет,белизна,существительное
159,ибхь суман джагварф,нет,нет,белоснежный,прилагательное
160,ибхьин пурцI,мн. ч. ибхьин пурцIар,нет,снежинка,существительное
161,ибхьин тIурфан,мн. ч. ибхьин тIурфанар,нет,буран,существительное
162,ибхьинф,нет,нет,снежный,прилагательное
163,ивра,мн. ч. иврабур,нет,жеребенок,существительное
164,ивриккен,мн. ч. ивриккенар,да,серьга,существительное
165,ивур,мн. ч. ивурар,да,ухо,существительное
166,игит,мн. ч. игитар,нет,храбрец; герой,существительное
167,игит суманф,нет,нет,мужественный,прилагательное
168,игитвел,нет,нет,мужество; героизм,существительное
169,игитди,нет,нет,мужество,существительное
170,игитти,нет,нет,мужественно; героически,наречие
171,играми,нет,нет,любимый,прилагательное
172,игьанат,нет,нет,вероломный; коварный,прилагательное
173,идара,мн. ч. идарабур,нет,учреждение; организация; контора; управление,существительное
174,идарайин хIаф,мн. ч. идарайин хIафар,нет,начальник,существительное
175,идеми,мн. ч. идемар,нет,человек; мужчина,существительное
176,идемивел1,нет,нет,человечность,существительное
177,идемивел2,нет,нет,мужество,существительное
178,иджвел,нет,нет,добро; доброта; благо; благость,существительное
179,идже улар адаф,нет,нет,дурноглазый,прилагательное
180,иджвеел,нет,нет,мягкость,существительное
181,иджеф1,нет,нет,добрый; хороший,прилагательное
182,иджеф2,нет,нет,добротный,прилагательное
183,иджи,нет,нет,добротно; хорошо,наречие
184,иджи дакьуф,нет,нет,формальный,прилагательное
185,иджи хураф,мн. ч. иджи хураттар,нет,отличник,существительное
186,изан,мн. ч. изанар,да,пахота; пашня,существительное
187,изин,нет,нет,благословение,существительное
188,иин таб,мн. ч. иин табар,нет,вена,существительное
189,иинф,нет,нет,кровавый,прилагательное
190,икрагь,нет,да,отвращение,существительное
191,икке ларз,мн. ч. икке ларзар,нет,коридор,существительное
192,иккевел,мн. ч. иккевелар,нет,худоба,существительное
193,иккевелар,нет,нет,худощавость,существительное
194,икърар,нет,нет,договорённость; обговаривание; соглашение; подтверждение; признание,существительное
195,илан,мн. ч. иланар,нет,змея,существительное
196,илгунди,нет,нет,легкомысленно; легко,наречие
197,илгунди тIуршаф,нет,нет,легкомысленный,прилагательное
198,илгунди тIушуб,нет,нет,легкомысленность,существительное
199,илгунф,нет,нет,легковесный; лёгкий,прилагательное
200,илдеш,мн. ч. илдешар,нет,друг; товарищ,существительное
201,илдешвел,мн. ч. илдешвелар,нет,товарищество,существительное
202,иллевел,нет,нет,мужество,существительное
203,иллевелди,нет,нет,мужественно,наречие
204,иллеф,нет,нет,мужество,существительное
205,имам,мн. ч. имамар,нет,имам,существительное
206,иман,мн. ч. иманар,нет,вера,существительное
207,иманвел,нет,нет,покорность,существительное
208,имансуз,нет,нет,бессовестный,прилагательное
209,имансузди,нет,нет,беспощадно,наречие
210,имансузф,нет,нет,беспощадный,прилагательное
211,имунилди,нет,нет,скромно; тихо,наречие
212,инджиклу акьас,нет,нет,беспокоить,глагол
213,инджир,нет,нет,инжир,существительное
214,инн,мн. ч. инибур,нет,боярышник,существительное
215,инсан,мн. ч. инсанар,нет,человек,существительное
216,инсанар вере рекъ,мн. ч. инсанар вере рекъар,нет,тротуар,существительное
217,инсанвел,нет,нет,человечность,существительное
218,инсанвел хъаф,нет,нет,милосердный,прилагательное
219,инсанвел хьуб,нет,нет,милосердие,существительное
220,инсандин джан,мн. ч. инсандин джанар,нет,тело,существительное
221,инсандин руьхI,мн. ч. инсандин руьхIар,нет,душа,существительное
222,инсанф,нет,нет,сострадание; милосердие; пощада,существительное
223,инсафсуз,нет,нет,беспощадный; жестокий,прилагательное
224,инчI,мн. ч. инчIар,нет,улыбка,существительное
225,ипак,мн. ч. ипакар,нет,шёлк,существительное
226,ипакинф,нет,нет,шёлковый,прилагательное
227,ипцIел,мн. ч. ипцIелар,нет,стружка,существительное
228,иргунф,нет,нет,невесомый; лёгкий,прилагательное
229,ире-буреф,нет,нет,красно-бурый,прилагательное
230,иревел,нет,нет,краснота,существительное
231,иреф,нет,нет,красный; алый,прилагательное
232,ире ягълукъ,мн. ч. ире ягълукъар,нет,платок,существительное
233,иркк,мн. ч. ирккар,нет,кость,существительное
234,ирккарин гьаб,нет,нет,костлявый,прилагательное
235,ирс,мн. ч. ирсар,нет,наследство,существительное
236,ирхе акьас,нет,нет,вытянуть; удлинить,глагол
237,ирхе хьас,нет,нет,вытянуться; удлиниться,глагол
238,ирхе Iуьмур хъаф,нет,нет,долговечный,прилагательное
239,ирхевел1,мн. ч. ирхевелар,нет,долгота,существительное
240,ирхевел2,мн. ч. ирхевелар,нет,рост,существительное
241,ирхеф1,нет,нет,высокий,прилагательное
242,ирхеф2,нет,нет,длинный; протяжённый,прилагательное
243,ирхи,нет,нет,длинно,наречие
244,ирIе рекъ,нет,нет,широкий,прилагательное
245,ирIевел,нет,нет,ширина; широта,существительное
246,ирIеф,нет,нет,широкий,прилагательное
247,ирIи,нет,нет,пошире; широко,наречие
248,ирIэ акьас,нет,нет,расширить,глагол
249,ис,мн. ч. исар,нет,возраст; год,существительное
250,ис атIуб,мн. ч. ис атIубар,нет,годовщина,существительное
251,исал рекъ,мн. ч. исал рекъар,нет,тропинка,существительное
252,исалвел,нет,нет,узость; теснота,существительное
253,исалди,нет,нет,узко; тесно,наречие
254,исалф,нет,нет,узкий; тесный,прилагательное
255,исар дахьун,нет,нет,несовершеннолетие,существительное
256,ислехI,нет,нет,справедливый,прилагательное
257,испахьи,мн. ч. испахьибур,нет,господин,существительное
258,испахьи хьир,мн. ч. испахьи хьирар,нет,госпожа,существительное
259,иститут,мн. ч. иститутар,нет,перец,существительное
260,исттикан,мн. ч. исттиканар,нет,стакан,существительное
261,исукъ,мн. ч. исукьар,нет,годовщина,существительное
262,итни,нет,нет,понедельник,существительное
263,иттал,мн. ч. итталар,нет,болезнь; заболевание,существительное
264,иттар давереф,нет,нет,закалённый,прилагательное
265,иттар дахьас акьас,нет,нет,закалить,глагол
266,иттар хьас,нет,нет,заболеть,глагол
267,иттар хьас дакьас,нет,нет,закалиться,глагол
268,иттаф,нет,нет,нездоровый,прилагательное
269,итте кьутIур,мн. ч. итте кьутIурар,нет,пирог,существительное
270,иттеф1,нет,нет,вкусный,прилагательное
271,иттеф2,нет,нет,сладкий,прилагательное
272,иттефдаваф,нет,нет,невкусный,прилагательное
273,итти,нет,нет,вкусно,наречие
274,итIул,мн. ч. итIулар,нет,петля,существительное
275,иф,нет,нет,медь,существительное
276,ифал,мн. ч. ифалар,нет,масло,существительное
277,ифрит,мн. ч. ифритар,нет,дьявол,существительное
278,ифул,мн. ч. ифулар,нет,лихорадка,существительное
279,ихал,нет,нет,наждак,существительное
280,ихтилат,мн. ч. ихтилатар,нет,беседа; разговор,существительное
281,ицIас,нет,да,давать,глагол
282,ицIул,мн. ч. ицIулар,нет,запястье,существительное
283,ишан,мн. ч. ишанар,нет,отметина; метка; след; эмблема; шрам; рубец,существительное
284,ишиг,мн. ч. ишигер,нет,ящик,существительное
285,ишкатвел,мн. ч. ишкатвелар,нет,информация,существительное
286,ишкатчи,мн. ч. ишкатчибур,нет,сплетник,существительное
287,ишкаф,мн. ч. ишкафар,нет,шкаф,существительное
288,ишкил,мн. ч. ишкилар,нет,картина; открытка; фотография,существительное
289,ишкилар атаф,мн. ч. ишкилар ататтар,нет,художник; фотограф,существительное
290,ишкит,мн. ч. ишкитар,нет,донесение,существительное
291,иштагь,мн. ч. иштагьар,нет,аппетит,существительное
292,иштараквел,нет,нет,участие,существительное
293,ишттагь,мн. ч. ишттагьар,нет,желание,существительное
294,иъ,нет,нет,кровь,существительное
295,июл,нет,нет,июль,существительное
296,июн,нет,нет,июнь,существительное
297,йа,нет,нет,как,наречие
298,йиркIв,мн. ч. йиркIвар,нет,сердце,существительное
299,йиркIв алиянф,нет,нет,послушный; покорный,прилагательное
300,йиркIв дахьас,нет,нет,признание,существительное
301,йиркIв дахьас,нет,нет,открыться,глагол
302,йиркIв дахьун,нет,нет,открыто; душевно,наречие
303,йиркIв ккидаф,нет,нет,брезгливый,прилагательное
304,йиркIв фай,нет,нет,душевно,наречие
305,йиркIвар-лекIер,нет,нет,лёгкие,существительное
306,йиркIвуран иджвелвел,мн. ч. йиркIвуран иджвеллелар,нет,душевность,существительное
307,йиркIвуран иджеф,нет,нет,душевный,прилагательное
308,йиркIвуранф,нет,нет,душевный,прилагательное
309,йиркIвураъ Iайвел адаф,нет,нет,беззлобный,прилагательное
310,йиркIуралас даве регьелди,нет,нет,наизусть,наречие
0,йиркIурас ибгIаф,нет,нет,приятный,прилагательное
1,йиркIурахъ Iайвел хъудахъуб,нет,нет,беззлобность,существительное
2,йирт,мн. ч. йиртар,нет,имение,существительное
3,йируш,мн. ч. йирушар,нет,походка,существительное
4,йирхIас,нет,нет,бить; ударять; избить,глагол
5,йирхIубар,нет,нет,побои,существительное
6,йис,нет,нет,давать,глагол
7,йицIуд,нет,нет,десять,числительное
8,кавха,мн. ч. кавхабур,нет,староста,существительное
9,кагъаз,мн. ч. кагъазар,да,письмо,существительное
10,кагIфир,нет,нет,неверный,прилагательное
11,калам,мн. ч. каламар,нет,капуста,существительное
12,каламар гIахъу ракъ,мн. ч. каламар гIахъу ракъар,нет,борщ,существительное
13,калима,мн. ч. калимабур,да,слово,существительное
14,калкам,мн. ч. калкамар,да,клюв; подбородок,существительное
15,калтуф,мн. ч. калтуфар,нет,картошка,существительное
16,камал,нет,нет,зрелый,прилагательное
17,камаллуди,нет,нет,мудро; разумно,наречие
18,камшир,нет,нет,бронза,существительное
19,кантI,мн. ч. кантIар,нет,нож,существительное
20,кар,мн. ч. курар,нет,работа; труд; дело,существительное
21,кар даркьаф,мн. ч. кар даркьаттар,нет,безработный,прилагательное
22,караван,мн. ч. караванар,нет,караван,существительное
23,каравел,нет,нет,глухота,существительное
24,карди ккеф,нет,нет,активный; деятельный,прилагательное
25,кардикк ккедаф,нет,нет,безработный,прилагательное
26,кардикк хъуб,нет,нет,занятость,существительное
27,касиб,мн. ч. касибар,нет,бедняк,существительное
28,касиб,нет,нет,бедный,прилагательное
29,касиб хьас,нет,нет,обеднеть,глагол
30,касиб шуй,мн. ч. касиб шувар,нет,бедняк,существительное
31,касибвел,нет,нет,бедность; нищета; нужда,существительное
32,касибди,нет,нет,бедно,наречие
33,касибди ахъуб,нет,нет,бедствовать,глагол
34,касибф,нет,нет,бедный; нищий; несчастный,прилагательное
35,кафан,мн. ч. кафанар,нет,саван,существительное
36,кафар,нет,нет,север,существительное
37,кафир,нет,нет,неверный,прилагательное
38,качал,нет,нет,паршивый,прилагательное
39,квал акъувус,мн. ч. квал акъувусар,нет,граница,существительное
40,кваниш,мн. ч. кванишар,нет,браслет,существительное
41,квац,мн. ч. квацIар,нет,гроздь,существительное
42,ке,нет,нет,самый,местоимение
43,ке ахиранф,нет,нет,последний,прилагательное
44,ке кьабахь хъаф,нет,нет,конечный,прилагательное
45,ке удигьай,нет,нет,сначала,наречие
46,ке чIирхIеф,нет,нет,худший,прилагательное
47,ке Іайи кканеф,мн. ч. ке Іайи кканеттар,нет,любимчик,существительное
48,кегъдис,нет,нет,вырасти,глагол
49,кегъучIас,нет,нет,созреть,глагол
50,кедаркуб,мн. ч. кедаркубар,нет,наклон,существительное
51,кедаркувус,нет,нет,склон,существительное
52,кедаркувус,нет,нет,отвесный,прилагательное
53,кедаркун,нет,нет,круто; отвесно; наклонно,наречие
54,кедаркуф,нет,нет,покатый,прилагательное
55,кезийин,нет,нет,сердито,наречие
56,кезийинас,нет,нет,опечалиться,глагол
57,кеки1,нет,нет,честно; правдиво,наречие
58,кеки2,нет,нет,точно,наречие
59,кекинди,нет,нет,истинно; подлинно; натурально,наречие
60,кекинф,нет,нет,истинный; подлинный; натуральный,прилагательное
61,кела,мн. ч. келабур,нет,голова; череп,существительное
62,келагъан,мн. ч. келагъанар,нет,платок,существительное
63,келпит,мн. ч. келпитар,нет,спичка,существительное
64,келиши,мн. ч. келишшар,нет,кирпич,существительное
65,келпуш,мн. ч. келишшар,нет,кирпич,существительное
66,келхъанас,нет,нет,издеваться; насмехаться,глагол
67,келхъуб,мн. ч. келхъубар,нет,насмешка; издёвка; усмешка,существительное
68,кемеф,нет,да,полоумный,прилагательное
69,кепек,мн. ч. кепекер,нет,копейка,существительное
70,кепкил,мн. ч. кепкилар,нет,шумовка,существительное
71,керавел,нет,да,глухота,существительное
72,керкв,мн. ч. керквар,да,ноготь,существительное
73,кеспи,мн. ч. кеспибур,да,ремесло,существительное
74,кеттирхIас давереф,мн. ч. кеттирхIас давереттар,нет,недотрога,существительное
75,кеттирхIас дахьуб,нет,нет,раздражительность,существительное
76,кеф,мн. ч. кефар,нет,наслаждение; удовольствие,существительное
77,кефи,мн. ч. кефибур,нет,настроение; самочувствие,существительное
78,кехIей,нет,нет,аж,частица
79,ки,мн. ч. кибур,нет,частица,существительное
80,кикIас,мн. ч. кикIасар,нет,упрек,существительное
81,килавар,нет,нет,вес,существительное
82,килавар алцанф,нет,нет,весь,существительное
83,килиса,мн. ч. килисабур,нет,церковь,существительное
84,кимкима,нет,да,хаос,существительное
85,кирадж,мн. ч. кираджар,нет,известь; мел,существительное
86,кирачи,мн. ч. кирачибур,нет,арендатор,существительное
87,кирк,мн. ч. киркар,нет,ноготь,существительное
88,китаб,мн. ч. китабар,нет,книга,существительное
89,киф,мн. ч. кифар,нет,наслаждение; удовольствие,существительное
90,киш,нет,нет,суббота,существительное
91,ку,мн. ч. кубур,да,кизяк,существительное
92,куквел,нет,нет,полнота; ожирение,существительное
93,куку,мн. ч. кукубур,нет,яичница,существительное
94,кукф,нет,нет,полный; толстый; жирный,прилагательное
95,кул1,мн. ч. кулар,нет,штанина,существительное
96,кул2,мн. ч. кулар,нет,ветка; гроздь,существительное
97,кулагь,мн. ч. кулагьар,нет,бусинка; жемчужина,существительное
98,кулак,мн. ч. кулакар,нет,ветер; метель,существительное
99,кулаккеф,нет,нет,ветреный,прилагательное
100,кулегъ,мн. ч. кулегьар,нет,бусинка; кадык,существительное
101,кум1,мн. ч. кумар,нет,пар,существительное
102,кум2,мн. ч. кумар,нет,дым,существительное
103,кум3,мн. ч. кумар,нет,пыль,существительное
104,кума,мн. ч. кумабур,нет,землянка,существительное
105,кумак,нет,нет,помощь; поддержка; подмога,существительное
106,кумак акьас,нет,нет,выручить,глагол
107,кумак хъудаф,нет,нет,беспомощный,прилагательное
108,кумакчи,мн. ч. кумакчибур,нет,помощник,существительное
109,куманф,нет,нет,дымчатый,прилагательное
110,куме хьас,нет,нет,глупеть; тупеть,глагол
111,кумевел,нет,нет,тупость; дурость,существительное
112,кумеф,мн. ч. куметтар,нет,дурак; глупец,существительное
113,кумеф,мн. ч. куметтар,нет,глупый; полоумный,прилагательное
114,кумул,мн. ч. кумулар,нет,палец,существительное
115,кумулин ккедаф,нет,нет,недостойный,прилагательное
116,кумун ранг алеф,нет,нет,серый,прилагательное
117,кунар,нет,нет,одежда,существительное
118,купп,мн. ч. куппар,нет,кизяк,существительное
119,куранас,нет,нет,испачкать,глагол
120,куранас акьас,нет,нет,запачкать,глагол
121,курвел,нет,да,слепота,существительное
122,куреф,нет,нет,смуглый; чернявый,прилагательное
123,курмаг1,мн. ч. курмагIар,нет,дымоход,существительное
124,курси,мн. ч. курсибур,нет,стул,существительное
125,куруш,мн. ч. курушар,да,веник,существительное
126,курцIул,мн. ч. курцIулар,нет,щенок,существительное
127,куршам,нет,нет,айва,существительное
128,кут,нет,нет,побои,существительное
129,кутал,мн. ч. куталар,нет,плуг,существительное
130,кутар,нет,нет,побои,существительное
131,кутегь,мн. ч. кутегьар,нет,конец,существительное
132,кутIул,мн. ч. кутIулар,нет,прут,существительное
133,куц,мн. ч. куцар,нет,вид; облик,существительное
134,куц алеф,нет,нет,видный,прилагательное
135,куч,мн. ч. кучар,нет,коса,существительное
136,куча,мн. ч. кучабур,да,улица,существительное
137,куче акьас,нет,нет,греть; нагреть,глагол
138,куче хьас,нет,нет,нагреться,глагол
139,кучевел,нет,нет,жара,существительное
140,кучеф,нет,нет,горячий,прилагательное
141,кучиди,нет,да,горячо,наречие
142,кучи-кучи,нет,нет,горячо,наречие
143,куш-кушди,нет,нет,шепотом,наречие
144,куьгьна,нет,нет,старый; ветхий,прилагательное
145,куьгьнавел,мн. ч. куьгьнавелар,нет,староста,существительное
146,куьче,мн. ч. куьчебур,нет,улица,существительное
147,куьчебринф,нет,нет,уличный,прилагательное
148,ккабалай,мн. ч. ккабалаяр,нет,ящерица,существительное
149,ккабан,мн. ч. ккабанар,нет,скотовод; пастух,существительное
150,ккабачккалар,нет,нет,брусника,существительное
151,ккабилай,мн. ч. ккабилаяр,да,ящерица,существительное
152,ккан хьас,нет,нет,любить,глагол
153,ккан хьуб,мн. ч. ккан хьубар,нет,любовь,существительное
154,кканегьилди,нет,нет,свободно; вольно,наречие
155,кканегьилди аф,нет,нет,просторный; свободный; вольный,прилагательное
156,кканеф,нет,нет,милый; любимый; возлюбленный,прилагательное
157,кканчч,мн. ч. кканччар,нет,выступ; клык,существительное
158,ккачелибур,нет,нет,аттракцион,существительное
159,кквееревус,мн. ч. кквееревусар,нет,спуск,существительное
160,ккевес,нет,нет,спуститься,глагол
161,ккедагъас,нет,нет,удлиниться; вытянуться,глагол
162,ккедикас,нет,нет,разгромить,глагол
163,ккедихьас,нет,нет,уничтожить; разрушать; разорять; ликвидировать,глагол
164,ккедихьуб,нет,нет,уничтожение; разрушение,существительное
165,ккейшуб,нет,нет,обветшалость; ветхость,существительное
166,ккейшувусар,нет,нет,развалины; руины,существительное
167,ккейшуф,нет,нет,старый; ветхий,прилагательное
168,ккекк,мн. ч. ккеккер,нет,петух,существительное
169,ккеккеланф,нет,нет,петушиный,прилагательное
170,ккеку,мн. ч. ккекубур,нет,кукушка,существительное
171,ккел,мн. ч. ккелар,нет,ягнёнок,существительное
172,ккеруцай,нет,нет,изворотливо,наречие
173,ккеттархьас,нет,нет,уничтожиться,глагол
174,ккеттивун,мн. ч. ккеттивунар,нет,наслаждение,существительное
175,ккеттузас,нет,нет,выдоить,глагол
176,кке-ттушуф,нет,нет,прошедший,прилагательное
177,ккикку,мн. ч. ккиккубур,нет,кукушка,существительное
178,ккиркIвас,нет,нет,закончить,глагол
179,ккифккир,мн. ч. ккифккирар,да,шумовка,существительное
180,ккубул,нет,нет,ревматизм,существительное
181,ккул,мн. ч. ккулар,нет,полушубок; шуба; тулуп,существительное
182,ккулин байталман,мн. ч. ккулин байталманар,нет,бездельник; тунеядец,существительное
183,ккулинвел,мн. ч. ккулинвелар,нет,скука; тоска; лень,существительное
184,ккулинди1,нет,нет,лениво; нехотя,наречие
185,ккулинди2,нет,нет,тоскливо,наречие
186,ккулинф,нет,нет,ленивый,прилагательное
187,ккумук шуй,мн. ч. ккумук шувар,нет,кумык,существительное
188,ккунчI,мн. ч. ккунчIар,нет,букет,существительное
189,кукрт,мн. ч. кукртар,да,рубашка,существительное
190,къаб,мн. ч. къабар,нет,тарелка; чашка,существительное
191,къабан,мн. ч. къабанар,нет,кабан; вепрь,существительное
192,къабар,нет,нет,посуда,существительное
193,къабахь,мн. ч. къабахьар,нет,тыква,существительное
194,къавахIан1,мн. ч. къавахIанар,нет,замечание; порицание; упрёк,существительное
195,къавахIан2,мн. ч. къавахIанар,нет,прозвище,существительное
196,къавахIанар акъас,нет,нет,упрекнуть,глагол
197,къавум1,мн. ч. къавумар,нет,дыня,существительное
198,къавум2,мн. ч. къавумар,нет,сват,существительное
199,къад,нет,нет,двадцать,числительное
200,къадагъа,мн. ч. къадагъабур,нет,запрет,существительное
201,къадагъа акъас,нет,нет,запретить,глагол
202,къадакъ,мн. ч. къадакъар,нет,гвоздь,существительное
203,къаз,мн. ч. къазар,нет,гусь,существительное
204,къазалмишар,нет,нет,богатство,существительное
205,къазамат,мн. ч. къазаматар,нет,тюрьма,существительное
206,къазамиш,мн. ч. къазамишар,нет,заработок,существительное
207,къазан,мн. ч. къазанар,нет,котел,существительное
208,къазанджи,мн. ч. къазанджибур,нет,барыш,существительное
209,къайгура адай,нет,нет,беззаботно; беспечно,наречие
210,къайфат,мн. ч. къайфатар,нет,конфета,существительное
211,къакъ,мн. ч. къакъар,нет,тяжесть; ноша; груз; поклажа,существительное
212,къакъ алди,нет,нет,тяжко,наречие
213,къал фаф,нет,нет,скандальный,прилагательное
214,къала,мн. ч. къалабур,нет,крепость; замок,существительное
215,къалай,нет,нет,олово,существительное
216,къалайчи,мн. ч. къалайчибур,нет,лудильщик,существительное
217,къалат1,мн. ч. къалатар,нет,ошибка,существительное
218,къалат2,мн. ч. къалатар,нет,склока,существительное
219,къалат3,мн. ч. къалатар,нет,умысел,существительное
220,къалат кедахьуб,нет,нет,несправедливость,существительное
221,къалат кикIас,нет,нет,упрек,существительное
222,къалат кикIас,нет,нет,обвинить,глагол
223,къалат кикIлуб,нет,нет,обвинение,существительное
224,къалат хьас,нет,нет,ошибиться,глагол
225,къалка гIлуб,мн. ч. къалка гIлубар,нет,черепаха,существительное
226,къал-макъал,мн. ч. къал-макъалар,нет,ссора; скандал,существительное
227,къалпуз,мн. ч. къалпузар,нет,арбуз,существительное
228,къамат,мн. ч. къаматар,нет,фигура,существительное
229,къами,мн. ч. къамибур,нет,обжора,существительное
230,къамиш,мн. ч. къамишар,нет,тростник,существительное
231,къамчи,мн. ч. къамчибур,нет,плеть,существительное
232,къантIузай,мн. ч. къантIузаяр,нет,конопля,существительное
233,къапубур,нет,нет,ворота,существительное
234,къараваш,мн. ч. къаравашар,нет,слуга,существительное
235,къаравул,мн. ч. къаравулар,нет,сторож; страж; охрана; караул,существительное
236,къаравул акьас,нет,нет,охранять,глагол
237,къари1,мн. ч. къарибур,нет,старуха,существительное
238,къари2,нет,нет,полметра,существительное
239,къариб,нет,нет,странный,прилагательное
240,къариблух,мн. ч. къариблухар,да,чужбина,существительное
241,къарк,мн. ч. къаркар,нет,кора,существительное
242,къармах,мн. ч. къармахар,нет,крюк,существительное
243,къарфун,мн. ч. къарфунар,нет,желудок; живот; обжора; чревоугодник,существительное
244,къархьил,мн. ч. къархьилар,нет,локоть,существительное
245,къатир,мн. ч. къатирар,нет,мул,существительное
246,къафаз,мн. ч. къафазар,нет,клетка,существительное
247,къафкъазлу,мн. ч. къафкъазлубур,нет,кавказец,существительное
248,къафлан,мн. ч. къафланар,нет,тигр,существительное
249,къачагъ,мн. ч. къачагъар,нет,разбойник; грабитель,существительное
250,къаягъ,нет,да,послезавтра,наречие
251,къвадекь,мн. ч. къвадекьар,да,кожа,существительное
252,къвакъва,нет,да,чернослив,существительное
253,къвал,мн. ч. къвалар,нет,бок,существительное
254,къвалахь,нет,нет,возле; рядом,наречие
255,къвац,мн. ч. къвацар,нет,копыто,существительное
256,къев,мн. ч. къевар,нет,бутон,существительное
257,къегI,мн. ч. къегIар,нет,раздор,существительное
258,къейд акьас,нет,нет,записать,глагол
259,къейфат,мн. ч. къейфатар,нет,конфета,существительное
260,къекъеф,нет,нет,тяжёлый,прилагательное
261,къекъи,нет,нет,тяжело,наречие
262,къекъиди,нет,да,тяжело,наречие
263,къемчи,мн. ч. къемчибур,нет,кнут,существительное
264,къерекъел,мн. ч. къерекъелар,нет,сорока,существительное
265,къидж,мн. ч. къиджар,нет,папоротник,существительное
266,къиз,мн. ч. къизар,да,девочка; девушка; дочь,существительное
267,къизгъин,нет,нет,разъярённый,прилагательное
268,къизгъинвел,нет,нет,разъярённость,существительное
269,къизгъин хьас,нет,нет,разъяриться,глагол
270,къизил,нет,нет,золото,существительное
271,къизил шейъ,мн. ч. къизил шейъар,нет,драгоценность,существительное
272,къизилгюль,мн. ч. къизилгюлар,нет,роза,существительное
273,къизилф,нет,нет,драгоценный,прилагательное
274,къизмиш1,нет,нет,усталость,существительное
275,къизмиш2,нет,нет,жажда,существительное
276,къизмиш хьас,нет,нет,злиться,глагол
277,къизмишвел,нет,нет,злоба,существительное
278,къизмишди,нет,нет,злобно,наречие
279,къикъе адаф,нет,нет,невесомый,прилагательное
280,къикъевел,нет,нет,тяжесть,существительное
281,къикъеф,нет,нет,серьёзный; тяжёлый,прилагательное
282,къикъи,нет,нет,тяжело,наречие
283,къилит,мн. ч. къилитар,нет,засов,существительное
284,къир,мн. ч. къирар,нет,кружево,существительное
285,къирагъ,мн. ч. къирагъар,нет,край; сторона; окраина; берег; перила,существительное
286,къиргъиш,мн. ч. къиргъишар,нет,проклятие,существительное
287,къирибур,нет,нет,облака; тучи,существительное
288,къирибур алайкуна,нет,нет,безоблачный,прилагательное
289,къирибур алдай,нет,нет,безоблачный,прилагательное
290,къирмизи,мн. ч. къирмизибур,да,платок,существительное
291,къирхаягъ,мн. ч. къирхаягъар,нет,рак,существительное
292,къубу,мн. ч. къубубур,нет,купол,существительное
293,къугъ,мн. ч. къугъар,нет,перо; пух,существительное
294,къудур бег,мн. ч. къудур бегар,нет,самодур,существительное
295,къуджа,мн. ч. къуджабур,нет,старик,существительное
296,къуй,мн. ч. къуяр,нет,яма; колодец,существительное
297,къул,мн. ч. къулар,нет,подпись; роспись,существительное
298,къул дивас,нет,нет,подтверждение,существительное
299,къулайвел,нет,нет,удобство,существительное
300,къулайди,нет,нет,удобно,наречие
301,къулайсуз,нет,нет,неудобный,прилагательное
302,къулайсузвел,нет,нет,неудобство,существительное
303,къулайсузди,нет,нет,неудобно,наречие
304,къуллугъ,мн. ч. къуллугъар,нет,служба; должность,существительное
305,къуллугъвел,нет,нет,служение,существительное
306,къуллугъчи1,мн. ч. къуллугъчибур,нет,чин,существительное
307,къуллугъчи2,мн. ч. къуллугъчибур,нет,служащий,существительное
308,къум,мн. ч. къумар,нет,песок,существительное
309,къумбар хьас,нет,да,развеселиться,глагол
310,къумрал,нет,да,смуглый,прилагательное
311,къун,мн. ч. къунар,нет,горбун,существительное
312,къунши,мн. ч. къуншибур,нет,сосед,существительное
313,къуншивел,нет,нет,соседство,существительное
314,къуншинф,нет,нет,соседний,прилагательное
315,къупп,мн. ч. къуппар,нет,клюв,существительное
316,къураба,мн. ч. къурабабур,нет,чужак,существительное
317,къурах,нет,нет,засушливый,прилагательное
318,къурахвел,нет,нет,засуха,существительное
319,къурбеф,нет,да,рассыпчатый,прилагательное
320,къургъушум,нет,нет,свинец,существительное
321,къурумсагъ,нет,да,подлый,прилагательное
322,къурумсагъвел,нет,да,подлость,существительное
323,къурумсагъди,нет,нет,подло,наречие
324,къурху,нет,да,испуг; страх; угроза,существительное
325,къурч,мн. ч. къурчар,нет,пустырь,существительное
326,къускъун,мн. ч. къускъунар,нет,горб,существительное
327,къускъун аф,мн. ч. къускъун аттар,нет,горбун,существительное
328,къут,мн. ч. къутар,нет,приятель,существительное
329,къутармиш,нет,нет,выручить,глагол
330,къучагъ,мн. ч. къучагъар,нет,удалец; храбрец,существительное
0,къучи,мн. ч. къучибур,нет,разбойник,существительное
1,къучма,мн. ч. къучмабур,нет,друг; подруга; приятель,существительное
2,къуша,мн. ч. къушабур,да,пара,существительное
3,къушум,нет,нет,армия; войско,существительное
4,къуьре акьас,нет,нет,затупить,глагол
5,къуьре хъас,нет,нет,затупиться,глагол
6,кьаб,мн. ч. кьабар,нет,опора,существительное
7,кьабахъ,нет,да,сзади; позади,наречие
8,кьабахъай,нет,нет,после,наречие
9,кьабахъас,нет,да,сзади; позади,наречие
10,кьабул,нет,нет,приятие,существительное
11,кьабул акъас,нет,нет,принять,глагол
12,кьабулдаф,нет,нет,неприемлемый,прилагательное
13,кьабулсуз,нет,нет,неприемлемый,прилагательное
14,кьав,мн. ч. кьавар,да,опора,существительное
15,кьавалар,нет,нет,музыканты,существительное
16,кьавкI,нет,да,моль,существительное
17,кьавул,нет,нет,согласие; приятие,существительное
18,кьагьар хьас,нет,нет,опечалиться,глагол
19,кьада,мн. ч. кьадабур,нет,беда,существительное
20,кьадам,мн. ч. кьадамар,нет,визит; шаг,существительное
21,кьадар1,нет,нет,предопределённость; решение,существительное
22,кьадар2,нет,нет,стоимость; достоинство,существительное
23,кьадар3,нет,нет,объём,существительное
24,кьадар сан,нет,нет,количество,существительное
25,кьадирсуз,нет,нет,неблагодарный,прилагательное
26,кьадри адавел,нет,нет,неблагодарность,существительное
27,кьадри адай,нет,нет,неблагодарно,наречие
28,кьадри адаф,нет,нет,неблагодарный,прилагательное
29,кьадрисузвел,нет,нет,неблагодарность,существительное
30,кьадрисузди,нет,нет,неблагодарно,наречие
31,кьаза,нет,да,несчастье,существительное
32,кьайда,нет,нет,мера; степень; величина,существительное
33,кьайда хьуб,нет,нет,экономность,существительное
34,кьайда ягIаф,нет,нет,экономный,прилагательное
35,кьайдасузди гъургаф,нет,нет,болтливый,прилагательное
36,кьайдасузди гъургъуб,нет,нет,болтливо,наречие
37,кьайде,нет,нет,экономия,существительное
38,кьайди,нет,нет,экономно,наречие
39,кьакь,мн. ч. кьакьар,нет,обхват,существительное
40,кьал,мн. ч. кьалар,нет,стебелёк,существительное
41,кьалам,мн. ч. кьаламар,нет,карандаш; перо; ручка,существительное
42,кьалар,нет,нет,полынь,существительное
43,кьалп,нет,да,поддельный; фальшивый,прилагательное
44,кьамкьаш,мн. ч. кьамкьашар,нет,хрящ,существительное
45,кьана акьун,нет,нет,поздно,наречие
46,кьанди,нет,нет,поздно,наречие
47,кьаниIэт,нет,нет,экономия,существительное
48,кьаниIэтди,нет,нет,экономно,наречие
49,кьаниIэтлу,нет,нет,экономный,прилагательное
50,кьаниIэтлувал,нет,нет,экономность,существительное
51,кьап кедахъун,нет,нет,неряшливо,наречие
52,кьапар,нет,нет,нечистоты,существительное
53,кьапач,мн. ч. кьапачар,нет,неряха,существительное
54,кьапIкI,нет,нет,моль,существительное
55,кьарар1,нет,нет,постановление,существительное
56,кьарар2,нет,нет,терпение,существительное
57,кьарар акьас,нет,нет,подождать; потерпеть,глагол
58,кьарар ккедавел,нет,нет,нетерпеливость,существительное
59,кьарар ккедай,нет,нет,нетерпеливо,наречие
60,кьарар ккедаф,нет,нет,нетерпеливый,прилагательное
61,кьарар ккеф,нет,нет,терпеливый,прилагательное
62,кьарар хьуб,нет,нет,выносливость,существительное
63,кьарарсуз,нет,нет,нетерпеливый,прилагательное
64,кьарарсузвел,нет,нет,нетерпеливость,существительное
65,кьарарсузди,нет,нет,нетерпеливо,наречие
66,кьаратиген,мн. ч. кьаратигенар,нет,растение,существительное
67,кьаркьала,нет,нет,телосложение,существительное
68,кьартIанай,мн. ч. кьартIанаяр,нет,лопух,существительное
69,кьас,мн. ч. кьасар,да,полка,существительное
70,кьас,нет,нет,делать,глагол
71,кьаса,мн. ч. кьасабур,нет,смычок,существительное
72,кьасабхана,мн. ч. кьасабханабур,нет,скотобойня,существительное
73,кьастсузди,нет,нет,бесцельно; непреднамеренно,наречие
74,кьастт,нет,нет,старание; упорство; терпение; воля; цель,существительное
75,кьастт акьуб,нет,нет,решимость,существительное
76,кьасустти,нет,нет,нарочно,наречие
77,кьасустти давай,нет,нет,непреднамеренно,наречие
78,кьасусттира,нет,нет,специально,наречие
79,кьацінкá медж,нет,нет,крапива,существительное
80,кьацIра,нет,нет,вообще,наречие
81,кьацIра миндай,нет,нет,совсем; насовсем; окончательно,наречие
82,кьвадекь,мн. ч. кьвадекьар,нет,кожа,существительное
83,кьвадилкьван,мн. ч. кьвадилкьванар,нет,ковёр; сумах,существительное
84,кьвакь,мн. ч. кьвакьар,нет,колено,существительное
85,кьвали,мн. ч. кьвалибур,нет,куст,существительное
86,кьвани,мн. ч. кьванибур,нет,короб,существительное
87,кьавIачI,мн. ч. кьавIачIар,нет,локоть,существительное
88,кьебзур,нет,нет,рассол,существительное
89,кьедибан,мн. ч. кьедибанар,нет,ёж,существительное
90,кьел,нет,нет,соль,существительное
91,кьеланди,нет,нет,кисло; горько,наречие
92,кьеланф,нет,нет,солёный; пересоленный; горький,прилагательное
93,кьерзул,нет,да,рассол,существительное
94,кьесусттинф,нет,нет,специальный,прилагательное
95,къеклел,мн. ч. къеклелар,нет,герой,существительное
96,къеклел,нет,да,храбрый,прилагательное
97,къеклелвел,нет,нет,героизм,существительное
98,къеклелди,нет,нет,героически,наречие
99,къеклетвел,нет,нет,дефицит,существительное
100,кьец,мн. ч. кьецар,нет,козёл,существительное
101,кьецлар1,нет,нет,щипцы,существительное
102,кьецар2,нет,нет,плоскогубцы,существительное
103,кьецIу лекари,нет,нет,босиком,наречие
104,кьецIул джан,мн. ч. кьецIул джанар,нет,тело,существительное
105,кьецIулвел,нет,нет,нагота,существительное
106,кьибла,нет,нет,юг,существительное
107,кьидибан,мн. ч. кьибиданар,да,ёж,существительное
108,кьимат,нет,нет,стоимость; плата; хвала; похвала,существительное
109,кьимат ай,нет,нет,значимо,наречие
110,кьимат аф,нет,нет,драгоценный; значимый,прилагательное
111,кьимат ахьуб,нет,нет,ценность,существительное
112,кьимат йис,мн. ч. кьимат йибар,нет,оценка,существительное
113,кьимат хьуб,нет,нет,значимость,существительное
114,кьиматлувел,нет,нет,ценность,существительное
115,кьиматсузвел,нет,нет,бесполезность; ничтожность,существительное
116,кьиматсузди,нет,нет,дёшево; даром,наречие
117,кьиса,мн. ч. кьисабур,нет,случай; событие,существительное
118,кьисас,нет,нет,месть; возмездие; кара,существительное
119,кьисасчи,мн. ч. кьисасчибур,нет,мститель,существительное
120,кьис-кьис,нет,нет,жадный,прилагательное
121,кьис-кьисвел,нет,нет,жадность; скупость,существительное
122,кьис-кьисди,нет,да,жадно; алчно,наречие
123,кьисмат,нет,нет,судьба; доля; рок,существительное
124,кьисматкар,нет,нет,счастливый,прилагательное
125,кьит,нет,нет,дефицит,существительное
126,кьитхъуб,нет,нет,дефицит,существительное
127,кьиф,мн. ч. кьифар,нет,воронка,существительное
128,кьицI-кьицIвел,нет,нет,алчность,существительное
129,кьицI-кьицIди,нет,нет,алчно,наречие
130,кьицI-кьицIф,нет,нет,алчный,прилагательное
131,кьияматди,нет,нет,странно; непонятно,наречие
132,кьуват,нет,нет,сила; мощь; могущество,существительное
133,кьуват адаф,нет,нет,бессильный,прилагательное
134,кьуват кедаф,нет,нет,немощный,прилагательное
135,кьуватинф,нет,нет,мощный; могучий,прилагательное
136,кьуватсуз,нет,нет,бессильный; немощный,прилагательное
137,кьуватти,нет,нет,сильно,наречие
138,кьуваттди,нет,нет,оживлённо; бодро,наречие
139,кьудакь,мн. ч. кьудакьар,нет,кожа; шкура; шкурка,существительное
140,кьудикь,мн. ч. кьудикьар,да,кожа; шкура,существительное
141,кьудук,нет,да,улей,существительное
142,кьукь,мн. ч. кьукьар,нет,колено,существительное
143,кьулкьум,нет,нет,горечь,существительное
144,кьулкьумф,нет,нет,горький; едкий,прилагательное
145,кьумаш,нет,нет,трикотаж,существительное
146,кьун,мн. ч. кьунар,нет,козёл,существительное
147,кьур,мн. ч. кьурар,нет,зёрнышко,существительное
148,кьурамат,нет,нет,суша; материк,существительное
149,кьуркь1,мн. ч. кьуркьар,нет,шея; горло,существительное
150,кьуркь2,мн. ч. кьуркьар,нет,лебедь,существительное
151,кьуркьул,нет,нет,едкий,прилагательное
152,кьуртI,мн. ч. кьуртIар,нет,глоток,существительное
153,кьуртI акьас,нет,нет,выпить,глагол
154,кьурукь,мн. ч. кьурукьар,нет,журавль,существительное
155,кьурц,мн. ч. кьурцар,нет,кусок; долька,существительное
156,кьутт,мн. ч. кьуттар,нет,камень; камушек,существительное
157,кьутI,мн. ч. кьутIар,нет,морковь,существительное
158,кьутIур,мн. ч. кьутIурар,нет,пирог,существительное
159,кьуш,мн. ч. кьушар,нет,черпак; половник,существительное
160,кьуIрд,нет,да,зима,существительное
161,кIампур,мн. ч. кIампурар,нет,подбородок; челюсть,существительное
162,кIар,нет,нет,темнота; чернота,существительное
163,кIар атIас,нет,нет,потемнеть,глагол
164,кIарантIур,мн. ч. кIарантIурар,нет,бородавка,существительное
165,кIаратI,мн. ч. кIаратIар,нет,отара; стадо,существительное
166,кIаре,нет,нет,темно; тяжко,наречие
167,кIаре акьас,нет,нет,почернить,глагол
168,кIаре хут,мн. ч. кIаре хутар,нет,слива; чернослив,существительное
169,кIаре хьас,нет,нет,потемнеть; почернеть,глагол
170,кIаре хьуб,нет,нет,чернеть,глагол
171,кIареф,нет,нет,чёрный,прилагательное
172,кIари,нет,нет,черно,наречие
173,кIариди,нет,да,черно,наречие
174,кIарч,мн. ч. кIарчар,нет,рог,существительное
175,кIачIа-кIулар,нет,да,щекотка,существительное
176,кIачIал тIуб,мн. ч. кIачIал тIубар,нет,мизинец,существительное
177,кIачIалай,мн. ч. кIачIалаяр,нет,мизинец,существительное
178,кIаш,мн. ч. кIашар,нет,палка,существительное
179,кIашниш,мн. ч. кIашнишар,нет,кориандр,существительное
180,кIвал акъас,нет,нет,подсказка,существительное
181,кIвал акъас,нет,нет,вспомнить; напомнить,глагол
182,кIвалас вес,нет,нет,забыть,глагол
183,кIвалас ушуб,нет,нет,забыться,глагол
184,кIвана кIили адай,нет,нет,вдруг; внезапно,наречие
185,кIватIал,мн. ч. кIватIалар,нет,группа,существительное
186,кIедж1,мн. ч. кIеджар,нет,бумага; письмо,существительное
187,кIедж2,мн. ч. кIеджар,нет,амулет; талисман,существительное
188,кIедж акъуф,нет,нет,порча,существительное
189,кIекIец,мн. ч. кIекIецар,да,трость,существительное
190,кIен,мн. ч. кIенар,нет,дно; основание,существительное
191,кIенакк,нет,нет,вон внизу,наречие
192,кIенакк аликIа кунар,нет,нет,бельё,существительное
193,кIенар1,нет,нет,остатки; отходы,существительное
194,кIенар2,нет,нет,осадок,существительное
195,кIес,нет,нет,умирать,глагол
196,кIетIа,мн. ч. кIетIабур,нет,лопата,существительное
197,кIивус,нет,нет,похороны,существительное
198,кIил,мн. ч. кIилар,нет,голова,существительное
199,кIил асаруцас,мн. ч. кIил асаруцасар,нет,головокружение,существительное
200,кIил дивас,нет,да,проведать,глагол
201,кIил дивуб,мн. ч. кIил дивубар,нет,визит,существительное
202,кIил ккей чIуф,нет,нет,лысый,прилагательное
203,кIилди,нет,нет,весь,местоимение
204,кIиле хьас,нет,нет,утончиться,глагол
205,кIилеф,нет,нет,хрупкий,прилагательное
206,кIили,нет,нет,заглавный,прилагательное
207,кIили аф,мн. ч. кIили аттар,нет,голова (должностное лицо),существительное
208,кIили гъареф,нет,нет,ведущий,прилагательное
209,кIилил аликIа ягълукъ,мн. ч. кIилил аликIа ягълукъар,нет,платок,существительное
210,кIилинвел,нет,нет,независимость,существительное
211,кIилинф,нет,нет,целый,прилагательное
212,кIилле акьас,нет,нет,истончить,глагол
213,кIилле хьас,нет,нет,истончиться,глагол
214,кIиллевел,нет,нет,тонкость; худоба,существительное
215,кIиллеф,нет,нет,тонкий,прилагательное
216,кIилли,нет,нет,тонко,наречие
217,кIиллиди,нет,да,тонко,наречие
218,кIинаф,мн. ч. кIинаттар,нет,покойный,существительное
219,кIиркI,мн. ч. кIиркIар,нет,мальчик; юноша; парень; сын,существительное
220,кIиркIвас,нет,нет,кончить,глагол
221,кIитIуб,нет,нет,эксплуатация,существительное
222,кIукI,мн. ч. кIукIар,нет,верхушка; вершина; макушка,существительное
223,кIукI алавей,нет,нет,обильно,наречие
224,кIукI алеф,мн. ч. кIукI алеттар,нет,верхушка,существительное
225,кIукI алеф,нет,нет,обильный,прилагательное
226,кIулкIум,мн. ч. кIулкIумар,нет,прорубь,существительное
227,кIум,нет,да,сметана,существительное
228,кIумп,мн. ч. кIумпар,нет,пробка,существительное
229,кIумпI,мн. ч. кIумпIар,нет,щека,существительное
230,кIунтI гъутIуф,нет,нет,курносый,прилагательное
231,кIур1,мн. ч. кIурар,нет,дерево,существительное
232,кIур2,мн. ч. кIурар,нет,жребий,существительное
233,кIурандуракь,нет,нет,оранжевый,прилагательное
234,кIурандуракьинф,нет,нет,оранжевый,прилагательное
235,кIутIурар,нет,нет,пироги,существительное
236,кIучI,мн. ч. кIучIар,нет,пуговица,существительное
237,кIуьркIвас,нет,нет,кончить,глагол
238,лавгьади,нет,да,болтливо; несерьёзно,наречие
239,лаган,мн. ч. лаганар,нет,таз,существительное
240,лаззат,нет,да,удовольствие,существительное
241,лаззатсуз,нет,нет,невкусный,прилагательное
242,лазим даваф,нет,да,бесполезный,прилагательное
243,лазим хьас,нет,да,понадобиться,глагол
244,лазимвел,нет,да,надобность; необходимость,существительное
245,лазимсуз,нет,да,ненужный,прилагательное
246,лазимф,нет,да,нужный; необходимый,прилагательное
247,лакIаб,мн. ч. лакIабар,нет,кличка,существительное
248,лал,нет,нет,потерять,глагол
249,лам,нет,нет,сырость; мокрота,существительное
250,лам ай,нет,нет,влажность,существительное
251,лам кей,нет,нет,влажно; сыро,наречие
252,лам кеф,нет,нет,влажный,прилагательное
253,ламус,нет,нет,совесть; честь,существительное
254,ламус адай,нет,нет,бессовестно; нагло,наречие
255,ламус гIадавел,нет,нет,бессовестность,существительное
256,ламус кеф,нет,нет,добросовестный,прилагательное
257,ламус хъудавел,нет,нет,бесчестность,существительное
258,ламусвел,нет,нет,совестивость,существительное
259,ламусди,нет,нет,совестливо; стыдливо; неудобно,наречие
260,ламусдинф,нет,нет,добросовестный,прилагательное
261,ламусинф,нет,нет,совестливый,прилагательное
262,ламуссуз,мн. ч. ламусузар,нет,негодяй; подлец,существительное
263,ламуссуз,нет,нет,бессовестный; бесчестный,прилагательное
264,ламуссузвел,нет,нет,бесчестность,существительное
265,ламуссузди,нет,нет,бессовестно; нагло,наречие
266,ламусф,нет,нет,неудобный,прилагательное
267,ланда,мн. ч. ландабур,нет,рубанок,существительное
268,лап хаб,нет,нет,очень,наречие
269,лап Iуьсеф,нет,нет,престарелый,прилагательное
270,ларз1,мн. ч. ларзар,нет,веранда; терраса,существительное
271,ларз2,мн. ч. ларзар,нет,коридор; прихожая,существительное
272,лат,мн. ч. латар,нет,бассейн,существительное
273,лату,мн. ч. латубур,нет,жир,существительное
274,лахшан,мн. ч. лахшанар,нет,издевка; насмешка,существительное
275,лахшанар акьас,нет,да,издеваться,глагол
276,лачахь,мн. ч. лачахьар,нет,платок,существительное
277,лачин,мн. ч. лачинар,нет,сокол,существительное
278,лаш,мн. ч. лашар,нет,тело,существительное
279,ле1,нет,нет,такой,местоимение
280,ле2,нет,нет,этот,местоимение
281,ле3,нет,нет,который,союзное слово
282,леген,мн. ч. легенар,да,таз,существительное
283,легIли,мн. ч. легIлибур,нет,жемчужина,существительное
284,леджбер,мн. ч. леджберар,нет,крестьянин,существительное
285,лезги шуй,мн. ч. лезги шувар,нет,лезгин,существительное
286,лек1,мн. ч. лекар,нет,шаг,существительное
287,лек2,мн. ч. лекар,нет,нога,существительное
288,лек ахьишаф адаф,нет,нет,беззащитный,прилагательное
289,лек ишивус,мн. ч. лек ишивусар,нет,след,существительное
290,лекар алдархьавус,мн. ч. лекар алдархьавусар,нет,прихожая,существительное
291,лекарил аликIаттар,нет,нет,обувь,существительное
292,лекулди,нет,нет,пешком,наречие
293,лекун ишан,мн. ч. лекун ишанар,нет,след,существительное
294,лекун кIен,мн. ч. лекун кIенар,нет,стопа; подошва,существительное
295,лекI,мн. ч. лекIер,нет,печень,существительное
296,ленг,нет,нет,замедлить; затормозить,глагол
297,лепе,мн. ч. лепебур,нет,волна,существительное
298,лепI-лепI,нет,нет,лепет,существительное
299,лехьун,мн. ч. лехьунар,нет,танец,существительное
300,лехIаф,мн. ч. лехIафар,нет,одеяло; покрывало,существительное
301,лехIеф,мн. ч. лехIефар,да,одеяло,существительное
302,лехIзе,нет,нет,миг; мгновение,существительное
303,леIэн,мн. ч. леIэнар,нет,подкова,существительное
304,лигим,нет,нет,закалённый,прилагательное
305,лигим акьас,нет,нет,закалить,глагол
306,лигим хьас,нет,нет,закалиться,глагол
307,лигимвел,нет,нет,закалка,существительное
308,ликIенас1,нет,нет,записать,глагол
309,ликIенас2,нет,нет,напечатать,глагол
310,ликIи хатI,мн. ч. ликIи хатIар,нет,почерк,существительное
311,ликIинаф,нет,нет,предопределённость,существительное
312,лил,мн. ч. лилар,нет,синька,существительное
313,лиркIен хIерфар,нет,нет,орфография,существительное
314,лит,мн. ч. литар,нет,бурка,существительное
315,литература,мн. ч. литературабур,нет,литература,существительное
316,лихун,мн. ч. лихунар,да,труд; дело; работа,существительное
317,лихъун,мн. ч. лихъунар,да,танец,существительное
318,лиI,мн. ч. лиIар,нет,орёл,существительное
319,лагьа,нет,нет,там,наречие
320,лилась,нет,нет,там,наречие
321,лудж,мн. ч. луджар,да,стадо,существительное
322,лукман,мн. ч. лукманар,нет,песчинка,существительное
323,лукI,мн. ч. лукIар,нет,слуга; раб,существительное
324,лути,мн. ч. лутибур,нет,озорник; гуляка,существительное
325,лутивел,нет,нет,озорство,существительное
326,луф,мн. ч. луфар,нет,голубь,существительное
327,луьхIуьм,нет,да,средство,существительное
328,мавгьумат,мн. ч. мавгьуматар,нет,обвинение; упрёк,существительное
329,мавлуд,мн. ч. мавлудар,нет,мавлид,существительное
330,мавун чарккв,мн. ч. мавун чаркквар,нет,почка,существительное
331,магариш,мн. ч. магаришар,нет,подарок,существительное
332,магариш акьас,нет,нет,подарить,глагол
333,магъара,мн. ч. магъарабур,нет,пещера,существительное
334,магъриб,нет,нет,запад,существительное
335,магьа,нет,нет,вот,частица
336,магьи,нет,нет,чистый,прилагательное
337,магьме,нет,нет,это,частица
338,магьме,нет,нет,этот,местоимение
339,магьмисаас,нет,нет,вот (отсюда),частица
340,магьмисаь,нет,нет,вот (здесь),частица
341,магьмишттинф1,нет,нет,такой; такой-то,местоимение
342,магьмишттинф2,нет,нет,этот,местоимение
343,магьмишттинф3,нет,нет,некий,местоимение
344,магьмишттинф,нет,нет,который,союзное слово
345,магьур,мн. ч. магьурар,нет,заклинание; наговор,существительное
346,магьшур хьас,нет,да,увеличиться,глагол
347,магIдж,мн. ч. магIджар,да,крапива,существительное
348,мадар,нет,да,помощь,существительное
349,маджбур,нет,нет,обязать,глагол
350,маджбурвал,мн. ч. маджбурвалар,да,обязательство,существительное
351,маджус,мн. ч. маджусар,нет,язычник,существительное
352,мазахай,мн. ч. мазахаяр,нет,весельчак; шутник,существительное
353,мазгит,мн. ч. мазгитар,нет,мечеть,существительное
354,май,нет,нет,май,существительное
355,майдан,мн. ч. майданар,нет,плоскость; долина,существительное
356,майдан мукь,мн. ч. майдан мукьар,нет,равнина; площадь,существительное
357,майданди,нет,нет,гладко,наречие
358,майданф1,нет,нет,бесхитростный,прилагательное
359,майданф2,нет,нет,гладкий,прилагательное
360,майил1,нет,нет,поблажка,существительное
361,майил2,нет,да,поддержка,существительное
362,майит,мн. ч. майитар,нет,труп,существительное
363,маймун,мн. ч. маймунар,нет,обезьяна,существительное
364,мактаб,мн. ч. мактабар,да,школа,существительное
365,макур1,нет,нет,хитрость,существительное
366,макур2,нет,нет,авантюра,существительное
367,макур кей,нет,нет,коварно,наречие
368,макурар акьас,нет,нет,хитрить,глагол
369,макурар кеф,нет,нет,коварный,прилагательное
370,макурди,нет,нет,вероломно; коварно,наречие
371,макурзана,мн. ч. макурзанабур,нет,хитрец; авантюрист; льстец,существительное
372,макурзана,нет,нет,хитрый; коварный,прилагательное
373,макьала,мн. ч. макьалабур,нет,статья,существительное
374,макьалачи,мн. ч. макьалачибур,нет,корреспондент,существительное
375,макъам,мн. ч. макъамар,нет,мелодия; мотив,существительное
376,макъарунар,нет,нет,макароны,существительное
377,мал,мн. ч. малар,нет,животное,существительное
378,малайик,мн. ч. малайикар,нет,ангел,существительное
379,малар,нет,нет,скотина,существительное
380,малар ухIа чул,мн. ч. малар ухIа чулар,нет,пастбище,существительное
381,малар ухIавус,мн. ч. малар ухIавусар,нет,ферма,существительное
382,маларин духттур,мн. ч. маларин духттурар,нет,ветеринар,существительное
383,маларин сал,мн. ч. маларин салар,нет,коровник,существительное
384,маларин Iелеф,мн. ч. маларин Iелеттар,нет,корм,существительное
385,малдар,мн. ч. малдарар,нет,скотовод,существительное
386,мал-девлет,нет,нет,имущество,существительное
387,малдин якк,нет,нет,говядина,существительное
388,малик,нет,нет,торжественный,прилагательное
389,малла,мн. ч. маллабур,нет,мулла,существительное
390,малхазина,мн. ч. малхазинабур,нет,богатство,существительное
391,манат,мн. ч. манатар,нет,рубль,существительное
392,манзил,мн. ч. манзилар,нет,расстояние; промежуток,существительное
393,маракам,нет,нет,чернила,существительное
394,маргъал,мн. ч. маргъалар,нет,ландыш,существительное
395,мармалат,нет,нет,мармелад,существительное
396,март,нет,нет,март,существительное
397,мархал,мн. ч. мархалар,нет,лавина,существительное
398,маскъв,мн. ч. маскъвар,нет,мозг,существительное
399,маслихIат,нет,нет,решение; мир,существительное
400,маслихIат акьуб,мн. ч. маслихIат акьубар,нет,соглашение; договорённость,существительное
401,маслихIат акьуф,нет,нет,согласованный,прилагательное
402,мастт,мн. ч. масттар,нет,кефир,существительное
403,масттала,мн. ч. мастталабур,нет,загадка; головоломка,существительное
404,матлаб,мн. ч. матлабар,нет,намерение; цель,существительное
405,махлукъ,мн. ч. махлукъар,нет,народ; толпа,существительное
406,махппур,нет,нет,бархат,существительное
407,махь,мн. ч. махьар,да,овчарня,существительное
408,махьттаб,мн. ч. махьттабар,нет,школа,существительное
409,махьттабиди вереф,мн. ч. махьттабиди верефар,нет,школьник,существительное
410,махIсул,нет,нет,посевы,существительное
411,мац,мн. ч. мацар,нет,очаг,существительное
412,мач,мн. ч. мачар,нет,поцелуй,существительное
413,мач икIас,нет,нет,поцеловать,глагол
414,маш,мн. ч. машар,да,щека,существительное
415,машгъулвел,нет,нет,занятость,существительное
416,машгьур,нет,нет,известный,прилагательное
417,машгьурвел,нет,нет,известность; слава,существительное
418,машмаш,мн. ч. машмашар,нет,абрикос,существительное
419,машрикь,нет,нет,восток,существительное
420,ме,нет,нет,это,частица
421,мегьела,мн. ч. мегьелабур,нет,околоток,существительное
422,мегьелди,нет,нет,пока,наречие
423,мегьрибан,нет,нет,приветливый,прилагательное
424,мегелим,мн. ч. мегелимар,нет,учитель; преподаватель,существительное
425,мегелим хьир,мн. ч. мегелим хьирар,нет,учительница,существительное
426,мегели,нет,нет,ласковый,прилагательное
427,мегеливел,нет,нет,ласковость; душевность,существительное
428,мегелум,нет,нет,понятный; ясный,прилагательное
429,мегелумат,мн. ч. мегелуматар,нет,информация; донесение,существительное
430,мегелуматич,мн. ч. мегелуматчибур,нет,вестник,существительное
431,мегелумвел,нет,да,ясность,существительное
432,мегелумсуз,нет,нет,неизвестный,прилагательное
433,мегIна,мн. ч. мегIнабур,нет,смысл,существительное
434,мегIналу,нет,нет,содержательный; значимый,прилагательное
435,мегIналувел,нет,нет,содержательность; значимость,существительное
436,мегIналуди,нет,нет,содержательно; значимо,наречие
437,мегIни,мн. ч. мегIнибур,нет,песня; стихотворение,существительное
438,мегIнибур аркьаф,мн. ч. мегIнибур аркьафар,нет,певец,существительное
439,медж,мн. ч. маджар,нет,крапива,существительное
440,меджмеIер,нет,нет,чечевица,существительное
441,мез,мн. ч. мезар,нет,язык,существительное
442,мез акьас,нет,нет,лесть,существительное
443,мез акьуб,нет,нет,подхалимство,существительное
444,мез йирхIас,нет,нет,лизать; облизывать; слизывать,глагол
445,мез кедавел,нет,нет,грубость,существительное
446,мез кедай,нет,нет,грубо,наречие
447,мез кей ширинф,нет,нет,ласковый,прилагательное
448,мез эс,нет,да,облизывать,глагол
449,мезар кей,нет,нет,льстиво,наречие
450,мезар-гIзмалар,нет,нет,лесть,существительное
451,мезрухI,мн. ч. мезрухIар,нет,говорун,существительное
452,мезрухI,нет,нет,красноречивый,прилагательное
453,мезуралвел,нет,нет,красноречивость,существительное
454,мезуралди,нет,нет,ласковость,существительное
455,мезуралди,нет,нет,красноречиво,наречие
456,мектеб,мн. ч. мектебар,да,школа,существительное
457,мекь хьуная,нет,нет,простуда,существительное
458,мекI,мн. ч. мекIар,нет,холод; мороз; стужа,существительное
459,мекI акьас,нет,нет,морозить,глагол
460,мекI хьуб,нет,нет,простуда,существительное
461,мелIуьнвел1,нет,нет,упрямство,существительное
462,мелIуьнвел2,нет,нет,хитрость,существительное
463,менгена,нет,нет,тиски,существительное
464,мерджан,мн. ч. мерджанар,нет,коралл,существительное
465,мере,мн. ч. меребур,нет,ежевика,существительное
466,меркез,мн. ч. меркезар,нет,столица,существительное
467,меркк,мн. ч. мерккар,нет,лёд; град,существительное
468,меркIв,мн. ч. меркIвар,нет,колючка; чертополох,существительное
469,мертеба,мн. ч. мертебабур,нет,этаж,существительное
470,мертт акьас,нет,нет,чистить,глагол
471,мертт хьас,нет,нет,очиститься,глагол
472,мерттвел,нет,нет,чистота,существительное
473,мерттевел,нет,нет,незапятнанность; непорочность; честность; чистота,существительное
474,мерттеф,нет,нет,незапятнанный; чистый,прилагательное
475,мерттеф даф,нет,нет,нечистый,прилагательное
476,мертти,нет,нет,окончательно; совсем; насовсем,наречие
477,мертти-гIаттивуб,мн. ч. мертти-гIаттивубар,нет,порядок,существительное
478,мерхIемат,нет,нет,сострадание,существительное
479,мерхIематлу,нет,нет,милосердный,прилагательное
480,мерI,мн. ч. мерIар,нет,корень,существительное
481,месела,мн. ч. меселабур,нет,проблема,существительное
482,мессебсузвел,мн. ч. мессебсузвелар,нет,грубость,существительное
483,мессебсузди,нет,нет,грубо,наречие
484,метлеб,мн. ч. метлебар,нет,намерение; пожелание,существительное
485,мефеIэт,мн. ч. мефеIетар,нет,выгода; польза; отдача; полезность,существительное
486,мефеIэт акьас,нет,нет,принести (пользу),глагол
487,мефеIэт гьас,нет,нет,принести,глагол
488,мефеIэт кедай,нет,нет,невыгодно; бесполезно,наречие
489,мефеIэт кеф,нет,нет,полезный,прилагательное
490,мефеIэт кидаф,нет,нет,бесполезный,прилагательное
491,мефеIэт хьеб,нет,нет,выгодность,существительное
492,мефеIэт эс,нет,нет,принести,глагол
493,мефеIэтвел,нет,нет,выгодность,существительное
494,мефеIэтлу,нет,нет,полезный,прилагательное
495,мефеIэтлувел,нет,нет,полезность,существительное
496,мефеIэтсузди,нет,нет,бесполезно; невыгодно,наречие
497,мехь,мн. ч. мехъар,нет,ржавчина,существительное
498,мехь ярхIас,нет,да,ржаветь; заржаветь,глагол
499,мехъв,мн. ч. мехъвар,нет,дуб,существительное
500,мехь1,мн. ч. мехъар,нет,овчарня,существительное
501,мехь2,мн. ч. мехъар,нет,пригоршня,существительное
502,мехIала,мн. ч. мехIалабур,нет,округ,существительное
503,мехIеджар,мн. ч. мехIеджарар,нет,перила,существительное
504,мехIел,мн. ч. мехIелар,нет,любимчик,существительное
505,мехIел,нет,нет,любимый,прилагательное
506,мехIела,мн. ч. мехIелабур,нет,улица,существительное
507,мехIелайинф,нет,нет,уличный,прилагательное
508,мехIелди,нет,нет,пока,наречие
509,мехIкам,нет,нет,крепкий,прилагательное
510,мехIкамвел,нет,нет,прочность,существительное
511,мехIкамди,нет,нет,прочно,наречие
512,мехIкамф,нет,нет,бережный,прилагательное
513,мехIрумвел,нет,да,нужда; обездоленность,существительное
514,мехIрумди,нет,нет,обездоленность,существительное
515,мехIрумф,нет,нет,обездоленный,прилагательное
516,мехIсул,мн. ч. мехIсулар,нет,урожай,существительное
517,мехIсулдар,мн. ч. мехIсулдарар,нет,земледелец,существительное
518,мехIталф,нет,нет,удивлённый,прилагательное
519,мешебег,мн. ч. мешебегер,нет,лесник,существительное
520,мешреб,мн. ч. мешребар,нет,вид,существительное
521,меъдан,мн. ч. меъданар,нет,место,существительное
522,мидал,мн. ч. мидалар,нет,медаль; орден,существительное
523,мидегьан,нет,нет,столько,наречие
524,мизан,мн. ч. мизанар,да,порядок,существительное
525,мизанвел,нет,да,общепринятость,существительное
526,мизмизай,мн. ч. мизмизаяр,да,комар,существительное
527,миккробар,мн. ч. миккробарар,нет,инфекция,существительное
528,микьдар,мн. ч. микьдарар,нет,достоинство,существительное
529,микIилвел,мн. ч. микIилвелар,нет,холод,существительное
530,микIилди,нет,нет,холодно,наречие
531,микIилф,нет,нет,морозный,прилагательное
532,милах,нет,нет,воск,существительное
533,милехъв,мн. ч. милехъвар,нет,червь; гусеница,существительное
534,миллат,мн. ч. миллатар,нет,народность; национальность,существительное
535,миллатинф,нет,нет,народный,прилагательное
536,минавар,мн. ч. минаварар,нет,посол,существительное
537,минбар,мн. ч. минбарар,нет,трибуна,существительное
538,миннат,мн. ч. миннатар,нет,просьба; мольба,существительное
539,миннат акъас,нет,нет,просить; умолять,глагол
540,миннатчи,мн. ч. миннатчибур,нет,проситель,существительное
541,минтIикъ,мн. ч. минтIикьар,нет,скупец; жадюга,существительное
542,мирг,мн. ч. миргар,нет,олень,существительное
543,мисала,мн. ч. мисалабур,нет,поговорка,существительное
544,мисала,мн. ч. мисалабур,нет,пословица,существительное
545,мисаъ,нет,нет,здесь,наречие
546,мискин,нет,нет,одинокий; несчастный,прилагательное
547,мискинф,нет,нет,бедный,прилагательное
548,миштти,нет,нет,этак,наречие
549,муг1,мн. ч. мугар,нет,гнездо; дупло; нора; берлога,существительное
550,муг2,мн. ч. мугар,нет,кормушка; ясли,существительное
551,муг пеIэрин,мн. ч. мугар пеIэрин,нет,курятник,существительное
552,мугул,мн. ч. мугулар,нет,метла,существительное
553,мугул тIул,мн. ч. мугул тIулар,нет,ребро,существительное
554,мугулди,нет,нет,криво,наречие
555,мугулин тIул,мн. ч. мугулин тIулар,нет,ребро,существительное
556,мугьатвел,нет,нет,неторопливость,существительное
557,мугьаттинф,нет,нет,осторожный,прилагательное
558,мугьатвел,нет,нет,осторожность; бдительность,существительное
559,мугьаятди,нет,нет,осторожно; бдительно,наречие
560,мугьаятлу,нет,нет,осторожный; бдительный,прилагательное
561,мугьлат вахтт,нет,нет,срок,существительное
562,мугьман,мн. ч. мугьманар,да,гость,существительное
563,мугьур,мн. ч. мугьурар,нет,печать,существительное
564,мугI,мн. ч. мугIар,нет,мост,существительное
565,мудур,мн. ч. мудурар,нет,козлёнок,существительное
566,муджур,мн. ч. муджурар,нет,борода,существительное
567,муеверш,нет,нет,восемьсот,числительное
568,муздур,мн. ч. муздурар,нет,батрак,существительное
569,музе гъванар,нет,нет,щебень,существительное
570,музеф,нет,нет,мелкий,прилагательное
571,музи,нет,нет,мелко,наречие
572,музиди,нет,нет,мелко,наречие
573,муз-муз акьас,нет,нет,расколоть,глагол
574,муз-муз хьун,нет,нет,вдребезги,наречие
575,мукь,мн. ч. мукьар,нет,место,существительное
576,мукьам,мн. ч. мукьамар,нет,мелодия; напев,существительное
577,мукьар,мн. ч. мукьарар,нет,область,существительное
578,мулк,мн. ч. мулкар,нет,богатство; владение,существительное
579,мум,нет,нет,воск,существительное
580,мунафикь,мн. ч. мунафикьар,нет,льстец,существительное
581,мункин,нет,нет,возможно,наречие
582,мункинвел,мн. ч. мункинвелар,нет,возможность,существительное
583,мункинди,нет,нет,возможно,наречие
584,мункинди,нет,нет,возможно,вводное слово
585,мункинф,нет,нет,вероятный; возможный,прилагательное
586,мурабба,мн. ч. мураббабур,нет,варенье,существительное
587,мурад,мн. ч. мурадар,нет,желание; стремление; мечта; цель,существительное
588,мурдал,нет,нет,скверный,прилагательное
589,мурдалвел,мн. ч. мурдалвелар,нет,подлость,существительное
590,мурдалди,нет,нет,подло,наречие
591,мурс,мн. ч. мурсар,нет,плесень,существительное
592,муртт,мн. ч. мурттар,нет,угол,существительное
593,мурхIар,нет,нет,сани,существительное
594,мусибат,нет,да,беда; несчастье,существительное
595,муссе,нет,нет,когда,наречие
596,муссу,нет,нет,толокно,существительное
597,мутакалим,мн. ч. мутакалимар,нет,богослов,существительное
598,мутал,нет,нет,творог,существительное
599,муттаIи,мн. ч. муттаIибур,нет,противник,существительное
600,мутIел,нет,нет,покорный,прилагательное
601,мутIеIинф,нет,нет,покорный; послушный,прилагательное
602,мутIелф,нет,нет,послушный,прилагательное
603,муул,мн. ч. муулар,нет,губа,существительное
604,мух,нет,нет,ячмень,существительное
605,муханф,нет,нет,ячменный,прилагательное
606,мухур1,мн. ч. мухурар,нет,грудь,существительное
607,мухур2,нет,нет,кашель,существительное
608,мухур акьас,нет,нет,кашлять,глагол
609,мухургьан,мн. ч. мухургьанар,да,фартук,существительное
610,мухури хъаф,нет,нет,грудной,прилагательное
611,мухуригьас гьайхьаф,нет,нет,фартук,существительное
612,мучI,нет,нет,мрак; темнота; темень; тьма,существительное
613,мучI ккеми,нет,нет,затемно,наречие
614,мучI фадаркас,нет,нет,стемнеть,глагол
615,мучIе къуй,мн. ч. мучIе къуйвур,нет,погреб,существительное
616,мучIе хьас,нет,нет,потемнеть; стемнеть,глагол
617,мучIевел,нет,нет,темнота; чернота,существительное
618,мучIеф,нет,нет,тёмный,прилагательное
619,мучIе-чулеф,нет,нет,тёмно-синий,прилагательное
620,мучIи,нет,нет,темно; черно,наречие
621,муштари,мн. ч. муштарибур,нет,покупатель,существительное
622,мушттари,мн. ч. мушттарибур,нет,попутчик,существительное
623,муьхIтал хьас,нет,нет,удивляться,глагол
624,муьхIтал хьун,нет,нет,удивлённо,наречие
625,муьхIтал хьуф,нет,нет,удивлённый,прилагательное
626,муьхIталди,нет,нет,удивительно,наречие
627,муьхIталф,нет,нет,удивительный,прилагательное
628,муьхIталхьуб,нет,нет,удивление,существительное
629,муяд,нет,нет,восемь,числительное
630,нагагь,нет,нет,если,союз
631,нагь,нет,нет,наличный,прилагательное
632,нагIнат,мн. ч. нагIнатар,нет,проклятие,существительное
633,надинджвел,нет,нет,упрямство; своеволие,существительное
634,надинж,мн. ч. надинжар,да,шалун; проказник,существительное
635,надинж,нет,да,шаловливый,прилагательное
636,надир,нет,нет,уникальный,прилагательное
637,наз,нет,нет,кокетливость; жеманство,существительное
638,назани,мн. ч. назанибур,нет,недотрога,существительное
639,назанивел,нет,нет,кокетливость; жеманство,существительное
640,назик,нет,нет,хрупкий,прилагательное
641,назиквел,нет,нет,хрупкость,существительное
642,назиквел,нет,нет,худоба,существительное
643,назлу,нет,нет,жеманный,прилагательное
644,назум,мн. ч. назумар,нет,поэзия,существительное
645,найе,нет,нет,который,местоимение
646,найиб,мн. ч. найибар,нет,заместитель; наместник,существительное
647,найч,нет,нет,куда,наречие
648,накъ,нет,нет,вчера,наречие
649,накьанф,нет,нет,вчерашний,прилагательное
650,накьиш1,мн. ч. накьишар,нет,метка; клеймо,существительное
651,накьиш2,мн. ч. накьишар,да,узор; орнамент,существительное
652,намус,нет,нет,совесть; честь,существительное
653,намусвел,нет,нет,совестливость; честность,существительное
654,намусди,нет,нет,совестливо; честно,наречие
655,намуслувел,нет,да,совестливость; честность,существительное
656,намуслувел,нет,нет,стеснительность; стыдливость,существительное
657,намуслуди,нет,нет,стеснительно; стыдливо,наречие
658,намуслуди,нет,да,совестливо; честно,наречие
659,нан агъаф,мн. ч. нан агъафар,нет,заявитель,существительное
660,нан пас,нет,нет,просить; умолять,глагол
661,нанди,нет,нет,где,наречие
0,нар,мн. ч. нарар,нет,гранат,существительное
1,наразивел,нет,нет,недовольство,существительное
2,нарат,мн. ч. наратар,нет,сосна,существительное
3,нарджитук,мн. ч. нарджитукар,нет,нарцисс,существительное
4,насиб,мн. ч. насихIетар,нет,судьба; удел,существительное
5,насихIет,мн. ч. насихIетар,нет,пожелание; совет; подсказка,существительное
6,насихIетчи,мн. ч. насихIетчибур,нет,наставник; советчик,существительное
7,наккибур,нет,нет,носок,существительное
8,натиджалу,нет,нет,результативный; продуктивный,прилагательное
9,натиджалувел,нет,нет,результативность; продуктивность,существительное
10,нафас1,нет,нет,дыхание; вздох,существительное
11,нафас2,мн. ч. нафасар,нет,речь,существительное
12,нафтт,нет,нет,керосин,существительное
13,нафттач,нет,да,чернявый,прилагательное
14,нах,нет,нет,мякина,существительное
15,наха,мн. ч. нахабур,нет,акула,существительное
16,нахшир1,мн. ч. нахширар,нет,птичка; дичь,существительное
17,нахшир2,мн. ч. нахширар,нет,зверь,существительное
18,начагъ,нет,нет,нездоровый,прилагательное
19,нашатI,нет,нет,общительный; дружелюбный,прилагательное
20,нашатIтти,нет,нет,дружелюбно,наречие
21,негъв,мн. ч. негъвар,нет,слеза,существительное
22,негIнат,нет,нет,позор,существительное
23,неджбер,мн. ч. неджберар,нет,батрак,существительное
24,некехI,мн. ч. некехIар,нет,бракосочетание,существительное
25,некк,нет,нет,молоко,существительное
26,неккдин IуькI,мн. ч. неккдин IуькIар,нет,одуванчик,существительное
27,неккдинф,нет,нет,молочный,прилагательное
28,неккунф,нет,нет,молочный,прилагательное
29,некьв1,нет,нет,грунт; почва,существительное
30,некьв2,мн. ч. некьвар,нет,могила,существительное
31,некьвар,нет,нет,кладбище,существительное
32,некьвдинф,нет,нет,могильный,прилагательное
33,некьи,мн. ч. некьибур,нет,ягода,существительное
34,некьинф,нет,нет,почвенный,прилагательное
35,нендихьучира,нет,нет,повсюду,наречие
36,нетт,мн. ч. неттар,нет,вошь,существительное
37,нетI,мн. ч. нетIар,нет,гнида,существительное
38,нефтт,нет,нет,керосин,существительное
39,некIекьвел,нет,нет,озорство,существительное
40,некIекьинф,нет,нет,драчливый,прилагательное
41,некIс,мн. ч. нехIсар,нет,хулиган,существительное
42,некIс кар,мн. ч. нехIс карар,нет,несчастье; бедствие,существительное
43,некIсвел1,нет,нет,вредность,существительное
44,некIсвел2,нет,нет,хулиганство,существительное
45,нецIв,мн. ч. нецIвар,нет,река,существительное
46,нецIварин къамиш,мн. ч. нецIварин къамишар,нет,камыш,существительное
47,неч,нет,нет,совесть,существительное
48,неч гIадавел,нет,нет,наглость,существительное
49,неч гIадай,нет,нет,бессовестно; нагло,наречие
50,неч гIадаф,мн. ч. нечгIадаттар,нет,циник,существительное
51,неч гIадаф,мн. ч. неч гIадафар,нет,бесстыдник,существительное
52,неч гIадаф,нет,нет,наглый,прилагательное
53,неч гIаф,нет,нет,совестливый,прилагательное
54,неч гIудавел,нет,нет,бесстыдство,существительное
55,неч гIудай,нет,нет,бесстыдно,наречие
56,неч гIудаф,нет,нет,бессовестный,прилагательное
57,нечар акьай,нет,нет,стеснительно,наречие
58,нечар акьуб,нет,нет,смущение,существительное
59,нечар-ламусар,нет,нет,приличие; скромность,существительное
60,нечвел,нет,нет,стеснительность; стыдливость,существительное
61,нечди,нет,нет,стыдливо; стеснительно; неудобно,наречие
62,неч-ламус кей,нет,нет,скромно,наречие
63,нечунинф,нет,нет,стеснительный; застенчивый; скромный,прилагательное
64,нигIмат,мн. ч. нигIматар,нет,драгоценность,существительное
65,никехI,мн. ч. никехIар,нет,брак (бракосочетание),существительное
66,никехI акьуб,нет,нет,бракосочетание,существительное
67,нирхI,мн. ч. нирхIар,нет,крупа,существительное
68,нис,мн. ч. нисар,нет,сыр; брынза,существительное
69,нихьи,нет,нет,где,наречие
70,нить,мн. ч. ниар,нет,запах,существительное
71,ният,мн. ч. ниятар,нет,намерение,существительное
72,ноябр,нет,нет,ноябрь,существительное
73,нубарак акьас,нет,нет,приветствовать; поздравить,глагол
74,нубаракар,нет,нет,поздравления,существительное
75,нубат,мн. ч. нубатар,нет,порядок; очередь; черёд,существительное
76,нубатвел,нет,нет,очерёдность,существительное
77,нубатлувел,нет,нет,очерёдность,существительное
78,нубатти,нет,нет,порядок; очередь,существительное
79,нугъат,мн. ч. нугъатар,нет,диалект,существительное
80,нукар,мн. ч. нукарар,нет,нукёр,существительное
81,нукътIа,мн. ч. нукътIабур,нет,точка,существительное
82,нукIрухI1,мн. ч. нукIрухIар,нет,жалобщик,существительное
83,нукIрухI2,мн. ч. нукIрухIар,нет,сплетник,существительное
84,нукIутчи,мн. ч. нукIутчибур,нет,шутник; острослов,существительное
85,нукIутIар,нет,нет,анекдот,существительное
86,нуну,нет,нет,гнусавый,прилагательное
87,нунувур акьас,нет,нет,гнусавить,глагол
88,нур1,нет,нет,свет; блеск,существительное
89,нур2,мн. ч. нурар,нет,луч,существительное
90,нур ичаф,нет,нет,лучистый,прилагательное
91,нурлу,нет,нет,освещённый,прилагательное
92,нушдинф,нет,нет,приятный,прилагательное
93,нушф,нет,нет,приятный,прилагательное
94,олимпиада,мн. ч. олимпиадабур,нет,олимпиада,существительное
95,оазис,мн. ч. оазисар,нет,оазис,существительное
96,обещани,мн. ч. обещанибур,нет,обещание,существительное
97,обмотка,мн. ч. обмоткабур,нет,обмотка,существительное
98,оборона,нет,нет,оборона,существительное
99,образ,мн. ч. образар,нет,образ,существительное
100,образовани,мн. ч. образованибур,нет,образование,существительное
101,общежити,мн. ч. общежитибур,нет,общежитие,существительное
102,объединени,мн. ч. объединенибур,нет,объединение,существительное
103,объявлени,мн. ч. объявленибур,нет,объявление,существительное
104,огнетушител,мн. ч. огнетушителар,нет,огнетушитель,существительное
105,океан,мн. ч. океанар,нет,океан,существительное
106,округ,мн. ч. округар,нет,округ,существительное
107,октябр,нет,нет,октябрь,существительное
108,опера,мн. ч. операбур,нет,опера,существительное
109,оперетта,мн. ч. опереттабур,нет,оперетта,существительное
110,определени,мн. ч. определенибур,нет,определение,существительное
111,орган,мн. ч. органар,нет,орган,существительное
112,орден,мн. ч. орденар,нет,орден,существительное
113,оригинал,мн. ч. оригиналар,нет,оригинал,существительное
114,орфографи,нет,нет,орфография,существительное
115,отделени,мн. ч. отделенибур,нет,отделение,существительное
116,открытка,мн. ч. открыткабур,нет,открытка,существительное
117,отличник,мн. ч. отличникар,нет,отличник,существительное
118,офицер,мн. ч. офицерар,нет,офицер,существительное
119,официант,мн. ч. официантар,нет,официант,существительное
120,пагьливан,мн. ч. пагьливанар,нет,акробат; канатоходец,существительное
121,пагьриз,мн. ч. пагьризар,нет,диета,существительное
122,падж,мн. ч. паджар,нет,пристройка,существительное
123,пази,мн. ч. пазибур,нет,сокол,существительное
124,пай,мн. ч. паяр,нет,доля; часть,существительное
125,пайгьамбар,мн. ч. пайгьамбарар,нет,пророк,существительное
126,пайдагь,мн. ч. пайдагьар,нет,флаг; знамя,существительное
127,паквел,нет,нет,честность; непорочность,существительное
128,пакди,нет,нет,честно; безупречно,наречие
129,паланпус,мн. ч. паланпусар,да,гриб,существительное
130,палнамуч,нет,нет,уполномоченный,прилагательное
131,паргар,нет,да,стойкий; устойчивый,прилагательное
132,паргарвел,нет,да,устойчивость; равновесие,существительное
133,парда,мн. ч. пардабур,нет,занавес,существительное
134,парча,мн. ч. парчабур,нет,шёлк; атлас,существительное
135,парчайинф,нет,нет,шёлковый,прилагательное
136,парI,мн. ч. парIар,нет,лопух,существительное
137,пас,нет,нет,сказать,глагол
138,паспупрт,мн. ч. паспупртар,нет,паспорт,существительное
139,паччагь,мн. ч. паччагьар,нет,царь; король,существительное
140,пашмал,нет,нет,грустный,прилагательное
141,пашмал акьас,нет,да,опечалить,глагол
142,пашмал хьас,нет,нет,опечалиться,глагол
143,пашмалди,нет,нет,грустно,наречие
144,паяр,мн. ч. паярар,нет,подарок; подношение; гостинец,существительное
145,пелекен,мн. ч. пелекенар,нет,засов; задвижка,существительное
146,пелтек,мн. ч. пелтекар,нет,заика,существительное
147,пенджек,мн. ч. пенджекар,нет,пиджак; куртка,существительное
148,пенцI,мн. ч. пенцIар,да,ресница,существительное
149,перерыв,мн. ч. перерывар,нет,перерыв,существительное
150,перишан,нет,нет,озабоченный,прилагательное
151,перишанвел,нет,да,грусть,существительное
152,перишанди,нет,да,грустно,наречие
153,пертди,нет,да,яростно,наречие
154,петтар акъуб,нет,нет,повиновение,существительное
155,пеша,мн. ч. пешабур,нет,ремесло; профессия,существительное
156,пешкеш,мн. ч. пешкешар,нет,подарок; подношение; взятка,существительное
157,пешкеш акъас,нет,нет,подарить,глагол
158,пеI,мн. ч. пеIар,нет,курица,существительное
159,пеIуын чарккв,мн. ч. пеIуын чаркквар,нет,цыплёнок,существительное
160,пеIэрин муг,мн. ч. пеIэрин мугар,нет,курятник,существительное
161,пилав,мн. ч. пилавар,нет,плов,существительное
162,пирп,нет,нет,бук,существительное
163,пирч акъас,нет,да,чихнуть,глагол
164,пич,мн. ч. пичар,нет,печь,существительное
165,пиша,мн. ч. пишабур,нет,профессия,существительное
166,пиянф,нет,нет,пьяный,прилагательное
167,пугъилди,нет,нет,сразу; немедленно,наречие
168,пул ачадис,нет,нет,приход,существительное
169,пулар,нет,нет,деньги,существительное
170,пулдар,мн. ч. пулдарар,нет,богач,существительное
171,пулсуз,нет,нет,бедный,прилагательное
172,пурар,нет,нет,седло,существительное
173,пурусттин,мн. ч. пурусттинар,нет,простыня,существительное
174,пурцI,мн. ч. пурцIар,нет,пушинка; снежинка,существительное
175,пурцIеф,нет,нет,рассыпчатый,прилагательное
176,пус,мн. ч. пусар,нет,куча,существительное
177,пустталай,мн. ч. пустталаяр,нет,гриб,существительное
178,пуф акъас,нет,да,подуть,глагол
179,пуч акъас,нет,нет,портить,глагол
180,пучвел,нет,нет,порча,существительное
181,пушмал акьас,нет,нет,опечалить,глагол
182,пушмал хьас,нет,нет,опечалиться; истосковаться,глагол
183,пушмал хьуб,нет,нет,сожаление; раскаяние,существительное
184,пушмалвел,нет,нет,грусть,существительное
185,пушмалди,нет,нет,печально; тоскливо; грустно,наречие
186,пушмалф,нет,нет,печальный; грустный; горестный,прилагательное
187,ппара гъургъаф,мн. ч. ппара гъургъафар,нет,говорун; оратор,существительное
188,ппара гъургъаф,нет,нет,болтливый,прилагательное
189,ппара гъучадархьаф,нет,нет,уникальный,прилагательное
190,ппара даъ,нет,нет,немного,наречие
191,ппара ирхеф,нет,нет,продолжительный,прилагательное
192,ппара исаринф,нет,нет,долговечный,прилагательное
193,ппара пулар хьас,нет,нет,разбогатеть,глагол
194,ппара тамаши,нет,нет,удивительно,наречие
195,ппара хьас,нет,нет,увеличиться,глагол
196,ппара Iалеф,мн. ч. ппара Iалефар,нет,едок,существительное
197,ппарайинф,нет,нет,значительный,прилагательное
198,ппара-ппара акьас,нет,нет,расколоть,глагол
199,ппара-Iайи,нет,нет,слишком,наречие
200,ппарз,мн. ч. ппарзар,нет,перевал,существительное
201,ппул,мн. ч. ппулар,нет,пол,существительное
202,ппай гын,нет,нет,конечно,вводное слово
203,ппаппрус,мн. ч. ппаппруса,нет,папироса,существительное
204,ппаппрус дивас,нет,нет,курить,глагол
205,ппара,нет,нет,много; значительно,наречие
206,ппара адаф,нет,нет,уникальный,прилагательное
207,ппара гагьдинф,нет,нет,длительный,прилагательное
208,пIа,мн. ч. пIабур,нет,поцелуй,существительное
209,пIа акьас,нет,нет,поцеловать,глагол
210,пIанкI,мн. ч. пIанкIар,нет,затяжка (при курении),существительное
211,пIипI,мн. ч. пIипIар,нет,козырёк,существительное
212,пIузар,нет,нет,щёчки,существительное
213,рагъ,нет,нет,солнце,существительное
214,рагъ афучIавус,нет,нет,запад,существительное
215,рагъ фагъучIа багв,нет,нет,восток,существительное
216,рагъунф,нет,нет,солнечный,прилагательное
217,рагъухъан,мн. ч. рагъухъанар,нет,радуга,существительное
218,рагьимсуз,нет,нет,безжалостный,прилагательное
219,рагI,мн. ч. рагIар,нет,мельница,существительное
220,рагIухъан,мн. ч. рагIухъанар,нет,мельник,существительное
221,радж,мн. ч. раджар,нет,ряд; грядка,существительное
222,раджар,мн. ч. раджарар,нет,эпидемия,существительное
223,рази ай,нет,нет,довольно,наречие
224,рази акьас,нет,нет,угождение,существительное
225,рази аркьаф,нет,нет,приемлемый,прилагательное
226,рази давевелар,нет,нет,недовольство,существительное
227,рази хьуб,нет,нет,соглашение; довольствие,существительное
228,рази э,нет,нет,согласен,прилагательное
229,разивел,нет,нет,согласие; примирение,существительное
230,разу,нет,нет,значительный,прилагательное
231,ракк1,мн. ч. раккар,нет,улица,существительное
232,ракк2,мн. ч. раккар,нет,дверь,существительное
233,раккагь ккеруцубар,мн. ч. раккагь ккеруцубарар,нет,прогулка,существительное
234,раккан гамар,мн. ч. раккан гамарар,нет,задвижка; засов,существительное
235,ракканф,нет,нет,уличный,прилагательное
236,раккаттай,мн. ч. раккаттаяр,нет,нищий; бродяга,существительное
237,ракъ,мн. ч. ракъар,нет,бульон; суп,существительное
238,ракьихъан,мн. ч. ракьихъанар,да,иждивенец,существительное
239,рама,мн. ч. рамабур,нет,табун,существительное
240,рамайихъан,мн. ч. рамайихъанар,нет,табунщик,существительное
241,ранг,мн. ч. рангар,нет,цвет,существительное
242,ранг адавел,мн. ч. ранг адавелар,нет,бесцветность,существительное
243,ранг адай,нет,нет,бесцветно,наречие
244,ранг алайчIвас,нет,нет,полинять,глагол
245,ранг алайчIуб,нет,нет,линька,существительное
246,ранг алайчIуф,нет,нет,полинявший,прилагательное
247,рангар адаф,нет,нет,бесцветный,прилагательное
248,рангар ай,нет,нет,цветасто,наречие
249,ранг атIуф,нет,нет,бледный; светлый,прилагательное
250,ранг ккетивуна аф,нет,нет,бледный,прилагательное
251,ранглуди,нет,нет,цветасто,наречие
252,рангрангаринф,нет,нет,пёстрый,прилагательное
253,рангсуз,нет,нет,бесцветный,прилагательное
254,рангсузвел,нет,нет,бесцветность,существительное
255,рангсузди,нет,нет,бесцветно,наречие
256,ранда,мн. ч. рандабур,нет,рубанок,существительное
257,расад,нет,да,истинный; правдивый,прилагательное
258,ратт,мн. ч. раттар,нет,гумно,существительное
259,раттаккай,нет,нет,нищий,прилагательное
260,рахI,мн. ч. рахIар,нет,мельница,существительное
261,рахIетинф,нет,нет,нетрудный; лёгкий,прилагательное
262,рахIухъан,мн. ч. рахIухъанар,нет,мельник,существительное
263,рашва,мн. ч. рашвабур,нет,подношение; взятка,существительное
264,рашватчи,мн. ч. рашватчибур,нет,взяточник,существительное
265,реб,мн. ч. ребар,нет,шило,существительное
266,регъвеф,нет,нет,серый,прилагательное
267,регъеф,нет,нет,серый,прилагательное
268,регъбер,мн. ч. регъберар,нет,вождь,существительное
269,регIбат,нет,нет,скромность; приличие,существительное
270,регIбатлу,нет,нет,приличный,прилагательное
271,рекъ,мн. ч. рекъар,нет,путь; тропинка; дорога; колея,существительное
272,рекъуьас аттархьеб,нет,нет,беспутство,существительное
273,рекъуьн-илдеш,мн. ч. рекъуьн-илдешар,нет,путник,существительное
274,рекI,нет,нет,сияние,существительное
275,рекIв,нет,нет,блеск,существительное
276,рес,мн. ч. ресар,нет,палка,существительное
277,рехIет,нет,нет,отдых,существительное
278,рехIет акьас,нет,нет,отдохнуть,глагол
279,рехIет хьас,нет,нет,отдохнуть,глагол
280,рехIетар,мн. ч. рехIетарар,нет,удобство,существительное
281,рехIетинф,нет,нет,нетрудный; лёгкий,прилагательное
282,рехIетти,нет,нет,удобно; легко,наречие
283,рехIимлу,нет,нет,добрый; милостивый,прилагательное
284,рехIматлу,нет,нет,усопший,прилагательное
285,рехIматлу,мн. ч. рехIматлубур,нет,покойный,существительное
286,рехIми,нет,нет,доброта; милость,существительное
287,рехIятвел,нет,нет,простота,существительное
288,риба,мн. ч. рибабур,нет,прибыль,существительное
289,риваят,мн. ч. риваятар,нет,сказание; предание,существительное
290,ризин,нет,нет,резина,существительное
291,ризининф,нет,нет,резиновый,прилагательное
292,ризкъ,нет,да,хлеб; пища,существительное
293,рикI,нет,да,блеск; сияние,существительное
294,рицI,мн. ч. рицIар,нет,тетива,существительное
295,ричI,нет,нет,иней,существительное
296,руб,мн. ч. рубар,нет,иголка; шприц,существительное
297,рубариккен,мн. ч. рубариккенар,нет,игольница,существительное
298,руг,мн. ч. ругар,нет,почва; земля,существительное
299,ругдинф,нет,нет,почвенный,прилагательное
300,ругун ранг алеф,нет,нет,серый,прилагательное
301,ругунф,нет,нет,почвенный,прилагательное
302,руд,мн. ч. рудар,нет,кишка,существительное
303,рудж,мн. ч. руджар,нет,хвост,существительное
304,рукъ,нет,нет,зола,существительное
305,рукъал,мн. ч. рукъалар,нет,проклятие,существительное
306,рукъугьил,нет,нет,сухорукость,существительное
307,рукъуф,нет,нет,жёсткий,прилагательное
308,рукъ,нет,нет,металл; сталь; железо,существительное
309,рукъанф,нет,нет,металлический; железный,прилагательное
310,рукъар,мн. ч. рукъарар,нет,запор; замок,существительное
311,рукъсат,мн. ч. рукъсатар,нет,позволение,существительное
312,рукъас,нет,нет,рыть,глагол
313,румар эс,нет,да,толкать,глагол
314,русвагь,нет,нет,опозоренный,прилагательное
315,русвагьвел,нет,нет,позор,существительное
316,рутул шуй,мн. ч. рутул шувар,нет,рутулец,существительное
317,рухас,нет,да,рожать,глагол
318,рухуб,нет,нет,грохот,существительное
319,рухум-салам,нет,нет,приветствие,существительное
320,рухум-салам акьас,нет,нет,приветствовать,глагол
321,рухум-саламинф,нет,нет,приветливый,прилагательное
322,руцас,нет,нет,искать,глагол
323,руцубар,нет,нет,поиски,существительное
324,ручI,нет,нет,иней,существительное
325,руш,мн. ч. рушар,нет,девушка; дочь,существительное
326,руькъ,нет,нет,зола; пепел; прах,существительное
327,руьхьес,нет,нет,кипеть,глагол
328,руьхьуь хьед,нет,нет,кипяток,существительное
329,руьхI,мн. ч. руьхIар,нет,дух; душа,существительное
330,са,нет,нет,указание на одну единицу,частица
331,са багв,мн. ч. са багвар,нет,отделение,существительное
332,са багьана,мн. ч. са багьанабур,нет,повод; причина,существительное
333,са вахт,мн. ч. са вахтар,нет,мгновение; миг; время; период,существительное
334,са гагьдинф,нет,нет,длительный; продолжительный,прилагательное
335,са галинф,нет,да,одноразовый,прилагательное
336,са гелайинф,нет,нет,одноразовый,прилагательное
337,са гьамра адавел,нет,нет,беспечность,существительное
338,са гьамра адай,нет,нет,беззаботность,существительное
339,са гьамра кедай,нет,нет,беззаботно,наречие
340,са гьамра кедаф,нет,нет,беззаботный; беспечный,прилагательное
341,са джаранф,нет,нет,однослойный,прилагательное
342,са йицIуд,нет,нет,десяток,существительное
343,са классинф,мн. ч. са классинттар,нет,одноклассник,существительное
344,са кьатт,мн. ч. са кьаттар,нет,группа,существительное
345,са мукьунф,мн. ч. са мукьунттар,нет,земляк,существительное
346,са пай,мн. ч. са паяр,нет,четверть,существительное
347,са пус,мн. ч. са пусар,нет,пачка,существительное
348,са рангунинф,нет,нет,одноцветный,прилагательное
349,са рангуф,нет,нет,одноцветный,прилагательное
350,са фера,нет,нет,"ничто, ничего",местоимение
351,са хайира кидай,нет,нет,бессмысленно,наречие
352,са хIуринф,мн. ч. са хIуринттар,нет,земляк,существительное
353,са цIуьппеф,мн. ч. са цIуьппеттар,нет,скряга,существительное
354,са чIалул алдаф,мн. ч. са чIалул алдаттар,нет,циник,существительное
355,са ягъанф,нет,нет,однодневный,прилагательное
356,сабур,нет,нет,терпение,существительное
357,сабур акьас,нет,нет,потерпеть,глагол
358,сабур хъаф,нет,нет,выносливость,существительное
359,сабур хъаф,нет,нет,терпеливый,прилагательное
360,сабур хъуб,нет,нет,терпение,существительное
361,сабурлу,нет,нет,терпеливый,прилагательное
362,савда,нет,нет,торговля,существительное
363,савдашей,мн. ч. савдашеяр,нет,товар,существительное
364,савкьат,мн. ч. савкьатар,нет,подарок; гостинец,существительное
365,савт,мн. ч. савтар,нет,мелодия,существительное
366,сагелай,мн. ч. сагелаяр,нет,раз,существительное
367,сагелай,нет,нет,сначала,наречие
368,сагъ акьас,нет,нет,лечить,глагол
369,сагъ акьуб,мн. ч. сагъ акьубар,нет,исцеление,существительное
370,сагъ акьурай,нет,нет,счастливо,наречие
371,сагъ аркьаф,мн. ч. сагъ аркьаттар,нет,целитель,существительное
372,сагъ хьуб,нет,нет,выздоравливать,глагол
373,сагъай хьас1,нет,да,портить,глагол
374,сагъай хьас2,нет,нет,претерпеть (трудности),глагол
375,сагъвелар,нет,нет,самочувствие,существительное
376,сагъул,нет,нет,спасибо,частица
377,сагъф1,нет,нет,здоровый,прилагательное
378,сагъф2,нет,нет,целый,прилагательное
379,сагьиб,мн. ч. сагьибар,да,хозяин,существительное
380,сагьна,мн. ч. сагьнабур,нет,арена; сцена,существительное
381,сад1,мн. ч. садар,нет,раз,существительное
382,сад2,мн. ч. садар,нет,единица,существительное
383,сад,нет,нет,один,числительное
384,сад сайигьас гьаттивас,нет,нет,разлучить,глагол
385,сад сайил алчикас,нет,нет,настропалить,глагол
386,сад сайил алчихьас,нет,нет,умножение,существительное
387,сад сайин кьабахь,нет,нет,гуськом,наречие
388,сад сайиъ хъел ай,нет,нет,враждебно,наречие
389,сад сайиъ хъел ахьуб,нет,нет,вражда,существительное
390,садаф,нет,нет,перламутр,существительное
391,садвел,мн. ч. садвелар,нет,единство,существительное
392,садж,мн. ч. саджар,нет,сковородка,существительное
393,саджал,нет,да,однослойный,прилагательное
394,саджум,мн. ч. саджумар,нет,сажень,существительное
395,садпе шиниккв,мн. ч. садпе шиникквар,нет,первенец,существительное
396,садпун1,нет,нет,моментально; сразу,наречие
397,садпун2,нет,нет,неожиданно,наречие
398,садпуна,нет,нет,вдруг; внезапно; мгновенно,наречие
399,садра даь,нет,нет,никто,местоимение
400,саил,нет,нет,обездоленный; одинокий,прилагательное
401,сай,мн. ч. саяр,нет,достоинство; авторитет,существительное
402,сайигъа,нет,нет,послезавтра,наречие
403,сайир,мн. ч. сайирар,нет,прогулка,существительное
404,сайисра дагъай,нет,нет,независимо,наречие
405,сайисра дагъаф,нет,нет,неизвестный; секретный,прилагательное
406,сайисра дапун,нет,нет,тайно,наречие
407,сайрак,нет,нет,редкий,прилагательное
408,сака,нет,нет,наружность; внешность,существительное
409,саки,нет,нет,почти,наречие
410,сакинвел,нет,нет,спокойствие,существительное
411,сакинвел,мн. ч. сакинвелар,нет,покой,существительное
412,сакин даваф,нет,нет,беспокойный,прилагательное
413,сакинди,нет,нет,скромно; тихо,наречие
414,сакинф,мн. ч. сакинттар,нет,тихоня; молчун,существительное
415,сакинф,нет,нет,тихий; скромный,прилагательное
416,сакмиш акъас,нет,нет,разворотить; разрушить,глагол
417,сакрат,мн. ч. сакратар,да,яд,существительное
418,сакIал,мн. ч. сакIалар,да,перстень,существительное
419,сал,мн. ч. салар,нет,сарай; хлев; коровник,существительное
420,салам,мн. ч. саламар,нет,привет; приветствие; мир; поклон,существительное
421,салам,нет,нет,здравствуйте,междометие
422,саламат,нет,нет,спокойствие,существительное
423,саламатвел,нет,нет,благополучие,существительное
424,саламатти,нет,нет,тихо; скромно; мирно; спокойно,наречие
425,саламаттинф,нет,нет,тихий; спокойный; мирный,прилагательное
426,салбан,мн. ч. салбанар,нет,уздечка,существительное
427,салдат,мн. ч. салдатар,нет,боец; воин,существительное
428,салдатарин хIаф,мн. ч. салдатарин хIаттар,нет,офицер,существительное
429,салихI,нет,нет,полезный,прилагательное
430,салхуз,нет,нет,гордый; возгордившийся,прилагательное
431,самехI,нет,да,плавать,глагол
432,сан,мн. ч. санар,нет,цифра; счёт,существительное
433,сан акьас,нет,нет,считать,глагол
434,сан дивас,мн. ч. сан дивубар,нет,счёт; подсчёт,существительное
435,сан диваф,мн. ч. сан дивафар,нет,счетовод,существительное
436,сан кьадар,мн. ч. сан кьадарар,нет,число,существительное
437,сана,нет,нет,похвала; хвала,существительное
438,санайа,нет,нет,промышленность,существительное
439,саннапуна,нет,нет,быстро,наречие
440,саралухь,нет,нет,желтуха,существительное
441,сарин,мн. ч. саринар,нет,тень,существительное
442,саринвел,нет,нет,прохлада,существительное
443,сарф акьас,нет,да,тратить; расходовать,глагол
444,сархушвел,нет,нет,беспечность,существительное
445,сархушди,нет,нет,беспечно,наречие
446,сархушф,нет,нет,беспечный,прилагательное
447,сасаглай,нет,нет,иногда,наречие
448,са-сатти,нет,нет,поодиночке,наречие
449,сасра,нет,нет,отдельный,прилагательное
450,сасра хIуькуматтинф,нет,нет,иностранный,прилагательное
451,сасрабур суман даф,нет,нет,незаменимый,прилагательное
452,сасуман дахьуб,нет,нет,непохожесть,существительное
453,сасуманвел1,нет,нет,равновесие,существительное
454,сасуманвел2,мн. ч. сасуманвелар,нет,сходство,существительное
455,сасуманф,нет,нет,похожий,прилагательное
456,сасуманф даваф,нет,нет,непохожий,прилагательное
457,сатпун гьузар акьас,нет,нет,затормозить,глагол
458,сатти аф,нет,нет,уединённый,прилагательное
459,сатти ахъуб,нет,нет,уединение,существительное
460,сатти сад,нет,нет,единственный,прилагательное
461,саф,нет,нет,честный,прилагательное
462,сафарчи,мн. ч. сафарчибур,нет,путешественник,существительное
463,сахават,нет,нет,щедрый; великодушный,прилагательное
464,сачах,нет,нет,бахрома,существительное
465,саIат,мн. ч. саIатар,нет,час,существительное
466,саIудар,нет,нет,несколько,числительное
467,саярат,мн. ч. саяратар,нет,планета,существительное
468,сегьна,мн. ч. сегьнабур,нет,арена,существительное
469,селеб,мн. ч. селебар,да,зуб,существительное
470,сем,мн. ч. семар,нет,овца,существительное
471,серг,мн. ч. сергар,нет,чеснок,существительное
472,сечкибур,нет,нет,выборы,существительное
473,сечкичи,мн. ч. сечкичибур,нет,избиратель,существительное
474,сеIат,мн. ч. сеIатар,нет,час; часы,существительное
475,сеIбун,нет,нет,мыло,существительное
476,сибуне ами,нет,да,почти,наречие
477,сибцIи ами,нет,нет,почти,наречие
478,сив,нет,нет,рот,существительное
479,сив ккерхьас,мн. ч. сив ккерхьубар,нет,изумление,существительное
480,сив ккерхьуб,нет,нет,удивление,существительное
481,сивин гъвад,мн. ч. сивин гъвадар,нет,нёбо,существительное
482,сийагь,нет,нет,бесхозный,прилагательное
483,сийагь хъуф,нет,нет,заброшенный,прилагательное
484,силеб,мн. ч. силебар,нет,зуб; клык,существительное
485,сим,мн. ч. симар,нет,струна,существительное
486,син,мн. ч. синар,нет,ограда; забор,существительное
487,синджил,мн. ч. синджилар,нет,цепь,существительное
488,сининф,нет,нет,проволочный,прилагательное
489,синтябр,нет,нет,сентябрь,существительное
490,сир,мн. ч. сирар,нет,секрет; тайна,существительное
491,сирдаб,мн. ч. сирдабар,да,погреб,существительное
492,сирка,нет,нет,уксус,существительное
493,сирнав,мн. ч. сирнавар,да,плавание,существительное
494,сифир,мн. ч. сифирар,нет,ноль,существительное
495,сифта,нет,нет,сначала; вначале,наречие
496,сифтта,нет,да,сначала; вначале,наречие
497,сиягъат,мн. ч. сиягъатар,нет,путешествие,существительное
498,сиясат,нет,нет,политика,существительное
499,суал,мн. ч. суалар,нет,вопрос,существительное
500,субай,нет,да,одинокий,прилагательное
501,субайвел,нет,нет,одиночество,существительное
502,субхIенар,нет,нет,чётки,существительное
503,суванф,нет,нет,горный,прилагательное
504,суварин идеми,мн. ч. суварин идемибур,нет,горец,существительное
505,сук,мн. ч. сукар,нет,сок,существительное
506,сукъур акъас,нет,нет,ослепить,глагол
507,сукъур хъас,нет,нет,ослепнуть,глагол
508,сукъурвел,нет,нет,слепота,существительное
509,суфра,мн. ч. суфрабур,нет,стол; скатерть,существительное
510,суьве хьир,нет,нет,толстая,прилагательное
511,суьве шуй,нет,нет,толстый,прилагательное
512,суьвеф,нет,нет,жирный; толстый; толстенький,прилагательное
513,суьл,нет,нет,рожь,существительное
514,суьре митIри,мн. ч. суьре митIрибур,нет,полметра,существительное
515,суьре сеIэт,мн. ч. суьре сеIэтар,нет,полчаса,существительное
516,суьретI,мн. ч. суьретIар,нет,свирель,существительное
517,суьрIэвел,нет,нет,ветхость,существительное
518,суьрIэф,нет,нет,ветхий,прилагательное
519,суьхIбат,мн. ч. суьхIбатар,да,рассказ,существительное
520,суьхIур,мн. ч. суьхIурар,нет,волшебство,существительное
521,суьхIуьрчи,мн. ч. суьхIуьрчибур,нет,волшебник; чародей,существительное
522,схема,мн. ч. схемабур,нет,чертёж,существительное
523,таб,мн. ч. табар,нет,жила; вена,существительное
524,табаккананф,нет,нет,предвечерний,прилагательное
525,табалус,мн. ч. табалусар,нет,подорожник,существительное
526,табаргъан,мн. ч. табаргъанар,нет,сурок,существительное
527,табасаран шуй,мн. ч. табасаран шувар,нет,табасаранец,существительное
528,табдилвел,мн. ч. табдилвелар,нет,перемена,существительное
529,табиIвел,нет,нет,повиновение,существительное
530,табиъ хьас,нет,нет,верить,глагол
531,табрик акъас,нет,нет,приветствовать; поздравить,глагол
532,табрикар,нет,нет,поздравления,существительное
533,табун,мн. ч. табунар,нет,рама,существительное
534,табунф,нет,нет,жилистый; сосудистый,прилагательное
535,табшуругъ,нет,нет,поручение,существительное
536,тав,мн. ч. тавар,да,жила; вена,существительное
537,тава,мн. ч. тавабур,нет,сковородка,существительное
538,тавази,нет,нет,ласковый,прилагательное
539,тавазивел,нет,нет,ласковость,существительное
540,таваккал,нет,нет,вероятный,прилагательное
541,таваккананф,нет,нет,предвечерний,прилагательное
542,тавакъал,нет,нет,упование,существительное
543,тавунф,мн. ч. тавунфар,да,подорожник,существительное
544,тавунф,нет,да,жилистый; сосудистый,прилагательное
545,тавурхал,мн. ч. тавурхалар,нет,гостиная,существительное
546,тагарин кIен,мн. ч. тагарин кIенар,нет,подоконник,существительное
547,тагьна,мн. ч. тагьнабур,нет,укор; упрёк,существительное
548,тагьнабур алайхьас,нет,нет,упрекнуть,глагол
549,тагIай,мн. ч. тагIабур,да,оса,существительное
550,тагIбир,нет,нет,толкование,существительное
551,тадж,мн. ч. таджар,нет,венец,существительное
552,таджриба,мн. ч. таджрибабур,нет,практика; опыт,существительное
553,таза,нет,нет,свежий,прилагательное
554,тазавел,нет,да,свежесть,существительное
555,тазкил акьас,нет,нет,создать,глагол
556,тай,нет,нет,пара; напарник,существительное
557,тайди,нет,нет,попарно,наречие
558,тайди аф,мн. ч. тайди аттар,нет,напарник,существительное
559,тайинф,нет,нет,парный,прилагательное
560,такабур,нет,нет,высокомерие,существительное
561,тал,мн. ч. талар,нет,полоса,существительное
562,тамази хьас,нет,да,смотреть,глагол
563,тамам,нет,нет,подробный; полный,прилагательное
564,тамаш акьас,нет,нет,поразить,глагол
565,тамаш хьас,нет,нет,изумить,глагол
566,тамаш хьуб,нет,нет,удивление,существительное
567,тамаш хьун,нет,нет,удивлённо; изумлённо,наречие
568,тамаш хьуф,нет,нет,удивлённый; изумлённый,прилагательное
569,тамаша,нет,нет,представление; зрелище,существительное
570,тамаша хьас,нет,нет,удивляться,глагол
571,тамашвел,нет,нет,необычность,существительное
572,тамашибур,нет,нет,представление; зрелище,существительное
573,тамашингъилди,нет,нет,странно; необычно,наречие
574,тамашинф,мн. ч. тамашинттар,нет,шутник; весельчак,существительное
575,тамашинф1,нет,нет,удивлённый; изумлённый,прилагательное
576,тамашинф2,нет,нет,удивительный; необычный; странный,прилагательное
577,тамбаку,нет,да,табак,существительное
578,тамбигъ,нет,нет,ограничение; запрет,существительное
579,тамгъа,мн. ч. тамгъабур,нет,печать,существительное
580,тамехI,нет,нет,корысть,существительное
581,тан,мн. ч. танар,да,туловище,существительное
582,танафус,мн. ч. танафусар,нет,перерыв,существительное
583,тараза1,мн. ч. таразабур,нет,баланс,существительное
584,тараза2,мн. ч. таразабур,нет,балансир,существительное
585,тарбиялу,нет,нет,воспитанный,прилагательное
586,тарг акъас,нет,да,ликвидировать; уничтожить,глагол
587,тарг хъас,нет,нет,уничтожиться,глагол
588,тарджума,мн. ч. тарджумабур,нет,перевод,существительное
589,тарзуман,нет,нет,вознаграждение,существительное
590,тарикь,мн. ч. тарикьар,нет,дата; летопись; история,существительное
591,тарих,мн. ч. тарихар,нет,дата; летопись; история,существительное
592,тарихчи,мн. ч. тарихчибур,нет,историк,существительное
593,таркв,мн. ч. тарквар,да,ступа,существительное
594,таркусалат,мн. ч. таркусалатар,нет,упрямец; атеист,существительное
595,таркусалатвел1,нет,нет,отказ,существительное
596,таркусалатвел2,нет,нет,упрямство,существительное
597,тарта,мн. ч. тартабур,да,собака; пёс,существительное
598,тастикь акьас,нет,да,принять; утвердить,глагол
599,тафсир,нет,нет,объяснение; толкование,существительное
600,тахлукь,мн. ч. тахлукьар,да,род; племя,существительное
601,тахлукь,нет,да,родственный,прилагательное
602,тахмиф,мн. ч. тахмифар,нет,предложение; рекомендация,существительное
603,тахсир,мн. ч. тахсирар,нет,вина; грех,существительное
604,тахсир акьуб,мн. ч. тахсир акьубар,нет,обвинение,существительное
605,тахсир кикIас джуреттик,нет,нет,обговаривание,существительное
606,тахтт,мн. ч. тахттар,нет,лежанка; тахта; топчан; диван; трон; престол,существительное
607,тахтта,мн. ч. тахттабур,нет,доска; дощечка; фанера,существительное
608,тахттудж,мн. ч. тахттуджар,нет,бахрома,существительное
609,тахча,мн. ч. тахчабур,нет,полка,существительное
610,таш,мн. ч. ташар,нет,корыто; таз,существительное
611,тая,мн. ч. таяр,нет,стог,существительное
612,те1,нет,нет,он,местоимение
613,те2,нет,нет,тот,местоимение
614,тебур1,нет,нет,они,местоимение
615,тебур2,нет,нет,те,местоимение
616,тегьер1,мн. ч. тегьерар,нет,образ,существительное
617,тегьер2,мн. ч. тегьерар,нет,положение,существительное
618,тегькумвал,нет,да,нетерпеливость,существительное
619,тегIде хьуб,нет,нет,спешка,существительное
620,тегIдевел,нет,нет,быстрота; скорость,существительное
621,тегIдеф,нет,нет,быстрый; скорый,прилагательное
622,тегIди,нет,нет,быстро; спешно; сразу,наречие
623,тегIджуб,нет,нет,удивлённый; изумлённый,прилагательное
624,тегIриф,мн. ч. тегIрифар,нет,оценка; хвала,существительное
625,тек,нет,нет,нечётный,прилагательное
626,тек,нет,нет,только,наречие
627,текIил,мн. ч. текIилар,нет,конец,существительное
628,тембекуь,нет,нет,табак,существительное
629,тембел,мн. ч. тембелар,нет,лодырь,существительное
630,тембел1,нет,нет,ленивый,прилагательное
631,тембел2,нет,нет,полный,прилагательное
632,тенбуьхI,мн. ч. тенбуьхIар,нет,упрек; порицание,существительное
633,тенг,нет,нет,равный,прилагательное
634,терс,нет,нет,страшный,прилагательное
635,техIкумвал,нет,нет,быстрота,существительное
636,ти,нет,нет,те,местоимение
637,тибитI,мн. ч. тибитIар,нет,сундук,существительное
638,тигазар,нет,нет,весы,существительное
639,тик,нет,нет,вертикально,наречие
640,тик,мн. ч. тикар,нет,осколок,существительное
641,тик,нет,нет,отвесный,прилагательное
642,тика1,мн. ч. тикабур,нет,лоскут,существительное
643,тика2,мн. ч. тикабур,нет,ломтик,существительное
644,тикан,мн. ч. тиканар,нет,терновник,существительное
645,тикди,нет,нет,отвесно; круто; вертикально,наречие
646,тикра,мн. ч. тикрабур,нет,лук,существительное
647,тикрар,нет,нет,повторение,существительное
648,тикрар акьас,нет,нет,повторить; возобновить,глагол
649,тилисим,мн. ч. тилисимар,да,талисман,существительное
650,тилифан,мн. ч. тилифанар,нет,телефон,существительное
651,тилифун,мн. ч. тилифунар,да,телефон,существительное
652,тин агъаф,мн. ч. тин агъафар,нет,заявитель,существительное
653,тин пас,нет,нет,просить; запросить,глагол
654,тип,мн. ч. типар,нет,тип,существительное
655,тип ухшар,нет,нет,похожий,прилагательное
656,тир,мн. ч. тирар,нет,тир,существительное
657,тире,нет,нет,тире,существительное
658,тиса,нет,нет,там,наречие
659,тисагьас,нет,нет,оттуда,наречие
660,тисагIди,нет,нет,туда,наречие
661,тисади,нет,нет,туда,наречие
662,тисанф,нет,нет,тамошний,прилагательное
663,тисаь,нет,нет,там,наречие
664,титул,мн. ч. титулар,нет,титул,существительное
665,тиф,нет,нет,тиф,существительное
666,тич,нет,нет,туда,наречие
0,тич-мич,нет,нет,вразброс,наречие
1,тиштти,нет,нет,этак,наречие
2,тиштти,нет,нет,так,частица
3,тишттинф,нет,нет,этакий,прилагательное
4,тиян,мн. ч. тиянар,нет,корыто,существительное
5,тиятир,мн. ч. тиятирар,да,театр,существительное
6,товар,мн. ч. товарар,нет,товар,существительное
7,ток,нет,нет,ток,существительное
8,томат,мн. ч. томатар,нет,томат,существительное
9,тормоз,мн. ч. тормозар,нет,тормоз,существительное
10,торпеда,мн. ч. торпедабур,нет,торпеда,существительное
11,торф,нет,нет,торф,существительное
12,точка,мн. ч. точкабур,нет,точка,существительное
13,точно,нет,нет,точно,наречие
14,традици,мн. ч. традицибур,нет,традиция,существительное
15,трактор,мн. ч. тракторар,нет,трактор,существительное
16,тракторист,мн. ч. трактористар,нет,тракторист,существительное
17,трансформатор,мн. ч. трансформаторар,нет,трансформатор,существительное
18,трапеци,мн. ч. трапецибур,нет,трапеция,существительное
19,трест,мн. ч. трестар,нет,трест,существительное
20,треугольник,мн. ч. треугольникар,нет,треугольник,существительное
21,трикотаж,нет,нет,трикотаж,существительное
22,троллейбус,мн. ч. троллейбусар,нет,троллейбус,существительное
23,тротуар,мн. ч. тротуарар,нет,тротуар,существительное
24,труппа,мн. ч. труппабур,нет,труппа,существительное
25,туба,нет,нет,зарок; обет,существительное
26,тугь акьас,нет,нет,плюнуть,глагол
27,тугьмат1,нет,нет,оговор,существительное
28,тугьмат2,нет,нет,упрек,существительное
29,тугьмат акьас,нет,нет,упрекнуть,глагол
30,туй,нет,нет,торжество,существительное
31,тук,мн. ч. тукар,нет,цветок,существительное
32,тукан,мн. ч. туканар,нет,магазин,существительное
33,тукаринф,нет,нет,цветочный,прилагательное
34,тукун кIил,мн. ч. тукун кIилар,нет,бутон,существительное
35,тукунф,нет,нет,цветочный,прилагательное
36,тукъмакъ,мн. ч. тукъмакъар,нет,палица,существительное
37,тулак,нет,нет,полинявший,прилагательное
38,тулак хьас,нет,да,полинять,глагол
39,тулаквел,нет,нет,линька,существительное
40,тум,мн. ч. тумар,нет,семя; зёрнышко,существительное
41,тумавар,нет,нет,насморк,существительное
42,тунгулай,нет,нет,легкомысленный,прилагательное
43,тундра,нет,нет,тундра,существительное
44,тунт хасиятинф,нет,нет,вспыльчивый,прилагательное
45,тунт хьас,нет,нет,бушевать,глагол
46,тунтвел,мн. ч. тунтвелар,нет,степень,существительное
47,туп,мн. ч. тупар,нет,мяч; ядро; пушка; рулон,существительное
48,тупанчи,мн. ч. тупанчибур,нет,пистолет,существительное
49,тупламишди,нет,нет,собранно; мобилизованно,наречие
50,тупчи,мн. ч. тупчибур,нет,артиллерист; хвастун; лгун,существительное
51,тупп дурхIас,нет,нет,футбол,существительное
52,тупп дурхIаф,мн. ч. тупп дурхIаттар,нет,футболист,существительное
53,тур1,мн. ч. турар,нет,невод,существительное
54,тур2,мн. ч. турар,нет,сабля; меч,существительное
55,турба кум агъвереф,мн. ч. турбабур кумар агъвереттар,нет,дымоход,существительное
56,турбина,мн. ч. турбинабур,нет,турбина,существительное
57,турзи,мн. ч. турзибур,нет,кислота,существительное
58,турист,мн. ч. туристар,нет,турист,существительное
59,турк,мн. ч. туркар,нет,ласка,существительное
60,турф,мн. ч. турфар,нет,редька; редис; бурак; репа,существительное
61,турф,нет,нет,торф,существительное
62,туршевел,нет,нет,закислённость,существительное
63,туршеф,нет,нет,кислый,прилагательное
64,тут,мн. ч. тутар,нет,тутовник; шелковица,существительное
65,туткульш,мн. ч. тутукъушар,нет,попугай,существительное
66,тутуф,нет,да,слюна,существительное
67,тутуф,нет,да,плевок,существительное
68,туфанг,мн. ч. туфангар,нет,ружьё,существительное
69,туфангин ун,мн. ч. туфангин унар,нет,выстрел,существительное
70,тухум,мн. ч. тухумар,нет,племя; род; родня,существительное
71,тухъвел,нет,нет,сытость,существительное
72,тухъди,нет,нет,сыто; сытно,наречие
73,тушкинди,нет,нет,тяжело; трудно,наречие
74,туьк,мн. ч. туькар,нет,пушок,существительное
75,туьлекъ гиргенар,нет,нет,обмотка,существительное
76,туьлле хьас,нет,нет,потерять,глагол
77,туьти,мн. ч. туьтибур,нет,плевок,существительное
78,туьтуь,мн. ч. туьтуьбур,нет,слюна,существительное
79,тутьуь акьас,нет,нет,плюнуть,глагол
80,тталат,нет,нет,вторник,существительное
81,ттамат,мн. ч. ттаматар,нет,томат,существительное
82,ттамгъа,мн. ч. ттамгъабур,нет,метка; клеймо,существительное
83,ттарзан,мн. ч. ттарзанар,нет,иголка,существительное
84,ттармус,мн. ч. ттармусар,нет,тормоз,существительное
85,ттарпеда,мн. ч. ттарпедабур,нет,торпеда,существительное
86,ттел,мн. ч. ттелр,нет,молозиво,существительное
87,ттиаттр,мн. ч. ттиаттрар,нет,театр,существительное
88,ттипографи,мн. ч. ттипографибур,нет,типография,существительное
89,ттирзин,мн. ч. ттирзинар,нет,велосипед,существительное
90,ттиттрат,мн. ч. ттиттратар,нет,тетрадь,существительное
91,ттракттар,мн. ч. трактатрар,нет,трактор,существительное
92,ттракттардихь хъаф,мн. ч. трактатарарихь хъаттар,нет,тракторист,существительное
93,ттугь акьас,нет,да,прогнать,глагол
94,ттук,нет,нет,ток; электричество,существительное
95,ттукар,нет,нет,электрификация,существительное
96,ттукунф,нет,нет,электрический,прилагательное
97,ттуллевел,мн. ч. ттуллевелар,нет,тонкость,существительное
98,ттун1,мн. ч. ттунар,нет,нить; пряжа,существительное
99,ттун2,мн. ч. ттунар,нет,тонна,существительное
100,ттунин гирген,мн. ч. ттунин гиргенар,нет,обмотка,существительное
101,ттур1,мн. ч. турар,нет,имя,существительное
102,ттур2,мн. ч. турар,нет,ложка,существительное
103,ттур аф,нет,нет,известный; знаменитый,прилагательное
104,ттур ахъуб,нет,нет,слава,существительное
105,ттур хьас,нет,нет,авторитет,существительное
106,ттур хьеб,нет,нет,авторитет,существительное
107,турник1,мн. ч. турникIар,нет,турник,существительное
108,ттурнир,мн. ч. ттурнирар,нет,турнир,существительное
109,туттас,нет,нет,потрясти,глагол
110,туфлибур,нет,нет,туфли,существительное
111,ттучка,мн. ч. ттучкабур,нет,точка,существительное
112,тульле хьас,нет,нет,утончиться,глагол
113,тульлеф1,нет,нет,плоский,прилагательное
114,тульлеф2,нет,нет,тонкий,прилагательное
115,тульли,нет,нет,плоско,наречие
116,тIаб1,мн. ч. тIабар,нет,чурбак,существительное
117,тIаб2,мн. ч. тIабар,нет,капкан,существительное
118,тIаб кIуранин,мн. ч. тIабар кIурарин,нет,полено,существительное
119,тIабак1,мн. ч. тIабакIар,нет,поднос,существительное
120,тIабак1,мн. ч. тIабакIар,нет,подсолнечник,существительное
121,тIабиIат,мн. ч. тIабиIатар,нет,нрав,существительное
122,тIабиIвел,нет,нет,покорность,существительное
123,тIабиIэт,нет,нет,природа,существительное
124,тIабиIэтинф,нет,нет,природный,прилагательное
125,тIабиIэтчи,мн. ч. тIабиIэтчибур,нет,натуралист,существительное
126,тIавус,мн. ч. тIавусар,нет,павлин,существительное
127,тIагар,мн. ч. тIагарар,нет,окно,существительное
128,тIагьре хьас,нет,да,соскучиться,глагол
129,тIагьрибур,нет,да,алыча,существительное
130,тIагIас,нет,нет,опухать; распухнуть,глагол
131,тIакьай,мн. ч. тIакьаяр,нет,дятел,существительное
132,тIакьат,нет,нет,ресурсы; богатство; состоятельность,существительное
133,тIакьатсуз,нет,нет,невыносливый,прилагательное
134,тIакьван акьас,нет,нет,запачкать,глагол
135,тIакьванди,нет,нет,нечисто; грязно; неряшливо,наречие
136,тIакьванф,нет,нет,грязный,прилагательное
137,тIакьвар,нет,нет,нечистоты,существительное
138,тIакьвач,мн. ч. тIакьвачар,нет,неряха,существительное
139,тIалаб,мн. ч. тIалабар,нет,просьба,существительное
140,тIалаб акьас,нет,нет,просить; запросить,глагол
141,тIалабчи,мн. ч. тIалабчибур,нет,заявитель,существительное
142,тIама,мн. ч. тIамабур,нет,пешка,существительное
143,тIамавур,нет,нет,игра,существительное
144,тIамс,мн. ч. тIамсар,нет,ковёр; сумах,существительное
145,тIам-тIам,нет,нет,пятно,существительное
146,тIаракьу,нет,нет,шумливый; шумный,прилагательное
147,тIарам,нет,нет,надёжный; прочный; безупречный,прилагательное
148,тIараш,мн. ч. тIарашар,нет,грабёж,существительное
149,тIараш акьас,нет,нет,грабить; ограбить,глагол
150,тIарашчи,мн. ч. тIарашчибур,нет,грабитель; разбойник,существительное
151,тIаркIил,мн. ч. тIаркIилар,нет,полено,существительное
152,тIарпIди,нет,нет,быстро; сразу,наречие
153,тIарум,нет,нет,сажа,существительное
154,тIарум,нет,нет,копать,глагол
155,тIафал,мн. ч. тIафалар,нет,вор; домушник,существительное
156,тIафалвел,нет,нет,воровство,существительное
157,тIафалчи,мн. ч. тIафалчибур,нет,грабитель; вор,существительное
158,тIахIурар,нет,нет,помои,существительное
159,тIебиэт,нет,нет,нрав,существительное
160,тIегIем,нет,нет,вкус,существительное
161,тIегIем адай,нет,нет,безвкусно,наречие
162,тIегIем акьас,нет,нет,попробовать,глагол
163,тIегIемсуз,нет,нет,невкусный,прилагательное
164,тIегIемсузди1,нет,нет,безвкусно,наречие
165,тIегIемсузди2,нет,нет,бессмысленно,наречие
166,тIекьванди,нет,да,нечисто; грязно,наречие
167,тIекьванф,нет,да,грязный,прилагательное
168,тIем,нет,нет,вкус,существительное
169,тIем адай,нет,нет,безвкусно,наречие
170,тIем акьас,нет,нет,попробовать,глагол
171,тIем хьадаф,нет,нет,безвкусно,наречие
172,тIемехI,мн. ч. тIемехIар,нет,желание; аппетит; соблазн,существительное
173,тIемехIкар,мн. ч. тIемехIкурар,нет,скряга,существительное
174,тIеIуын,нет,нет,мор,существительное
175,тIибитI,мн. ч. тIибитIар,нет,виноград,существительное
176,тIибитIарин багъ,мн. ч. тIибитIарин багъар,нет,виноградник,существительное
177,тIибитIчи,мн. ч. тIибитIчибур,нет,виноградарь,существительное
178,тIил1,мн. ч. тIилар,нет,верёвка; аркан,существительное
179,тIил2,мн. ч. тIилар,нет,струна,существительное
180,тIинкI,мн. ч. тIинкIар,нет,капелька,существительное
181,тIинкIар,нет,нет,брызги,существительное
182,тIирI,мн. ч. тIирIар,нет,кустарник,существительное
183,тIуб,мн. ч. тIубар,нет,палец,существительное
184,тIубруц,мн. ч. тIубруцар,нет,юла,существительное
185,тIубул,мн. ч. тIубулар,нет,колечко; перстень,существительное
186,тIубул руцас,нет,нет,вертеть,глагол
187,тIул,мн. ч. тIулар,нет,прут,существительное
188,тIулар акьас,нет,нет,притворяться,глагол
189,тIулкI,нет,нет,конфискация,существительное
190,тIулкI акьас,нет,нет,конфисковать,глагол
191,тIумбагI,мн. ч. тIумбагIар,нет,пузырь,существительное
192,тIун1,мн. ч. тIунар,нет,кормушка; ясли,существительное
193,тIун2,мн. ч. тIунар,нет,ограда,существительное
194,тIур1,мн. ч. тIурар,нет,почка,существительное
195,тIур2,мн. ч. тIурар,нет,родинка,существительное
196,тIурс,нет,нет,скрученность,существительное
197,тIурс йирхьуб,нет,нет,скрученность,существительное
198,тIурфан,мн. ч. тIурфанар,нет,вьюга; буря; буран; ливень,существительное
199,тIутI,мн. ч. тIутIар,нет,муха,существительное
200,тIухас,нет,нет,вянуть,глагол
201,тIухь,мн. ч. тIухьар,нет,соска,существительное
202,тIучIанас,нет,нет,помять,глагол
203,убад,мн. ч. убадар,нет,стадо,существительное
204,угас,нет,нет,жечь,глагол
205,угьал,мн. ч. угьалар,нет,дождь,существительное
206,угьалин тIурфан,мн. ч. угьаларин тIурфанар,нет,гроза,существительное
207,угьраш,мн. ч. угьрашар,нет,негодяй; подлец; предатель,существительное
208,угьраш,нет,нет,подлый,прилагательное
209,угьрашвел,нет,нет,подлость,существительное
210,угь,мн. ч. угьар,нет,стон,существительное
211,угьар акьас,нет,нет,стонать,глагол
212,угьар-цIугьар,нет,нет,стенания; стоны,существительное
213,уд,мн. ч. удар,нет,зёрнышко,существительное
214,ударени,мн. ч. ударенибур,нет,ударение,существительное
215,ударник,мн. ч. ударникар,нет,ударник,существительное
216,удигь,нет,нет,впереди,наречие
217,удигь ягьа,нет,нет,позавчера,наречие
218,удигьай,нет,нет,вначале; раньше; сначала; прежде,наречие
219,удигьас,нет,нет,спереди,наречие
220,удигьастти,нет,нет,спереди,наречие
221,удигьвел1,нет,нет,прямота,существительное
222,удигьвел2,нет,нет,справедливость,существительное
223,удиягь,нет,да,позавчера,наречие
224,удул,мн. ч. удулар,да,дыра,существительное
225,уджагь,мн. ч. уджагьар,нет,дом,существительное
226,уджагь хал,мн. ч. уджагь халар,да,очаг,существительное
227,уджас,нет,нет,испéчь; жарить,глагол
228,уджвел,нет,нет,жара,существительное
229,уджуз хьуф,нет,нет,униженный,прилагательное
230,уджузвел1,нет,нет,дешевизна,существительное
231,уджузвел2,нет,нет,ничтожность,существительное
232,уджузди,нет,нет,дёшево; недорого; даром,наречие
233,уджузинф,нет,нет,дешёвый,прилагательное
234,узанги,нет,нет,стремя,существительное
235,узас,нет,нет,сеять; посеять,глагол
236,узе къаравел,нет,нет,стеснительность; стыдливость,существительное
237,узе къарахьуб,нет,нет,смущение; стыдливость,существительное
238,узиагь,нет,нет,честный; незапятнанный,прилагательное
239,узиагьвел,нет,нет,незапятнанность,существительное
240,узикъара хьас,нет,нет,попасть (в неловкое положение),глагол
241,узубар,нет,нет,посадка,существительное
242,узуна кегъучIас,нет,нет,вырастить,глагол
243,уйин,мн. ч. уйинар,нет,игра; уловка; козырь; фокус,существительное
244,уйинар акъас,нет,нет,хитрить; плутовать,глагол
245,уйинар аттивас,нет,нет,плутовать,глагол
246,уйинар аттивуб,нет,нет,кокетливость,существительное
247,уйинбаз,мн. ч. уйинбазар,нет,обманщик; хитрец,существительное
248,уйинсуз,нет,нет,честный; бесхитростный,прилагательное
249,уйинсузвел,нет,нет,честность; прямота,существительное
250,уйинсузди,нет,нет,честно; прямо,наречие
251,укъаф,нет,нет,драчливый,прилагательное
252,укъуб,нет,нет,борьба,существительное
253,укьар,мн. ч. укьарар,нет,баран,существительное
254,укьум,мн. ч. укьумар,нет,палец,существительное
255,ул,мн. ч. улар,нет,глаз,существительное
256,ул гьай,нет,нет,боязливо,наречие
257,ул киркьваф,нет,нет,дурноглазый,прилагательное
258,ул хьархьас,нет,нет,соскучиться; истосковаться,глагол
259,ул хьархьуб,нет,нет,печаль; тоска,существительное
260,ул хъаф,нет,нет,скучающий,прилагательное
261,улам,нет,да,глубь; топь,существительное
262,уликен,мн. ч. уликенар,нет,уровень,существительное
263,уликIетIуб1,нет,нет,упрямство,существительное
264,уликIетIуб2,нет,нет,хитрость,существительное
265,уликIетIун,нет,нет,упрямо,наречие
266,уликIетIуф,мн. ч. уликIетIуттар,нет,упрямец,существительное
267,улин варттал багв,мн. ч. улин варттал багвар,нет,веко,существительное
268,улин Iзгв,мн. ч. улин Iзгвар,нет,зрачок,существительное
269,улить гаш аф,нет,нет,алчный,прилагательное
270,улуд,мн. ч. улудар,нет,дыра,существительное
271,уммат,нет,нет,потомство; родня; род,существительное
272,умножени,нет,нет,умножение,существительное
273,умуд,мн. ч. умудар,нет,надежда,существительное
274,умуд кеф,нет,нет,надёжный,прилагательное
275,умуд кехьубвел,нет,нет,честность; надёжность,существительное
276,умуд хьуб,нет,нет,надёжность,существительное
277,умуми,нет,да,всеобщий; общий,прилагательное
278,умуми,нет,нет,совокупно,наречие
279,ун1,мн. ч. унар,нет,звук; лязг; звон; стук,существительное
280,ун2,мн. ч. унар,нет,крик; призыв,существительное
281,ун вес,нет,нет,стонать,глагол
282,ун хъаф,нет,нет,шумливый,прилагательное
283,унар,нет,нет,переполох; шум,существительное
284,унар акъас гIезаб кей,нет,нет,стонать,глагол
285,унар аркъаф,нет,нет,шумный,прилагательное
286,унар-гIезабар,нет,нет,стенания,существительное
287,унахъас,нет,нет,"приглашать, звать",глагол
288,унетI,мн. ч. унетIар,нет,бровь,существительное
289,университет,мн. ч. университетар,нет,университет,существительное
290,управлени,мн. ч. управленибур,нет,управление,существительное
291,управляющи,нет,нет,управляющий,прилагательное
292,уравнени,мн. ч. уравненибур,нет,уравнение,существительное
293,урай,нет,да,мята,существительное
294,ург,мн. ч. ургар,нет,баран,существительное
295,урдег,мн. ч. урдегар,нет,утка,существительное
296,урелусар,нет,нет,щавель,существительное
297,уриар,нет,нет,мята,существительное
298,уринф,нет,нет,дальний,прилагательное
299,уркъ1,мн. ч. уркьар,нет,ватрушка; беляш,существительное
300,уркъ2,мн. ч. уркьар,нет,ступа,существительное
301,уркI,мн. ч. уркIар,нет,отверстие; ячейка,существительное
302,урс,нет,нет,моль,существительное
303,урта,нет,нет,средний,прилагательное
304,уртабаб,мн. ч. уртабабар,нет,середняк,существительное
305,уртахъ,мн. ч. уртахъар,нет,напарник,существительное
306,уртахъ,нет,нет,совместный; общий,прилагательное
307,уртахъди,нет,нет,совместно,наречие
308,урцанф,нет,нет,скучный,прилагательное
309,урч,мн. ч. урчар,нет,телёнок,существительное
310,урчунин якк,мн. ч. урчарин яккар,нет,телятина,существительное
311,ус,мн. ч. усар,да,место,существительное
312,усанф,нет,нет,земельный,прилагательное
313,уссал,мн. ч. уссалар,нет,трус,существительное
314,уссал1,нет,нет,испорченный,прилагательное
315,уссал2,нет,нет,робкий; трусоватый,прилагательное
316,уссалвел1,нет,нет,испорченность; никчёмность,существительное
317,уссалвел2,нет,нет,трусость,существительное
318,устав,мн. ч. уставар,нет,устав,существительное
319,устта,мн. ч. усттабур,нет,рабочий; ремесленник; умелец; мастер; плотник,существительное
320,усттавел,нет,нет,мастерство,существительное
321,усттаз,мн. ч. усттазар,нет,мастер; наставник,существительное
322,усттайин кумакчи,нет,нет,подмастерье,существительное
323,усттайи суман,нет,нет,умело; мастерски,наречие
324,усттул,мн. ч. усттулар,нет,стол,существительное
325,утанмаз,мн. ч. утанмазар,нет,циник; бесстыдник,существительное
326,утанмазвел,нет,нет,наглость; бесстыдство,существительное
327,утас,нет,нет,бить; ударять,глагол
328,утас дар,нет,нет,избить,глагол
329,ути,мн. ч. утибур,да,утюг,существительное
330,утун,мн. ч. утунар,да,спина,существительное
331,утуь,мн. ч. утуьбур,нет,утюг,существительное
332,утIас,нет,нет,гнить; сгнить; пропасть,глагол
333,утIувел,нет,нет,вредность,существительное
334,утIуф1,нет,нет,вредный; привередливый,прилагательное
335,утIуф2,нет,нет,гнилой,прилагательное
336,уф акьас,нет,нет,подуть,глагол
337,уфатI,мн. ч. уфатIар,нет,толстяк; толстушка,существительное
338,уха сук,мн. ч. уха сукар,нет,напиток,существительное
339,ухас,нет,нет,выпить,глагол
340,ухшар аеф,нет,нет,подобный,прилагательное
341,уч учин кIилинди аф,нет,нет,независимый,прилагательное
342,уч учин хIаф,нет,нет,независимый,прилагательное
343,участтак,мн. ч. участтакар,нет,участок,существительное
344,ученик,мн. ч. ученикар,нет,ученик,существительное
345,учёт,нет,нет,учёт,существительное
346,учи,нет,нет,сам,местоимение
347,учикес гъургъвас,нет,нет,бурчать,глагол
348,училище,мн. ч. училищебур,нет,училище,существительное
349,учин мефеIэт,мн. ч. учин мефеIэтар,нет,интерес,существительное
350,учинтилас,нет,нет,упрямо,наречие
351,учинтилас аладайчIваф,мн. ч. учинтилас аладайчIваттар,нет,упрямец,существительное
352,учинтилас аладайчIуб,нет,нет,упрямство,существительное
353,учинтилас алддучIуб,нет,нет,устойчивость,существительное
354,учис хайир кедай,нет,нет,корысть,существительное
355,учис хайир хьас,нет,нет,умысел,существительное
356,учитил,мн. ч. учитилар,нет,учитель,существительное
357,учитилница,мн. ч. учитилницабур,нет,учительница,существительное
358,учихъди аркьаф,нет,нет,располагающий,прилагательное
359,учур,мн. ч. учурар,нет,очередь,существительное
360,уцас,нет,нет,косить,глагол
361,уьзуьм,мн. ч. уьзуьмар,нет,виноград,существительное
362,уьзуьмлух,мн. ч. уьзуьмлухар,нет,виноградник,существительное
363,уьзуьмчи,мн. ч. уьзуьмчибур,нет,виноградарь,существительное
364,уькъевел1,нет,нет,густота; насыщенность,существительное
365,уькъевел2,нет,нет,прочность; надёжность; крепость,существительное
366,уькъеф,нет,нет,насыщенный,прилагательное
367,уькъи,нет,нет,густо; насыщенно,наречие
368,уькъиди,нет,нет,густо; насыщенно,наречие
369,уьлке,мн. ч. уьлкебур,нет,страна; край,существительное
370,уьлчи,мн. ч. уьлчибур,нет,вестник,существительное
371,уьмур,мн. ч. уьмурар,нет,век,существительное
372,уьреген,мн. ч. уьрегенар,нет,улей,существительное
373,уьркIе акьас,нет,нет,углубить,глагол
374,уьркIе мукъ,мн. ч. уьркIе мукьар,нет,топь,существительное
375,уьркIевел,нет,нет,глубь; глубина; топь,существительное
376,уьркIеф,нет,нет,глубокий,прилагательное
377,уьркIи,нет,нет,глубоко; углублённо,наречие
378,уьрцIел,мн. ч. уьрцIелар,да,стружка,существительное
379,уьстт,мн. ч. уьсттар,да,свист; свисток; гул,существительное
380,уьсхьер,мн. ч. уьсхьерар,нет,крот,существительное
381,уьтт,нет,нет,мёд,существительное
382,уьхь,мн. ч. уьхьар,да,снег,существительное
383,уьхьттинф,нет,да,снежный,прилагательное
384,уьцIай-цIурас,нет,нет,истощение,существительное
385,уьцIас,нет,нет,истощение,существительное
386,уьштт,мн. ч. уьшттар,нет,свист,существительное
387,уьштт атаф,мн. ч. уьштт ататтар,нет,свисток,существительное
388,уягь,мн. ч. уягьар,нет,известие,существительное
389,фабрика,мн. ч. фабрикабур,нет,фабрика,существительное
390,фагьум,мн. ч. фагьумар,нет,ум; разум; интеллект; рассудок; сознание,существительное
391,фагьум акьас,нет,нет,подумать; сообразить,глагол
392,фагьум фаф,нет,нет,проницательный,прилагательное
393,фагьумлу,нет,нет,сообразительный; проницательный,прилагательное
394,фадихьас,нет,нет,бросить,глагол
395,файтун,мн. ч. файтунар,нет,фаэтон,существительное
396,факт,мн. ч. фактар,нет,факт,существительное
397,факьи,мн. ч. факьибур,нет,мулла,существительное
398,факьир1,нет,нет,нищий; бедный,прилагательное
399,факьир2,нет,нет,беззащитный,прилагательное
400,фал,мн. ч. фалар,нет,гадание; предсказание,существительное
401,фалиджа,мн. ч. фалиджабур,нет,паралич,существительное
402,фалчи,мн. ч. фалчибур,нет,гадальщик,существительное
403,фана,нет,нет,пропасть,глагол
404,фанавел,нет,нет,свéутность,существительное
405,фанар,мн. ч. фанарар,нет,фонарь,существительное
406,фандигар,мн. ч. фандигаяр,нет,хитрец; ловкач,существительное
407,фандигар,нет,да,коварный; хитрый,прилагательное
408,фандигарвел,нет,нет,хитрость; ловкачество,существительное
409,фанера,нет,нет,фанера,существительное
410,фантази,мн. ч. фантазибур,нет,фантазия,существительное
411,фара,мн. ч. фарабур,нет,фара,существительное
412,фараш,нет,нет,жизнерадостный; бойкий,прилагательное
413,фарз,мн. ч. фарзар,нет,обязанность,существительное
414,фарискатьвел,нет,нет,спокойствие,существительное
415,фарискатьди,нет,нет,спокойно; мирно,наречие
416,фарискатьтинф,нет,нет,спокойный; мирный,прилагательное
417,фаркъ,мн. ч. фаркъар,да,разница; разное,существительное
418,фаруз,нет,нет,бирюза,существительное
419,фас,нет,нет,зачем; почему,наречие
420,фасадвел,нет,нет,порочность; развращенность,существительное
421,фасикъ,мн. ч. фасикъар,нет,нечестивец; грешник,существительное
422,фасикъ,нет,нет,нечестивый; беспутный,прилагательное
423,фасикъвел,нет,нет,беспутство,существительное
424,фасон,мн. ч. фасонар,нет,фасон,существительное
425,фатуна,нет,нет,вольно,наречие
426,фатуна аф,нет,нет,вольный,прилагательное
427,фатуф,нет,нет,свободный,прилагательное
428,фатфа,мн. ч. фатфабур,нет,мнение,существительное
429,фатфачи,мн. ч. фатфачибур,нет,сплетник,существительное
430,фаттивас,нет,нет,конфисковать,глагол
431,фаттивуб,мн. ч. фаттивубар,нет,конфискация,существительное
432,фацанас,нет,нет,задержать,глагол
433,фачиенас,нет,нет,передать,глагол
434,феврал,нет,нет,февраль,существительное
435,фегIла,мн. ч. фегIлабур,да,рабочий; ремесленник,существительное
436,федераци,мн. ч. федерацибур,нет,федерация,существительное
437,фейджан,мн. ч. фейджанар,нет,фаянс,существительное
438,фера,нет,нет,ничего,местоимение
439,фера дадуьрхьеф,мн. ч. фера дадуьрхьефар,нет,неудачник,существительное
440,фера дай,нет,нет,зря,наречие
441,ферма,мн. ч. фермабур,нет,ферма,существительное
442,фи,нет,нет,что,местоимение
443,фидегьан,нет,нет,сколько,наречие
444,фидегьанра,нет,нет,нисколько,наречие
445,физик,мн. ч. физикар,нет,физик,существительное
446,физика,нет,нет,физика,существительное
447,фикир1,мн. ч. фикирар,нет,дума; мысль; раздумье; размышление; замысел; идея; намерение; смысл; помысел; предположение; мнение,существительное
448,фикир2,мн. ч. фикирар,нет,печаль; тоска; переживание,существительное
449,фикир акъас,нет,нет,думать; задуматься; мыслить; подумать; призадуматься; сообразить,глагол
450,фикир акьун,нет,нет,мудро; разумно,наречие
451,фикир аркьаф,нет,нет,мыслящий,прилагательное
452,фикир дакьун,нет,нет,неразумно,наречие
453,фикир фаф1,нет,нет,задумчивый; озабоченный,прилагательное
454,фикир фаф2,нет,нет,сообразительный,прилагательное
455,фикирар,нет,нет,раздумье,существительное
456,фикирар аркьаф,нет,нет,думающий,прилагательное
457,фикирвел,нет,нет,задумчивость; озабоченность; грусть,существительное
458,фикирлу,нет,нет,думающий; мыслящий,прилагательное
459,фил,мн. ч. филар,нет,слон,существительное
460,филиал,мн. ч. филиалар,нет,филиал,существительное
461,филолог,мн. ч. филологар,нет,филолог,существительное
462,филологи,нет,нет,филология,существительное
463,философ,мн. ч. философар,нет,философ,существительное
464,филфилар къара,мн. ч. филфилар къарабур,да,перец,существительное
465,фира,нет,нет,"ничто, ничего",местоимение
466,фирехI,нет,да,открытый; широкий,прилагательное
467,фирехI акъас,нет,да,расширить,глагол
468,фирехIвел,нет,да,просторность; широта,существительное
469,фирехIди,нет,нет,весело; радостно; открыто,наречие
470,фирехIди,нет,да,просторно; широко,наречие
471,фирма,мн. ч. фирмабур,нет,фирма,существительное
472,фитна,мн. ч. фитнабур,да,сплетня; клевета; раздор,существительное
473,фиттигI хьучира гIаф,нет,нет,привередливый,прилагательное
474,фиттина ккедаф,мн. ч. фиттина ккедаттар,нет,недотепа,существительное
475,фиттина ккедаф,нет,нет,никчёмный,прилагательное
476,фиттисра дахьуф,нет,нет,никчёмность; недотепа,существительное
477,фиттисра лазим даваф,нет,нет,трусость,существительное
478,фиттисра лазим дахьуб,нет,нет,никчёмность,существительное
479,фихьучира ягIархьуб,мн. ч. фихьучира ягIархьубар,нет,информированность,существительное
480,фиштти,нет,нет,как,наречие
481,флот,мн. ч. флотар,нет,флот,существительное
482,фольклор,нет,нет,фольклор,существительное
483,фонд,мн. ч. фондар,нет,фонд,существительное
484,фонетика,нет,нет,фонетика,существительное
485,фонтан,мн. ч. фонтанар,нет,фонтан,существительное
486,форма,мн. ч. формабур,нет,форма,существительное
487,формальни,нет,нет,формальный,прилагательное
488,фосфор,нет,нет,фосфор,существительное
489,фотограф,мн. ч. фотографар,нет,фотограф,существительное
490,фронт,мн. ч. фронтар,нет,фронт,существительное
491,фронтовик,мн. ч. фронтовикар,нет,фронтовик,существительное
492,фугъара,мн. ч. фугъарабур,нет,бедняк,существительное
493,фугъара,нет,нет,бедный; несчастный,прилагательное
494,фугьум фаф,нет,нет,сообразительный,прилагательное
495,фукьиран,мн. ч. фукьиранар,нет,домосед; бездельник; тунеядец,существительное
496,фуланкас,нет,нет,такой-то,местоимение
497,фуланф1,мн. ч. фуланфар,да,некий,местоимение
498,фуланф2,мн. ч. фуланфар,да,такой-то,местоимение
499,фун,мн. ч. фунар,нет,живот; брюхо,существительное
500,фун арцIагьилди,нет,нет,сытно,наречие
501,фун ацIуб,нет,нет,сытость,существительное
502,фун ацIун,нет,нет,сытно,наречие
503,фун ацIуф,нет,нет,сытый,прилагательное
504,фундамент,мн. ч. фундаментар,нет,фундамент,существительное
505,фундугъ,мн. ч. фундугъар,нет,фундук,существительное
506,фуни хьас,нет,нет,беременеть,глагол
507,фуни хьуб,нет,нет,беременность,существительное
508,фунин гутай,мн. ч. фунин гутаяр,да,пуп; пупок; пуповина,существительное
509,фунин гIан,нет,нет,нутро,существительное
510,фунин хутI,мн. ч. фунин хутIар,нет,пуп; пупок; пуповина,существительное
511,фунин хIаф,мн. ч. фунин хIафар,нет,обжора,существительное
512,фунтахI,мн. ч. фунтахIар,нет,обжора,существительное
513,функьур,мн. ч. фунхьурар,да,чревоугодник; обжора,существительное
514,фур,мн. ч. фурар,нет,колесо,существительное
515,фургьан1,нет,нет,просторный; свободный,прилагательное
516,фургьан2,нет,нет,изобильный,прилагательное
517,фургьанвел,нет,нет,изобилие,существительное
518,фургьанди1,нет,да,обильно,наречие
519,фургьанди2,нет,нет,вольно; свободно,наречие
520,фургьанф,нет,нет,вольный,прилагательное
521,фургъун,мн. ч. фургъунар,нет,фургон,существительное
522,фурегь,нет,нет,широкий; свободный,прилагательное
523,фурс,нет,нет,форс,существительное
524,фурс кей,нет,нет,заносчиво; важно,наречие
525,фурс керхьуб,нет,нет,зазнайство,существительное
526,фурсар кедахьуб,нет,нет,простота,существительное
527,фурсар керхьуф,нет,нет,возгордившийся,прилагательное
528,фурсар кеф,нет,нет,гордый,прилагательное
529,футбол,нет,нет,футбол,существительное
530,футболист,мн. ч. футболистар,нет,футболист,существительное
531,фуш,нет,нет,кто,местоимение
532,фушкканчира,нет,нет,любой,прилагательное
533,фушра,нет,нет,никто,местоимение
534,фушчин агъаф,нет,нет,некий,местоимение
535,хаб1,нет,нет,снова,наречие
536,хаб2,нет,нет,потом,наречие
537,хаб адис,нет,нет,вернуться,глагол
538,хаб акьас1,нет,нет,обновить; повторить,глагол
539,хаб акьас2,нет,нет,отодвинуть; прогнать,глагол
540,хаб акьуб,мн. ч. хаб акьубар,нет,повторение,существительное
541,хаб удигьай суман,нет,нет,снова; по-прежнему,наречие
542,хабар,мн. ч. хабарар,нет,известие; весть; информация; рассказ; слух; молва,существительное
543,хабар акьас,нет,нет,сообщить; известить,глагол
544,хабар акьуф,нет,нет,извещённый,прилагательное
545,хабарар гьареф,мн. ч. хабарар гьареттар,нет,вестник,существительное
546,хабардар,нет,нет,извещённый; осведомлённый,прилагательное
547,хабардарвел,мн. ч. хабардарвелар,нет,информированность,существительное
548,хабарди аф,нет,нет,осведомлённый,прилагательное
549,хабарди ахьуб,мн. ч. хабарди ахьубар,нет,информированность,существительное
550,хабарсузвел,мн. ч. хабарсузвелар,нет,неосведомлённость,существительное
551,хабарсузди,нет,нет,неожиданно; нечаянно,наречие
552,хабарчи,мн. ч. хабарчибур,нет,вестник,существительное
553,хаб йис,нет,нет,вернуть,глагол
554,хабра,нет,нет,ещё; опять; снова,наречие
555,хав,мн. ч. хавар,нет,обхват; охапка,существительное
556,хав,нет,да,по-прежнему; снова,наречие
557,хав акьас,нет,да,отодвинуть,глагол
558,хаджалат1,мн. ч. хаджалатар,нет,мысль,существительное
559,хаджалат2,мн. ч. хаджалатар,да,тоска; печаль,существительное
560,хаджалаттинф,нет,нет,печальный; скорбный; горестный,прилагательное
561,хаджалатлу,нет,нет,горюющий; скорбящий,прилагательное
562,хаджил,нет,нет,полный,прилагательное
563,хаз1,мн. ч. хазар,нет,белка,существительное
564,хаз2,мн. ч. хазар,нет,куница,существительное
565,хазандар,мн. ч. хазандарар,нет,казначей,существительное
566,хаин,мн. ч. хаинар,нет,предатель; изменник,существительное
567,хаинвел,мн. ч. хаинвелар,нет,предательство; измена,существительное
568,хайир,нет,нет,польза; полезность; прибыль; прок; доход; добро,существительное
569,хайир адай,нет,нет,непреднамеренно,наречие
570,хайир ачадиб,мн. ч. хайир ачадибар,нет,приход,существительное
571,хайир вереф,нет,нет,полезный; выгодный; прибыльный,прилагательное
572,хайир дакканвел,нет,нет,недоброжелательность,существительное
573,хайир дакканф,нет,нет,недоброжелательный,прилагательное
574,хайир идихъуб,нет,нет,угождение,существительное
575,хайир кеф1,нет,нет,полезный; выгодный; прибыльный; результативный,прилагательное
576,хайир кеф2,нет,нет,добрый,прилагательное
577,хайир кидавел,мн. ч. хайир кидавелар,нет,бесполезность,существительное
578,хайир кидай,нет,нет,бесцельно,наречие
579,хайир хъеб,нет,нет,выгодность,существительное
580,хайир хьуб,мн. ч. хайир хъубар,нет,результативность,существительное
581,хайирвел1,нет,нет,доброта; благость,существительное
582,хайирвел2,нет,нет,выгодность,существительное
583,хайир-дуьгIе,мн. ч. хайир-дуьгIебур,нет,благодарение,существительное
584,хайирлу,нет,нет,полезный; выгодный; прибыльный,прилагательное
585,хайирлувел1,нет,нет,полезность,существительное
586,хайирлувел2,нет,нет,благость,существительное
587,хайирсуз,нет,нет,недоброжелательный,прилагательное
588,хайирсузвел1,мн. ч. хайирсузвелар,нет,бесполезность,существительное
589,хайирсузвел2,нет,нет,недоброжелательность,существительное
590,хайли,нет,да,изрядно; немало,наречие
591,хайлин,нет,нет,несколько,числительное
592,хайлин,нет,да,немало,наречие
593,хайлинф,нет,да,изрядный; немалый,прилагательное
594,хайрат,нет,нет,милостыня; благодеяние,существительное
595,хал1,мн. ч. халар,нет,помещение; жильё; дом; комната,существительное
596,хал2,мн. ч. халар,нет,чехол; футляр,существительное
597,хал алде гIуб,мн. ч. хал алде гIубар,да,черепаха,существительное
598,хал ухIаф,мн. ч. хал ухIаттар,нет,домосед,существительное
599,хал хъудаф,нет,нет,бездомный,прилагательное
600,халагIан,мн. ч. халагIанар,да,хозяйка,существительное
601,халат,мн. ч. халатар,нет,халат,существительное
602,халатный,нет,нет,халатный,прилагательное
603,халват,нет,нет,уединённый,прилагательное
604,халватвел,нет,да,уединение,существительное
605,халик,мн. ч. халикар,нет,творец,существительное
606,халис,нет,нет,натуральный,прилагательное
607,халисвел,нет,нет,честность; правдивость; натуральность,существительное
608,халисди,нет,да,честно; правдиво; натурально,наречие
609,халиф,мн. ч. халифар,нет,головокружение,существительное
610,халича,мн. ч. халичабур,нет,ковёр,существительное
611,халкь,мн. ч. халкьар,нет,народ; толпа,существительное
612,халкь акьас,нет,нет,создать; сотворить,глагол
613,халписак,мн. ч. халписакар,да,арбуз,существительное
614,хам,мн. ч. хамар,нет,кожа; шкура; шкурка,существительное
615,хам1,нет,нет,избалованный,прилагательное
616,хам2,нет,нет,гордый,прилагательное
617,хамис,нет,нет,четверг,существительное
618,хан,мн. ч. ханар,нет,хан,существительное
619,хана,мн. ч. ханабур,нет,клетка; графа,существительное
620,хандаг,мн. ч. хандагар,нет,канава; овраг; ров; яма,существительное
621,хандак1,мн. ч. хандак1ар,нет,ров; яма,существительное
622,ханджал,мн. ч. ханджалар,нет,кинжал,существительное
623,ханум,мн. ч. ханумар,нет,госпожа,существительное
624,ханчI,мн. ч. ханчIар,нет,царапина,существительное
625,ханчIар икIас,нет,нет,царапать,глагол
626,хараб акьас,нет,да,разрушение; уничтожение,существительное
627,хараб акьас,нет,да,разорять; разрушать,глагол
628,харабар,нет,нет,развалины; руины,существительное
629,харабат,мн. ч. харабатар,нет,разрушение; хаос,существительное
630,харабвел,мн. ч. харабвелар,нет,разорённость; разрушенность,существительное
631,харай,мн. ч. хараяр,нет,шёлк,существительное
632,харайинф,нет,нет,шёлковый,прилагательное
633,характеристика,мн. ч. характеристикабур,нет,характеристика,существительное
634,хардж,мн. ч. харджар,нет,расход; издержки; затрата; налог,существительное
635,хардж акьас,нет,нет,расходовать; тратить,глагол
636,харджи,мн. ч. харджибур,нет,зарплата; доход,существительное
637,хас,нет,нет,рожать,глагол
638,хасият,мн. ч. хасиятар,нет,характер; привычка,существительное
639,хасиятна,мн. ч. хасиятнабур,нет,характеристика,существительное
640,хатир,нет,нет,угождение,существительное
641,хатирлу,нет,нет,почтительный,прилагательное
642,хатирлувел,нет,нет,почтительность,существительное
643,хатI,мн. ч. хатIар,нет,линия; колея; штрих; полоса; зарубка; почерк,существительное
644,хатIа1,мн. ч. хатIабур,нет,опасность; риск,существительное
645,хатIа2,мн. ч. хатIабур,да,вина; ошибка,существительное
646,хач,мн. ч. хачар,нет,крест,существительное
647,хашав,мн. ч. хашавар,нет,скребок,существительное
648,хаятI,мн. ч. хаятIар,нет,нитка,существительное
649,хаятIинф,нет,нет,нитяной,прилагательное
650,хван,нет,нет,покатый,прилагательное
651,хвар хIуьни,мн. ч. хвар хIуьнивар,нет,кобыла,существительное
652,хев,мн. ч. хевар,нет,орех,существительное
653,хевар,нет,нет,орех; фундук,существительное
654,хецI,мн. ч. хецIар,нет,пиявка,существительное
655,хецIв,мн. ч. хецIвар,нет,клещ,существительное
656,хибхел,мн. ч. хибхелар,нет,град,существительное
657,хизан,мн. ч. хизанар,нет,жена; супруга,существительное
658,хил1,мн. ч. хилар,нет,крыло,существительное
659,хил2,мн. ч. хилар,да,рука,существительное
660,хил гьадив,нет,да,простите,междометие
661,хилив,мн. ч. хиливар,да,рукав,существительное
662,хилин кьав,мн. ч. хилин кьавар,нет,крыло,существительное
663,химир кедаф,нет,нет,пресный,прилагательное
664,химически,нет,нет,химический,прилагательное
665,хими,нет,нет,химия,существительное
0,химхел,мн. ч. химхелар,да,град,существительное
1,химчистка,мн. ч. химчисткабур,нет,химчистка,существительное
2,хинзизай,мн. ч. хинзизаяр,нет,паук,существительное
3,хинзизин чал,мн. ч. хинзизин чалар,нет,паутина,существительное
4,хинкI,мн. ч. хинкIар,нет,хинкал,существительное
5,хирда,мн. ч. хирдабур,нет,мелочь,существительное
6,хирда,нет,нет,мелкий,прилагательное
7,хирург,мн. ч. хирургар,нет,хирург,существительное
8,хирург аппераци аркьавус,мн. ч. хирургар апперацибур аркьавусар,нет,хирургия,существительное
9,хирхем,мн. ч. хирхемар,да,щебень,существительное
10,хиял,мн. ч. хиялар,нет,размышление; дума; предположение; замысел; мечта,существительное
11,хиял акьас,нет,нет,задуматься; призадуматься,глагол
12,хиял хьуб,нет,нет,задумчивость,существительное
13,хияларигI гIачушун,нет,нет,задумчиво,наречие
14,хиялвел,нет,нет,задумчивость; озабоченность,существительное
15,хиялин хьас,нет,нет,изумить; призадуматься,глагол
16,хиялин хьуб,мн. ч. хиялин хьубар,нет,изумление,существительное
17,хиялин хьун,нет,нет,изумлённо,наречие
18,хиялинф1,нет,нет,изумлённый,прилагательное
19,хиялинф2,нет,нет,задумчивый,прилагательное
20,хияллувел,нет,нет,озабоченность,существительное
21,хиянат,нет,нет,коварный,прилагательное
22,хиянаткар,мн. ч. хиянаткурар,нет,изменник; предатель,существительное
23,хиянаткарди,нет,нет,коварно,наречие
24,хлор,нет,нет,хлор,существительное
25,хозяйство,мн. ч. хозяйствабур,нет,хозяйство,существительное
26,хоккей,нет,нет,хоккей,существительное
27,холера,нет,нет,холера,существительное
28,холодильник,мн. ч. холодильникар,нет,холодильник,существительное
29,хрестомати,мн. ч. хрестоматибур,нет,хрестоматия,существительное
30,хрустальни,нет,нет,хрустальный,прилагательное
31,ху,мн. ч. хубур,нет,поле,существительное
32,хуб,нет,да,очень,наречие
33,хубджи,нет,нет,значительно; изрядно; немало,наречие
34,хубджинф,нет,нет,немалый; значительный,прилагательное
35,художник,мн. ч. художникар,нет,художник,существительное
36,хуз,нет,нет,приятный; располагающий,прилагательное
37,хул,мн. ч. хулар,нет,борозда,существительное
38,хулан,мн. ч. хуланар,нет,пол,существительное
39,хулан гъвад,мн. ч. хулан гъвадар,нет,потолок,существительное
40,хулан хьир,мн. ч. хулан хьирар,нет,хозяйка,существительное
41,хулан эесси,мн. ч. хулан эессибур,нет,хозяин,существительное
42,хул-мукъ,мн. ч. хулар-мукьар,нет,хозяйство; владение,существительное
43,хума,мн. ч. хумабур,нет,лихорадка; тиф,существительное
44,хумбевел,нет,нет,женственность,существительное
45,хумбеф,нет,нет,женский,прилагательное
46,хумбехал,мн. ч. хумбехулар,нет,плацента; послед,существительное
47,хундуз1,мн. ч. хундузар,нет,бобр,существительное
48,хундуз2,мн. ч. хундузар,нет,выдра,существительное
49,хуппай,нет,нет,потом,наречие
50,хуппур,мн. ч. хуппурар,нет,поле,существительное
51,хур I,мн. ч. хурIар,нет,глоток,существительное
52,хур I акьас,нет,нет,выпить,глагол
53,хураг,мн. ч. хурагар,да,пища; еда,существительное
54,хурар,нет,нет,горох,существительное
55,хурас1,нет,нет,учиться,глагол
56,хурас2,нет,нет,читать,глагол
57,хурас-ликIенас ягIаф,нет,нет,грамотный,прилагательное
58,хурд,мн. ч. хурдар,нет,кулак,существительное
59,хурдул,мн. ч. хурдулар,нет,лёгкое,существительное
60,хурт,нет,да,пена,существительное
61,хуруб,мн. ч. хурубар,нет,чтение; образование; учёба,существительное
62,хурубар,нет,нет,учёность,существительное
63,хурубар кеф,нет,нет,грамотный,прилагательное
64,хурувел,нет,нет,образованность; учёность,существительное
65,хуруф,мн. ч. хуруфар,нет,учёный,существительное
66,хуруф,нет,да,родимый,прилагательное
67,хурхур,мн. ч. хурхурар,да,храп,существительное
68,хуршеф,нет,нет,серый,прилагательное
69,хусуси,нет,нет,специальный,прилагательное
70,хусусивел,мн. ч. хусусивелар,нет,особенность,существительное
71,хут,мн. ч. хутар,нет,слива,существительное
72,хут ихьаф,мн. ч. хут ихьаттар,нет,заводила,существительное
73,хуттул,мн. ч. хуттулар,нет,внук; внучка; правнук,существительное
74,хутI,мн. ч. хутIар,нет,оса; жало,существительное
75,хуф-хеф,нет,нет,родимый,прилагательное
76,хух ярхIас,нет,нет,храпеть,глагол
77,хуш,мн. ч. хушIар,нет,страсть,существительное
78,хушIевел,мн. ч. хушIевелар,нет,шершавость; шероховатость,существительное
79,хушIеф,нет,нет,рассыпчатый; шершавый,прилагательное
80,хушIи,нет,нет,шершаво; шероховато,наречие
81,хуш,нет,нет,приятный,прилагательное
82,хушбахтт,нет,нет,счастливый,прилагательное
83,хушбахттди,нет,да,счастливо,наречие
84,хъагъишаф,мн. ч. хъагъишаттар,нет,защитник; заступник,существительное
85,хъагъишаф адаф,нет,нет,беззащитный,прилагательное
86,хъагъишиб,нет,нет,заступничество,существительное
87,хъадикIенас,нет,нет,грабить,глагол
88,хъадикIиб,нет,нет,воровство; грабёж; разбой,существительное
89,хъай,нет,нет,совместно,наречие
90,хъалпусак,мн. ч. хъалпусак,нет,арбуз,существительное
91,хъалхъам,мн. ч. хъалхъамар,нет,дупло,существительное
92,хъалхъас,мн. ч. хъалхъасар,да,черепаха,существительное
93,хъамелгуттар,нет,нет,остатки; отходы,существительное
94,хъара,нет,нет,опять; снова; ещё,наречие
95,хъара тич,нет,нет,дальше,наречие
96,хъарца ппалтту,мн. ч. хъарца ппалттубур,нет,пальто,существительное
97,хъатрикI,мн. ч. хъаттрикIер,нет,вор; грабитель; мошенник; разбойник,существительное
98,хъатрикIвел,мн. ч. хъатрикIвелар,нет,воровство,существительное
99,хъаттикIиб,мн. ч. хъаттикIибир,нет,кража,существительное
100,хъаттрухаф,мн. ч. хъаттрухаттар,нет,сплетник,существительное
101,хъаттрухубар,нет,нет,склока,существительное
102,хъаягъа,нет,нет,послезавтра,наречие
103,хъвагIанай,мн. ч. хъвагIанаяр,нет,ворона,существительное
104,хъвагIанин чарккв,мн. ч. хъвагIанин чаркквар,нет,воронёнок,существительное
105,хъветт,мн. ч. хъветтар,нет,ворона,существительное
106,хъветталанф,нет,нет,вороний,прилагательное
107,хъветтун чарккв,мн. ч. хъветтун чаркквар,нет,воронёнок,существительное
108,хъвехь,мн. ч. хъвехьар,нет,нос,существительное
109,хъел,нет,нет,злоба; злость; гнев; раздражительность; обида,существительное
110,хъел адис,нет,нет,злиться,глагол
111,хъел акъас,нет,нет,обидеться; злиться,глагол
112,хъел акъуф,нет,нет,обиженный,прилагательное
113,хъел алатас,нет,нет,месть,существительное
114,хъел кей,нет,нет,сердито; злобно; яростно,наречие
115,хъел кеф,нет,нет,сердитый; гнёвный,прилагательное
116,хъерар,нет,нет,седло,существительное
117,хъехь,нет,да,желтизна,существительное
118,хъехьеф,нет,да,жёлтый,прилагательное
119,хъидананф,нет,нет,весенний,прилагательное
120,хъинитI,мн. ч. хъинитIар,нет,полочка,существительное
121,хъитIанас,нет,нет,сочинять,глагол
122,хъитIас,нет,нет,сочинять,глагол
123,хъитIуна ттур,мн. ч. хъитIуна ттурар,нет,кличка,существительное
124,хъугъас,нет,нет,верить,глагол
125,хъудугъаф,нет,нет,неверный,прилагательное
126,хъудухьъуьттар,нет,нет,равный,прилагательное
127,хъудухьъуьф1,нет,нет,подходящий,прилагательное
128,хъудухьъуьф2,нет,нет,полезный,прилагательное
129,хъузийинас,нет,нет,толкать,глагол
130,хъуруф алгъархьас,нет,нет,головокружение,существительное
131,хъуруцуна,нет,нет,кругом,наречие
132,хъутт дуьхьин,нет,нет,неудобно,наречие
133,хъуттрихьел,мн. ч. хъуттрихьелар,нет,рогатка,существительное
134,хъуттурфанас,нет,нет,смотреть,глагол
135,хъуттурфуб,мн. ч. хъуттурфубар,нет,забота,существительное
136,хъух1,мн. ч. хъухар,нет,хрип,существительное
137,хъух2,мн. ч. хъухар,нет,храп,существительное
138,хъух йирхIас,нет,нет,храпеть,глагол
139,хъучавереф петтихь,нет,нет,доверчивость,существительное
140,хъучадис,мн. ч. хъучадибар,нет,желание,существительное
141,хъучатуб,мн. ч. хъучатубар,нет,соблазн,существительное
142,хъучикас,нет,нет,заставить,глагол
143,хъучма,мн. ч. хъучмабур,нет,товарищ; приятель,существительное
144,хъучмавел,мн. ч. хъучмавелар,нет,товарищество,существительное
145,хъуш-хъущди,нет,нет,шёпотом,наречие
146,хъуьлаас,нет,нет,назло,наречие
147,хъуьлаастти,нет,нет,назло,наречие
148,хъуьнтIар,нет,нет,сопли,существительное
149,хъуьнтIич,мн. ч. хъуьнтIичар,нет,сопляк,существительное
150,хъуьссу1,мн. ч. хъуьссубур,нет,лицо,существительное
151,хъуьссу2,мн. ч. хъуьссубур,нет,щека,существительное
152,хъуьхъ,мн. ч. хъуьхъар,да,нос,существительное
153,хъуьхъар фацубар,нет,нет,насморк,существительное
154,хъуьхъевел,нет,нет,желтизна,существительное
155,хъуьхъеф,нет,нет,жёлтый,прилагательное
156,хъуьхье ччам,нет,нет,масло,существительное
157,хъял алгъадиб,нет,нет,ярость,существительное
158,хьам,нет,нет,нёбо,существительное
159,хьар1,мн. ч. хьарар,нет,очаг; камин,существительное
160,хьар2,мн. ч. хьарар,нет,пекарня,существительное
161,хьас,нет,нет,стать,глагол
162,хьас,нет,нет,единение,существительное
163,хьас ккея,нет,нет,случиться,глагол
164,хьас лидеф,нет,нет,будущий,прилагательное
165,хьеб,нет,нет,быть,глагол
166,хьебайи,нет,нет,низко,наречие
167,хьед,мн. ч. хьеттар,нет,вода,существительное
168,хьед а къуй,мн. ч. хьед а къувар,нет,колодец,существительное
169,хьед аларуцавус,мн. ч. хьед аларуцавусар,нет,водоворот,существительное
170,хьей,мн. ч. хьейар,нет,шерсть,существительное
171,хьел,мн. ч. хьелар,нет,сноп,существительное
172,хьибуверш,нет,нет,триста,числительное
173,хьибуд,нет,нет,три,числительное
174,хьибу къад,нет,нет,шестьдесят,числительное
175,хьибцIур,нет,нет,тридцать,числительное
176,хьид,мн. ч. хьидар,нет,весна,существительное
177,хьидана,нет,нет,весной,наречие
178,хьиджар баб,мн. ч. хьиджар бабар,нет,свекровь; тёща,существительное
179,хьиджар дад,мн. ч. хьиджар дадар,нет,свёкр; тесть,существительное
180,хьиджар чи,мн. ч. хьиджар чияр,нет,свояченица,существительное
181,хьиджар чу,мн. ч. хьиджар чуппар,нет,свояк; шурин,существительное
182,хьил,мн. ч. хьилар,нет,след,существительное
183,хьилаба,нет,нет,пешком,наречие
184,хьилаба веф,мн. ч. хьилаба веттар,нет,пешеход,существительное
185,хьилаванф,мн. ч. хьилаванфар,да,пешеход,существительное
186,хьиличIан,мн. ч. хьиличIанар,да,ложь; обман,существительное
187,хьиличIанчи,мн. ч. хьиличIанчибур,да,врун; обманщик,существительное
188,хьимуд,нет,нет,сколько,наречие
189,хьын,нет,нет,мы,местоимение
190,хьыр,мн. ч. хьырар,нет,женщина; жена; супруга,существительное
191,хьыран чи,мн. ч. хьыран чияр,нет,свояченица,существительное
192,хьыран чу,мн. ч. хьыран чуппар,нет,шурин,существительное
193,хьыриг,мн. ч. хьыригар,нет,веник,существительное
194,хьу кар,мн. ч. хьу курар,нет,событие; факт,существительное
195,хьу кар мусчин,нет,нет,случай,существительное
196,хьуб кканхьас IуьтIанас,мн. ч. хьуб кканхьубар IуьтIанасар,нет,желание,существительное
197,хьурай,нет,нет,хорошо,наречие
198,хьухьал,мн. ч. хьухьалар,нет,варежка; рукавица; перчатка,существительное
199,хIа,нет,нет,большой,прилагательное
200,хIа агъ,мн. ч. хIа агъар,нет,бедро,существительное
201,хIа акьас,нет,нет,вырастить,глагол
202,хIа гаф,мн. ч. хIа гафар,нет,похвала,существительное
203,хIа гаф акьуб,нет,нет,примерность,существительное
204,хIа гафарар акьуб,нет,нет,хвастливость,существительное
205,хIа гаф аркьаф,мн. ч. хIа гафарар аркьаттар,нет,хвастун,существительное
206,хIа гаф аркьагилди,нет,нет,примерно; образцово,наречие
207,хIа гафарчи,мн. ч. хIа гафарчибур,нет,хвастун,существительное
208,хIа датта,мн. ч. хIа даттабур,нет,юбилей,существительное
209,хIа йиркIв хьаф,нет,нет,великодушный,прилагательное
210,хIа хIуьл,мн. ч. хIа хIуьлар,нет,океан,существительное
211,хIа Iул,мн. ч. хIа Iулар,нет,крыса,существительное
212,хIабаб,мн. ч. хIабабар,нет,бабушка,существительное
213,хIав1,мн. ч. хIавар,нет,воротник,существительное
214,хIав2,нет,нет,терпение; упорство,существительное
215,хIав ккидахьеб,нет,нет,брезгливость,существительное
216,хIавахь,мн. ч. хIавахьар,нет,вечер,существительное
217,хIавахьи,нет,нет,вечером,наречие
218,хIавел1,мн. ч. хIавелар,нет,величина,существительное
219,хIавел2,мн. ч. хIавелар,нет,власть; главарь,существительное
220,хIад,мн. ч. хIадар,да,звезда,существительное
221,хIадад,мн. ч. хIададар,нет,дедушка,существительное
222,хIажатхан,мн. ч. хIажатханар,да,туалет,существительное
223,хIайван,мн. ч. хIайванар,нет,животное,существительное
224,хIайи,нет,нет,крупно,наречие
225,хIайифвел хъудаф,нет,нет,безжалостный,прилагательное
226,хIакьвел,нет,нет,натуральность,существительное
227,хIакьди,нет,нет,натурально,наречие
228,хIакьди,нет,нет,точнее,частица
229,хIакьф,нет,нет,натуральный,прилагательное
230,хIала шуй,мн. ч. хIала шувар,нет,гость,существительное
231,хIалатут,мн. ч. хIалатутар,нет,лён,существительное
232,хIамам,мн. ч. хIамамар,нет,баня,существительное
233,хIамга,нет,нет,хрусталь,существительное
234,хIан,мн. ч. хIанар,нет,лук,существительное
235,хIапахьан,мн. ч. хIапахьанар,да,чабан,существительное
236,хIаракат,нет,нет,спешка,существительное
237,хIарфар,нет,нет,азбука,существительное
238,хIархIан,мн. ч. хIархIанар,нет,кольчуга,существительное
239,хIаттин мукъ,мн. ч. хIаттин мукьар,нет,трон,существительное
240,хIач,мн. ч. хIачар,нет,яблоко,существительное
241,хIачи,мн. ч. хIачияр,нет,троюродный,прилагательное
242,хIачу,мн. ч. хIачуппар,нет,троюродный,прилагательное
243,хIаш,мн. ч. хIашар,нет,туалет,существительное
244,хIаягь,мн. ч. хIаягьар,нет,праздник,существительное
245,хIаягьанф,нет,нет,праздничный,прилагательное
246,хIаят,мн. ч. хIаятар,нет,двор,существительное
247,хIвал хьас,нет,нет,вспомнить,глагол
248,хIебз,мн. ч. хIебзар,нет,бассейн,существительное
249,хIеджибугьда,нет,нет,кукуруза,существительное
250,хIезур акьас,нет,нет,готовить,глагол
251,хIезурвел,нет,нет,подготовленность; готовность,существительное
252,хIезурф,нет,нет,готовый; согласованный,прилагательное
253,хIезурхьуб,нет,нет,подготовленность,существительное
254,хIейван,мн. ч. хIейванар,нет,конь; лошадь,существительное
255,хIейифвел,нет,нет,жалость; сожаление,существительное
256,хIейран акьас,нет,нет,изумить; поразить,глагол
257,хIейранвел,мн. ч. хIейранвелар,нет,удивление; изумление; восхищение; восторг,существительное
258,хIейранди,нет,нет,удивлённо; изумлённо,наречие
259,хIейранф,нет,нет,удивлённый; изумлённый; восхищённый; восторженный,прилагательное
260,хIекандаз,мн. ч. хIекандазар,да,совок,существительное
261,хIекаят,мн. ч. хIекаятар,да,сказка,существительное
262,хIекаятчи,мн. ч. хIекаятчибур,да,сказочник,существительное
263,хIеким,мн. ч. хIекимар,нет,начальник,существительное
264,хIекъи,мн. ч. хIекъибур,нет,плата; зарплата,существительное
265,хIекъисагь,нет,нет,честный; правдивый,прилагательное
266,хIекъисагьвел,нет,нет,честность; надёжность,существительное
267,хIекъисузди,нет,нет,бесплатно; безвозмездно,наречие
268,хIекь,нет,нет,правда,существительное
269,хIекь кар,нет,нет,истина,существительное
270,хIекьвел,нет,нет,честность; правдивость; истинность; подлинность,существительное
271,хIекьдан,мн. ч. хIекьданар,нет,реальность,существительное
272,хIекьданф,мн. ч. хIекьданттар,нет,натуралист,существительное
273,хIекьди1,нет,нет,честно; правдиво; истинно; подлинно; реально,наречие
274,хIекьди2,нет,нет,разве,наречие
275,хIекьди3,нет,нет,даже,частица
276,хIекьдинф,нет,нет,честный; правдивый; истинный,прилагательное
277,хIекьикьат,нет,да,реальность,существительное
278,хIекьикьатти,нет,да,реально,наречие
279,хIекьикьи1,нет,да,подлинный,прилагательное
280,хIекьикьи2,нет,да,постоянный,прилагательное
281,хIекьикьивел,нет,да,подлинность,существительное
282,хIекьикьиди,нет,да,подлинно,наречие
283,хIекьф,нет,нет,правдивый; истинный,прилагательное
284,хIел1,мн. ч. хIелар,нет,состояние; настроение,существительное
285,хIел2,мн. ч. хIелар,нет,скалка,существительное
286,хIелакди,нет,да,спешно,наречие
287,хIелва,нет,нет,халва,существительное
288,хIелсиз,нет,да,хилый,прилагательное
289,хIел-хIел аркьай,нет,нет,изрядно,наречие
290,хIел-хIелдинф,нет,нет,изрядный,прилагательное
291,хIемам,мн. ч. хIемамар,нет,баня,существительное
292,хIемрамвел,мн. ч. хIемрамвелар,нет,запретность,существительное
293,хIемчи,нет,да,чиханье; чих,существительное
294,хIеракат1,нет,нет,старание; усердие,существительное
295,хIеракат2,нет,нет,скорость,существительное
296,хIеракатлу,нет,да,быстрый; скорый; деятельный; активный,прилагательное
297,хIерф,мн. ч. хIерфар,нет,буква,существительное
298,хIесул,нет,нет,случиться,глагол
299,хIефтта,мн. ч. хIефттабур,нет,неделя,существительное
300,хIеялу,нет,нет,скромный,прилагательное
301,хIикал,мн. ч. хIикалар,нет,амулет; талисман,существительное
302,хIикат,мн. ч. хIикатар,нет,сказка,существительное
303,хIикатчи,мн. ч. хIикатчибур,нет,сказочник,существительное
304,хIикаят,мн. ч. хIикаятар,нет,сказка,существительное
305,хIила акьун,мн. ч. хIила акьубар,нет,натяжка,существительное
306,хIируз,нет,нет,легковесный,прилагательное
307,хIисаб,мн. ч. хIисабар,нет,счёт,существительное
308,хIисаб акьас,нет,нет,считать,глагол
309,хIисаб акьуб,нет,нет,учёт,существительное
310,хIисаб аркьаф,мн. ч. хIисаб аркьаттар,нет,счетовод,существительное
311,хIисаб ккедаф,нет,нет,униженный,прилагательное
312,хIисабвел,нет,нет,почтительность,существительное
313,хIиянат,нет,нет,вероломный,прилагательное
314,хIянаткарди,нет,нет,вероломно,наречие
315,хIу,мн. ч. хIуппур,нет,заклинание; клятва,существительное
316,хIуб,мн. ч. хIубар,нет,овца; баранина,существительное
317,хIуджум,мн. ч. хIуджумар,нет,атака,существительное
318,хIук,мн. ч. хIукар,нет,плесень,существительное
319,хIукум,мн. ч. хIукумар,нет,сила; власть,существительное
320,хIулдан,нет,нет,сталь,существительное
321,хIуни,мн. ч. хIунибур,нет,корова,существительное
322,хIунин хIав,мн. ч. хIунин хIавар,нет,вымя,существительное
323,хIуппан якк,нет,нет,баранина,существительное
324,хIуппар,нет,нет,скотина,существительное
325,хIур,мн. ч. хIурар,нет,село,существительное
326,хIур але юкI,нет,нет,мать-и-мачеха,существительное
327,хIурагIан,мн. ч. хIурагIанар,нет,озорник; гуляка,существительное
328,хIурин инсанар,нет,нет,население,существительное
329,хIурин шуй,мн. ч. хIурин шувар,нет,односельчанин,существительное
330,хIуринф,нет,нет,сельский,прилагательное
331,хIуррият,нет,нет,независимость,существительное
332,хIуч,мн. ч. хIучар,нет,волк,существительное
333,хIучан чарккв,мн. ч. хIучан чаркквар,нет,волчонок,существительное
334,хIучанф,нет,нет,волчий,прилагательное
335,хIуяг,мн. ч. хIуягар,нет,котёл; кастрюля,существительное
336,хIуьджат,мн. ч. хIуьджатар,нет,спор; перепалка; соперничество,существительное
337,хIуьджатар акьас,нет,нет,конфликтовать,глагол
338,хIуьджум,мн. ч. хIуьджумар,нет,нападение; налёт; штурм,существительное
339,хIуькумат,мн. ч. хIуькуматар,нет,государство; страна,существительное
340,хIуькуматин гIедатар,нет,нет,закон,существительное
341,хIуькуматин хIаф,мн. ч. хIуькуматин хIафар,нет,правитель,существительное
342,хIуькумдар,мн. ч. хIуькумдарар,нет,правитель,существительное
343,хIуьл,мн. ч. хIуьлар,нет,море,существительное
344,хIуьлмат,нет,нет,почёт,существительное
345,хIуьлмат акьас,нет,нет,вознаграждение,существительное
346,хIуьлмат кеф,нет,нет,вежливый; уважительный,прилагательное
347,хIуьлматвел,нет,нет,почтительность,существительное
348,хIуьлматлу,нет,нет,уважительный,прилагательное
349,хIуьлматти аф,нет,нет,почтительный,прилагательное
350,хIуьппахъан,мн. ч. хIуьппахъанар,нет,чабан,существительное
351,хIуьрчал,мн. ч. хIуьрчалар,нет,суслик,существительное
352,хIуьтте муул,мн. ч. хIуьтте муулар,нет,клюв,существительное
353,хIуьттез,мн. ч. хIуьттезар,нет,ножницы,существительное
354,хIуьттевел,мн. ч. хIуьттевелар,нет,острота,существительное
355,хIуьттеф,нет,нет,острый,прилагательное
356,хIуьтIри,мн. ч. хIуьтIрибур,нет,пиявка,существительное
357,хIуьчI,мн. ч. хIуьчIар,нет,плесень,существительное
358,хIуьяг,мн. ч. хIуьягар,нет,котёл; кастрюля,существительное
359,хIякьданф,нет,да,очевидный; явный; ясный,прилагательное
360,хIякьф,нет,нет,истинность,существительное
361,хIякьф,нет,нет,подлинный,прилагательное
362,цал,мн. ч. цалар,нет,стена,существительное
363,цацанф,нет,нет,прошлогодний,прилагательное
364,целлофан,мн. ч. целлофанар,нет,целлофан,существительное
365,целлюлоза,мн. ч. целлюлозабур,нет,целлюлоза,существительное
366,цемент,мн. ч. цементар,нет,цемент,существительное
367,центр,мн. ч. центрар,нет,центр,существительное
368,цивилизаци,мн. ч. цивилизацибур,нет,цивилизация,существительное
369,цилиндр,мн. ч. цилиндрар,нет,цилиндр,существительное
370,цинга,нет,нет,цинга,существительное
371,цинк,нет,нет,цинк,существительное
372,цирк,мн. ч. циркар,нет,цирк,существительное
373,циркул,мн. ч. циркулар,нет,циркуль,существительное
374,цистерна,мн. ч. цистернабур,нет,цистерна,существительное
375,цитата,мн. ч. цитатабур,нет,цитата,существительное
376,цитрус,мн. ч. цитрусар,нет,цитрус,существительное
377,циферблат,мн. ч. циферблатар,нет,циферблат,существительное
378,цифра,мн. ч. цифрабур,нет,цифра,существительное
379,цул,мн. ч. цулар,нет,осень,существительное
380,цулана,нет,нет,осенью,наречие
381,цIа,мн. ч. цIабур,нет,огонь; костёр,существительное
382,цIа ичаф,мн. ч. цIа ичафар,нет,огнемёт,существительное
383,цIа кертаф,мн. ч. цIа кертафар,нет,огнетушитель,существительное
384,цIаб,мн. ч. цIабар,нет,лист,существительное
385,цIабар,нет,нет,листва,существительное
386,цIабрахъил,мн. ч. цIабрахъилар,нет,бабочка,существительное
387,цIагъун,мн. ч. цIагъунар,нет,бревно; столб,существительное
388,цIадевел,нет,нет,прозрачность,существительное
389,цIадеф,нет,нет,прозрачный,прилагательное
390,цIади,нет,нет,прозрачно,наречие
391,цIае акьас,нет,нет,обновить; починить,глагол
392,цIаеф,нет,нет,свежий,прилагательное
393,цIайила,нет,да,снова; заново,наречие
394,цIакувел,мн. ч. цIакувелар,нет,кривизна,существительное
395,цIакун,нет,нет,криво,наречие
396,цIакIин,мн. ч. цIакIинар,нет,свадьба,существительное
397,цIамцI,мн. ч. цIамцIар,нет,глина,существительное
398,цIамцIдинф,нет,нет,глиняный,прилагательное
399,цIантук,мн. ч. цIантукар,нет,мак,существительное
400,цIафул,мн. ч. цIафулар,нет,очаг; камин,существительное
401,цIе хал,мн. ч. цIе халар,нет,гостиная,существительное
402,цIегь,мн. ч. цIегьер,нет,коза,существительное
403,цIегIуьфуд,нет,нет,пятнадцать,числительное
404,цIее акьас,нет,нет,обновить,глагол
405,цIеевел,нет,нет,новизна,существительное
406,цIеерид,нет,нет,семнадцать,числительное
407,цIеерхъид,нет,нет,шестнадцать,числительное
408,цIеерчIуд,нет,нет,девятнадцать,числительное
409,цIееф,нет,нет,новый,прилагательное
410,цIекIиластти,нет,нет,заново; снова,наречие
411,цIекIиластти акьас,нет,нет,возобновить,глагол
412,цIелп,мн. ч. цIелпар,нет,зарница,существительное
413,цIемуяд,нет,нет,восемнадцать,числительное
414,цIесад,нет,нет,одиннадцать,числительное
415,цIеф акьас,нет,нет,создать,глагол
416,цIехьибуд,нет,нет,тринадцать,числительное
417,цIеIуд,нет,нет,двенадцать,числительное
418,цIеякъуд,нет,нет,четырнадцать,числительное
419,цибицибай,мн. ч. цибицибаяр,нет,цыплёнок,существительное
420,цив,нет,нет,писк,существительное
421,цимилар,нет,нет,бахрома,существительное
422,ципп-ципп,мн. ч. ципп-циппар,нет,ресница,существительное
423,цици1,мн. ч. цициар,нет,сверчок,существительное
424,цици2,мн. ч. цициар,нет,кузнечик,существительное
425,цугъреф,нет,нет,постный,прилагательное
426,цунтIа,нет,нет,хитрый,прилагательное
427,цуппе,нет,нет,сильно,наречие
428,цуппевел,нет,нет,надёжность; крепость,существительное
429,цуппи,нет,нет,крепко,наречие
430,цурарин хьас,нет,нет,заболеть,глагол
431,цурахай,мн. ч. цIурахавур,да,прозвище,существительное
432,цIурцIул,мн. ч. цIурцIулар,нет,куница,существительное
433,цIуьппе,нет,нет,прочно,наречие
434,цIуьппевел,нет,нет,прочность,существительное
435,цIуьппеф,нет,нет,крепкий; прочный,прилагательное
436,цIуьппеф,нет,нет,упруго,наречие
437,цIуьппи,нет,нет,крепко,наречие
438,цIуьре акьас,нет,нет,износить,глагол
439,цIуьреф,нет,нет,старый; ветхий,прилагательное
440,чабхунчи,мн. ч. чабхунчибур,нет,захватчик,существительное
441,чавуш,мн. ч. чавушар,нет,сторож; охрана,существительное
442,чагъигругъз,нет,нет,дурноглазый,прилагательное
443,чагъундур,мн. ч. чагъундурар,нет,бурак,существительное
444,чагIпелахъди,нет,нет,налево,наречие
445,чагIпул,мн. ч. чагIпулар,нет,левша,существительное
446,чагIпул,нет,нет,левый; левосторонний,прилагательное
447,чагIпулахъди,нет,нет,налево,наречие
448,чадира,мн. ч. чадирабур,да,покрывало,существительное
449,чадур,мн. ч. чадурар,нет,палатка,существительное
450,чадура,мн. ч. чадурабур,нет,шатёр,существительное
451,чайгъун,мн. ч. чайгъунар,нет,буран,существительное
452,чакма,мн. ч. чакмабур,нет,сапог,существительное
453,чакмайинф,нет,нет,сапожный,прилагательное
454,чакмачи,мн. ч. чакмачибур,нет,сапожник,существительное
455,чакъал,мн. ч. чакъалар,нет,шакал,существительное
456,чакъул,нет,нет,пакля,существительное
457,чал1,мн. ч. чалар,нет,паутина,существительное
458,чал2,мн. ч. чалар,нет,цепочка,существительное
459,чали,мн. ч. чалибур,нет,ограда,существительное
460,чалишмишвел,нет,нет,усердие; энергичность,существительное
461,чалишмишди,нет,нет,энергично,наречие
462,чамадан,мн. ч. чамаданар,нет,чемодан,существительное
463,чанг1,мн. ч. чангар,нет,горсть,существительное
464,чанг2,мн. ч. чангар,нет,ладонь,существительное
465,чангур,мн. ч. чангурар,нет,балалайка,существительное
466,чанта,мн. ч. чантабур,нет,мешок; сумка,существительное
467,чап акъас,нет,нет,печатать; напечатать,глагол
468,чапар,мн. ч. чапарар,нет,ограда; забор,существительное
469,чапвел,мн. ч. чапвелар,нет,кривизна,существительное
470,чапди,нет,нет,криво,наречие
471,чапра,нет,нет,косой,прилагательное
472,чапрасвел,нет,нет,косоглазие,существительное
473,чапрахвел,нет,нет,косоглазие,существительное
474,чапхана,мн. ч. чапханабур,нет,типография,существительное
475,чапп,мн. ч. чаппар,нет,тряпка,существительное
476,чапп ачата лекар,нет,нет,шлёпанцы,существительное
477,чаппар,нет,нет,пелёнки,существительное
478,чар,нет,нет,всходы,существительное
479,чара1,мн. ч. чарабур,нет,возможность; уловка,существительное
480,чара2,мн. ч. чарабур,нет,опора,существительное
481,чара адаф,нет,нет,безвыходный,прилагательное
482,чарава,нет,нет,скотина,существительное
483,чарасуз,нет,нет,безвыходный,прилагательное
484,чардак,мн. ч. чардакар,нет,чердак,существительное
485,чардах,мн. ч. чардахар,нет,шалаш,существительное
486,чаркк,мн. ч. чарккар,нет,детёныш,существительное
487,чарккв,мн. ч. чаркквар,нет,птенец,существительное
488,чарпа,мн. ч. чарпабур,нет,лежанка; топчан,существительное
489,чарх,мн. ч. чархар,нет,колесо; арка,существительное
490,чархачи,мн. ч. чархачибур,нет,заводила,существительное
491,чарч,мн. ч. чарчар,нет,сетка,существительное
492,чатин,нет,нет,неудобный,прилагательное
493,чахир,мн. ч. чахирар,нет,вино,существительное
494,чахмах,мн. ч. чахмахар,нет,кремень; огниво,существительное
495,чахIппил,мн. ч. чахIппилар,нет,левша,существительное
496,чахIппил,нет,нет,левый,прилагательное
497,чахIппил багв,нет,нет,левосторонний,прилагательное
498,чахIппилахъди,нет,нет,налево,наречие
499,чашкка,мн. ч. чашккабур,нет,чашка,существительное
500,чве,нет,нет,ваш,местоимение
501,чвеф,нет,нет,ваш,местоимение
502,чевеккер,нет,да,чувяки,существительное
503,чей,мн. ч. чеяр,нет,чай,существительное
504,чейдан,мн. ч. чейданар,нет,чайник,существительное
505,чейхана,мн. ч. чейханабур,нет,чайхана,существительное
506,челег,мн. ч. челегар,нет,бочка,существительное
507,челегчи,мн. ч. челегчибур,нет,бондарь,существительное
508,чемпион,мн. ч. чемпионар,нет,чемпион,существительное
509,чемпионат,мн. ч. чемпионатар,нет,чемпионат,существительное
510,черепица,мн. ч. черепицабур,нет,черепица,существительное
511,черновик,мн. ч. черновикар,нет,черновик,существительное
512,чертёж,мн. ч. чертёжар,нет,чертёж,существительное
513,чертёжник,мн. ч. чертёжникар,нет,чертёжник,существительное
514,чиновник,мн. ч. чиновникар,нет,чиновник,существительное
515,чиреф,нет,нет,рыжий,прилагательное
516,чиркин акьас,нет,нет,запачкать,глагол
517,чиркинвелар,нет,нет,нечистоты,существительное
518,чиркинф,нет,нет,нечистый; грязный,прилагательное
519,чирнил,нет,нет,чернила,существительное
520,чиринлинца,мн. ч. чиринлинцабур,нет,чернильница,существительное
521,чирIеф,нет,нет,свежий,прилагательное
522,чистовик,мн. ч. чистовикар,нет,чистовик,существительное
523,чистописани,мн. ч. чистописанибур,нет,чистописание,существительное
524,читавут,мн. ч. читавутар,нет,счетовод,существительное
525,читанвел,мн. ч. читинвелар,нет,сложность; затруднение; проблема,существительное
526,читинвелар агвас,нет,нет,претерпеть,глагол
527,читинвеларикк ккихас,нет,нет,претерпеть,глагол
528,читинди,нет,нет,трудно; тяжело,наречие
529,читинф,нет,нет,неудобный; трудный,прилагательное
530,читинф даф,нет,нет,нетрудный,прилагательное
531,читт,мн. ч. читтар,нет,ситец,существительное
532,читтинф,нет,нет,ситцевый,прилагательное
533,чишна,мн. ч. чишнабур,нет,образец; макет; узор,существительное
534,чишналувел,нет,да,примерность; образцовость,существительное
535,чишналуди,нет,да,примерно; образцово,наречие
536,чишначи,мн. ч. чишначибур,нет,передовик,существительное
537,чу,мн. ч. чубур,нет,брат,существительное
538,чувал,мн. ч. чувалар,нет,мешок,существительное
539,чувун,мн. ч. чувунар,нет,чугун,существительное
540,чугурт,мн. ч. чугуртар,да,подмастерье,существительное
541,чугь сагъул,нет,нет,спасибо,частица
542,чугь сагъул адавел,нет,нет,неблагодарность,существительное
543,чугь сагъул адай,нет,нет,неблагодарно,наречие
544,чугь сагъул адаф,нет,нет,неблагодарный,прилагательное
545,чукьвар,мн. ч. чукьварар,нет,телега; арба,существительное
546,чул1,мн. ч. чулар,нет,равнина; степь; пустыня; долина; пастбище,существительное
547,чул2,нет,нет,синева,существительное
548,чулагъ,мн. ч. чулагъар,нет,калека,существительное
549,чулагъвел,мн. ч. чулагъвелар,нет,сухорукость,существительное
550,чуллевел,нет,нет,синева,существительное
551,чуллеф,нет,нет,синий,прилагательное
552,чума,нет,нет,чума,существительное
553,чун,нет,нет,вы,местоимение
554,чунк1,мн. ч. чункIер,да,стрекоза,существительное
555,чупур,нет,нет,рябой,прилагательное
556,чуха,мн. ч. чухабур,нет,недотепа,существительное
557,чухай,мн. ч. чухавур,нет,черкеска,существительное
558,чухра,мн. ч. чухрабур,нет,прялка,существительное
559,чхур,мн. ч. чухурар,да,овраг,существительное
560,чуькI1,мн. ч. чуькIер,нет,кузнечик,существительное
561,чуькI2,мн. ч. чуькIер,нет,стрекоза,существительное
562,чуьллевел,нет,нет,голубизна,существительное
563,чуьруьтмиш хьас,нет,нет,пропасть,глагол
564,чам,нет,нет,масло,существительное
565,ччеI,мн. ч. ччеIар,нет,нитка,существительное
566,чипччай,мн. ч. чпиччаяр,нет,старшая сестра; тётя,существительное
567,чууччу,мн. ч. ччуччар,да,старший брат,существительное
568,чIагъанчи,мн. ч. чIагъанчибур,нет,баянист,существительное
569,чIал1,мн. ч. чIалар,нет,сорняк,существительное
570,чIал2,мн. ч. чIалар,нет,слово; речь; язык,существительное
571,чIал акьас,нет,нет,полоть; прополоть,глагол
572,чIал гьучавереф,нет,нет,доступность,существительное
573,чIал дапуб,мн. ч. чIал дапубар,нет,поблажка,существительное
574,чIал кикIас,нет,нет,безупречно,наречие
575,чIал кикIас девеф,нет,нет,безупречный,прилагательное
576,чIалар пас,мн. ч. чIалар пасар,нет,перепалка,существительное
577,чIалар пас,нет,нет,обидеть; оскорбить,глагол
578,чIалар хъухьаф,мн. ч. чIалар хъухьафар,нет,заика,существительное
579,чIалар-гъургъубар,нет,нет,мнение,существительное
580,чIам гIаф,нет,нет,жирный,прилагательное
581,чIапIатIар,нет,нет,шлёпанцы,существительное
582,чIапIлухI,нет,да,голый,прилагательное
583,чIар1,мн. ч. чIарар,нет,волос,существительное
584,чIар2,мн. ч. чIарар,нет,луг,существительное
585,чIар алавес,нет,нет,линька,существительное
586,чIаранпай,мн. ч. чIаранпаяр,нет,сороконожка,существительное
587,чIекI,мн. ч. чIекIер,нет,рыба,существительное
588,чIиб,мн. ч. чIибар,нет,пядь,существительное
589,чIивар,мн. ч. чIиварар,нет,шиповник,существительное
590,чIигъан,мн. ч. чIигъанар,нет,гармонь,существительное
591,чIигъан йирхIаф,мн. ч. чIигъан йирхIаттар,нет,баянист; гармонист,существительное
592,чIигъанчи,мн. ч. чIигъанчибур,нет,баянист; гармонист,существительное
593,чIигIв,мн. ч. чIигIвар,да,пядь,существительное
594,чIид,мн. ч. чIидар,нет,блоха,существительное
595,чIид,мн. ч. чIидар,нет,гнида,существительное
596,чIил1,мн. ч. чIилар,нет,балка; брус,существительное
597,чIил2,мн. ч. чIилар,нет,ремень; пояс,существительное
598,чIилчIем,мн. ч. чIилчIемар,нет,перепел,существительное
599,чIилIан,мн. ч. чIилIанар,нет,мешок; сумка,существительное
600,чIимчIир,мн. ч. чIимчIирар,нет,чиж,существительное
601,чIиникI,мн. ч. чIиникIер,нет,серп,существительное
602,чIир,мн. ч. чIирар,да,пастбище; сенокос,существительное
603,чIир акьас,нет,нет,портить; испортить,глагол
604,чIир хьас,нет,нет,испортиться; гнить; сгнить,глагол
605,чIир хьеф,мн. ч. чIир хьеттар,нет,залежь,существительное
606,чIир хьуб,нет,нет,испорченность,существительное
607,чIирвел,нет,нет,порча,существительное
608,чIиргъил,мн. ч. чIиргъилар,нет,щепка,существительное
609,чIире бакъал,мн. ч. чIиребакъалар,нет,скряга; скупец; жадюга; крохобор,существительное
610,чIире бакъал,нет,нет,жадный,прилагательное
611,чIире рекъуь аф,нет,нет,беспутный,прилагательное
612,чIире хьуф,нет,нет,заброшенный,прилагательное
613,чIиревел,нет,нет,жадность; мелочность,существительное
614,чIирин гитан,мн. ч. чIирин гитанар,нет,рысь,существительное
615,чIири-чIири,нет,нет,жадно; алчно; мелочно,наречие
616,чIирхьуф,нет,нет,испорченный,прилагательное
617,чIирхI,мн. ч. чIирхIар,нет,соринка,существительное
618,чIирхIар,нет,нет,мусор; сор,существительное
619,чIирхIар алгъарцIаф,мн. ч. чIирхIар алгъарцIаттар,нет,совок,существительное
620,чIирхIе ннъ,нет,нет,вонь,существительное
621,чIирхIеф1,нет,нет,некрасивый,прилагательное
622,чIирхIеф2,нет,нет,никчёмный,прилагательное
623,чIирхIи,нет,нет,грязно; нечисто,наречие
624,чIичI,мн. ч. чIичIар,нет,ворсинка; мех,существительное
625,чIичIакI,мн. ч. чIичIакIар,нет,лук,существительное
626,чIичIинф,нет,нет,ворсистый,прилагательное
627,чIиI,мн. ч. чIиIар,нет,верёвка,существительное
628,чIукь,нет,нет,немного,наречие
629,чIукь IутIанас,мн. ч. чIукь IутIубар,нет,диета,существительное
630,чIукьда,нет,нет,немало,наречие
631,чIукьдаф,нет,нет,немалый,прилагательное
632,чIукI,мн. ч. чIукIар,нет,долька,существительное
633,чIулучI,мн. ч. чIулучIар,нет,спица,существительное
634,чIургъас,нет,нет,порвать,глагол
635,чIуркъас,нет,нет,жевать,глагол
636,чIурух,мн. ч. чIурухар,нет,залежь,существительное
0,шаб пас,нет,нет,приглашать,глагол
1,шабалут,мн. ч. шабалутар,нет,каштан,существительное
2,шавлавел,нет,нет,усталость,существительное
3,шагь,мн. ч. шагьар,нет,шах,существительное
4,шагьид,мн. ч. шагьидар,нет,свидетель,существительное
5,шагьра,нет,нет,широкий,прилагательное
6,шагьур,мн. ч. шагьурар,нет,город,существительное
7,шадвел,мн. ч. шадвелар,нет,радость,существительное
8,шадвеларинф,нет,нет,торжественный,прилагательное
9,шадлукъ,мн. ч. шадлукъар,да,веселье; радость,существительное
10,шадтти,нет,нет,весело; радостно; оживлённо; бодро,наречие
11,шаир,мн. ч. шаирар,нет,стихотворение,существительное
12,шак,мн. ч. шакар,нет,подозрение,существительное
13,шаккар,мн. ч. шаккарар,нет,сахар,существительное
14,шала,мн. ч. шалабур,нет,ноша; бремя,существительное
15,шалва ккетуб,нет,нет,отдых,существительное
16,шалвавел,мн. ч. шалвавелар,нет,усталость,существительное
17,шалвавел ккета,нет,нет,отдохнуть,глагол
18,шалвар,нет,нет,брюки,существительное
19,шалман,мн. ч. шалманар,нет,столб,существительное
20,шам,мн. ч. шамар,нет,свеча,существительное
21,шар,мн. ч. шарар,нет,глист,существительное
22,шараб,мн. ч. шарабар,нет,напиток,существительное
23,шартI,мн. ч. шартIар,нет,условие,существительное
24,шартI алихъуб,нет,нет,ультиматум,существительное
25,шат хьас,нет,нет,развеселиться,глагол
26,шатт,мн. ч. шаттар,нет,комар,существительное
27,шатти,нет,нет,счастливо; радостно,наречие
28,шаттинф,нет,нет,торжественный,прилагательное
29,шафттал,мн. ч. шафтталар,нет,персик,существительное
30,шебетай,мн. ч. шебетаяр,да,неряха,существительное
31,шейтIан,мн. ч. шейтIанар,нет,чёрт; шайтан,существительное
32,шейъ,мн. ч. шейъар,нет,вещь; предмет,существительное
33,шейъар,нет,нет,имущество,существительное
34,шеэр,мн. ч. шеэр,нет,товар,существительное
35,шиит,мн. ч. шиитар,нет,шиит,существительное
36,шикат,мн. ч. шикатар,нет,жалоба,существительное
37,шикатвел,мн. ч. шикатвелар,нет,донесение,существительное
38,шикатчи,мн. ч. шикатчибур,нет,жалобщик,существительное
39,шикил,мн. ч. шикилар,да,рисунок; открытка; фотография; образ,существительное
40,шиниккв,мн. ч. шиникквар,нет,ребёнок; дитя; мальчик; юноша; парень; сын,существительное
41,шиниккв чIир акьуб,мн. ч. шиниккв чIир акьубар,нет,аборт,существительное
42,шиникквар дахьуб,мн. ч. шиникквар дахьубар,нет,бездетность,существительное
43,шинихIвел,нет,нет,просторность; широта,существительное
44,шинихIди,нет,нет,просторно; широко,наречие
45,шинихIдинф,нет,нет,просторный,прилагательное
46,шир,мн. ч. ширар,нет,краска; эмаль,существительное
47,шир кеф,нет,нет,эмалированный,прилагательное
48,ширинди,нет,нет,вкусно,наречие
49,ширинф,нет,нет,вкусный; сладкий,прилагательное
50,ширма,мн. ч. ширмабур,нет,ширма,существительное
51,ширчи,мн. ч. ширчибур,нет,маляр,существительное
52,шит,нет,нет,неприятный; пресный,прилагательное
53,шитти,нет,нет,несерьёзно,наречие
54,шифанер,мн. ч. шифанер,нет,шифоньер,существительное
55,шифир,мн. ч. шифирар,нет,шифер,существительное
56,шифун,мн. ч. шифунар,нет,шифон,существительное
57,шифур,мн. ч. шифурар,нет,шифр,существительное
58,шиш1,мн. ч. шишар,нет,вилка,существительное
59,шиш2,мн. ч. шишар,нет,шпага,существительное
60,шиш кабаб,мн. ч. шиш кабабар,нет,шашлык,существительное
61,шишал,мн. ч. шишалар,нет,мешок,существительное
62,шишикI,мн. ч. шишикIер,нет,ячмень,существительное
63,шишхана,мн. ч. шишханабур,нет,шашлычная,существительное
64,шккаттулкка,мн. ч. шккаттулккабур,нет,шкатулка,существительное
65,шккола,мн. ч. шкколабур,нет,школа,существительное
66,шккуркка,мн. ч. шкурккабур,нет,шкурка,существительное
67,шланг,мн. ч. шлангар,нет,шланг,существительное
68,шлем,мн. ч. шлемар,нет,шлем,существительное
69,шок,нет,нет,шок,существительное
70,шоссе,нет,нет,шоссе,существительное
71,шпаргалкка,мн. ч. шпаргалккабур,нет,шпаргалка,существительное
72,шпион,мн. ч. шпионар,нет,шпион,существительное
73,шприц,мн. ч. шприцар,нет,шприц,существительное
74,шрифт,мн. ч. шрифтар,нет,шрифт,существительное
75,штаб,мн. ч. штабар,нет,штаб,существительное
76,штанга,мн. ч. штангабур,нет,штанга,существительное
77,штангист,мн. ч. штангистар,нет,штангист,существительное
78,штат,мн. ч. штатар,нет,штат,существительное
79,штурман,мн. ч. штурманар,нет,штурман,существительное
80,штык,мн. ч. штыкар,нет,штык,существительное
81,шувас вес,мн. ч. шувас веттар,нет,женитьба; замужество,существительное
82,шуй1,мн. ч. шувар,нет,мужчина,существительное
83,шуй2,мн. ч. шувар,нет,муж; супруг,существительное
84,шурпа,мн. ч. шурпабур,нет,бульон; суп; борщ,существительное
85,шуруп1,мн. ч. шурупIар,нет,шуруп,существительное
86,шуткка,мн. ч. шутккабур,нет,щётка,существительное
87,шуша,мн. ч. шушабур,нет,стекло; бутылка,существительное
88,шушайинф,нет,нет,стеклянный,прилагательное
89,шуьргеф,нет,нет,гладкий,прилагательное
90,шуьрги,нет,нет,гладко,наречие
91,шуьхь,нет,нет,шёпотом,наречие
92,шам,мн. ч. шамар,нет,свеча,существительное
93,щёлок,нет,нет,щёлок,существительное
94,щим,нет,нет,сланцевый песок,существительное
95,щука,мн. ч. щукабур,нет,щука,существительное
96,Iайе кар,мн. ч. Iайе карар,нет,опасность,существительное
97,Iайи1,нет,нет,злобно,наречие
98,Iайи2,нет,нет,слишком,наречие
99,Iайи алгъадис,нет,нет,разъяриться,глагол
100,Iайи бицIиф,нет,нет,крошечный,прилагательное
101,Iайи кканеф,нет,нет,любимый; обожаемый,прилагательное
102,Iайи хIаф,нет,нет,крупный,прилагательное
103,Iайиб,нет,нет,стыд; срам,существительное
104,Iайибвел,нет,нет,развращённость; порочность,существительное
105,Iайибинф,нет,нет,позорный,прилагательное
106,Iайиб-Iейиб,нет,нет,позор,существительное
107,Iайсузвел,нет,нет,грубость,существительное
108,Iайсузди,нет,нет,грубо,наречие
109,Iакв алеф,нет,нет,светлый,прилагательное
110,Iакв але-чулеф,нет,нет,светло-синий,прилагательное
111,Iакъул,мн. ч. Iакъулар,нет,смысл,существительное
112,Iаламатар,нет,нет,чудеса,существительное
113,Iалим,мн. ч. Iалимар,нет,знаток; учёный,существительное
114,Iаб,мн. ч. Iабар,нет,кольбель; люлька,существительное
115,Iабкъун,мн. ч. Iабкъунар,нет,шут,существительное
116,Iабкъун,мн. ч. Iабкъунар,нет,ряженый,прилагательное
117,Iаванцай,мн. ч. Iаванцаяр,да,лягушка,существительное
118,Iагъвес,нет,нет,подняться,глагол
119,Iаджал,нет,нет,гибель,существительное
120,Iаджалинф,нет,нет,печальный; скорбный,прилагательное
121,Iайвел1,нет,нет,злоба; злость; несчастье,существительное
122,Iайвел2,мн. ч. Iайвелар,нет,бедствие,существительное
123,Iайвел вус,мн. ч. Iайвел вуар,нет,риск,существительное
124,Iамалар аркьаф,мн. ч. Iамалар аркьаттар,нет,врун,существительное
125,Iамалсуз,нет,нет,хитрый,прилагательное
126,Iамалчи1,мн. ч. Iамалчибур,нет,обманщик; врун,существительное
127,Iамалчи2,мн. ч. Iамалчибур,нет,хитрец,существительное
128,Iам-Iалай,нет,нет,мать-и-мачеха,существительное
129,Iареф,нет,нет,пустой,прилагательное
130,Iари1,нет,нет,пусто,наречие
131,Iари2,нет,нет,только,наречие
132,IартI,мн. ч. IартIвар,нет,тряпка,существительное
133,Iаруш,мн. ч. Iарушар,да,грязь,существительное
134,IарцIулвел,нет,да,нагота,существительное
135,IарцIулф,нет,нет,голый,прилагательное
136,Iаттевел,нет,нет,хромота,существительное
137,Iаф,нет,нет,гневный,прилагательное
138,Iачун,нет,нет,глиняный,прилагательное
139,Iаш1,мн. ч. Iашвар,нет,подошва,существительное
140,Iаш2,нет,нет,сырость; мокрота; влажность,существительное
141,Iаш кей,нет,нет,сыро,наречие
142,Iашас,нет,нет,промокнуть,глагол
143,Iашв,мн. ч. Iашвар,нет,путка,существительное
144,IаIав,мн. ч. IаIавар,нет,шаг,существительное
145,Iебаб хьас,нет,нет,потерять (дар речи),глагол
146,Iевам,мн. ч. Iевамар,нет,невежда,существительное
147,Iегв1,мн. ч. Iегвар,нет,зеркало,существительное
148,Iегв2,мн. ч. Iегвар,нет,зрачок,существительное
149,Iегвал хьудавел,нет,нет,жестокость,существительное
150,Iегвал хьас,нет,нет,пожалеть,глагол
151,Iегвалвел,нет,нет,жалость; сострадание,существительное
152,Iегвалвел хьаф,нет,нет,жалостливый,прилагательное
153,Iегвалвел хьудай,нет,нет,жестоко; беспощадно,наречие
154,Iегвалвел хьудаф,нет,нет,беспощадный; жестокий,прилагательное
155,Iегвалди,нет,нет,жалостливо; сострадательно,наречие
156,Iегвалсузди,нет,нет,жестоко; беспощадно,наречие
157,Iедат,мн. ч. Iедатар,да,обычай; адат,существительное
158,Iеджабди,нет,нет,странно; непонятно; удивительно,наречие
159,Iеджаванф,нет,да,странноватый; непонятный,прилагательное
160,Iеджайиб,нет,нет,странный; чудный,прилагательное
161,Iеджайибвел,нет,да,необычность; странность,существительное
162,Iеджайибди,нет,нет,странно; удивительно,наречие
163,Iеджал,мн. ч. Iеджалар,нет,смерть,существительное
164,Iеджал хъудаф,нет,нет,бессмертный,прилагательное
165,Iеджалсуз,нет,нет,бессмертный,прилагательное
166,Iеджиз хьас,нет,нет,обеднеть,глагол
167,Iезаб эс,нет,да,пытать,глагол
168,Iезабсуз,нет,нет,лёгкий,прилагательное
169,Iейиб кар,нет,нет,позор,существительное
170,Iек баркайинф,нет,нет,прекрасный,прилагательное
171,Iек гьаттивас,нет,нет,ослепнуть,глагол
172,Iек ичиф,нет,нет,освещённый,прилагательное
173,Iекаф,нет,нет,освещённый,прилагательное
174,Iекв,мн. ч. Iеквар,нет,сияние,существительное
175,Iеквевел,нет,нет,яркость,существительное
176,Iеквеф,нет,нет,светлый; яркий,прилагательное
177,Iекукъиран,нет,нет,близорукий,прилагательное
178,Iекьрав,мн. ч. Iекьравар,нет,скорпион,существительное
179,Iекьул,мн. ч. Iекьулар,нет,ум,существительное
180,Iекьул кедай,нет,нет,неразумно,наречие
181,Iекьул кедаф,нет,нет,неразумный,прилагательное
182,Iекьул кей,нет,нет,мудро,наречие
183,Iекьулар кеф,мн. ч. Iекьулар кеттар,нет,мудрец,существительное
184,Iекьулдар,нет,да,разумный; умный,прилагательное
185,Iекьуллуди,нет,нет,разумно,наречие
186,Iекьулсуз,нет,нет,неразумный,прилагательное
187,Iекьулсузди,нет,нет,неразумно,наречие
188,Iекьулфаф,нет,нет,разумный,прилагательное
189,Iеламатинф,нет,нет,удивительный; таинственный; мистический,прилагательное
190,Iелат,мн. ч. Iелатар,нет,инструмент,существительное
191,Iелаф,мн. ч. Iелафар,нет,корм,существительное
192,Iелим,мн. ч. Iелимар,нет,мудрец,существительное
193,Iемал1,мн. ч. Iемалар,нет,обман; ложь,существительное
194,Iемал2,мн. ч. Iемалар,нет,средство,существительное
195,Iемал кей,нет,нет,лживо; изворотливо,наречие
196,Iемалар акъас,нет,нет,соврать; обмануть,глагол
197,Iемалар акьун,нет,нет,лживо,наречие
198,Iемалар кедаф,нет,нет,бесхитростный,прилагательное
199,Iемалар-тIулар акъас,нет,нет,притворяться,глагол
200,Iемалвел,мн. ч. Iемалвелар,нет,обман,существительное
201,Iемалдар,мн. ч. Iемалдарар,нет,обманщик; хитрец,существительное
202,Iемалдарди,нет,нет,лживо,наречие
203,Iемам,нет,нет,забитый,прилагательное
204,IентIевел,нет,нет,брезгливость,существительное
205,IентIеф,нет,нет,брезгливый,прилагательное
206,IентIиди,нет,нет,брезгливо,наречие
207,Iер,нет,нет,совесть,существительное
208,Iераба,мн. ч. Iерабабур,нет,арба; телега; подвода,существительное
209,Iерба,мн. ч. Iербабур,нет,беспорядок,существительное
210,Iерд,мн. ч. Iердар,нет,ляжка,существительное
211,Iерза,мн. ч. Iерзабур,нет,жалоба,существительное
212,Iериф,мн. ч. Iерифар,да,знаток; учёный,существительное
213,Iерифдарвел,нет,да,образованность; учёность,существительное
214,Iерсузди,нет,нет,бессовестно; бесстыдно,наречие
215,Iесса,мн. ч. Iессабур,нет,посох; трость,существительное
216,Iетри,нет,нет,духи,существительное
217,IечI,мн. ч. IечIар,да,подмышка,существительное
218,Iешкъ,мн. ч. Iешкъар,да,желание; увлечение,существительное
219,Iешкъиллу,нет,да,увлечённый; устремлённый,прилагательное
220,Iешкъиллувел,нет,да,устремлённость; увлечённость,существительное
221,Iешкъиллуди,нет,да,увлечённо; устремлённо,наречие
222,Iешкъсуз,нет,нет,пассивный; инертный,прилагательное
223,Iешкъсузди,нет,нет,пассивно; инертно,наречие
224,Iешукъ,мн. ч. Iешукъар,нет,певец; ашуг,существительное
225,IикIас,нет,нет,сунуть,глагол
226,Iилми,мн. ч. Iилмибур,нет,наука,существительное
227,Iихьас,нет,нет,бросить,глагол
228,Iу сур акьун,нет,нет,пополам,наречие
229,Iу сурат гIаф,нет,нет,двулично,наречие
230,Iуверш,нет,нет,двести,числительное
231,Iугелай,нет,нет,дважды,наречие
232,Iуд,нет,нет,два,числительное
233,Iудари хъай,нет,нет,вдвоём,наречие
234,Iуй1,нет,нет,грабли,существительное
235,Iуй2,мн. ч. Iувур,да,вилка,существительное
236,Iул,мн. ч. Iулар,нет,мышь,существительное
237,Iурд,мн. ч. Iурдар,нет,зима,существительное
238,Iурдана,нет,нет,зимой,наречие
239,Iусач,мн. ч. Iусачар,да,старец,существительное
240,IутIанас,нет,нет,есть,глагол
241,IутIас,нет,нет,есть,глагол
242,IутIуб,нет,нет,питание,существительное
243,Iухьу,мн. ч. Iухьубур,нет,кашель,существительное
244,Iухьу акьас,нет,нет,кашлять,глагол
245,IуькI,мн. ч. IуькIер,нет,растение; трава; зелень; сено,существительное
246,IуькIерин майдан,мн. ч. IуькIерин майданар,нет,поляна,существительное
247,Iульдеккен,мн. ч. Iульдеккенар,нет,подушка,существительное
248,Iуьмур,мн. ч. Iуьмурар,нет,жизнь,существительное
249,Iуьмурди,нет,нет,вообще,наречие
250,Iуьмурдил шатти аф,нет,нет,жизнерадостный,прилагательное
251,Iуьмурлу,нет,нет,долговечный,прилагательное
252,Iуьр1,мн. ч. Iуьрар,нет,озеро,существительное
253,Iуьр2,мн. ч. Iуьрар,нет,болото,существительное
254,IуьркI,мн. ч. IуьркIар,нет,жвачка,существительное
255,Iуьрус,нет,нет,русский,прилагательное
256,Iуьрус,мн. ч. Iуьрусар,нет,русский,существительное
257,IуьрчIе рангаринф,нет,нет,пёстрый,прилагательное
258,IуьрчIевел,нет,нет,пестрота,существительное
259,IуьрчIеф,нет,нет,пёстрый,прилагательное
260,Iуьссе къуджа,мн. ч. Iуьссе къуджабур,нет,старик,существительное
261,Iуьссе хьир,мн. ч. Iуьссе хьирар,нет,старуха,существительное
262,Iуьссе хьуф,нет,нет,устаревший,прилагательное
263,Iуьссевел,мн. ч. Iуьссевелар,нет,старость,существительное
264,Iуьссеф,мн. ч. Iуьсеттар,нет,старец,существительное
265,Iуьссеф,нет,нет,старый; престарелый; дряхлый,прилагательное
266,IуьтIанас,нет,нет,кушать,глагол
267,IуьфритI,мн. ч. IуьфритIар,нет,дьявол; демон,существительное
268,IуьфритIвел,мн. ч. IуьфритIвелар,да,хитрость,существительное
269,Iуьчанас,нет,нет,стирать,глагол
270,Iуьчас,нет,да,стирать,глагол
271,Iуьччанас,нет,нет,мыть; стирать; купать,глагол
272,IуьчIе лус,мн. ч. IуьчIе лусар,нет,щавель,существительное
273,IуьчIе хут,мн. ч. IуьчIе хутар,нет,алыча,существительное
274,IуьчIе хьуб,мн. ч. IуьчIе хьубар,нет,закислённость,существительное
275,IуьчIевел,нет,нет,горечь,существительное
276,IуьчIеф,нет,нет,кислый; горький,прилагательное
277,IуьчIи,нет,нет,кисло; горько,наречие
278,IуьчI-IуьчIай,мн. ч. IуьчI-IуьчIаяр,нет,щавель,существительное
279,Iуьш,мн. ч. Iуьшар,нет,ночь,существительное
280,Iуьшанттар,нет,нет,ужин,существительное
281,Iуьшуй,нет,нет,ночью,наречие
282,Iэбаб хьас,нет,нет,онеметь,глагол
283,Iэгвалвел хъудаф,нет,нет,безжалостный,прилагательное
284,Iэк иссалф,нет,нет,близорукий,прилагательное
285,Iэк ккеми,нет,нет,засветло,наречие
286,Iэкв,мн. ч. Iэквар,нет,свет; рассвет,существительное
287,Iэкве иреф,нет,нет,алый,прилагательное
288,Iэкве рангунинф,нет,нет,яркий,прилагательное
289,Iэквевел,нет,нет,яркость,существительное
290,Iэквеф,нет,нет,ясный,прилагательное
291,Iэкуль,мн. ч. Iэкульар,нет,ум; разум; интеллект,существительное
292,Iэкуль кеф,нет,нет,умный,прилагательное
293,Iэкуль фай,нет,нет,разумно,наречие
294,Iэкульар,мн. ч. Iэкульар,нет,совет; пожелание,существительное
295,Iэкульфаф,нет,нет,умный,прилагательное
296,Iэлучай,мн. ч. Iэлучаяр,нет,алыча,существительное
297,Iэмал1,мн. ч. Iэмалар,нет,фокус,существительное
298,Iэмал2,мн. ч. Iэмалар,нет,неправда; фантазия,существительное
299,Iэмалар агваракьаф,мн. ч. Iэмалар агваракьаттар,нет,фокусник,существительное
300,Iэмалар кеф,нет,нет,хитрый; фальшивый,прилагательное
301,Iэмалвел,мн. ч. Iэмалвелар,нет,хитрость,существительное
302,Iэмалдарвел,мн. ч. Iэмалдарвелар,нет,хитрость,существительное
303,Iэмалчи,мн. ч. Iэмалчибур,нет,обманщик; лгун,существительное
304,Iэмбар,мн. ч. Iэмбарар,нет,склад,существительное
305,Iэсса,мн. ч. Iэссабур,нет,костыль,существительное
306,Iэшал,мн. ч. Iэшалар,нет,плач; рыдание; причитание,существительное
307,Iэшалар акьас,нет,нет,плакать; причитать,глагол
308,Iэшас,нет,нет,плакать; рыдать,глагол
309,IэширкI,мн. ч. IэширкIер,нет,плакса,существительное
310,э,нет,нет,да,наречие
311,э,нет,нет,да,частица
312,эвледсузвел,нет,нет,бездетность,существительное
313,эвленмишвел,нет,нет,женитьба; замужество,существительное
314,эв-уьлке,мн. ч. эв-уьлкебур,нет,страна,существительное
315,эген,нет,да,если,союз
316,эгер,нет,нет,если,союз
317,эесси адаф,нет,нет,бесхозный,прилагательное
318,эесси хъаф,нет,нет,собственность,существительное
319,эесси хъудаф,нет,нет,заброшенность,существительное
320,эйван,мн. ч. эйванар,нет,балкон,существительное
321,экватор,мн. ч. экваторар,нет,экватор,существительное
322,экзамен,мн. ч. экзаменар,нет,экзамен,существительное
323,экзаменатор,мн. ч. экзаменаторар,нет,экзаменатор,существительное
324,экзема,нет,нет,экзема,существительное
325,экземпляр,мн. ч. экземплярар,нет,экземпляр,существительное
326,экипаж,мн. ч. экипажар,нет,экипаж,существительное
327,экран,мн. ч. экранар,нет,экран,существительное
328,экскаватор,мн. ч. экскаваторар,нет,экскаватор,существительное
329,экскурси,мн. ч. экскурсиябур,нет,экскурсия,существительное
330,экспедици,мн. ч. экспедициябур,нет,экспедиция,существительное
331,эксперт,мн. ч. экспертар,нет,эксперт,существительное
332,эксперттиза,мн. ч. эксперттизабур,нет,экспертиза,существительное
333,эксплуататор,мн. ч. эксплуататорар,нет,эксплуататор,существительное
334,экспорт,мн. ч. экспортар,нет,экспорт,существительное
335,экспресс,мн. ч. экспрессарар,нет,экспресс,существительное
336,экьвас,нет,нет,сидеть,глагол
337,экI,нет,нет,пшеница,существительное
338,эл1,нет,нет,воздух,существительное
339,эл2,мн. ч. элар,нет,дыхание,существительное
340,эл3,мн. ч. элар,да,ветер,существительное
341,эл4,мн. ч. элар,нет,население,существительное
342,эл гьатас1,мн. ч. эл гьатасар,нет,вдох,существительное
343,эл гьатас2,мн. ч. эл гьатубар,нет,дыхание,существительное
344,эл гьатуб,мн. ч. эл гьатубар,нет,выдох,существительное
345,эл дивас,нет,нет,дышать,глагол
346,эл ккуькас,мн. ч. эл ккуькасар,нет,тоска,существительное
347,эл ккуькаф,нет,нет,скучный,прилагательное
348,эл ккуькуб,мн. ч. эл ккуькубар,нет,скука,существительное
349,элбеэл,нет,нет,немедленно,наречие
350,элверчи,мн. ч. элверчибур,да,торговец,существительное
351,элдетмиш аркьаф,мн. ч. элдетмиш аркьаттар,нет,обманщик; врун,существительное
352,электрификация,нет,нет,электрификация,существительное
353,электричество,нет,нет,электричество,существительное
354,элл ихьуф,нет,нет,воздушный,прилагательное
355,эллигъ,нет,нет,старый,прилагательное
356,элмес,мн. ч. элмесар,нет,алмаз; стеклорез,существительное
357,элпен,мн. ч. элпенар,нет,скирд,существительное
358,элхь,нет,нет,смех; хохот,существительное
359,элхьенас,нет,нет,смеяться,глагол
360,эльхIяд,нет,нет,воскресенье,существительное
361,эмалировани,нет,нет,эмалированный,прилагательное
362,эмаль,мн. ч. эмалар,нет,эмаль,существительное
363,эмблема,мн. ч. эмблемабур,нет,эмблема,существительное
364,эмигрант,мн. ч. эмигрантар,нет,эмигрант,существительное
365,эмкI1,мн. ч. эмкIар,нет,пот,существительное
366,эмкI2,мн. ч. эмкIар,нет,сон,существительное
367,эмкI ичас,нет,нет,потеть,глагол
368,эпел,мн. ч. эпелар,нет,стог,существительное
369,эпитет,мн. ч. эпитетар,нет,эпитет,существительное
370,эпос,мн. ч. эпосар,нет,эпос,существительное
371,эра,мн. ч. эрабур,нет,эра,существительное
372,эрбеI,нет,нет,среда,существительное
373,эрдж,мн. ч. эрджар,нет,метка; клеймо,существительное
374,эрзиман,нет,нет,милый,прилагательное
375,эркек,нет,нет,мужественный,прилагательное
376,эркекди,нет,нет,мужественно,наречие
377,эркин,нет,нет,свободный,прилагательное
378,эркинвел,нет,нет,самостоятельность; независимость,существительное
379,эрмени,мн. ч. эрменибур,нет,армянин,существительное
380,эскер,мн. ч. эскерар,нет,боец; воин; солдат,существительное
381,эски,нет,нет,старый; устаревший; драный,прилагательное
382,эскивел,нет,нет,обветшалость; ветхость,существительное
383,этажерка,мн. ч. этажеркабур,нет,этажерка,существительное
384,этюд,мн. ч. этюдар,нет,этюд,существительное
385,эфир,мн. ч. эфирар,нет,эфир,существительное
386,эхтигьар,мн. ч. эхтигьарар,да,разрешение; позволение,существительное
387,эхтигьар,мн. ч. эхтигьарар,нет,право; полномочие; воля,существительное
388,эхтигьарсузвел,нет,нет,бесправие,существительное
389,эхтилат,мн. ч. эхттилатар,нет,легенда,существительное
390,эхтилатчи,мн. ч. эхттилатчибур,да,собеседник,существительное
391,эхь,мн. ч. эхьар,нет,тень,существительное
392,эхIваллувел,нет,нет,состоятельность,существительное
393,эхIмакъ,мн. ч. эхIмакъар,нет,болван,существительное
394,эхIтималвел,нет,нет,возможность,существительное
395,эхIтималди,нет,нет,возможно,наречие
396,эхIтималф,нет,нет,возможный,прилагательное
397,эхIтияджвел,нет,нет,нуждаемость,существительное
398,эхIтиятлу,нет,да,осторожный,прилагательное
399,эхIтимал,нет,нет,вероятный,прилагательное
400,эхIттият,нет,да,осторожность; предосторожность,существительное
401,эхIттият хъаф,нет,нет,бдительный,прилагательное
402,эшег,мн. ч. эшегер,да,осёл; ишак,существительное
403,эшелон,мн. ч. эшелонар,нет,эшелон,существительное
404,юбиле,мн. ч. юбилеяр,нет,юбилей,существительное
405,юз,нет,нет,наклон; крутость,существительное
406,юзди,нет,нет,наклонно,наречие
407,юлдаш,мн. ч. юлдашар,да,друг; товарищ,существительное
408,юлкка,мн. ч. юлккабур,нет,ёлка,существительное
409,юлла аф,нет,нет,покорный,прилагательное
410,юлла суманф,мн. ч. юлла суманттар,нет,ловкач,существительное
411,юллавел1,нет,нет,умение,существительное
412,юллавел2,нет,нет,ловкость,существительное
413,юллавелар,нет,нет,ловкачество,существительное
414,юлчи,мн. ч. юлчибур,нет,путник,существительное
415,юмор,мн. ч. юморар,нет,юмор,существительное
416,юпкка,мн. ч. юпккабур,нет,юбка,существительное
417,юридически,нет,нет,юридический,прилагательное
418,юрист,мн. ч. юристар,нет,юрист,существительное
419,юркл атIас,нет,нет,отвращение,существительное
420,юркл ккидай,нет,нет,брезгливо,наречие
421,юртсуз,нет,нет,бездомный,прилагательное
422,юрутмиш акъас,нет,нет,исполнить; совершить,глагол
423,юхсул,нет,да,никчёмный,прилагательное
424,явавел,мн. ч. явавелар,нет,слабость,существительное
425,яваш,нет,нет,медленный; неторопливый,прилагательное
426,яваш акъас,нет,нет,замедлить,глагол
427,явашвел,нет,нет,неторопливость,существительное
428,яваштти,нет,нет,медленно; тихо; потихоньку; инертно; пассивно,наречие
429,явашттинф,нет,нет,медленный; тихий; неторопливый; инертный; пассивный,прилагательное
430,ягъ,мн. ч. ягъар,нет,день,существительное
431,ягъа-ягъа,нет,нет,ежедневно,наречие
432,ягъдинф,нет,нет,частый,прилагательное
433,ягълукъ,мн. ч. ягълукъар,нет,платок,существительное
434,ягъна-Iуьш,нет,нет,сутки,существительное
435,ягъниш1,мн. ч. ягънишар,нет,умысел,существительное
436,ягъниш2,мн. ч. ягънишар,нет,изъян; недостаток,существительное
437,ягъсуз,нет,нет,наглый,прилагательное
438,ягъщIур,нет,нет,сорок,числительное
439,ягь,нет,нет,совесть,существительное
440,ягьлу1,нет,нет,совестливый,прилагательное
441,ягьлу2,нет,нет,добросовестный,прилагательное
442,ягIа,нет,нет,сегодня,наречие
443,ягIай,нет,нет,умело,наречие
444,ягIайинф,нет,нет,сегодняшний,прилагательное
445,ягIанф,нет,нет,теперешний,прилагательное
446,яIар,мн. ч. яIарар,нет,поясница,существительное
447,ягIар акьас,нет,нет,запросить,глагол
448,ягIар акьуб1,мн. ч. ягIар акьубар,нет,знакомство,существительное
449,ягIар акьуб2,мн. ч. ягIар акьубар,нет,объяснение; толкование; подсказка,существительное
450,ягIар дахьуб,нет,нет,неосведомлённость,существительное
451,ягIар хьуб1,мн. ч. ягIар хьубар,нет,аргумент; довод; ясность,существительное
452,ягIар хьуб2,мн. ч. ягIар хьубар,нет,знакомство,существительное
453,ягIарвел,нет,нет,умение,существительное
454,ягIаф,мн. ч. ягIафар,нет,знакомый; приятель,существительное
455,язан,мн. ч. язанар,нет,пахота; пашня,существительное
456,язид,мн. ч. язидар,нет,подлец,существительное
457,язид,нет,нет,непримиримый,прилагательное
458,язна,мн. ч. язнабур,нет,зять,существительное
459,язукъ,нет,нет,жалость; сожаление,существительное
460,язукъ давеф,нет,нет,безжалостный,прилагательное
461,язукъ хьас,нет,нет,пожалеть,глагол
462,язукъвел,нет,нет,жалость; сострадание,существительное
463,язукъди,нет,нет,жалостливо; сострадательно,наречие
464,язукъинф,нет,нет,жалостливый,прилагательное
465,язукъф,нет,нет,жалкий,прилагательное
466,языкознани,нет,нет,языкознание,существительное
467,як,мн. ч. якар,нет,як,существительное
468,яки,нет,нет,точнее,частица
469,якк,мн. ч. яккар,нет,мясо,существительное
470,якьуверш,нет,нет,четыреста,числительное
471,якьуд,нет,нет,четыре,числительное
472,якьукъад,нет,нет,восемьдесят,числительное
473,якьут,мн. ч. якьутар,нет,яхонт,существительное
474,якIв,мн. ч. якIвар,нет,топор,существительное
475,ялвар,нет,нет,мольба,существительное
476,ялгьуз,нет,нет,одинокий,прилагательное
477,ялгьузвел,нет,нет,одиночество,существительное
478,ялгьузф,нет,нет,одинокий,прилагательное
479,ялтакъвел,нет,да,лесть; подхалимство,существительное
480,ялтакъди,нет,нет,двулично; льстиво,наречие
481,ямаг,мн. ч. ямагар,нет,пища; блюдо,существительное
482,ямагар аркьаф,мн. ч. ямагар аркьаттар,нет,повар,существительное
483,ямадж,мн. ч. ямаджар,нет,склон,существительное
484,ямак,нет,нет,еда; пища,существительное
485,яманвел,нет,нет,злоба,существительное
486,яманди,нет,нет,злобно,наречие
487,яр,нет,нет,любимый,прилагательное
488,яракь,мн. ч. яракьар,нет,оружие,существительное
489,яракь фаф,нет,нет,вооружённый,прилагательное
490,яракь фахьуб,нет,нет,вооружённость,существительное
491,ярамаз,мн. ч. ярамазар,нет,негодяй,существительное
492,ярамиш,нет,нет,годный; приемлемый,прилагательное
493,ярашугъ,нет,да,подобный,прилагательное
494,ярд,мн. ч. ярдар,нет,бычок,существительное
495,яржцIур,нет,нет,девяносто,числительное
496,ярма,мн. ч. ярмабур,нет,корм,существительное
497,ярх,мн. ч. ярхар,нет,лавина,существительное
498,ярцIуд,нет,нет,семьдесят,числительное
499,ярчIуверш,нет,нет,девятьсот,числительное
500,ярчIуицI,нет,нет,девяносто,числительное
501,яс,нет,нет,траур,существительное
502,ясир,мн. ч. ясирар,нет,узник,существительное
503,ятум,мн. ч. ятумар,нет,сирота,существительное
504,яхмиш,нет,нет,пропасть,глагол
505,яхтта,мн. ч. яхттабур,нет,яхта,существительное
506,яхул шуй,мн. ч. яхул шувар,нет,лакец,существительное
507,яхун хьас,нет,да,похудеть,глагол
508,яхI,нет,нет,честь; благородство,существительное
509,яхI хъудаф,нет,нет,бессильный,прилагательное
510,яхI-намус1,нет,нет,совесть,существительное
511,яхI-намус2,нет,нет,честь,существительное
512,яхI-намусвел,нет,нет,совестливость,существительное
513,яхI-намусди,нет,нет,совестливо,наречие
514,яхIсуз,нет,нет,бессовестный,прилагательное
515,яш,мн. ч. яшар,нет,возраст,существительное
516,яшамиш,мн. ч. яшамишар,нет,быт,существительное
517,яшамиш веф,мн. ч. яшамиш веттар,нет,житель,существительное
518,яшамиш хьуб,нет,нет,существование; житьё,существительное
519,яшар адай,нет,нет,несовершеннолетие,существительное
520,яшаринф,нет,нет,зрелый,прилагательное
521,яI,мн. ч. яIар,нет,половина; середина,существительное
522,яIан,мн. ч. яIанар,нет,центр,существительное
523,яIани гIаф,нет,нет,средний,прилагательное
524,яIар ахьас,нет,нет,плавать; искупаться,глагол
525,яIар ахьуб,мн. ч. яIар ахьубар,нет,плавание,существительное

Writing dct_all.csv

In [ ]:
dct = pd.read_csv('dct_all.csv').drop(columns = ('Unnamed: 0'))
dct.to_csv('mazanaev_dict.csv', encoding='utf-8-sig')
dct

,агульское слово,заметка,диалектологизм,русский перевод,часть речи
0,абаб,мн. ч. абабар,нет,тётя,существительное
1,абажур,мн. ч. абажурар,нет,абажур,существительное
2,абанемент,мн. ч. абанементар,нет,абонемент,существительное
3,абанент,мн. ч. абанентар,нет,абонент,существительное
4,абанкьул,мн. ч. абанкьулар,нет,лоб,существительное
...,...,...,...,...,...
5207,яI,мн. ч. яIар,нет,половина; середина,существительное
5208,яIан,мн. ч. яIанар,нет,центр,существительное
5209,яIани гIаф,нет,нет,средний,прилагательное
5210,яIар ахьас,нет,нет,плавать; искупаться,глагол
5211,яIар ахьуб,мн. ч. яIар ахьубар,нет,плавание,существительное

In [ ]:
pos_mapping = {
    'существительное': 'NOUN',
    'прилагательное': 'ADJ',
    'глагол': 'VERB',
    'наречие': 'ADV',
    'числительное': 'NUM',
    'местоимение': 'PRON',
    'частица': 'PART',
    'междометие': 'INTJ',
    'союз': 'CONJ',
    'вводное слово': 'INTR',
    'деепричастие': 'PARTICIPLE',
    'союзное слово': 'CONJ_WORD',
    'предлог': 'PREP'
}

dct['часть речи'] = dct['часть речи'].map(pos_mapping).fillna(dct['часть речи'])

In [ ]:
dct['часть речи'].value_counts()

часть речи
NOUN          3201
ADJ            913
ADV            528
VERB           438
NUM             41
PRON            41
PART            27
INTJ             7
CONJ             6
INTR             5
PARTICIPLE       2
CONJ_WORD        2
PREP             1
Name: count, dtype: int64

In [ ]:
part_of_speech_mapping = {
    'NOUN': 'Nouns',
    'ADJ': 'Adjectives',
    'ADV': 'Adverbs',
    'VERB': 'Verbs',
    'NUM': 'Numerals',
    'PRON': 'Pronouns',
    'PART': 'Particles',
    'INTJ': 'Interjections',
    'CONJ': 'Conjunctions',
    'INTR': 'Interjections',
    'PARTICIPLE': 'Participles',
    'CONJ_WORD': 'Conjunctions',
    'PREP': 'Prepositions'
}

pof = dct['часть речи'].unique()

for part in pof:
    f_dct = dct[dct['часть речи'] == part].copy()
    max_len = f_dct['агульское слово'].str.len().max()
    file_name = part_of_speech_mapping.get(part, part)
    output_filename = f"aghul_dct_{file_name}.lexd"

    with open(output_filename, 'w', encoding='utf-8') as f:
        f.write(f"LEXICON {file_name}\n\n")

        for idx, row in f_dct.iterrows():
            aghul_word = row['агульское слово']
            rus_tr = row['русский перевод']

            f.write(f"{aghul_word:<{max_len + 2}} # {rus_tr}\n")

#Транслитерация

In [ ]:
TRANSLIT_MAP = {
    "А": "a",   "а": "a",
    "Б": "b",   "б": "b",
    "В": "v",   "в": "v",
    "Г": "g",   "г": "g",
    "Д": "d",   "д": "d",
    "Е": "e",   "е": "e",
    "Ё": "ë",   "ё": "ë",
    "Ж": "ž",   "ж": "ž",
    "З": "z",   "з": "z",
    "И": "i",   "и": "i",
    "Й": "j",   "й": "j",
    "К": "k",   "к": "k",
    "Л": "l",   "л": "l",
    "М": "m",   "м": "m",
    "Н": "n",   "н": "n",
    "О": "o",   "о": "o",
    "П": "p",   "п": "p",
    "Р": "r",   "р": "r",
    "С": "s",   "с": "s",
    "Т": "t",   "т": "t",
    "У": "u",   "у": "u",
    "Ф": "f",   "ф": "f",
    "Х": "x",   "х": "x",
    "Ц": "c",   "ц": "c",
    "Ч": "č",   "ч": "č",
    "Ш": "š",   "ш": "š",
    "Щ": "šš",  "щ": "šš",
    "Ъ": "ʾ",   "ъ": "ʾ",
    "Ы": "y",   "ы": "y",
    "Ь": "ʹ",   "ь": "ʹ",
    "Э": "è",   "э": "è",
    "Ю": "ju",  "ю": "ju",
    "Я": "ja",  "я": "ja",


    "Гъ": "h",   "гъ": "h",
    "Гь": "ǧ",   "гь": "ǧ",
    "ГЫ": "ǧʾ",  "гы": "ǧʾ",

    "Дж": "dž",  "дж": "dž",

    "Къ": "q",   "къ": "q",
    "Кь": "qʼ",  "кь": "qʼ",
    "КI": "kʼ",  "кI": "kʼ",

    "ПI": "pʼ",  "пI": "pʼ",

    "Тт": "tt",  "тт": "tt",
    "ТI": "tʼ",  "тI": "tʼ",

    "Уь": "ü",   "уь": "ü",

    "Хъ": "qʰ",  "хъ": "qʰ",
    "Хь": "ẋ",   "хь": "ẋ",
    "ХI": "ḥ",   "хI": "ḥ",

    "ЦI": "cʼ",  "цI": "cʼ",
    "ЧI": "čʼ",  "чI": "čʼ",
}

MULTI_CHAR_MAP = {
    "ал": "aʻ",
    "аъ": "ä",
    "дз": "dz",
    "джв": "džw",
    "жв": "žw",
    "кк": "kk",
    "оь": "ö",
    "пп": "pp",
    "сс": "ss",
    "фф": "ff",
    "хх": "xx",
    "хъхъ": "qq",
    "хьхь": "ẋẋ",
    "щ": "cc",
    "чв": "čw",
    "чч": "čč",
    "ччв": "ččw",
    "чIв": "čʼw",
    "шв": "šw",
    "щв": "ššw",
}


def transliterate(text: str) -> str:

    # Combine mappings
    mapping = {}
    mapping.update(MULTI_CHAR_MAP)
    mapping.update(TRANSLIT_MAP)

    # Sort by descending key length
    keys = sorted(mapping.keys(), key=len, reverse=True)

    result = []
    i = 0

    while i < len(text):
        matched = False

        for key in keys:
            if text.startswith(key, i):
                result.append(mapping[key])
                i += len(key)
                matched = True
                break

        if not matched:
            result.append(text[i])
            i += 1

    return "".join(result)


# Example
sample = "гlафур"
print(transliterate(sample))
# -> dž q ẋ čʼ ju ja

glafur

#Numeric

In [ ]:
# @title
line = '''
1 - сад
2 - Iуд
3 - хьибуд
4 - якьуд
5 - гIафуд
6 - ерхьид
7 - ерид
8 - муяд
9 - ярчIуд
10 - ицIуд
11 - цIесад
20 - къад
30 - хьимцIур
40 - ягъцIур
50 - гlафцIур
60 - яхьцIур
70 - ярцIур
80 - муйцIур
90 - ярчIзур
100 - верш
1000 - агъзур
'''
nums = []
l = line.split("\n")
for i in l[1:-1]:
  a = i.split(" - ")
  nums.append(a[1]+"<n>:"+a[1])

for n in nums:
  print(n)

сад<n>:сад
Iуд<n>:Iуд
хьибуд<n>:хьибуд
якьуд<n>:якьуд
гIафуд<n>:гIафуд
ерхьид<n>:ерхьид
ерид<n>:ерид
муяд<n>:муяд
ярчIуд<n>:ярчIуд
ицIуд<n>:ицIуд
цIесад<n>:цIесад
къад<n>:къад
хьимцIур<n>:хьимцIур
ягъцIур<n>:ягъцIур
гlафцIур<n>:гlафцIур
яхьцIур<n>:яхьцIур
ярцIур<n>:ярцIур
муйцIур<n>:муйцIур
ярчIзур<n>:ярчIзур
верш<n>:верш
агъзур<n>:агъзур

In [ ]:
# @title numerics.lexd
#%%writefile aghul_numerals.lexd
%%writefile task.lexd
PATTERNS
NumStem
NumStem NumCase
NumStem NumNumber NumCase
Ten TenCase
Ten NumNumber TenCase
( NumStem | Ten ) OrdSuffix
( NumStem | Ten ) AdvSuffix
( NumStem | Ten ) Distributive
IndefNum

LEXICON NumStem
сад:са{Д} #1
lуд:lу{Д} #2
хьибуд:хьибу{Д} #3
якьуд:якьу{Д} #4
гlафуд:гlафу{Д} #5
ерхьид:ерхьи{Д} #6
ерид:ери{Д} #7
муйд:муй{Д} #8
ярчlуд:ярчlу{Д} #9
ицlуд:ицlу{Д} #10
къад #20

LEXICON Ten
хьимцlур #30
ягьцlур #40
гlафцlур #50
яхьцlур #60
ярцlур #70
муйцlур #80
ярчlзур #90

LEXICON NumCase
<nom>:
<erg>:и
<gen>:ин
<dat>:ис
<ins>:илди
<psl1>:ифай
<psl2>:ихъай
<psl3>:игlай

LEXICON TenCase
<nom>:
<erg>:а
<gen>:ан
<dat>:ас
<ins>:алди
<psl1>:афай
<psl2>:ахъай
<psl3>:агlай

LEXICON IndefNum
паратар #многие
чlукьтар #меньшие
сакьадартар #некоторые
саlудар #немногие
сахьимунасад #несколько

LEXICON NumNumber
<sg>:
<pl>:ар

LEXICON OrdSuffix
<ord>:пуф

LEXICON OrdCase
<nom>:
<erg>:ти
<gen>:тин
<dat>:тис
<ins>:тилди
<psl1>:тифай
<psl2>:тихъай
<psl3>:тигlай


LEXICON AdvSuffix
<adv>:{X}галай

LEXICON Distributive
<distr>:
<distr>:ди

Overwriting task.lexd

In [ ]:
dct[dct['русский перевод']== 'лошадь']

Empty DataFrame
Columns: [агульское слово, заметка, диалектологизм, русский перевод, часть речи]
Index: []

In [ ]:
# @title
%%writefile task.twol
'%%writefile aghul_numerals.twol'
Alphabet
  а б в г д е ё ж з и й к л м н о п р с т у ф х ц ч l ш щ ъ ы ь э ю я
  %{Д%}:д %{Д%}:й %{Д%}:0 %{X%}:0;
Rules
"д переходит в й перед падежными окончаниями единственного числа"
%{Д%}:й <=> _ и ;

"конечный д в числительных наречиях"
%{Д%}:0 <=> _ %{X%}:0 ;

Overwriting task.twol

In [ ]:
!make

Cleaning up old install, if any...
removed '/etc/apt/trusted.gpg.d/apertium.gpg'
removed '/etc/apt/preferences.d/apertium.pref'
removed '/etc/apt/sources.list.d/apertium.list'
Determining Debian/Ubuntu codename...
Found evidence of jammy...
Settling for jammy - enabling the Apertium nightly repo...
Installing Apertium GnuPG key to /etc/apt/trusted.gpg.d/apertium.gpg
Installing package override to /etc/apt/preferences.d/apertium.pref
Creating /etc/apt/sources.list.d/apertium.list
Running apt-get update...
All done - enjoy the packages! If you just want all core tools, do: sudo apt-get install apertium-all-dev
sudo apt-get install hfst lexd
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
hfst is already the newest version (3.17.1+g4008~52376baa-4~jammy1).
lexd is already the newest version (1.3.5+g180~55b0b7b6-20~jammy1).
0 upgraded, 0 newly installed, 0 to remove and 22 not upgraded.

In [ ]:
!make forms

task.generator.hfst is not a valid transducer file
make: *** [Makefile:33: forms] Error 1

In [ ]:
!make clean

#Pronouns

In [ ]:
#%%writefile task.lexd
%%writefile aghul_pronouns.lexd

PATTERNS
PronStem PronCase


LEXICON PronStem
зун<prn><p1><sg>:з{X} #я
вун<prn><p2><sg>:в{X} #ты
хъин<prn><p1><pl><inc>:хъ #мы инк
чин<prn><p1><pl><inc>:чи #мы экс
чун<prn><p2><pl><inc>:чу #вы

LEXICON PronCase
<nom>:н
<erg>:н
<gen>:
<dat>:ас
<ins>:лди
<psl1>:фай
<psl2>:хъай
<psl3>:гIай

<loc1>:ф
<loc2>:гь
<loc3>:хь
<loc4>:кк
<loc5>:к
<loc6>:'
<loc7>:л
<loc8>:гI

Overwriting aghul_pronouns.lexd

In [ ]:
%%writefile task.twol
Alphabet

Rules

Overwriting task.twol

In [ ]:
!make forms

RulesException: HfstException in file: htwolcpre1-parser.yy on line: 541
hfst-compose-intersect: Error: twol.hfst is not a valid transducer file
make: *** [Makefile:11: task.generator.hfst] Error 1

In [ ]:
!make clean

#Nouns

In [ ]:
#suppletive
'''хьир хумбар
руш шигlвар
уд ударар
ху хупур
гъуй гъурувур'''

'хьир хумбар\nруш шигlвар\nуд ударар\nху хупур\nгъуй гъурувур'

In [ ]:
# @title
@title
LEXICON Noun
LEXICON NounSgErg
ӏаб:ӏаба
ӏаб:ӏабала
ӏатӏуб:ӏатӏуба
ӏачӏ:ӏачӏа
ӏевам:ӏевами
ӏекьул:ӏекьулди
ӏелим:ӏелимди
ӏемал:ӏемалди
ӏешал:ӏешали
ӏурд:ӏурди
ӏучал:ӏучали
ӏуькӏ:ӏуькӏи
ӏуьмур:ӏуьмурди
ӏуьрдеккен:ӏуьрдеккенди
ӏуьтӏуб:ӏуьтӏуба
ӏуьш:ӏуьша
абанкьул:абанкьули
агуб:агуба
агъ:агъди
агъ:агъу
агъу:агъуйи
ад:аду
айван:айванди
айгъур:айгъура
алат:алати
алучӏуб:алучӏуба
арс:арсура
аслан:асланди
атӏуб:атӏуба
ахсар:ахсари
ахтта:ахттайи
ахттигьар:ахттигьарди
ахун:ахуни
ахъихьуб:ахъихьуба
ачӏ:ачӏа
аш:ашуни
ашкӏин:ашкӏинди
баб:баба
багам:багами
багниш:багниши
багур:багура
багъ:багъди
багъ:багъу
багъдихъан:багъдихъанди
багьадур:багьадура
бадра:бадрайи
бармак:бармаки
беӏ:беӏуь
берхӏем:берхӏеми
бишикӏ:бишикӏи
бугъ:бугъу
бугьу:бугьуйи
булах:булахи
вурдж:вурджуни
вакк:ваккала
вакъ:вакъала
ватан:ватанди
вахтт:вахттуни
вев:веву
вец:вецуна
гӏабдал:гӏабдали
гӏад:гӏадура
гӏан:гӏана
гӏаттивуб:гӏаттивуба
гӏафна:гӏафнайи
гӏелим:гӏелимди
гӏихьуб:гӏихьуба
гӏуб:гӏубура
гӏуд:гӏудура
гӏул:гӏули
гӏур:гӏура
гӏурч:гӏурча
гӏурчахъан:гӏурчахъанди
гавгьар:гавгьари
газа:газайи
гал:галу
гап:гапу
гардан:гарданди
гаш:гаши
гвадж:гваджа
гилегв:гилегви
гим:гими
гирав:гирави
гирген:гиргени
гитан:гитани
гуг:гугу
гугурт:гугурти
гунагь:гунагьи
гур:гура
гъаб:гъабала
гъавур:гъавурди
гъад:гъадала
гъазеттар:гъазеттари
гъалатӏ:гъалатӏи
гъам:гъамуни
гъара:гъарайи
гъараг:гъараги
гъвад:гъвади
гъван:гъванди
гъил:гъили
гъилив:гъиливи
гъун:гъуна
гъурагъал:гъурагъали
гъурбат:гъурбати
гъургъуб:гъургъуба
гъурд:гъурдала
гъурт:гъурту
гъуч:гъучу
гьава:гьавайи
гьеч:гьечи
гьудуркӏуб:гьудуркӏуба
гьуккуб:гьуккуба
гьунар:гьунари
гьучархьеб:гьучархьеба
дабакь:дабакьи
дабан:дабани
дагьар:дагьари
дагьра:дагьрайи
дагьур:дагьури
дад:дада
дайиб:дайиба
дакьикьа:дакьикьайи
далил:далили
дамдам:дамдами
дан:данди
дарагъадж:дарагъаджи
дарамат:дарамати
дард:дардуни
дарман:дармани
дарс:дарсуни
дарчин:дарчини
дасмал:дасмали
дафттар:дафттари
деве:девейи
джегьенем:джегьенемди
джемеӏет:джемеӏети
джил:джили
джихер:джихери
джуваб:джуваба
диф:дифура
дукӏ:дукӏу
дурахал:дурахалди
дуруц:дуруци
дурхӏуб:дурхӏуба
дустт:дусттура
дусттагъ:дусттагъи
духттур:духттури
дуч:дучу
душман:душманди
дуьнйа:дуьнйайи
дуьхӏуьб:дуьхӏуьби
зав:заву
зерфел:зерфели
зерфел:зерфели
ивур:ивури
ивурихъан:ивурихъанди
ибхь:ибхьи
ибцӏел:ибцӏели
игит:игити
игитвел:игитвелди
идара:идарайи
иджвел:иджвелди
илан:иланди
илдеш:илдеши
иллевел:иллевелди
иллеф:иллефилетти
инсан:инсанди
инсанвел:инсанвелди
ис:иса
исал:исали
иттал:иттали
иттал:иттали
иф:ифа
ифул:ифули
ицӏул:ицӏули
ишан:ишанди
ишан:ишанди
иъ:иъи
йирхӏуб:йирхӏуба
кӏапӏал:кӏапӏали
кӏаш:кӏашала
кӏеб:кӏеба
кӏедж:кӏеджи
кӏетӏа:кӏетӏайи
кӏил:кӏили
кӏиркӏ:кӏиркӏа
кӏунтӏ:кӏунтӏала
кӏур:кӏура
кӏур:кӏурани
кӏурар:кӏурари
кӏучӏ:кӏучӏала
кавха:кавхайи
кантӏ:кантӏала
кар:карди
кедихьуб:кедихьуба
келпит:келпити
келхъуьб:келхъуьба
кепек:кепеки
кируцуб:кируцуба
кквахӏ:кквахӏу
ккекк:ккеккела
ккел:ккела
кулагъ:кулагъи
кулак:кулаки
кум:кума
кум:кума
кумак:кумаки
кутӏул:кутӏули
кутӏул:кутӏули
куц:куца
куьча:куьчайи
къаб:къабу
къавахӏан:къавахӏанди
къайда:къайдайи
къала:къалайи
къапувур:къапувури
къаравул:къаравулди
къатир:къатири
къафлан:къафланди
къачагъ:къачагъа
къвал:къвала
къваркъв:къваркъва
къвац:къвацала
къемч:къемчу
къизил:къизилди
къирагъ:къирагъди
къуджа:къуджайи
къургъушум:къургъушумди
къух:къуху
къучма:къучмайи
къушум:къушумди
кьаб:кьабу
кьабуч:кьабуча
кьал:кьали
кьастт:кьасттуни
кьасу:кьасуйи
кьел:кьелкьела
кьибла:кьиблайи
кьулбан:кьулбанди
кьун:кьуна
кьуркь:кьуркьа
кьуркь:кьуркьа
кьутӏур:кьутӏури
лек:леку
лекар:лекари
лиӏ:лиӏура
лихун:лихуни
лихъун:лихъуни
лукӏ:лукӏу
луф:луфура
луькӏеб:луькӏеба
мав:маву
магӏишат:магӏишати
маджал:маджали
майдан:майданди
маккал:маккали
мактаб:мактаби
макьала:макьалайи
малайик:малайикди
малла:маллайи
маркв:марквмарку
мархал:мархали
мац:маца
мац:маца
мегӏелим:мегӏелимди
мегӏна:мегӏнайи
мез:мезура
мехь:мехьи
милат:милати
муг:мугуйи
мугӏ:мугӏуйи
муджур:муджури
мукь:мукьуйи
мурад:муради
мурз:мурзуни
муртт:муртту
мурхӏ:мурхӏуйи
мурхьил:мурхьили
муул:муули
мух:муха
мухур:мухури
мухуригьан:мухуригьанди
мучӏ:мучӏина
некк:неккди
некьв:некьвди
некьв:некьвди
нецӏв:нецӏвнецӏу
нецӏвар:нецӏвари
нис:ниси
нубат:нубати
пайгъамбар:пайгъамбарди
парӏ:парӏу
паччагь:паччагьди
паччагьвел:паччагьвелди
пеӏ:пеӏела
пиша:пишайи
пул:пулу
рагӏ:рагӏу
рагъ:рагъу
ракк:ракка
ратт:ратти
рекъ:рекъуь
руг:ругу
рудж:руджура
рукъал:рукъали
рукь:рукьа
рукьар:рукьари
ручӏ:ручӏу
руьхӏ:руьхӏди
сагъ:сагъди
сив:сиви
силеб:силеби
суал:суали
сув:сува
сул:сула
сур:сури
сурӏуьш:сурӏуьша
сурат:сурати
сус:суса
суфра:суфрайи
суьл:суьли
тӏабиӏет:тӏабиӏети
тӏагар:тӏагари
тӏакьв:тӏакьва
тӏалаб:тӏалаби
тӏибитӏ:тӏибитӏи
тӏубул:тӏубула
тӏул:тӏула
тӏун:тӏуна
тарих:тарихди
тарих:тарихди
текӏил:текӏили
ттур:ттурари
тук:туку
тум:туму
тухум:тухумди
угал:угали
угъал:угъали
укъуб:укъуба
ул:ули
урч:урчуна
ус:уса
утун:утуни
фикир:фикирди
фун:фуни
хӏабаб:хӏабаба
хӏадад:хӏадад
хӏаягъ:хӏаягъа
хӏейван:хӏейванди
хӏекь:хӏекьди
хӏеракатлу:хӏеракатлуйи
хӏефтта:хӏефттайи
хӏикат:хӏикати
хӏуппахъан:хӏуппахъанди
хӏур:хӏури
хӏуч:хӏуча
хӏуьл:хӏуьли
хӏуяг:хӏуяги
хабар:хабарди
хабарчи:хабарчийи
халкь:халкьди
хибхел:хибхели
хизан:хизанди
хил:хили
хулагъ:хулагъи
хъадикӏиб:хъадикӏиба
хъаттхуруб:хъаттхуруба
хъветт:хъветтала
хъуьссу:хъуьссуий
хьар:хьара
цӏагъун:цӏагъуни
чӏал:чӏала
чӏар:чӏара
чӏекӏ:чӏекӏела
чӏил:чӏили
чӏилӏан:чӏилӏани
чӏир:чӏири
чувал:чували
чуллевел:чуллевелди
шавлар:шавлари
шагьидвел:шагьидвелди
шагьур:шагьурди
шиниккв:шиникквди
шишал:шишали
яӏар:яӏари
яӏар:яӏари
ягӏарвел:ягӏарвелди
ягъ:ягъа
якӏв:якӏвала
ӏашв:ӏашу
ӏекв:ӏеку
Аллагь:Аллагьди
абаб:абаба
агӏай:агӏайи
адад:адада
адждагьа:аджагьайи
асхъай:асхъайи
ахв:аху
багв:багу
будай:буди
ӏаб:ӏаба
ваз:вазура
гӏалашуй:гӏалашува
гӏедат:гӏедати
ӏаб:ӏаба
гаф:гафтти
гъуй:гъвара
дар:дара
делекчи:делекчи
джан:джанди
джаннат:джаннати
джикас:джикай
емиш:емиша
йиркӏв:йиркӏура
кӏен:кӏена
ккабалай:ккабали
кьур:кьвара
лихъванас:лихъванди
мекӏ:микӏила
мерккв:мерккура
мехъв:мехъуь
рехӏет:рехӏетти
руш:руша
сеӏет:сеӏетти
хӏуб:хӏуппа
хӏуькумат:хӏуькуматти
хал:хула
ху:хуйи
хумбеф:хумбетти
хъехъв:хъехъуь
хьид:хьиди
хьиджарбаб:хьиджарбаба
хьиджардад:хьиджардада
хьир:хьира
цӏа:цӏи
цал:цили
чи:ччиччи
чу:ччуччу
шуй:шува
яхв:яху

LEXICON NounPlNom
ӏаб:ӏабар
ӏатӏуб:ӏатӏубар
ӏачӏ:ӏачӏар
ӏевам:ӏевамар
ӏелим:ӏелимар
ӏемал:ӏемалар
ӏешал:ӏешалар
ӏучал:ӏучалар
ӏуькӏ:ӏуькӏер
ӏуьмур:ӏуьмурар
ӏуьрдеккен:ӏуьрдеккенар
ӏуьтӏуб:ӏуьтӏубар
ӏуьш:ӏуьшар
абанкьул:абанкьулар
агуб:агубар
агъ:агъар
агъ:агъар
агъу:агъувур
ад:адар
айван:айванар
айгъур:айгъурар
алат:алатар
алучӏуб:алучӏубар
аслан:асланар
атӏуб:атӏубар
ахсар:ахсарар
ахтта:ахттавур
ахттигьар:ахттигьарар
ахттилатчи:ахттилатчивур
ахун:ахунар
ахъихьуб:ахъихьубар
ачӏ:ачӏар
аш:ашар
ашкӏин:ашкӏинар
баб:бабар
багам:багамар
багниш:багнишар
багур:багурар
багъ:багъар
багъ:багъар
багъдихъан:багъдихъанар
багьадур:багьадурар
бадра:бадравур
бармак:бармакар
беӏ:беӏер
бегӏли:бегӏливур
берхӏем:берхӏемар
бизи:бизивур
бишикӏ:бишикӏар
бугьу:бугьувур
булах:булахар
вурдж:вурджар
вакк:ваккар
вакъ:вакъар
вахтт:вахттар
вев:вевер
вец:вецар
гӏабдал:гӏабдалар
гӏад:гӏадар
гӏан:гӏанар
гӏаттивуб:гӏаттивубар
гӏафна:гӏафнавур
гӏелим:гӏелимар
гӏилми:гӏилмивур
гӏихьуб:гӏихьубар
гӏуб:гӏубар
гӏуд:гӏудар
гӏул:гӏулар
гӏур:гӏурар
гӏурч:гӏурчар
гӏурчахъан:гӏурчахъанар
гавгьар:гавгьарар
газа:газавур
гал:галар
гап:гапар
гардан:гарданар
гвадж:гваджар
гилегв:гилегвар
гим:гимар
гирав:гиравар
гирген:гиргенар
гитан:гитанар
гуг:гугар
гунагь:гунагьар
гуни:гунивар
гур:гурар
гъаб:гъабар
гъад:гъадар
гъалатӏ:гъалатӏар
гъам:гъамар
гъара:гъаравур
гъараг:гъарагар
гъарачи:гъарачивур
гъвад:гъвадар
гъван:гъванар
гъил:гъилар
гъилив:гъиливар
гъун:гъунар
гъурагъал:гъурагъалар
гъургъуб:гъургъубар
гъурд:гъурдар
гъурт:гъуртар
гъуч:гъучар
гьава:гьававур
гьеч:гьечар
гьудуркӏуб:гьудуркӏубар
гьуккуб:гьуккубар
гьунар:гьунарар
гьучархьеб:гьучархьебар
дабакь:дабакьар
дабан:дабанар
дагьар:дагьарар
дагьра:дагьравур
дагьур:дагьурар
дад:дадар
дайиб:дайибар
дакьикьа:дакьикьавур
далил:далилар
дамдам:дамдамар
дан:данар
дарагъадж:дарагъаджар
дарамат:дараматар
дард:дардар
дарман:дарманар
дарс:дарсар
дарчин:дарчинар
дасмал:дасмалар
дафттар:дафттарар
деве:девевур
дегӏви:дегӏвивур
джемеӏет:джемеӏетар
джил:джилар
джихер:джихерар
джуваб:джувабар
диф:дифар
дукӏ:дукӏар
дуканчи:дуканчивур
дурахал:дурахалар
дуруц:дуруцар
дурхӏуб:дурхӏубар
дустт:дусттар
дусттагъ:дусттагъар
духттур:духттурар
дуч:дучар
душман:душманар
дуьнйа:дуьнйавур
дуьхӏуьб:дуьхӏуьбар
зав:завар
зарафатчи:зарафатчивур
зерфел:зерфелар
зерфел:зерфелар
ивур:ивурар
ивурихъан:ивурихъанар
ибхь:ибхьер
ибцӏел:ибцӏелар
игит:игитар
идара:идаравур
идеми:идемиар
иджвел:иджвелар
илан:иланар
илдеш:илдешар
иллеф:иллефилар
инсан:инсанар
ис:исар
исал:исалар
иттал:итталар
иттал:итталар
ифул:ифулар
ицӏул:ицӏулар
ишан:ишанар
ишан:ишанар
ишкилчи:ишкилчивур
иъ:иъер
йирхӏуб:йирхӏубар
кӏапӏал:кӏапӏалар
кӏаш:кӏашар
кӏеб:кӏебар
кӏедж:кӏеджар
кӏетӏа:кӏетӏавур
кӏил:кӏилар
кӏиркӏ:кӏиркӏар
кӏунтӏ:кӏунтӏар
кӏур:кӏурар
кӏур:кӏурар
кӏучӏ:кӏучӏар
кавха:кавхавур
кантӏ:кантӏар
кар:карар
кедихьуб:кедихьубар
келпит:келпитар
келхъуьб:келхъуьбар
кепек:кепекар
кируцуб:кируцубар
кквахӏ:кквахӏар
ккекк:ккеккер
ккел:ккелар
кулагъ:кулагъар
кулак:кулакар
кумак:кумакар
кумакчи:кумакчивур
кутӏул:кутӏулар
кутӏул:кутӏулар
куьча:куьчавур
къаб:къабар
къавахӏан:къавахӏанар
къайда:къайдавур
къала:къалавур
къаравул:къаравулар
къари:къаривур
къатир:къатирар
къафлан:къафланар
къачагъ:къачагъар
къвал:къвалар
къваркъв:къваркъвар
къвац:къвацар
къемч:къемчар
къемчи:къемчивур
къирагъ:къирагъар
къири:къиривур
къуджа:къуджавур
къунши:къуншивур
къух:къухар
къучма:къучмавур
къушум:къушумар
кьаабчи:кьаабчивур
кьаб:кьабар
кьабуч:кьабучар
кьал:кьалар
кьастт:кьасттар
кьасу:кьасувур
кьвани:кьванивур
кьулбан:кьулбанар
кьун:кьунар
кьуркь:кьуркьар
кьуркь:кьуркьар
кьутӏур:кьутӏурар
лек:лекар
лиӏ:лиӏер
лихун:лихунар
лихъун:лихъунар
лукӏ:лукӏар
луф:луфар
луькӏеб:луькӏебар
магӏишат:магӏишатар
маджал:маджалар
майдан:майданар
маккал:маккалар
мактаб:мактабар
макьала:макьалавур
макьалачи:макьалачивур
малайик:малайикар
малла:маллавур
маркв:марквмаркар
мархал:мархалар
мац:мацар
мац:мацар
мегӏелим:мегӏелимар
мегӏни:мегӏнивур
мез:мезар
мехь:мехьер
милат:милатар
милатчи:милатчивур
муг:мугар
мугӏ:мугӏар
муджур:муджурар
мукь:мукьар
мурад:мурадар
мурз:мурзар
муртт:мурттар
мурхӏ:мурхӏар
мурхьил:мурхьилар
муул:муулар
мухур:мухурар
мухуригьан:мухуригьанар
мучӏ:мучӏар
некьв:некьвар
нецӏв:нецӏвар
нис:нисар
нубат:нубатар
пайгъамбар:пайгъамбарар
парӏ:парӏар
паччагь:паччагьар
паччагьвел:паччагьвелар
пеӏ:пеӏер
пиша:пишавур
пул:пулар
пут:путар
рагӏ:рагӏар
рагъ:рагъар
ракк:раккар
ратт:раттар
рекъ:рекъер
руг:ругар
рудж:руджар
рукъал:рукъалар
руьхӏ:руьхӏар
сив:сивар
силеб:силебар
суал:суалар
сув:сувар
сул:сулар
сур:сурар
сурӏуьш:сурӏуьшар
сурат:суратар
сус:сусар
суфра:суфравур
суьри:суьривур
тӏагар:тӏагарар
тӏалаб:тӏалабар
тӏибитӏ:тӏибитӏар
тӏубул:тӏубулар
тӏул:тӏулар
тӏун:тӏунар
тарих:тарихар
тарих:тарихар
текӏил:текӏилар
ттур:ттурар
тук:тукар
тум:тумар
тухум:тухумар
угал:угалар
угъал:угъалар
укъуб:укъубар
ул:улар
урч:урчар
ус:усар
утун:утунар
фикир:фикирар
фун:фунар
хӏабаб:хӏабабар
хӏадад:хӏададар
хӏаягъ:хӏаягъар
хӏейван:хӏейванар
хӏеракатлу:хӏеракатлувур
хӏефтта:хӏефттавур
хӏикат:хӏикатар
хӏуни:хӏунивар
хӏуппахъан:хӏуппахъанар
хӏур:хӏурар
хӏуч:хӏучар
хӏуьл:хӏуьлар
хӏуяг:хӏуягар
хабар:хабарар
хабарчи:хабарчивур
халкь:халкьар
хибхел:хибхелар
хизан:хизанар
хил:хилар
хулагъ:хулагъар
хъадикӏиб:хъадикӏибар
хъаттхуруб:хъаттхурубар
хъветт:хъветтар
хъуьссу:хъуьссувур
хьар:хьарар
цӏагъун:цӏагъунар
чӏал:чӏалар
чӏар:чӏарар
чӏекӏ:чӏекӏер
чӏигъанчи:чӏигъанчивур
чӏил:чӏилар
чӏилӏан:чӏилӏанар
чӏир:чӏирар
чакмачи:чакмачивур
чувал:чувалар
чуллевел:чуллевелар
шагьидвел:шагьидвелар
шагьур:шагьурар
шиниккв:шиникквар
шишал:шишалар
эесси:эессивур
яӏар:яӏарар
яӏар:яӏарар
ягӏарвел:ягӏарвелар
ягъ:ягъар
якӏв:якӏвар
мурхӏ:мурхӏар
ӏашв:ӏашвар
абаб:абабар
агӏай:агӏаяр
адад:ададар
адждагьа:аджагьабур
асхъай:асхъаяр
ахв:ахвар
багв:багвар
будай:будаяр
ваз:вазар
гӏалашуй:гӏалашувар
гӏалашуй:гӏулар
гӏедат:гӏедатар
гаф:гафар
гъуй:гъурур
дар:дарар
делекчи:делекчибур
джикас:джикуна
емиш:емишар
йиркӏв:йиркӏвар
ккабалай:ккабалаяр
лихъванас:лихъуна
мекӏ:мекӏер
мерккв:меркквар
мехъв:мехъвар
руш:рушар
руш:шибер
сеӏет:сеӏетар
хӏуб:хӏуппар
хӏуькумат:хӏуькуматар
хал:хулар
ху:хуппар
хумбеф:хумбар
хъехъв:хъехъвер
хьиджарбаб:хьиджарбабар
хьиджардад:хьиджардадар
хьир:хумбар
цӏа:цӏабур
цал:цилар
чи:чияр
чу:чуппар
шуй:шувар
яхв:яхвар

SyntaxError: invalid syntax (2881759496.py, line 3)

In [ ]:
# @title
:а[1]
:йи[2]
:и[3]
:и[4]
:и[5]
:-[6] #цlа-цlи
:айи[7]
:уни[8]
:ани[9]
:ди[10]
:ала[11]
:ва[12] #шуй
:уна[13] #вец-уна бык, ярд-уна бычок, луч1-уна - телка, урч-уна
:ура[14]
:ела[15]
:уь[16]
:й[17]
:б[18]
:[19] #чи-ччиччи чу-ччуччу

In [ ]:
%%writefile task.lexd
PATTERNS
Noun
(Noun Ergative)[^[1,2,8]] > (Case | (Locative Series))
(Noun Plural)[^[1,2,8]] > [:и] (Case | (Locative Series))

LEXICON Noun
<n>:дад[1]
<n>:геда[2]
бахт<n>:бахт[8]


LEXICON Plural
<pl>:ар[1] #plur on cons
<pl>:вур[2] #plur on vow

#Classes (эргатив, косвенные основы)
LEXICON Ergative
:а[1]
:йи[2]
:уни[8]


LEXICON Case
<erg>:
<gen>:н
<dat>:с
<instr>:лди
<post1>:фай
<post2>:хъай
<post3>:г1ай

LEXICON Locative
<loc1>:ф
<loc2>:гь
<loc3>:хъ
<loc4>:кк
<loc5>:к
<loc6>:'
<loc7>:л
<loc8>:гl

LEXICON Series
<calm>:
<futh>:ас
<clos>:ди

Overwriting task.lexd

In [ ]:
!make forms

In [ ]:
!make clean

#Adjectives

#Verbs

In [ ]:
# %%writefile aghul_verbs.lexd
%%writefile aghul_verbs.lexd
PATTERNS
Inf
Neg? Imp CheckInf? Participle

PATTERN Inf
Neg? Imp > ((Stem1 > (StemPerf | CheckInf| (CheckInf StemPerf))) InfSuffix)

LEXICON Imp
акь

LEXICON InfSuffix
<inf>:c

LEXICON Stem1
:а

LEXICON Neg
<neg>:д

LEXICON StemPerf
<perf>:гуна

LEXICON CheckInf
<checkadv>:чукьа

LEXICON Participle
<ipf><pt><prs>:аф
<ipf><pt><prf>:уф
<ipf><pt><hab>:аеф
<ipf><pt><aor>:унаеф

Writing aghul_verbs.lexd

PT причастие
PT:PRS презентное причастие
PT:PRF перфектное причастие
PT:HAB хабитуальное причастие
PT:AOR аористное причастие

In [ ]:
PATTERNS VerbMorf
<cit>:агъай

In [ ]:
type(csv_to_table(mulla_i_uchenik, "mulla_i_uchenik.csv"))

           cyr         lat                     gloss
0       дагина     dagi꞊na                    осел=и
1         деве        dewe                   верблюд
2        хьуне      x.u-ne              стать.PF-AOR
3        агъай        aʁaj                       CIT
4     хьундава   x.u-ndawa          стать.PF-AOR:NEG
..         ...         ...                       ...
209  алайхьуне  alajx.u-ne  SUPER-DOWN-класть.PF-AOR
210         ме          me                      DEMM
211       даги        dagi                      осел
212      нецlу      nec’.u                 река(ERG)
213    файшуне   fajš.u-ne            уносить.PF-AOR

[214 rows x 3 columns]

NoneType

In [ ]:
dct[(dct['часть речи']=='NOUN') & (dct['диалектологизм']=='нет')]

In [ ]:
!make forms

#Тексты

In [ ]:
import pandas as pd
from io import StringIO

def csv_to_table(csv_text, name):
  df = pd.read_csv(StringIO(csv_text))
  df['cyr'] = df['cyr'].str.lower().str.replace('i', 'l')
  display(df)
  df.to_csv(name, index=False, encoding="utf-8-sig")

In [ ]:
# @title Как школьники поймали лису
csv_caught_fox = r"""
cyr,lat,gloss
Суваъ,suw.a-ʔ,гора-IN
Чин,čin,мы:EXCL
сува,suw.a,гора(IN)
агъавейгана,aʁaw.e-j-gana,подниматься.IPF-PT-TEMP
ичас,iča-s,мы:EXCL-DAT
ссул,sːul,лиса
гьаркинав,hark.i-naw,встречаться.PF-AOR
Хъаркьигана,qarq’.i-gana,достигать.PF-TEMP
марччлихъанарис,marčːliqan-ar.i-s,пастух_овец-PL-DAT
пунав,p.u-naw,говорить.PF-AOR
пуна,p.u-na,говорить.PF-CONV
Тари,tar.i,DEMT:PL(ERG)
зарафатар,zarafat-ar,шутка-PL
акьай,aq’.a-j,делать.IPF-CONV
пунай,p.u-naj,говорить.PF-AOR:PST
Фас,fas,почему
авайсинда,awajs.i-nda,хватать.PF-AOR:NEG
чвун,cun,вы
кьацIайкIис,q’ac’-ajk’.i-s,укус-{IN}совать.INF-INF
гичI,gič’,страх
хьинай,x.i-naj,стать.PF-AOR:PST
Марччар,marčː-ar,овца-PL
узуна,uz.u-na,доить.PF-CONV
ккеркIин,kːerk’.i-n,заканчивать.PF-GEN
хав,χaw,назад
хала,χal.a,дом(IN)
вейгана,w.e-j-gana,идти.IPF-PT-TEMP
сса,sːa,один
марччалихъан,marčːaliqan,пастух_овец
гьатас,hat.a-s,посылать.INF-INF
аргинай,arg.i-naj,приходить.PF-AOR:PST
тиндис,tin.di-s,DEMT-DAT
гьарка,hark.a,встречать.PF
исв,isʷ,место
раькъ’аьс,räqːˁ.ä-s,видеть.INF-INF
кьунай,q’.u-naj,делать.PF-AOR:PST
Тиме,time,DEMT(ABS)
йикIваригI,jik’ʷ-ar.i-ʕ,трава-PL-INTER
гъванаригI,ʁʷan-ar.i-ʕ,камень-PL-INTER
ливуна,liw.u-na,смотреть.PF-CONV
агунай,ag.u-naj,видеть.PF-AOR:PST
час,ča-s,мы:EXCL-DAT
раькъ’ир,räqːˁ.i-r,видеть.PF-S
хьуй,xuj,словно
гьалганас,halg.an-as,убегать.INF-INF
хъахинай,qaχ.i-naj,начинать.PF-AOR:PST
Амма,amma,но
къ’аьттей,qːˁätːe-j,хромой-S
хьубас,x.u-b.a-s,стать.PF-MSD-DAT
ссулас,sːul.a-s,лиса-DAT
хьиндай,x.i-ndaj,мочь.PF-AOR:PST:NEG
фикир,fikir,мысль
кьундай,q’.u-ndaj,делать.PF-AOR:PST:NEG
вуйир,wu-ji-r,COP-PT-S
питIен,p.i-t’en,говорить.PF-COND
Марччлихъанди,marčːliqan.di,пастух_овец(ERG)
Эй,ej,эй
гичIрухIар,gič’ruʜ-ar,трус-PL
чвакес,ca-k-es,вы-CONT-ELAT
зурба,zurba,смелый
хьистта,x.i-s-tːa,стать.INF-INF-COP:NEG
Тигана,ti-gana,DEMT-TEMP
чал,ča-l,мы:EXCL-SUPER
алди,al-di,{SUPER}быть-CONV
миндай,mindaj,не_будучи
авайсина,awajs.i-na,хватать.PF-CONV
мектебдин,mekteb.di-n,школа-GEN
илагьди,ilah-di,впереди-LAT
Ме,me,DEMM
вахттна,waχtː.na,время(TMR)
вари,wari,все
бе’жаьр,beˁž-är,парень-PL
рушар,ruš-ar,девушка-PL
танафусдиъ,tanafus.di-ʔ,перемена-IN
ай,a-j,{IN}быть-CONV
шад,šad,радостный
ХъалтIуна,qalt’.u-na,{POST}завязывать.PF-CONV
ликрихъ,lik.ri-q,нога-POST
тIурин,t’urin,веревка
ссулакес,sːul.a-k-es,лиса-CONT-ELAT
тамашавур,tamaša-wur,игра-PL
ХIавахъдис,ʜawaq.di-s,вечер-DAT
шавлахьина,šawla-x.i-na,усталый-стать.PF-CONV
кIинай,k’.i-naj,умирать.PF-AOR:PST
"""

In [ ]:
# @title О селе
csv_o_sele = r"""
cyr,lat,gloss
Зун,zun,я
АрсугI,arsuʕ,Арсуг
яшамиш,jašamiš,<жить>
ваьйъа,w.ä-jʔa,стать.IPF-PRS
Ич,ič,наш:EXCL
гъул,ʁul,село
уцIид,uc’i-d,маленький-S
ву,wu,COP
КIилди,k’ildi,целиком
айид,a-ji-d,{IN}быть-PT-S
йишвцIур,jisc’ur,50
хал,χal,дом
Илагьас,ilah-as,впереди-ELAT
гъулаъ,ʁul.a-ʔ,село-IN
рухридар,ruχ-ri-d-ar,учиться:PF-PT-S-PL
чIвукь,c’uq’,немного
ай,a-j,{IN}быть-PST
Гьиъил,hiʔil,теперь
мектеб,mekteb,школа
ъа,ʔa,{IN}быть:PRS
Джилла,ǯilla,все
баьжар,bäž-ar,парень-PL
рушари,ruš-ar.i,девушка-PL(ERG)
рухай,ruχ.a-j,учиться.IPF-CONV
калхузра,kalχuz꞊ra,колхоз=ADD
Калхуз,kalχuz,колхоз
давлатлу,dawlatlu,богатый
калхуздиъ,kalχuz.di-ʔ,колхоз-IN
йишву,jisu,пять
азур,azur,тысяча
ме’рчч,meˁrčː,овца
гьил,hil,теперь
раькъ’аьр,räqːˁ-är,дорога-PL
иджидар,iǯi-d-ar,хороший-S-PL
Чин,čin,мы:EXCL
машинариъ,mašin-ar.i-ʔ,машина-PL-IN
шагьурди,šahur.di,город(IN)
ваьв,w.ä-w,идти.IPF-CONV+COP
Гьуьлин,hül.i-n,море-GEN
къирагъдихъ,qːiraʁ.di-q,край-POST
калхуздин,kalχuz.di-n,колхоз-GEN
гал,gal,кутан
хъа,qa,{POST}быть:PRS
Кь’урдана,q’ˁurd.ana,зима(TMR)
гали,gal.i,кутан(IN)
ме’рччар,meˁrčː-ar,овца-PL
гьатав,hat.a-w,посылать.IPF-CONV+COP
Ез,jez,мой
чвуй,cuj,брат
мерччлихъан,merčːliqan,пастух_овец
чи,či,сестра
муьаллим,müallim,учитель
гаг,gag,отец
кь’усед,q’ˁuse-d,старый-S
бав,baw,мать
шибу,šibu,три
иснан,is.na-n,год-GEN
илагь,ilah,впереди
кIинав,k’.i-naw,умирать.PF-AOR
кь’усе,q’ˁuse,старый
лап,lap,очень
кIинай,k’.i-naj,умирать.PF-AOR:PST
Захъ,za-q,я-POST
х’аьведра,χˁäwe-d꞊ra,жена-S=ADD
кь’у,q’ˁu,два
уцIидра,uc’i-d꞊ra,маленький-S=ADD
са,sa,один
баьжна,bäž꞊na,сын=и
руш,ruš,дочь
баьжин,bäž.i-n,сын-GEN
ис,is,год
рушан,ruš.a-n,дочь-GEN
исналас,is.na-l-as,год-SUPER-ELAT
баьж,bäž,сын
мектебдиъ,mekteb.di-ʔ,школа-IN
хису,χ.i-s-u,уходить.INF-INF-COP
Гъулан,ʁul.a-n,село-GEN
къирахар,qːiraχ-ar,край-PL
баьх’аь,bäχˁä,красивый
исвар,isʷ-ar,место-PL
тисариъ,ti-s-ar.i-ʔ,DEMT-LOC-PL-IN
ккелцанас,kːelc.an-as,гулять.INF-INF
ппара,pːara,много
джегьил,ǯehil,молодой
сусар,sus-ar,невеста
сус,sus,невеста
Зас,za-s,я-DAT
гим,gim,DEMG(ABS)
ккандив,kːan-di-w,любить-CONV-COP
Цулана,cul.ana,осень(TMR)
цIакIинар,c’ak’in-ar,свадьба-PL
акьазун,aq’.a-zun,делать.INF-я
"""

In [ ]:
#@title mulla_i_uchenik
mulla_i_uchenik = r"""cyr,lat,gloss
Дагина,dagi꞊na,осел=и
деве,dewe,верблюд
Хьуне,x.u-ne,стать.PF-AOR
агъай,aʁaj,CIT
хьундава,x.u-ndawa,стать.PF-AOR:NEG
агъай,aʁaj,CIT
са,sa,один
касиб,kasib,бедный
идеми,idemi,мужчина
Тихъ,ti-q,DEMT-POST
хъай,qa-j,POST-быть-PST
агъай,aʁaj,CIT
са,sa,один
дагина,dagi꞊na,осел=и
са,sa,один
деве,dewe,верблюд
Мин,mi-n,DEMM-GEN
тебур,te-bur,DEMT-PL
забун,zabun,худой
хьуне,x.u-ne,стать.PF-AOR
луькIуь,lük’.ü,умирать.IPF
хIалдил,ʜal.di-l,состояние-SUPER
адине,ad.i-ne,приходить.PF-AOR
Хуппай,χupːaj,потом
мебур,me-bur,DEMM-PL
ме,me,DEMM
касибди,kasib.di,бедный(ERG)
Зас,za-s,я-DAT
аргвай,argʷ.a-j,видеть.IPF-CONV
луькIуьйдала,lük’.ü-j꞊dala,умирать.IPF-CONV=CMP
зас,za-s,я-DAT
даргвай,d-argʷ.a-j,NEG-видеть.IPF-CONV
кIина,k’.i-na,умирать.PF-CONV
иджи,iǯi,хорошо
э,e,COP
пуна,p.u-na,говорить.PF-CONV
фаатуне,fāt.u-ne,APUD-ELAT-пускать.PF-AOR
Мебур,me-bur,DEMM-PL
са,sa,один
сувади,suw.a-di,гора-(IN)LAT
фаатуна,fāt.u-na,APUD-ELAT-пускать.PF-CONV
а,a,IN-быть:PRS
Са,sa,один
ягъ,jaʁ,день
хьуне,x.u-ne,стать.PF-AOR
гIу,ʕu,два
ягъ,jaʁ,день
са,sa,один
ваз,waz,месяц
хьибу,xibu,три
ваз,waz,месяц
хьуне,x.u-ne,стать.PF-AOR
Хуппай,χupːaj,потом
мебур,me-bur,DEMM-PL
кук,kuk,жирный
хьуне,x.u-ne,стать.PF-AOR
Ме,me,DEMM
даги,dagi,осел
девейис,dewe.ji-s,верблюд-DAT
пуне,p.u-ne,говорить.PF-AOR
Зафас,za-f-as,я-APUD-ELAT
ккехас,kːeχ.a-s,терпеть.INF-INF
вей,w.e-j,мочь.IPF-CONV
андава,an-dawa,IN-оставаться-PRS:NEG
зун,zun,я
мисаъ,mi-sa-ʔ,DEMM-LOC-IN
са,sa,один
цIекIин,c’ek’in,свадьба
акьасе,aq’.a-s-e,делать.INF-INF-COP
Девейи,dewe.ji,верблюд(ERG)
Ваъ,waʔ,нет
пуне,p.u-ne,говорить.PF-AOR
вун,wun,ты
аьхIмакь,äʜmaq’,дурак
мева,me-w.a,PROH-стать.IPF
хьин,xin,мы:INCL
те,te,DEMT
гIазабикк,ʕazab.i-kː,трудность-SUB
ккиеттар,kːi-je-tː-ar,SUB-быть-PT-S-PL
миштти,mi-štːi,DEMM-ADV
кук,kuk,жирный
хьуна,xu-na,стать.PF-CONV
вун,wun,ты
лебур,le-bur,DEML-PL
акьучин,aq’.u-čin,делать.PF-COND
эесис,ejesi-s,хозяин-DAT
уни,uni,звук
хьасе,x.a-s-e,стать.INF-INF-COP
хаб,χab,снова
хьин,xin,мы:INCL
те,te,DEMT
гIазабикк,ʕazab.i-kː,трудность-SUB
кичархьасе,kičarx.a-s-e,CONT-LAT-попадать.INF-INF-COP
Ваъ,waʔ,нет
пуне,p.u-ne,говорить.PF-AOR
даги,dagi,осел
зафас,za-f-as,я-APUD-ELAT
ккехас,kːeχ.a-s,терпеть.INF-INF
вей,w.e-j,мочь.IPF-CONV
андава,an-dawa,IN-оставаться-PRS:NEG
девейил,dewe.ji-l,верблюд-SUPER
йиркIв,jirk’ʷ,сердце
алдийина,al‹d›ij.i-na,NEG-SUPER-класть.PF-CONV
хъагъихьуна,qaʁix.u-na,POST-UP-класть.PF-CONV
джуфттара,ǯuftː-ar꞊a,брыкание-PL=ADD
ахъихьуне,aqix.u-ne,гнаться.PF-AOR
ме,me,DEMM
а-а,a~a,IDEOPH
ба,ba,IDEOPH
а-а,a~a,IDEOPH
учин,uč.i-n,сам-GEN
суннайихъ,sunna.ji-q,зурна-POST
ушуне,uš.u-ne,уходить.PF-AOR
ме,me,DEMM
даги,dagi,осел
са,sa,один
даради,dar.a-di,лес-(IN)LAT
Тидас,tid-as,DEMT:LOC-ELAT
вей,w.e-j,идти.IPF-CONV
са,sa,один
гIу,ʕu,два
савдагарарис,sawdagar-ar.i-s,купец-PL-DAT
агуне,ag.u-ne,видеть.PF-AOR
Агь,ah,INTJ
пуне,p.u-ne,говорить.PF-AOR
мебури,me-bur.i,DEMM-PL(ERG)
хье,xe,наш:INCL
дагибур,dagi-bur,осел-PL
мишттин,mi-štːi-n,DEMM-ADV-GEN
шавла,šawla,усталый
хьеттар,x.e-tː-ar,стать.PF-S-PL
магьа,maha,DEMM:PRED
хьес,xe-s,мы:INCL-DAT
даги,dagi,осел
ай,aj,INTJ
кук,kuk,жирный
даги,dagi,осел
саьйи,säji,другой
ай,aj,INTJ
деве,dewe,верблюд
Тебурилас,te-bur.i-l-as,DEMT-PL-SUPER-ELAT
къакъар,qːaqː-ar,ноша-PL
алттивуна,altːiw.u-na,SUPER-вынимать.PF-CONV
ме,me,DEMM
кукттарил,kuk-tː-ar.i-l,жирный-S-PL-SUPER
алийина,alij.i-na,SUPER-класть.PF-CONV
ушуне,uš.u-ne,уходить.PF-AOR
Мебур,me-bur,DEMM-PL
са,sa,один
нецIухъ,nec’.u-q,река-POST
хъучархьуне,qučarx.u-ne,POST-LAT-попадать.PF-AOR
даги,dagi,осел
пуне,p.u-ne,говорить.PF-AOR
ХIа,ʜa,большой
илдеш,ildeš,товарищ
зафас,za-f-as,я-APUD-ELAT
мидас,mid-as,DEMM:LOC-ELAT
кейчIваьс,kejč’ʷ.ä-s,CONT-вылезать.INF-INF
хьасттава,x.a-s-tːawa,мочь.INF-INF-COP:NEG
зун,zun,я
мидас,mid-as,DEMM:LOC-ELAT
кеттив,ketːiw,CONT-вынимать(IMP)
Девейи,dewe.ji,верблюд(ERG)
алийина,alij.i-na,SUPER-класть.PF-CONV
учил,uč.i-l,сам-SUPER
нецIун,nec’.u-n,река-GEN
ягIанди,jaʕ.an-di,середина-(IN)LAT
гIачафайшуне,ʕačafajš.u-ne,INTER-LAT-уносить.PF-AOR
Девейи,dewe.ji,верблюд(ERG)
дагис,dagi-s,осел-DAT
пуне,p.u-ne,говорить.PF-AOR
Илдеш,ildeš,товарищ
зафас,za-f-as,я-APUD-ELAT
ккехас,kːeχ.a-s,терпеть.INF-INF
вей,w.e-j,мочь.IPF-CONV
андава,an-dawa,IN-оставаться-PRS:NEG
зун,zun,я
мисаъ,mi-sa-ʔ,DEMM-LOC-IN
са,sa,один
луьхъуьнар,lüqün-ar,танец-PL
акьасе,aq’.a-s-e,делать.INF-INF-COP
Ваъ,waʔ,нет
пуне,p.u-ne,говорить.PF-AOR
даги,dagi,осел
луьхъуьнар,lüqün-ar,танец-PL
акьучин,aq’.u-čin,делать.PF-COND
зун,zun,я
нецIу,nec’.u,река(ERG)
гъасе,ʁ.a-s-e,нести.INF-INF-COP
Девейи,dewe.ji,верблюд(ERG)
пуне,p.u-ne,говорить.PF-AOR
Те,te,DEMT
кефуникк,kef.uni-kː,кайф-SUB
ккиеттар,kːi-je-tː-ar,SUB-быть-PT-S-PL
вун,wun,ты
ме,me,DEMM
балайикк,bala.ji-kː,несчастье-SUB
кичихьуне,kičix.u-ne,CONT-LAT-класть.PF-AOR
душман,dušman,враг
Гьал,hal,теперь
вас,wa-s,ты-DAT
миштти,mi-štːi,DEMM-ADV
иджи,iǯi,хорошо
э,e,COP
пуна,p.u-na,говорить.PF-CONV
са,sa,один
гIу,ʕu,два
гIамубур,ʕamu-bur,шаг-PL
фаатуна,fāt.u-na,APUD-ELAT-отпускать.PF-CONV
алайхьуне,alajx.u-ne,SUPER-DOWN-класть.PF-AOR
Ме,me,DEMM
даги,dagi,осел
нецIу,nec’.u,река(ERG)
файшуне,fajš.u-ne,уносить.PF-AOR"""

In [ ]:
csv_to_table(mulla_i_uchenik, "mulla_i_uchenik.csv")

           cyr         lat                     gloss
0       дагина     dagi꞊na                    осел=и
1         деве        dewe                   верблюд
2        хьуне      x.u-ne              стать.PF-AOR
3        агъай        aʁaj                       CIT
4     хьундава   x.u-ndawa          стать.PF-AOR:NEG
..         ...         ...                       ...
209  алайхьуне  alajx.u-ne  SUPER-DOWN-класть.PF-AOR
210         ме          me                      DEMM
211       даги        dagi                      осел
212      нецlу      nec’.u                 река(ERG)
213    файшуне   fajš.u-ne            уносить.PF-AOR

[214 rows x 3 columns]

#Компиляция трансдьюсера

In [ ]:
!curl -s https://apertium.projectjj.com/apt/install-nightly.sh | sudo bash
!sudo apt-get install hfst lexd

In [ ]:
! git clone https://github.com/shvn-inna/aghul_parser/tree/main
%cd main
! make all

In [ ]:
! lexd aghul_nous.lexd

In [ ]:
! lexd aghul_nous.lexd | hfst-txt2fst -o lexd.hfst

In [ ]:
%%writefile Makefile
.PHONY: all

all: analyzer.hfstol generator.hfstol

substring_search: generator.hfst
	@echo "$(REGEX)" | hfst-regexp2fst | hfst-compose-intersect generator.hfst | hfst-fst2strings

%.hfstol: %.hfst
	hfst-fst2fst -O $< -o $@

analyzer.hfst: generator.hfst remove_hyphen.hfst
	hfst-compose-intersect $^ | hfst-invert -o $@

remove_hyphen.hfst: remove_hyphen.twol
	hfst-twolc -q $< -o $@

generator.hfst: numerals.hfst pronouns.hfst adjectives.hfst nouns.hfst
	hfst-union numerals.hfst pronouns.hfst | hfst-union adjectives.hfst | hfst-union nouns.hfst -o $@

%.hfst: %.lexd
	lexd $< | hfst-txt2fst -o $@

%.lexd: %_formation.lexd %_lexicon.lexd
	cat $^ > $@

adjectives_lexicon.lexd: adjectives/regular/m.txt adjectives/exceptions/m.txt \
						 adjectives/regular/f.txt adjectives/exceptions/f.txt \
						 adjectives/regular/n.txt adjectives/exceptions/n.txt \
						 adjectives/regular/hpl.txt adjectives/exceptions/hpl.txt \
						 adjectives/regular/npl.txt adjectives/exceptions/npl.txt \
						 adjectives/regular/common.txt \
						 adjectives/regular/obl_m.txt adjectives/exceptions/obl_m.txt \
						 adjectives/regular/obl_f.txt adjectives/exceptions/obl_f.txt \
						 adjectives/regular/obl_n.txt adjectives/exceptions/obl_n.txt \
						 adjectives/regular/obl_hpl.txt adjectives/exceptions/obl_hpl.txt \
						 adjectives/regular/obl_npl.txt adjectives/exceptions/obl_npl.txt \
						 adjectives/regular/obl_common_c.txt adjectives/regular/obl_common_v.txt
	cat $+ > $@

nouns_lexicon.lexd: nouns/regular/common.txt nouns/exceptions/common.txt \
					nouns/regular/obl_common.txt nouns/exceptions/obl_common.txt \
					nouns/regular/obl_m.txt nouns/exceptions/obl_m.txt \
					nouns/regular/obl_f.txt nouns/exceptions/obl_f.txt \
					nouns/regular/obl_hpl.txt
	cat $+ > $@

In [ ]:
! echo "дад" | hfst-lookup lexd.hfst

# Тесты

In [ ]:
%%writefile corpus.txt
сува чин дадар дакьунаеф

In [ ]:
! lexd aghul_verbs.lexd | hfst-txt2fst | hfst-invert | hfst-fst2fst -O -o analyzer.hfstol

In [ ]:
! cat corpus.txt | hfst-proc -C analyzer.hfstol

In [ ]:
! cat corpus.txt | wc -w

In [ ]:
! cat corpus.txt | hfst-proc -C analyzer.hfstol | grep -c "*"